### ISSUE TITLE
NullPointerException thrown when loading. (KCauldron)

### ISSUE THREAD

**Issue by EAirPeter** [LambdaInnovation/AcademyCraft#109]
[17:03:33] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[17:03:33] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.NullPointerException: entry
[17:03:33] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.util.zip.ZipFile.getInputStream(Unknown Source)
[17:03:33] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.util.jar.JarFile.getInputStream(Unknown Source)
[17:03:33] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cn.annoreg.AnnoRegCorePlugin.injectData(AnnoRegCorePlugin.java:62)
[17:03:33] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:118)
[17:03:33] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[17:03:33] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[17:03:33] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[17:03:33] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[17:03:33] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[17:03:33] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[17:03:33] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43)
[17:03:33] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12)
[17:03:33] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLDeobfTweaker

**Comment by EAirPeter** [comment]
OK...It's my fault
