### ISSUE TITLE
"Failed to load recipes from String" when loading. (KCauldron)

### ISSUE THREAD

**Issue by EAirPeter** [LambdaInnovation/AcademyCraft#112]
java.lang.RuntimeException: Registry object reso_part doesn't exist
	at cn.liutils.crafting.RecipeRegistry.getNamedObject(RecipeRegistry.java:59) ~[RecipeRegistry.class:?]
	at cn.liutils.crafting.RecipeRegistry.getRegistryObject(RecipeRegistry.java:63) ~[RecipeRegistry.class:?]
	at cn.liutils.crafting.RecipeRegistry.addRecipe(RecipeRegistry.java:160) ~[RecipeRegistry.class:?]
	at cn.liutils.crafting.RecipeRegistry.addRecipeFromString(RecipeRegistry.java:142) [RecipeRegistry.class:?]
	at cn.liutils.crafting.RecipeRegistry.addRecipeFromResourceLocation(RecipeRegistry.java:127) [RecipeRegistry.class:?]
	at cn.academy.core.AcademyCraft.postInit(AcademyCraft.java:131) [AcademyCraft.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_51]
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532) [FMLModContainer.class:1.7.10-1448.133]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_51]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [server-1.7.10.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [server-1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [server-1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [server-1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) [server-1.7.10.jar:?]
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) [LoadController.class:1.7.10-1448.133]
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) [LoadController.class:1.7.10-1448.133]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_51]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [server-1.7.10.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [server-1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [server-1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [server-1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) [server-1.7.10.jar:?]
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119) [LoadController.class:1.7.10-1448.133]
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:742) [Loader.class:1.7.10-1448.133]
	at cpw.mods.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:97) [FMLServerHandler.class:1.7.10-1448.133]
	at cpw.mods.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:324) [FMLCommonHandler.class:1.7.10-1448.133]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:287) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:631) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_51]
[17:03:47] [Server thread/INFO]: |-------------------------------------------------------

**Comment by EAirPeter** [comment]
#113 will solve this.

**Comment by KSkun** [comment]
@EAirPeter Nope, this is a problem different from #113 .

**Comment by KSkun** [comment]
Commit 6263f34d0725e15d1fb65d48356e9471af6de339 fixed this.
