### ISSUE TITLE
ClassNotFoundException thrown when loading. (KCauldron)

### ISSUE THREAD

**Issue by EAirPeter** [LambdaInnovation/AcademyCraft#124]
[01:18:25] [Server thread/INFO]: Itemstack injection complete
[01:18:26] [Server thread/WARN]: java.lang.ClassNotFoundException: ic2.core.IC2
[01:18:26] [Server thread/WARN]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[01:18:26] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[01:18:26] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[01:18:26] [Server thread/WARN]: 	at java.lang.Class.forName0(Native Method)
[01:18:26] [Server thread/WARN]: 	at java.lang.Class.forName(Unknown Source)
[01:18:26] [Server thread/WARN]: 	at cn.academy.core.AcademyCraft.postInit(AcademyCraft.java:132)
[01:18:26] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[01:18:26] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[01:18:26] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[01:18:26] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[01:18:26] [Server thread/WARN]: 	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
[01:18:26] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[01:18:26] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[01:18:26] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[01:18:26] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[01:18:26] [Server thread/WARN]: 	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[01:18:26] [Server thread/WARN]: 	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[01:18:26] [Server thread/WARN]: 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[01:18:26] [Server thread/WARN]: 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[01:18:26] [Server thread/WARN]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[01:18:26] [Server thread/WARN]: 	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
[01:18:26] [Server thread/WARN]: 	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
[01:18:26] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[01:18:26] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[01:18:26] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[01:18:26] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[01:18:26] [Server thread/WARN]: 	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[01:18:26] [Server thread/WARN]: 	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[01:18:26] [Server thread/WARN]: 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[01:18:26] [Server thread/WARN]: 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[01:18:26] [Server thread/WARN]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[01:18:26] [Server thread/WARN]: 	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
[01:18:26] [Server thread/WARN]: 	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:742)
[01:18:26] [Server thread/WARN]: 	at cpw.mods.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:97)
[01:18:26] [Server thread/WARN]: 	at cpw.mods.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:324)
[01:18:26] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:287)
[01:18:26] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:631)
[01:18:26] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[01:18:26] [Server thread/WARN]: Caused by: java.lang.NullPointerException
[01:18:26] [Server thread/WARN]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
[01:18:26] [Server thread/WARN]: 	... 37 more
[01:18:26] [Server thread/INFO]: (null, null, null, 1xitem.ac_crystal_low@32767, 1xitem.ac_machine_frame@32767, 1xitem.ac_crystal_low@32767, 1xitem.ac_matter_unit@32767, null, 1xitem.ac_matter_unit@32767)

**Comment by EAirPeter** [comment]
IC2 may not be a runtime dependency.
