### ISSUE TITLE
Uses Java 1.8 Feature

### ISSUE THREAD

**Issue by KSkun** [LambdaInnovation/AcademyCraft#135]
Java 1.8 Feature cause a NoSuchMethodException on JRE1.7 Env.

cpw.mods.fml.common.LoaderException: java.lang.NoSuchMethodError: java.lang.reflect.Method.getParameterCount()I
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:559)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.jackhuang.hellominecraft.launcher.Launcher.main(SourceFile:122)
Caused by: java.lang.NoSuchMethodError: java.lang.reflect.Method.getParameterCount()I
	at cn.academy.core.util.ValuePipeline$SubscriberVisitor.<init>(ValuePipeline.java:223)
	at cn.academy.core.util.ValuePipeline.register(ValuePipeline.java:120)
	at cn.academy.ability.api.Skill.<init>(Skill.java:88)
	at cn.academy.vanilla.generic.skill.SkillBrainCourse.<init>(SkillBrainCourse.java:27)
	at cn.academy.vanilla.ModuleVanilla.addGenericSkills(ModuleVanilla.java:66)
	at cn.academy.vanilla.electromaster.CatElectroMaster.<init>(CatElectroMaster.java:74)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at java.lang.Class.newInstance(Class.java:379)
	at cn.annoreg.base.RegistrationFieldSimple.registerField(RegistrationFieldSimple.java:53)
	at cn.annoreg.core.RegistryType.registerAll(RegistryType.java:154)
	at cn.annoreg.core.RegistrationManager.registerAll(RegistrationManager.java:163)
	at cn.annoreg.core.RegistrationManager.registerAll(RegistrationManager.java:167)
	at cn.annoreg.core.RegistryType.registerAll(RegistryType.java:88)
	at cn.annoreg.core.RegistrationManager.registerAll(RegistrationManager.java:163)
	at cn.annoreg.core.RegistrationManager.registerAll(RegistrationManager.java:167)
	at cn.academy.core.AcademyCraft.preInit(AcademyCraft.java:111)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
	... 15 more

**Comment by KSkun** [comment]
No problem when we ask users to use JRE1.8
