### ISSUE TITLE
When put IC2 and AC together, MC will crash

### ISSUE THREAD

**Issue by KSkun** [LambdaInnovation/AcademyCraft#138]
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 15-8-22 下午8:41
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoSuchMethodError: net.minecraft.item.ItemStack.getItem()Lnet/minecraft/item/Item;
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:559)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
Caused by: java.lang.NoSuchMethodError: net.minecraft.item.ItemStack.getItem()Lnet/minecraft/item/Item;
	at ic2.api.recipe.RecipeInputItemStack.<init>(RecipeInputItemStack.java:16)
	at ic2.core.block.machine.tileentity.TileEntityCanner.addBottleRecipe(TileEntityCanner.java:111)
	at ic2.core.block.machine.tileentity.TileEntityCanner.init(TileEntityCanner.java:66)
	at ic2.core.IC2.load(IC2.java:256)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
	... 15 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 136584520 bytes (130 MB) / 330731520 bytes (315 MB) up to 2134114304 bytes (2035 MB)
	JVM Flags: 5 total; -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128m -Xmx2048m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1492 Optifine OptiFine_1.7.10_HD_U_C1 47 mods loaded, 47 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1492-1.7.10.jar) 
	UCH	Forge{10.13.4.1492} [Minecraft Forge] (forge-1.7.10-10.13.4.1492-1.7.10.jar) 
	UCH	CodeChickenCore{1.0.7.46} [CodeChicken Core] (minecraft.jar) 
	UCH	InputFix{1.7.10-v5} [InputFix] (minecraft.jar) 
	UCH	OpenEye{0.6} [OpenEye] ([信息采集]OpenEye-0.6-1.7.10.jar) 
	UCH	NotEnoughItems{1.0.5.111} [Not Enough Items] ([物品管理器]NotEnoughItems-1.7.10-1.0.5.111-universal.jar) 
	UCH	uniskinmod{1.2-dev4} [Universal Skin Mod] (minecraft.jar) 
	UCH	AnnoReg{1.0beta3} [Annotation Registry] (minecraft.jar) 
	UCH	craftguide{1.6.8.2} [CraftGuide] ([G键合成]CraftGuide-1.6.8.2-forge[hukk汉化].jar) 
	UCH	LunatriusCore{1.1.2.21} [LunatriusCore] ([Mod依赖]LunatriusCore-1.7.10-1.1.2.21-universal.jar) 
	UCH	AS_UpdateCheck{1.1.6} [AtomicStryker Update Check Mod] ([Mod依赖]UpdateCheckerMod-1.7.10.jar) 
	UCH	ProfilerEvents{1.0} [Profiler Events] ([Mod依赖项]ProfilerEvents.jar) 
	UCH	WailaHarvestability{1.1.2} [Waila Harvestability] ([NEI]WailaHarvestability-mc1.7.x-1.1.2.jar) 
	UCH	NEIAddons{1.12.10.33} [NEI Addons] ([NEI扩展]neiaddons-1.12.10.33-mc1.7.10.jar) 
	UCH	NEIAddons|AppEng{1.12.10.33} [NEI Addons: Applied Energistics 2] ([NEI扩展]neiaddons-1.12.10.33-mc1.7.10.jar) 
	UCH	NEIAddons|Botany{1.12.10.33} [NEI Addons: Botany] ([NEI扩展]neiaddons-1.12.10.33-mc1.7.10.jar) 
	UCH	NEIAddons|Forestry{1.12.10.33} [NEI Addons: Forestry] ([NEI扩展]neiaddons-1.12.10.33-mc1.7.10.jar) 
	UCH	NEIAddons|CraftingTables{1.12.10.33} [NEI Addons: Crafting Tables] ([NEI扩展]neiaddons-1.12.10.33-mc1.7.10.jar) 
	UCH	NEIAddons|ExNihilo{1.12.10.33} [NEI Addons: Ex Nihilo] ([NEI扩展]neiaddons-1.12.10.33-mc1.7.10.jar) 
	UCH	neiintegration{1.0.11} [NEI Integration] ([NEI扩展]NEIIntegration-MC1.7.10-1.0.11.jar) 
	UCH	Waila{1.5.10} [Waila] ([NEI扩展]Waila-1.5.10_1.7.10.jar) 
	UCH	DynamicLights{1.3.8} [Dynamic Lights] ([动态光源]DynamicLights-1.7.10.jar) 
	UCH	DynamicLights_onFire{1.0.4} [Dynamic Lights Burning Entity Module] ([动态光源]DynamicLights-1.7.10.jar) 
	UCH	DynamicLights_creepers{1.0.4} [Dynamic Lights Creeper Module] ([动态光源]DynamicLights-1.7.10.jar) 
	UCH	DynamicLights_dropItems{1.0.8} [Dynamic Lights EntityItem Module] ([动态光源]DynamicLights-1.7.10.jar) 
	UCH	DynamicLights_entityClasses{1.0.1} [Dynamic Lights Entity Light Module] ([动态光源]DynamicLights-1.7.10.jar) 
	UCH	DynamicLights_mobEquipment{1.0.8} [Dynamic Lights Mob Equipment Light Module] ([动态光源]DynamicLights-1.7.10.jar) 
	UCH	DynamicLights_flameArrows{1.0.0} [Dynamic Lights Fiery Arrows Light Module] ([动态光源]DynamicLights-1.7.10.jar) 
	UCH	DynamicLights_floodLights{1.0.2} [Dynamic Lights Flood Light] ([动态光源]DynamicLights-1.7.10.jar) 
	UCH	DynamicLights_otherPlayers{1.0.8} [Dynamic Lights OtherPlayers Light Module] ([动态光源]DynamicLights-1.7.10.jar) 
	UCH	DynamicLights_thePlayer{1.1.4} [Dynamic Lights Player Light Module] ([动态光源]DynamicLights-1.7.10.jar) 
	UCH	FastCraft{1.21} [FastCraft] ([游戏优化]fastcraft-1.21.jar) 
	UCH	InGameInfoXML{2.8.1.80} [InGame Info XML] ([游戏信息显示]InGameInfoXML-1.7.10-2.8.1.80-universal.jar) 
	UCH	InGameInfoXML|AWWayofTimeIntegration{2.8.1.80} [InGame Info XML - Blood Magic Integration] ([游戏信息显示]InGameInfoXML-1.7.10-2.8.1.80-universal.jar) 
	UCH	InGameInfoXML|simplyjetpacksIntegration{2.8.1.80} [InGame Info XML - Simply Jetpacks Integration] ([游戏信息显示]InGameInfoXML-1.7.10-2.8.1.80-universal.jar) 
	UCH	InGameInfoXML|terrafirmacraftIntegration{2.8.1.80} [InGame Info XML - TerraFirmaCraft Integration] ([游戏信息显示]InGameInfoXML-1.7.10-2.8.1.80-universal.jar) 
	UCH	InGameInfoXML|ThaumcraftIntegration{2.8.1.80} [InGame Info XML - Thaumcraft Integration] ([游戏信息显示]InGameInfoXML-1.7.10-2.8.1.80-universal.jar) 
	UCH	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] ([物品整理]InventoryTweaks-1.59-dev-152.jar) 
	UCH	bspkrsCore{6.16} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.16.jar) 
	UCH	ArmorStatusHUD{1.28} [ArmorStatusHUD] ([耐久显示]ArmorStatusHUD.jar) 
	UCH	DamageIndicatorsMod{3.2.3} [Damage Indicators] ([血量显示]DamageIndicatorsMod-3.2.3.jar) 
	UCH	Mineshot{v1.61-1.7.10} [Mineshot] ([高清截图]Mineshot.jar) 
	UCH	MouseTweaks{2.4.4} [Mouse Tweaks] ([鼠标手势]MouseTweaks.jar) 
	UCH	LIUtils{2.0a4} [LIUtils] (LIUtils-d1.0b2.jar) 
	UCE	IC2{2.2.765-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.765-experimental.jar) 
	UCH	academy-craft{1.0a1} [Academy Craft] (AcademyCraft-d1.0b2.jar) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 355.60' Renderer: 'GeForce GTX 750 Ti/PCIe/SSE2'

**Comment by WeAthFoLD** [comment]
你仿佛在逗我

**Comment by WeAthFoLD** [comment]
Actually I didn't meet this problem in any case= =

**Comment by KSkun** [comment]
@WeAthFoLD Maybe it's my 错觉, don't mind 2333

**Comment by KSkun** [comment]
@WeAthFoLD Maybe it's my 错觉, don't mind 2333
