### ISSUE TITLE
NullPointerException while using V key

### ISSUE THREAD

**Issue by WeAthFoLD** [LambdaInnovation/AcademyCraft#144]
Possibly out of sync?
```
java.lang.NullPointerException: Unexpected error
	at cn.academy.ability.api.ctrl.ClientController.getMutexHandler(ClientController.java:110)
	at cn.academy.ability.api.ctrl.ClientHandler$1.handles(ClientHandler.java:56)
	at cn.academy.ability.api.ctrl.ClientHandler.getActivateHandler(ClientHandler.java:123)
	at cn.academy.ability.api.ctrl.ClientHandler.access$000(ClientHandler.java:35)
	at cn.academy.ability.api.ctrl.ClientHandler$4.onKeyDown(ClientHandler.java:142)
	at cn.liutils.util.helper.KeyManager.tick(KeyManager.java:149)
	at cn.liutils.util.helper.KeyManager.onEvent(KeyManager.java:195)
```

**Comment by WeAthFoLD** [comment]
AnnotationRegistry out of date, 233
