### ISSUE TITLE
Client Crash in Forge 1448

### ISSUE THREAD

**Issue by LeLe570929726** [LambdaInnovation/AcademyCraft#152]
使用标记传送的时候会直接跳出当前存档，直接飞到多人游戏界面=A=
多来几次就Crash了
↓Crash Report

---- Minecraft Crash Report ----
// I just don't know what went wrong :(

Time: 15-8-27 下午3:23
Description: Getting biome

java.lang.NullPointerException: Getting biome
	at net.minecraft.world.chunk.Chunk.func_76591_a(Chunk.java:1289)
	at net.minecraft.world.World.getBiomeGenForCoordsBody(World.java:141)
	at net.minecraft.world.WorldProvider.getBiomeGenForCoords(WorldProvider.java:365)
	at net.minecraft.world.World.func_72807_a(World.java:130)
	at net.minecraftforge.client.ForgeHooksClient.getSkyBlendColour(ForgeHooksClient.java:407)
	at net.minecraft.world.World.getSkyColorBody(World.java:1597)
	at net.minecraft.world.WorldProvider.getSkyColor(WorldProvider.java:399)
	at net.minecraft.world.World.func_72833_a(World.java:1575)
	at net.minecraft.client.renderer.EntityRenderer.func_78466_h(EntityRenderer.java:1672)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1154)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1011)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.jackhuang.hellominecraft.launcher.Launcher.main(SourceFile:125)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.world.chunk.Chunk.func_76591_a(Chunk.java:1289)

-- Coordinates of biome request --
Details:
	Location: World: (-190,0,-96), Chunk: (at 2,0,0 in -12,-6; contains blocks -192,0,-96 to -177,255,-81), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
Stacktrace:
	at net.minecraft.world.World.getBiomeGenForCoordsBody(World.java:141)
	at net.minecraft.world.WorldProvider.getBiomeGenForCoords(WorldProvider.java:365)
	at net.minecraft.world.World.func_72807_a(World.java:130)
	at net.minecraftforge.client.ForgeHooksClient.getSkyBlendColour(ForgeHooksClient.java:407)
	at net.minecraft.world.World.getSkyColorBody(World.java:1597)
	at net.minecraft.world.WorldProvider.getSkyColor(WorldProvider.java:399)
	at net.minecraft.world.World.func_72833_a(World.java:1575)
	at net.minecraft.client.renderer.EntityRenderer.func_78466_h(EntityRenderer.java:1672)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1154)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['LeLeOuO'/481003, l='MpServer', x=-163.52, y=68.56, z=-69.32]]
	Chunk stats: MultiplayerChunkCache: 0, 0
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-30,64,-6), Chunk: (at 2,4,10 in -2,-1; contains blocks -32,0,-16 to -17,255,-1), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 3608 game time, 3608 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 4 total; [EntityPig['猪'/481007, l='MpServer', x=-230.75, y=68.00, z=-81.19], EntityPig['猪'/481006, l='MpServer', x=-227.03, y=68.00, z=-76.50], EntityPig['猪'/481005, l='MpServer', x=-232.22, y=69.00, z=-67.09], EntityClientPlayerMP['LeLeOuO'/481003, l='MpServer', x=-163.52, y=68.56, z=-69.32]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.jackhuang.hellominecraft.launcher.Launcher.main(SourceFile:125)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 550445112 bytes (524 MB) / 945242112 bytes (901 MB) up to 2077753344 bytes (1981 MB)
	JVM Flags: 5 total; -Xincgc -Xmx2048m -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 1, tcache: 48, allocated: 12, tallocated: 94
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAAAAAAAAAAAAAAAAAAAAAAAAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAAAAAAAAAAAAAAAAAAAAAAAAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1448-1.7.10.jar) 
	UCHIJAAAAAAAAAAAAAAAAAAAAAAAAAAAAA	Forge{10.13.4.1448} [Minecraft Forge] (forge-1.7.10-10.13.4.1448-1.7.10.jar) 
	UCHIJAAAAAAAAAAAAAAAAAAAAAAAAAAAAA	AnnoReg{2.0a} [Annotation Registry] (minecraft.jar) 
	UCHIJAAAAAAAAAAAAAAAAAAAAAAAAAAAAA	LIUtils{2.0a} [LIUtils] (LIUtils-1.0a-0002.jar) 
	UCHIJAAAAAAAAAAAAAAAAAAAAAAAAAAAAA	academy-craft{1.0a} [Academy Craft] (AcademyCraft-1.0a-0002.jar) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 355.60' Renderer: 'GeForce GTX 970/PCIe/SSE2'
	Launched Version: 1.7.10-Forge10.13.4.1448-1.7.10
	LWJGL: 2.9.1
	OpenGL: GeForce GTX 970/PCIe/SSE2 GL version 4.5.0 NVIDIA 355.60, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: 简体中文 (中国)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by WeAthFoLD** [comment]
这真的不是forge的锅么真的不是么

**Comment by LeLe570929726** [comment]
←←没看反正crash了然后就扔过来了
