### ISSUE TITLE
Crash in TileMatrix

### ISSUE THREAD

**Issue by WeAthFoLD** [LambdaInnovation/AcademyCraft#155]
[21:19:53] [Server thread/ERROR] [FML]: There was a critical exception handling a packet on channel core_ar_networkcall
java.lang.RuntimeException: ALLAROUNDPOINT expects a TargetPoint argument
    at cpw.mods.fml.common.network.FMLOutboundHandler$OutboundTarget$7.validateArgs(FMLOutboundHandler.java:183) ~[FMLOutboundHandler$OutboundTarget$7.class:?]
    at cpw.mods.fml.common.network.FMLOutboundHandler.write(FMLOutboundHandler.java:262) ~[FMLOutboundHandler.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:644) ~[DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:698) ~[DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:637) ~[DefaultChannelHandlerContext.class:?]
    at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:115) ~[MessageToMessageEncoder.class:?]
    at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[MessageToMessageCodec.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:644) ~[DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:698) ~[DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:688) ~[DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:717) ~[DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:893) ~[DefaultChannelPipeline.class:?]
    at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:239) ~[AbstractChannel.class:?]
    at cpw.mods.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendToAllAround(SimpleNetworkWrapper.java:210) ~[SimpleNetworkWrapper.class:?]
    at cn.annoreg.mc.network.NetworkCallManager$1.invoke(NetworkCallManager.java:142) ~[NetworkCallManager$1.class:?]
    at cn.annoreg.mc.network.NetworkCallManager.onNetworkCall(NetworkCallManager.java:115) ~[NetworkCallManager.class:?]
    at cn.academy.energy.block.TileMatrix.syncInventory(TileMatrix.java) ~[TileMatrix.class:?]
    at cn.academy.energy.block.TileMatrix.syncInventory(TileMatrix.java:186) ~[TileMatrix.class:?]
    at cn.academy.energy.block.TileMatrix.func_145845_h(TileMatrix.java:94) ~[TileMatrix.class:?]
    at net.minecraft.world.World.func_72939_s(World.java:1939) ~[ahb.class:?]
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2006) ~[bao.class:?]
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) ~[bao.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) ~[bao.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:148) ~[1.7.10.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_60]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_60]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_60]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) ~[launchwrapper-1.11.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) ~[launchwrapper-1.11.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_60]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_60]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_60]
    at org.jackhuang.hellominecraft.launcher.Launcher.main(SourceFile:122) ~[HMCL-2.3.3.exe:?]

**Comment by WeAthFoLD** [comment]
Unable to reproduce the problem. Issue closed.
