### ISSUE TITLE
Crash for JetEngine

### ISSUE THREAD

**Issue by WeAthFoLD** [LambdaInnovation/AcademyCraft#158]
```
java.lang.NullPointerException
    at cn.liutils.util.generic.VecUtils.add(VecUtils.java:101) ~[VecUtils.class:?]
    at cn.liutils.util.generic.VecUtils.subtract(VecUtils.java:105) ~[VecUtils.class:?]
    at cn.academy.vanilla.meltdowner.skill.JetEngine$JETriggerAction.onStart(JetEngine.java:166) ~[JetEngine$JETriggerAction.class:?]
    at cn.academy.ability.api.ctrl.SyncAction.start(SyncAction.java:194) ~[SyncAction.class:?]
    at cn.academy.ability.api.ctrl.AMClient.startFromServer(AMClient.java:100) ~[AMClient.class:?]
    at cn.academy.ability.api.ctrl.ActionManager.startAtClient_delegate_9(ActionManager.java:71) ~[ActionManager.class:?]
    at cn.annoreg.asm.NetworkCallDelegate_9.invoke(Unknown Source) ~[?:?]
```
When other one starts the ability in server.

**Comment by WeAthFoLD** [comment]
Issue already fixed.
