### ISSUE TITLE
点击升级到【超能力者】按钮时崩溃

### ISSUE THREAD

**Issue by gonglinyuan** [LambdaInnovation/AcademyCraft#198]
---- Minecraft Crash Report ----
// Oh - I know what I did wrong!

Time: 15-11-2 下午12:28
Description: Updating screen events

java.lang.NullPointerException: Updating screen events
	at cn.liutils.util.helper.PlayerData.get(PlayerData.java:121)
	at cn.academy.ability.api.data.AbilityData.get(AbilityData.java:294)
	at cn.academy.ability.developer.DevelopTypeLevel.getStimulations(DevelopTypeLevel.java:34)
	at cn.academy.ability.developer.Developer.getEstmCons(Developer.java:106)
	at cn.academy.ability.client.skilltree.GuiSkillTreeDev.createConfirmWidget(GuiSkillTreeDev.java:269)
	at cn.academy.ability.client.skilltree.GuiSkillTreeDev$1.handleEvent(GuiSkillTreeDev.java:87)
	at cn.academy.ability.client.skilltree.GuiSkillTreeDev$1.handleEvent(GuiSkillTreeDev.java:80)
	at cn.liutils.cgui.gui.event.GuiEventBus.postEvent(GuiEventBus.java:23)
	at cn.liutils.cgui.gui.Widget.postEvent(Widget.java:201)
	at cn.liutils.cgui.gui.LIGui.mouseClicked(LIGui.java:157)
	at cn.liutils.cgui.gui.LIGuiScreen.func_73864_a(LIGuiScreen.java:45)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.jackhuang.hellominecraft.launcher.Launcher.main(Launcher.java:114)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at cn.liutils.util.helper.PlayerData.get(PlayerData.java:121)
	at cn.academy.ability.api.data.AbilityData.get(AbilityData.java:294)
	at cn.academy.ability.developer.DevelopTypeLevel.getStimulations(DevelopTypeLevel.java:34)
	at cn.academy.ability.developer.Developer.getEstmCons(Developer.java:106)
	at cn.academy.ability.client.skilltree.GuiSkillTreeDev.createConfirmWidget(GuiSkillTreeDev.java:269)
	at cn.academy.ability.client.skilltree.GuiSkillTreeDev$1.handleEvent(GuiSkillTreeDev.java:87)
	at cn.academy.ability.client.skilltree.GuiSkillTreeDev$1.handleEvent(GuiSkillTreeDev.java:80)
	at cn.liutils.cgui.gui.event.GuiEventBus.postEvent(GuiEventBus.java:23)
	at cn.liutils.cgui.gui.Widget.postEvent(Widget.java:201)
	at cn.liutils.cgui.gui.LIGui.mouseClicked(LIGui.java:157)
	at cn.liutils.cgui.gui.LIGuiScreen.func_73864_a(LIGuiScreen.java:45)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)

-- Affected screen --
Details:
	Screen name: cn.academy.ability.client.skilltree.GuiSkillTreeDev

-- Affected level --
Details:
	Level name: MpServer
	All players: 2 total; [EntityClientPlayerMP['gonglinyuan'/1914734, l='MpServer', x=-320.37, y=70.62, z=-228.92], EntityOtherPlayerMP['GSSB'/210, l='MpServer', x=-339.31, y=64.00, z=-219.25]]
	Chunk stats: MultiplayerChunkCache: 214, 223
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-224,64,-44), Chunk: (at 0,4,4 in -14,-3; contains blocks -224,0,-48 to -209,255,-33), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 1795352 game time, 1933410 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 41 total; [EntityHorse['马'/1891096, l='MpServer', x=-358.84, y=66.00, z=-166.63], EntitySheep['羊'/1890905, l='MpServer', x=-361.94, y=65.00, z=-161.88], EntityHorse['马'/1891097, l='MpServer', x=-356.00, y=64.00, z=-173.88], EntityHorse['马'/1890906, l='MpServer', x=-370.91, y=68.00, z=-194.75], EntityXPOrb['经验球'/1895189, l='MpServer', x=-253.50, y=64.25, z=-256.16], EntityBat['蝙蝠'/1911060, l='MpServer', x=-367.09, y=50.98, z=-168.82], EntityHorse['马'/266, l='MpServer', x=-346.94, y=64.00, z=-261.72], EntityPigZombie['僵尸猪人'/1916759, l='MpServer', x=-320.87, y=68.00, z=-208.09], EntityBat['蝙蝠'/1911062, l='MpServer', x=-363.32, y=50.00, z=-159.05], EntityClientPlayerMP['gonglinyuan'/1914734, l='MpServer', x=-320.37, y=70.62, z=-228.92], EntityItem['item.item.apple'/1916817, l='MpServer', x=-336.53, y=73.02, z=-231.13], EntityOtherPlayerMP['GSSB'/210, l='MpServer', x=-339.31, y=64.00, z=-219.25], EntityCartChest['entity.MinecartChest.name'/1895365, l='MpServer', x=-409.50, y=20.34, z=-232.88], EntityCreeper['爬行者'/1910144, l='MpServer', x=-251.50, y=27.00, z=-177.50], EntitySkeleton['骷髅'/1913795, l='MpServer', x=-262.50, y=52.00, z=-291.50], EntityBlock['未知'/161, l='MpServer', x=-308.75, y=66.00, z=-265.75], EntityCartChest['entity.MinecartChest.name'/1895354, l='MpServer', x=-384.50, y=29.50, z=-195.50], EntityHorse['马'/1895350, l='MpServer', x=-392.50, y=72.00, z=-302.03], EntityHorse['马'/1089723, l='MpServer', x=-316.63, y=65.00, z=-240.97], EntitySkeleton['骷髅'/1910134, l='MpServer', x=-249.50, y=29.00, z=-177.50], EntityBat['蝙蝠'/1907190, l='MpServer', x=-248.60, y=28.40, z=-175.08], EntityCreeper['爬行者'/1913777, l='MpServer', x=-391.50, y=29.00, z=-216.50], EntityHorse['马'/1895347, l='MpServer', x=-393.16, y=73.00, z=-177.00], EntityCreeper['爬行者'/1913778, l='MpServer', x=-392.50, y=29.00, z=-213.50], EntityOtherPlayerMP['GSSB'/210, l='MpServer', x=-339.31, y=64.00, z=-219.25], EntityBlock['未知'/115, l='MpServer', x=-310.75, y=65.00, z=-249.75], EntityBlock['未知'/116, l='MpServer', x=-315.75, y=65.00, z=-243.75], EntityCow['牛'/1083495, l='MpServer', x=-347.75, y=64.00, z=-237.65], EntityCow['牛'/1083496, l='MpServer', x=-346.34, y=64.00, z=-238.63], EntityChicken['鸡'/1083497, l='MpServer', x=-347.47, y=64.00, z=-239.19], EntityCow['牛'/1083498, l='MpServer', x=-346.59, y=64.00, z=-236.56], EntityHorse['马'/1089706, l='MpServer', x=-352.00, y=63.00, z=-181.72], EntityChicken['鸡'/1083499, l='MpServer', x=-345.47, y=64.00, z=-239.19], EntityHorse['马'/1089707, l='MpServer', x=-372.88, y=71.00, z=-207.13], EntityCow['牛'/1083500, l='MpServer', x=-347.84, y=64.00, z=-236.50], EntityHorse['马'/1089708, l='MpServer', x=-350.88, y=65.00, z=-175.56], EntityChicken['鸡'/1083501, l='MpServer', x=-348.19, y=64.00, z=-238.54], EntityItem['item.item.egg'/1905952, l='MpServer', x=-346.19, y=64.13, z=-237.72], EntityChicken['鸡'/1083502, l='MpServer', x=-344.81, y=64.00, z=-238.47], EntityZombie['僵尸'/1913763, l='MpServer', x=-393.70, y=29.00, z=-223.07], EntityCreeper['爬行者'/1913762, l='MpServer', x=-255.50, y=27.00, z=-175.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.jackhuang.hellominecraft.launcher.Launcher.main(Launcher.java:114)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_65, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 392167872 bytes (374 MB) / 662044672 bytes (631 MB) up to 1597243392 bytes (1523 MB)
	JVM Flags: 7 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx1536m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 53 mods loaded, 53 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1448-1.7.10.jar) 
	UCHIJA	Forge{10.13.4.1448} [Minecraft Forge] (forge-1.7.10-10.13.4.1448-1.7.10.jar) 
	UCHIJA	appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core] (minecraft.jar) 
	UCHIJA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJA	InputFix{1.7.10-v5} [InputFix] (minecraft.jar) 
	UCHIJA	AnnoReg{1.0} [LambdaLib|Annotation Registry] (minecraft.jar) 
	UCHIJA	NotEnoughItems{1.0.5.118} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.118-universal.jar) 
	UCHIJA	betterloadingscreen{1.3.8} [Better Loading Screen] ([1.7.10] BetterLoadingScreen-1.3.8.jar) 
	UCHIJA	DamageIndicatorsMod{3.2.3} [Damage Indicators] ([1.7.10]DamageIndicatorsMod-3.2.3.jar) 
	UCHIJA	LIUtils{1.0} [LambdaLib|LIUtils] (LambdaLib-1.0.jar) 
	UCHIJA	academy-craft{1.0pr2} [Academy Craft] (AcademyCraft-1.0pr2.jar) 
	UCHIJA	AppleCore{1.1.0} [AppleCore] (AppleCore-mc1.7.10-1.1.0.jar) 
	UCHIJA	appliedenergistics2{rv2-stable-10} [Applied Energistics 2] (appliedenergistics2-rv2-stable-10.jar) 
	UCHIJA	BuildCraft|Core{7.1.12} [BuildCraft] (buildcraft-7.1.12.jar) 
	UCHIJA	BuildCraft|Builders{7.1.12} [BC Builders] (buildcraft-7.1.12.jar) 
	UCHIJA	BuildCraft|Transport{7.1.12} [BC Transport] (buildcraft-7.1.12.jar) 
	UCHIJA	BuildCraft|Energy{7.1.12} [BC Energy] (buildcraft-7.1.12.jar) 
	UCHIJA	BuildCraft|Silicon{7.1.12} [BC Silicon] (buildcraft-7.1.12.jar) 
	UCHIJA	BuildCraft|Robotics{7.1.12} [BC Robotics] (buildcraft-7.1.12.jar) 
	UCHIJA	BuildCraft|Factory{7.1.12} [BC Factory] (buildcraft-7.1.12.jar) 
	UCHIJA	HardcoreEnderExpansion{1.8.4} [Hardcore Ender Expansion] (HardcoreEnderExpansion  MC-1.7.10  v1.8.4.jar) 
	UCHIJA	IC2{2.2.790-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.790-experimental.jar) 
	UCHIJA	Forestry{4.1.0.788-unstable} [Forestry for Minecraft] (forestry_1.7.10-4.1.0.788-unstable.jar) 
	UCHIJA	BuildCraft|Compat{7.1.2} [BuildCraft Compat] (buildcraft-compat-7.1.2.jar) 
	UCHIJA	DynamicLights{1.3.9} [Dynamic Lights] (DynamicLights-1.7.10.jar) 
	UCHIJA	DynamicLights_onFire{1.0.5} [Dynamic Lights Burning Entity Module] (DynamicLights-1.7.10.jar) 
	UCHIJA	DynamicLights_creepers{1.0.4} [Dynamic Lights Creeper Module] (DynamicLights-1.7.10.jar) 
	UCHIJA	DynamicLights_dropItems{1.0.8} [Dynamic Lights EntityItem Module] (DynamicLights-1.7.10.jar) 
	UCHIJA	DynamicLights_entityClasses{1.0.1} [Dynamic Lights Entity Light Module] (DynamicLights-1.7.10.jar) 
	UCHIJA	DynamicLights_mobEquipment{1.0.8} [Dynamic Lights Mob Equipment Light Module] (DynamicLights-1.7.10.jar) 
	UCHIJA	DynamicLights_flameArrows{1.0.0} [Dynamic Lights Fiery Arrows Light Module] (DynamicLights-1.7.10.jar) 
	UCHIJA	DynamicLights_floodLights{1.0.2} [Dynamic Lights Flood Light] (DynamicLights-1.7.10.jar) 
	UCHIJA	DynamicLights_otherPlayers{1.0.8} [Dynamic Lights OtherPlayers Light Module] (DynamicLights-1.7.10.jar) 
	UCHIJA	DynamicLights_thePlayer{1.1.4} [Dynamic Lights Player Light Module] (DynamicLights-1.7.10.jar) 
	UCHIJA	FastCraft{1.21} [FastCraft] (fastcraft-1.21.jar) 
	UCHIJA	LunatriusCore{1.1.2.21} [LunatriusCore] (LunatriusCore-1.7.10-1.1.2.21-universal.jar) 
	UCHIJA	InGameInfoXML{2.8.1.82} [InGame Info XML] (InGameInfoXML-1.7.10-2.8.1.82-universal.jar) 
	UCHIJA	inventorytweaks{1.58-147-645ca10} [Inventory Tweaks] (InventoryTweaks-1.58-147.jar) 
	UCHIJA	MineTweaker3{3.0.10} [MineTweaker 3] (MineTweaker3-1.7.10-3.0.10B.jar) 
	UCHIJA	modtweaker2{0.9.4} [Mod Tweaker 2] (ModTweaker2-0.9.4.jar) 
	UCHIJA	NEIAddons{1.12.14.40} [NEI Addons] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJA	NEIAddons|Developer{1.12.14.40} [NEI Addons: Developer Tools] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJA	NEIAddons|AppEng{1.12.14.40} [NEI Addons: Applied Energistics 2] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJA	NEIAddons|Botany{1.12.14.40} [NEI Addons: Botany] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJA	NEIAddons|Forestry{1.12.14.40} [NEI Addons: Forestry] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJA	NEIAddons|CraftingTables{1.12.14.40} [NEI Addons: Crafting Tables] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJA	NEIAddons|ExNihilo{1.12.14.40} [NEI Addons: Ex Nihilo] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHIJA	neiintegration{1.0.13} [NEI Integration] (NEIIntegration-MC1.7.10-1.0.13.jar) 
	UCHIJA	Railcraft{9.8.0.0} [Railcraft] (Railcraft_1.7.10-9.8.0.0.jar) 
	UCHIJA	SpiceOfLife{1.2.4} [The Spice of Life] (SpiceOfLife-mc1.7.10-1.2.4.jar) 
	UCHIJA	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCHIJA	WailaHarvestability{1.1.3} [Waila Harvestability] (WailaHarvestability-mc1.7.10-1.1.3.jar) 
	AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
	AE2 Integration: IC2:ON, RotaryCraft:OFF, RC:ON, BC:ON, RF:ON, RFItem:ON, MFR:OFF, DSU:OFF, FZ:OFF, FMP:OFF, RB:OFF, CLApi:OFF, Waila:ON, InvTweaks:ON, NEI:ON, CraftGuide:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF
	Launched Version: 1.7.10
	LWJGL: 2.9.1
	OpenGL: AMD Radeon HD 7450A Graphics GL version 4.2.11399 Compatibility Profile Context, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: 简体中文 (中国)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: On (16)

**Comment by WeAthFoLD** [comment]
请问bug可以被稳定重现么？还是说只是偶发错误？

**Comment by gonglinyuan** [comment]
试了5,6次了都是这样

可能是联机游戏的问题，因为开服的那个人可以正常使用
