### ISSUE TITLE
服务端在linux系统开启崩溃

### ISSUE THREAD

**Issue by s690644034** [LambdaInnovation/AcademyCraft#210]
不知道是不是其他MOD冲突，还是服务器系统编码问题？
下面是错误报告：

---- Minecraft Crash Report ----
// Oops.

Time: 11/21/15 12:14 PM
Description: Exception in server tick loop

cpw.mods.fml.common.LoaderException: java.lang.ClassNotFoundException: cn.academy.core.AcademyCraft
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:544)
	at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:87)
	at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:319)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:176)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:631)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: cn.academy.core.AcademyCraft
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at cpw.mods.fml.common.ModClassLoader.loadClass(ModClassLoader.java:58)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:278)
	at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:440)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:513)
	... 5 more
Caused by: java.lang.UnsupportedClassVersionError: cn/academy/core/AcademyCraft : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 33 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	KCauldron Version: pw.prok:KCauldron:1.7.10-1492.152
	Operating System: Linux (amd64) version 3.11.0-26-generic
	Java Version: 1.7.0_80, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 262505320 bytes (250 MB) / 1026031616 bytes (978 MB) up to 2364014592 bytes (2254 MB)
	JVM Flags: 3 total; -Xms64M -Xmx2536M -XX:MaxPermSize=256m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1492 65 mods loaded, 65 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UC	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UC	FML{7.10.99.99} [Forge Mod Loader] (craftbukkit-1.7.2-gbk.jar) 
	UC	Forge{10.13.4.1492} [Minecraft Forge] (craftbukkit-1.7.2-gbk.jar) 
	UC	kimagine{0.1} [KImagine] (minecraft.jar) 
	UC	AppleMilkCore{1.1.0} [AppleMilkCore] (minecraft.jar) 
	UC	appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core] (minecraft.jar) 
	UC	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UC	AnnoReg{1.0} [LambdaLib|Annotation Registry] (minecraft.jar) 
	UC	NotEnoughItems{1.0.5.118} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.118-universal.jar) 
	UC	PotionExtensionCore{1.7.10-1.1.0} [PotionExtensionCore] (minecraft.jar) 
	UC	technomCore{0.12.0A} [Technomancy Core] (minecraft.jar) 
	UC	ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core] (minecraft.jar) 
	UC	WitchingGadgetsCore{1.1.9} [Witching Gadgets Core] (minecraft.jar) 
	UC	mod_ecru_MapleTree{1.1.32c} [MapleTree] (%5B1.7.10%5DMapleTree Forge v1.1.32c.jar) 
	UC	LIUtils{1.0} [LambdaLib|LIUtils] (LambdaLib-1.0.jar) 
	UE	academy-craft{1.0pr2_1} [Academy Craft] (AcademyCraft-1.0pr2_1.jar) 
	UC	DCsAppleMilk{1.7.10_2.8k} [Apple&Milk&Tea!] (AppleMilkTea2-1.7.10_2.8k.jar) 
	UC	DCsNEIPluginAMT{1.7.10_1.0a} [NEIPluginForAMT] (AppleMilkTea2-1.7.10_2.8k.jar) 
	UC	appliedenergistics2{rv2-stable-10} [Applied Energistics 2] (appliedenergistics2-rv2-stable-10.jar) 
	UC	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UC	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) 
	UC	Automagy{0.26.3} [Automagy] (Automagy-1.7.10-0.26.3.jar) 
	UC	BambooMod{Minecraft@MC_VERSION@ var@VERSION@} [BambooMod] (Bamboo-2.6.8.5.jar) 
	UC	betterrecords{1.7.10-1.1.9} [Better Records] (betterrecords-1.1.9.jar) 
	UC	BiblioCraft{1.11.2} [BiblioCraft] (BiblioCraft[v1.11.2][MC1.7.10].jar) 
	UC	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1462-universal.jar) 
	UC	AWWayofTime{v1.3.3} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.7.10-1.3.3-17.jar) 
	UC	Botania{r1.7-235} [Botania] (Botania r1.7-235.jar) 
	UC	BuildCraft|Core{7.1.12} [BuildCraft] (buildcraft-7.1.12.jar) 
	UC	BuildCraft|Builders{7.1.12} [BC Builders] (buildcraft-7.1.12.jar) 
	UC	BuildCraft|Transport{7.1.12} [BC Transport] (buildcraft-7.1.12.jar) 
	UC	BuildCraft|Energy{7.1.12} [BC Energy] (buildcraft-7.1.12.jar) 
	UC	BuildCraft|Silicon{7.1.12} [BC Silicon] (buildcraft-7.1.12.jar) 
	UC	BuildCraft|Robotics{7.1.12} [BC Robotics] (buildcraft-7.1.12.jar) 
	UC	BuildCraft|Factory{7.1.12} [BC Factory] (buildcraft-7.1.12.jar) 
	UC	DummyCore{1.13} [DummyCore] (DummyCore1.13.jar) 
	UC	IC2{2.2.791-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.791-experimental.jar) 
	UC	ThaumicTinkerer{unspecified} [Thaumic Tinkerer] (ThaumicTinkerer-2.5-1.7.10-164.jar) 
	UC	ForbiddenMagic{1.7.10-0.57} [Forbidden Magic] (Forbidden Magic-1.7.10-0.57.jar) 
	UC	Forestry{4.0.11.40} [Forestry for Minecraft] (forestry_1.7.10-4.0.11.40.jar) 
	UC	guideapi{1.7.10-1.0.1-20} [Guide-API] (Guide-API-1.7.10-1.0.1-20.jar) 
	UC	InfusionBrewing{1.7.10-1.3} [InfusionBrewing] (InfusionBrewing-1.7.10-1.3.jar) 
	UC	Railcraft{9.8.0.0} [Railcraft] (Railcraft_1.7.10-9.8.0.0.jar) 
	UC	MagicBees{1.7.10-2.4.0} [Magic Bees] (magicbees-1.7.10-2.4.0.jar) 
	UC	MagicCookie{1.0.7.1} [Magic Cookies, something yummy] (MagicCookies-1.0.7.1.jar) 
	UC	NEIAddons{1.12.14.40} [NEI Addons] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UC	NEIAddons|Developer{1.12.14.40} [NEI Addons: Developer Tools] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UC	NEIAddons|AppEng{1.12.14.40} [NEI Addons: Applied Energistics 2] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UC	NEIAddons|Botany{1.12.14.40} [NEI Addons: Botany] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UC	NEIAddons|Forestry{1.12.14.40} [NEI Addons: Forestry] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UC	NEIAddons|CraftingTables{1.12.14.40} [NEI Addons: Crafting Tables] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UC	NEIAddons|ExNihilo{1.12.14.40} [NEI Addons: Ex Nihilo] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UC	recipemod{0.2} [NoMoreRecipeConflict] (NoMoreRecipeConflict-0.2%281.7.10%29.jar) 
	UC	PowerConverters{1.7.10_3.2.1} [Power Converters] (PowerConverters-1.7.10_3.2.1.jar) 
	UC	TaintedMagic{1.1.5.7} [Tainted Magic] (TaintedMagic-1.1.5.7.jar) 
	UC	thaumicbases{1.3.1710.2} [Thaumic Bases] (ThaumicBases-1.3.1710.4.jar) 
	UC	thaumicenergistics{0.8.10.10} [Thaumic Energistics] (thaumicenergistics-0.8.10.10.jar) 
	UC	ThaumicHorizons{1.1.5} [Thaumic Horizons] (thaumichorizons-1.7.10-1.1.6.jar) 
	UC	thaumicinfusion{4.27} [Thaumic Infusion] (ThaumicInfusion-4.27.jar) 
	UC	TravellersGear{1.16.4} [Traveller's Gear] (TravellersGear-1.7.10-1.16.4.jar) 
	UC	TwilightForest{2.3.7} [The Twilight Forest] (twilightforest-1.7.10-2.3.7.jar) 
	UC	WitchingGadgets{1.1.9} [Witching Gadgets] (WitchingGadgets-1.7.10-1.1.9.jar) 
	UC	hearts{1.0} [Hearts] (我的世界mod1.7.10水晶之心.zip) 
	UC	AdvancedSolarPanel{1.7.10-3.5.1} [Advanced Solar Panels] (高级太阳能AdvancedSolarPanel-1.7.10-3.5.1[TFCN].jar) 
	UC	technom{0.12.0A} [Technomancy] (Technomancy - 0.12.1C - 1.7.10.jar) 
	AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'kcauldron,cauldron,craftbukkit,mcpc,fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by WeAthFoLD** [comment]
请使用Java8.
