### ISSUE TITLE
在服务器上使用床崩溃PR2/1版本～PR1不会

### ISSUE THREAD

**Issue by enjoyable1** [LambdaInnovation/AcademyCraft#219]
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 15-12-19 下午12:27
Description: Exception in server tick loop

java.lang.NoSuchFieldError: wakeImmediatly
        at cn.academy.ability.api.data.CPData$Events.playerWakeup(CPData.java:508)
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_207_Events_playerWakeup_PlayerWakeUpEvent.invoke(.dynamic)
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
        at net.minecraft.entity.player.EntityPlayer.func_70999_a(EntityPlayer.java:1636)
        at net.minecraft.entity.player.EntityPlayerMP.func_70999_a(EntityPlayerMP.java:741)
        at net.minecraft.entity.player.EntityPlayerMP.func_71123_m(EntityPlayerMP.java:1164)
        at net.minecraft.network.NetHandlerPlayServer.func_147231_a(NetHandlerPlayServer.java:971)
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:162)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:980)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
        at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
-----

**Comment by WeAthFoLD** [comment]
和#218重复

**Comment by WeAthFoLD** [comment]
确认了一下大概是你的forge版本太老了，请更新到1517或以上试一试
