### ISSUE TITLE
Unexpected Error crash

### ISSUE THREAD

**Issue by Alaberti** [LambdaInnovation/AcademyCraft#222]
One of the players on my server sent me this one: http://pastebin.com/dYUeAa0m not really sure how it happened.

**Comment by WeAthFoLD** [comment]
Interesting. Looks like the game crashed when trying to save the preset. Not sure start from where that NullPtr came in though. I'll try to reproduce it.

Crash log posted here for reference, we can't really visit pastebin directly in our country...

```
java.lang.NullPointerException: Unexpected error
	at cn.liutils.util.helper.PlayerData.get(PlayerData.java:121)
	at cn.academy.ability.api.data.PresetData.get(PresetData.java:175)
	at cn.academy.ability.api.ctrl.ClientController.rebuildOverrides(ClientController.java:160)
	at cn.academy.ability.api.ctrl.ClientController.checkOverrides(ClientController.java:152)
	at cn.academy.ability.api.ctrl.ClientController.editPreset(ClientController.java:132)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_840_ClientController_editPreset_PresetUpdateEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at cn.academy.ability.api.data.PresetData$PresetEditor.save(PresetData.java:219)
	at cn.academy.ability.client.ui.PresetEditUI.func_146281_b(PresetEditUI.java:128)
	at net.minecraft.client.Minecraft.func_147108_a(Unknown Source)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147231_a(Unknown Source)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(Unknown Source)
	at net.minecraft.client.Minecraft.func_71407_l(Unknown Source)
	at net.minecraft.client.Minecraft.func_71411_J(Unknown Source)
	at net.minecraft.client.Minecraft.func_99999_d(Unknown Source)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by knight-ryu12** [comment]
hmm. looks like PlayerData get method are broken.

**Comment by WeAthFoLD** [comment]
@knight-ryu12 I don't think so. It's likely the EntityPlayer instance passed in is null itself. This will require some inspection down the call path.

**Comment by WeAthFoLD** [comment]
This is likely connected to #232 . I have rewritten `EntityData` once so not sure if this report will be of too much help.
