### ISSUE TITLE
Crash Report 

### ISSUE THREAD

**Issue by Sermax18** [LambdaInnovation/AcademyCraft#227]
http://pastebin.com/AwkUJ9xs

**Comment by WeAthFoLD** [comment]
Revelant part:
```
[16:14:26] [Client thread/FATAL]: Reported exception thrown!
net.minecraft.util.ReportedException: Rendering screen
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1391) ~[blt.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001) ~[bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_65]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_65]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_65]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_65]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NullPointerException
	at cpw.mods.fml.common.versioning.VersionRange.getLowerBoundString(VersionRange.java:573) ~[VersionRange.class:?]
	at cpw.mods.fml.client.GuiModsMissing.func_73863_a(GuiModsMissing.java:54) ~[GuiModsMissing.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1357) ~[blt.class:?]
	... 9 more
[16:14:27] [Client thread/INFO] [STDOUT]: [net.minecraft.client.Minecraft:func_71377_b:349]: ---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 1/9/16 4:14 PM
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at cpw.mods.fml.common.versioning.VersionRange.getLowerBoundString(VersionRange.java:573)
	at cpw.mods.fml.client.GuiModsMissing.func_73863_a(GuiModsMissing.java:54)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1357)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at cpw.mods.fml.common.versioning.VersionRange.getLowerBoundString(VersionRange.java:573)
	at cpw.mods.fml.client.GuiModsMissing.func_73863_a(GuiModsMissing.java:54)
```

It seems you didn't have LambdaLib installed. You can find the link via the website or the curseforge page.
