### ISSUE TITLE
建立服务器后客户端提示a fatal error has occured,this connection is terminated

### ISSUE THREAD

**Issue by zxc123xyz456** [LambdaInnovation/AcademyCraft#239]
服务端和客户端除了LambdaLib-1.1.0和AcademyCraft-1.0pr3什么都没装
玩家加入服务器后，服务端提示
[23:57:01] [Server thread/INFO]: Gold[/192.168.1.37:9114] logged in with entity id 148 at ([world] 171.5, 64.0, 247.5)
[23:57:04] [Server thread/ERROR]: SimpleChannelHandlerWrapper exception
java.lang.NullPointerException
	at cn.lambdalib.util.datapart.EntityData.getPart(EntityData.java:155) ~[EntityData.class:?]
	at cn.lambdalib.util.datapart.EntityData.query_delegate_18(EntityData.java:295) ~[EntityData.class:?]
	at cn.lambdalib.networkcall.asm.NetworkCallDelegate_18.invoke(Unknown Source) ~[?:?]
	at cn.lambdalib.networkcall.NetworkCallManager$MessageHandler.onMessage(NetworkCallManager.java:95) ~[NetworkCallManager$MessageHandler.class:?]
	at cn.lambdalib.networkcall.NetworkCallManager$MessageHandler.onMessage(NetworkCallManager.java:72) ~[NetworkCallManager$MessageHandler.class:?]
	at cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:37) ~[SimpleChannelHandlerWrapper.class:git-Cauldron-MCPC-Plus-1.7.10-1.1307.06.218]
	at cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:17) ~[SimpleChannelHandlerWrapper.class:git-Cauldron-MCPC-Plus-1.7.10-1.1307.06.218]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [MessageToMessageDecoder.class:?]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) [MessageToMessageCodec.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:git-Cauldron-MCPC-Plus-1.7.10-1.1307.06.218]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:980) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_66]
[23:57:04] [Server thread/ERROR]: There was a critical exception handling a packet on channel core_ar_networkcall
java.lang.NullPointerException
	at cn.lambdalib.util.datapart.EntityData.getPart(EntityData.java:155) ~[EntityData.class:?]
	at cn.lambdalib.util.datapart.EntityData.query_delegate_18(EntityData.java:295) ~[EntityData.class:?]
	at cn.lambdalib.networkcall.asm.NetworkCallDelegate_18.invoke(Unknown Source) ~[?:?]
	at cn.lambdalib.networkcall.NetworkCallManager$MessageHandler.onMessage(NetworkCallManager.java:95) ~[NetworkCallManager$MessageHandler.class:?]
	at cn.lambdalib.networkcall.NetworkCallManager$MessageHandler.onMessage(NetworkCallManager.java:72) ~[NetworkCallManager$MessageHandler.class:?]
	at cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:37) ~[SimpleChannelHandlerWrapper.class:git-Cauldron-MCPC-Plus-1.7.10-1.1307.06.218]
	at cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:17) ~[SimpleChannelHandlerWrapper.class:git-Cauldron-MCPC-Plus-1.7.10-1.1307.06.218]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[MessageToMessageDecoder.class:?]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[MessageToMessageCodec.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[DefaultChannelPipeline.class:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[EmbeddedChannel.class:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:git-Cauldron-MCPC-Plus-1.7.10-1.1307.06.218]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:980) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_66]
[23:57:04] [Server thread/INFO]: Gold lost connection: A fatal error has occured, this connection is terminated
[23:57:04] [Server thread/INFO]: Gold left the game.

**Comment by WeAthFoLD** [comment]
和 #232 重复。会在下个bugfix版本修复的。
