### ISSUE TITLE
Crash in conection gui when hovering over the disconect button 

### ISSUE THREAD

**Issue by Horneat** [LambdaInnovation/AcademyCraft#241]
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 19.01.16 20:45
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at net.ilexiconn.llibrary.client.ClientEventHandler.onDrawScreen(ClientEventHandler.java:167)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_708_ClientEventHandler_onDrawScreen_Post.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1062)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by WeAthFoLD** [comment]
Can you please provide the LLibrary version and AcademyCraft version used?

**Comment by Horneat** [comment]
Yes happens every time and when you click any button in the Wireles Enegy GUI in any machine it crashes to with the same Crash log

**Comment by Horneat** [comment]
I have the version from ac craft is 1.0 pre 3
And mean you with llibray lambda lib 1.1.0

**Comment by WeAthFoLD** [comment]
I mean the version of [this library](https://github.com/iLexiconn/LLibrary/). It can be seen in the log that this mod caused the problem.

**Comment by Horneat** [comment]
Ohhh Okey when I am back from school I will look maybe the version who I have is to old

**Comment by Horneat** [comment]
oh okey i now  try a updatede

**Comment by Horneat** [comment]
fixt

**Comment by WeAthFoLD** [comment]
Good to hear :)
