### ISSUE TITLE
Crash when use skill to charge MFSU

### ISSUE THREAD

**Issue by KSkun** [LambdaInnovation/AcademyCraft#273]
---- Minecraft Crash Report ----
// Don't do that.

Time: 16-2-14 上午9:05
Description: Exception in server tick loop

com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'ac.category.electromaster.skills.charging.speed'
	at com.typesafe.config.impl.SimpleConfig.findKey(SimpleConfig.java:124)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:145)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:151)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:151)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:151)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:151)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:151)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:159)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:164)
	at com.typesafe.config.impl.SimpleConfig.getList(SimpleConfig.java:212)
	at com.typesafe.config.impl.SimpleConfig.getHomogeneousUnwrappedList(SimpleConfig.java:271)
	at com.typesafe.config.impl.SimpleConfig.getNumberList(SimpleConfig.java:294)
	at com.typesafe.config.impl.SimpleConfig.getDoubleList(SimpleConfig.java:320)
	at cn.academy.core.config.ConfigEnv.lerpf(ConfigEnv.java:86)
	at cn.academy.ability.api.Skill.callFloatWithExp(Skill.java:339)
	at cn.academy.vanilla.electromaster.skill.CurrentCharging.getChargingSpeed(CurrentCharging.java:69)
	at cn.academy.vanilla.electromaster.skill.CurrentCharging$ActionChargeBlock.onTick(CurrentCharging.java:110)
	at cn.academy.ability.api.ctrl.AMServer.onServerTick(AMServer.java:152)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_29_AMServer_onServerTick_ServerTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:247)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:657)
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:118)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:485)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:752)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_45, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 441206536 bytes (420 MB) / 1038876672 bytes (990 MB) up to 1038876672 bytes (990 MB)
	JVM Flags: 3 total; -Xincgc -Xmx1024M -Xms1024M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1517 11 mods loaded, 11 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forgeSrc-1.7.10-10.13.4.1517-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1517} [Minecraft Forge] (forgeSrc-1.7.10-10.13.4.1517-1.7.10.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.3.74} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.3.74-dev.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	LambdaLib|Core{1.1.1} [LambdaLib|Core] (minecraft.jar) 
	UCHIJAAAA	LambdaLib{1.1.1} [LambdaLib] (forge-1.7.10-10.13.4.1517-1.7.10-src) 
	UCHIJAAAA	academy-craft{1.0pr3_1} [Academy Craft] (forge-1.7.10-10.13.4.1517-1.7.10-src) 
	UCHIJAAAA	examplemod{1.0} [examplemod] (forge-1.7.10-10.13.4.1517-1.7.10-src) 
	UCHIJAAAA	IC2{2.2.811-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.811-experimental-dev.jar) 
	UCHIJAAAA	MineTweaker3{3.0.9B} [MineTweaker 3] (MineTweaker3-Dev-1.7.10-3.0.9C.jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [EntityPlayerMP['KSkun'/362, l='新的世界', x=-8.45, y=77.00, z=260.17]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by EAirPeter** [comment]
Fixed in 3fedad098091ab3d7b0b514c14872684cfd947f9.
