### ISSUE TITLE
能力开发机放下后报错

### ISSUE THREAD

**Issue by KomeijiRin** [LambdaInnovation/AcademyCraft#297]
在放下 高级/普通能力开发机 后后台刷报错
日志如下（没有crash但是一直在刷这个错误）

四月 01, 2016 3:00:37 下午 io.netty.channel.embedded.EmbeddedChannel recordException
警告: More than one exception was raised. Will report only the first one and log others.
java.lang.NullPointerException
        at cpw.mods.fml.common.network.FMLOutboundHandler$OutboundTarget$7.selectNetworks(FMLOutboundHandler.java:193)
        at cpw.mods.fml.common.network.FMLOutboundHandler.write(FMLOutboundHandler.java:273)
        at io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:644)
        at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:698)
        at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:637)
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:115)
        at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116)
        at io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:644)
        at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:698)
        at io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:688)
        at io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:717)
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:893)
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:239)
        at cpw.mods.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendToAllAround(SimpleNetworkWrapper.java:210)
        at cn.lambdalib.networkcall.NetworkCallManager$1.invoke(NetworkCallManager.java:142)
        at cn.lambdalib.networkcall.NetworkCallManager.onNetworkCall(NetworkCallManager.java:113)
        at cn.academy.ability.block.TileDeveloper.syncTheUser(TileDeveloper.java)
        at cn.academy.ability.block.TileDeveloper.func_145845_h(TileDeveloper.java:115)
        at net.minecraft.world.World.func_72939_s(World.java:1939)
        at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2006)
        at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
        at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
        at net.minecraft.client.main.Main.main(SourceFile:148)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by WeAthFoLD** [comment]
已在dev分支修复。请等待下一个版本发布 :ice_cream:
