### ISSUE TITLE
A problem of SideOnly

### ISSUE THREAD

**Issue by nirvanaxiao6** [LambdaInnovation/AcademyCraft#300]
```
[23:25:04] [Server thread/ERROR]: Failed to create an action
java.lang.NoClassDefFoundError: cn/academy/vanilla/meltdowner/entity/EntityMineRayLuck
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_77]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_77]
	at cn.academy.ability.api.ctrl.AMServer.startFromClient(AMServer.java:83) [AMServer.class:?]
	at cn.academy.ability.api.ctrl.ActionManager.startAtServer_delegate_1(ActionManager.java:52) [ActionManager.class:?]
	at cn.lambdalib.networkcall.asm.NetworkCallDelegate_1.invoke(Unknown Source) [?:?]
	at cn.lambdalib.networkcall.NetworkCallManager$MessageHandler.onMessage(NetworkCallManager.java:89) [NetworkCallManager$MessageHandler.class:?]
	at cn.lambdalib.networkcall.NetworkCallManager$MessageHandler.onMessage(NetworkCallManager.java:66) [NetworkCallManager$MessageHandler.class:?]
	at cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:37) [SimpleChannelHandlerWrapper.class:1.7.10-R0.1-SNAPSHOT]
	at cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:17) [SimpleChannelHandlerWrapper.class:1.7.10-R0.1-SNAPSHOT]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) [SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [MessageToMessageDecoder.class:?]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) [MessageToMessageCodec.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:1.7.10-R0.1-SNAPSHOT]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:991) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_77]
Caused by: java.lang.ClassNotFoundException: cn.academy.vanilla.meltdowner.entity.EntityMineRayLuck
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_77]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_77]
	... 26 more
```

**Comment by WeAthFoLD** [comment]
Fixed in e9234ae07037671072bfc4c550a9de94722e1c0e
