### ISSUE TITLE
Unterminated object at line 1 column 26688

### ISSUE THREAD

**Issue by xxlio109** [LambdaInnovation/AcademyCraft#330]
` com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 1 column 26688
 	at com.google.gson.Gson.fromJson(Gson.java:818)
 	at com.google.gson.Gson.fromJson(Gson.java:768)
 	at cn.lambdalib.util.version.Fetcher.run(CheckManger.java:135)
 	at java.lang.Thread.run(Unknown Source)
 Caused by: com.google.gson.stream.MalformedJsonException: Unterminated object at line 1 column 26688
 	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1505)
 	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:480)
 	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:403)
 	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:184)
 	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
 	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
 	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:81)
 	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:60)
 	at com.google.gson.Gson.fromJson(Gson.java:803)
 	... 3 more
 Exception in thread "Thread-10" 
 java.lang.NullPointerException
 	at cn.lambdalib.util.version.Fetcher.run(CheckManger.java:139)
 	at java.lang.Thread.run(Unknown Source)`

**Comment by WeAthFoLD** [comment]
Very much the version update fetcher problem. @ShieLian here

**Comment by WeAthFoLD** [comment]
I believe it is fixed in recent updates of LambdaLib. Please reopen this issue if you still have problem in newer versions.
