### ISSUE TITLE
Connection timed out when starting

### ISSUE THREAD

**Issue by jmas2007** [LambdaInnovation/AcademyCraft#373]
[16:30:45 INFO]: Starting LambdaLib
[16:30:45 INFO]: Copyright (c) Lambda Innovation, 2013-2016
[16:30:45 INFO]: http://www.li-dev.cn/
[16:30:46 INFO]: AcademyCraft Wireless Energy System is loading...
[16:30:47 INFO]: Starting AcademyCraft
[16:30:47 INFO]: Copyright (c) Lambda Innovation, 2013-2016
[16:30:47 INFO]: http://ac.li-dev.cn/
[16:32:56 WARN]: java.net.ConnectException: Connection timed out
[16:32:56 WARN]: 	at java.net.PlainSocketImpl.socketConnect(Native Method)
[16:32:56 WARN]: 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
[16:32:56 WARN]: 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
[16:32:56 WARN]: 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
[16:32:56 WARN]: 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[16:32:56 WARN]: 	at java.net.Socket.connect(Socket.java:589)
[16:32:56 WARN]: 	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
[16:32:56 WARN]: 	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
[16:32:56 WARN]: 	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
[16:32:56 WARN]: 	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
[16:32:56 WARN]: 	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
[16:32:56 WARN]: 	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
[16:32:56 WARN]: 	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
[16:32:56 WARN]: 	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
[16:32:56 WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)
[16:32:56 WARN]: 	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:989)
[16:32:56 WARN]: 	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:987)
[16:32:56 WARN]: 	at java.security.AccessController.doPrivileged(Native Method)
[16:32:56 WARN]: 	at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:782)
[16:32:56 WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:986)
[16:32:56 WARN]: 	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
[16:32:56 WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1513)
[16:32:56 WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:90)
[16:32:56 WARN]: 	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1433)
[16:32:56 WARN]: 	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1431)
[16:32:56 WARN]: 	at java.security.AccessController.doPrivileged(Native Method)
[16:32:56 WARN]: 	at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:782)
[16:32:56 WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1430)
[16:32:56 WARN]: 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
[16:32:56 WARN]: 	at java.net.URL.openStream(URL.java:1045)
[16:32:56 WARN]: 	at ruby.bamboo.UpdateNotify.run(UpdateNotify.java:43)
[16:32:56 WARN]: 	at java.lang.Thread.run(Thread.java:745)
[16:32:56 WARN]: 	at ruby.bamboo.BambooCore.preLoad(BambooCore.java:59)
[16:32:56 WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[16:32:56 WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[16:32:56 WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[16:32:56 WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[16:32:56 WARN]: 	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
[16:32:56 WARN]: 	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
[16:32:56 WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[16:32:56 WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[16:32:56 WARN]: 	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[16:32:56 WARN]: 	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[16:32:56 WARN]: 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[16:32:56 WARN]: 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[16:32:56 WARN]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[16:32:56 WARN]: 	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
[16:32:56 WARN]: 	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
[16:32:56 WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[16:32:56 WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[16:32:56 WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[16:32:56 WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[16:32:56 WARN]: 	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[16:32:56 WARN]: 	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[16:32:56 WARN]: 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[16:32:56 WARN]: 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[16:32:56 WARN]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[16:32:56 WARN]: 	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
[16:32:56 WARN]: 	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
[16:32:56 WARN]: 	at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:88)
[16:32:56 WARN]: 	at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:319)
[16:32:56 WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:176)
[16:32:56 WARN]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:633)
[16:32:56 WARN]: 	at java.lang.Thread.run(Thread.java:745)

**Comment by WeAthFoLD** [comment]
It's not crucial at all and this error doesn't even belong to AcademyCraft. You can ignore this.

**Comment by jmas2007** [comment]
Well. I missed that. Thx.
