### ISSUE TITLE
[1.0.1] Crash when MagManip is used on iron doors

### ISSUE THREAD

**Issue by WeAthFoLD** [LambdaInnovation/AcademyCraft#404]
Crash report:
```
java.lang.NullPointerException: Ticking entity
	at cn.academy.core.entity.EntityBlock$1.onEvent(EntityBlock.java:162)
	at cn.academy.core.entity.EntityBlock$1.onEvent(EntityBlock.java:144)
	at cn.lambdalib.util.entityx.EntityX.postEvent(EntityX.java:113)
	at cn.lambdalib.util.entityx.handlers.Rigidbody.onUpdate(Rigidbody.java:75)
	at cn.lambdalib.util.entityx.EntityX.update(EntityX.java:51)
	at cn.lambdalib.util.entityx.EntityAdvanced.func_70071_h_(EntityAdvanced.java:37)
	at cn.academy.core.entity.EntityBlock.func_70071_h_(EntityBlock.java:123)
	at cn.academy.vanilla.electromaster.MagManipEntityBlock.func_70071_h_(MagManip.scala:278)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
	at net.minecraft.world.World.func_72870_g(World.java:2034)
	at WorldServerOF.func_72870_g(WorldServerOF.java:347)
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```
I think the best solution is forbid the usage on iron doors...

**Comment by KSkun** [comment]
Solution:
Make the using on iron doors unavailable.
