### ISSUE TITLE
[1.0.2] 在Thermos服务端中玩家无法加入服务器

### ISSUE THREAD

**Issue by KSkun** [LambdaInnovation/AcademyCraft#413]
崩溃报告见下

```
[11:48:12] [User Authenticator #1/INFO]: UUID of player KSkun is 7f3a90dc-5f6e-32fe-b89a-dddfa8415313
[11:48:12] [Netty IO #1/INFO]: Client protocol version 2
[11:48:12] [Netty IO #1/INFO]: Client attempting to join with 10 mods : NotEnoughItems@1.0.4.105,CodeChickenCore@1.0.6.43,FML@7.10.99.99,MineTweaker3@3.0.9B,Forge@10.13.4.1517,IC2@2.2.811-experimental,mcp@9.05,academy-craft@1.0.2,LambdaLib|Core@1.2.1,LambdaLib@1.2.1
[11:48:12] [Netty IO #1/INFO]: Attempting connection with missing mods [kimagine] at CLIENT
[11:48:12] [Server thread/INFO]: [Server thread] Server side modded connection established
[11:48:12] [Server thread/INFO]: KSkun[/127.0.0.1:7494] logged in with entity id 1966 at ([world] 1.5, 71.0, 5.5)
[11:48:13] [Server thread/ERROR]: FMLIndexedMessageCodec exception caught
io.netty.handler.codec.DecoderException: java.lang.RuntimeException: Error deserializing network message itn_query_init@cn.lambdalib.util.datapart.EntityData@693ab3d9
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:99) ~[MessageToMessageDecoder.class:?]
    at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[MessageToMessageCodec.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
    at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?]
    at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:1.7.10-1614.25]
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?]
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:999) [MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:817) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:675) [MinecraftServer.class:?]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_60]
Caused by: java.lang.RuntimeException: Error deserializing network message itn_query_init@cn.lambdalib.util.datapart.EntityData@693ab3d9
    at cn.lambdalib.s11n.network.NetworkMessage$Message.fromBytes(NetworkMessage.java:343) ~[NetworkMessage$Message.class:?]
    at cpw.mods.fml.common.network.simpleimpl.SimpleIndexedCodec.decodeInto(SimpleIndexedCodec.java:17) ~[SimpleIndexedCodec.class:1.7.10-1614.25]
    at cpw.mods.fml.common.network.simpleimpl.SimpleIndexedCodec.decodeInto(SimpleIndexedCodec.java:7) ~[SimpleIndexedCodec.class:1.7.10-1614.25]
    at cpw.mods.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:77) ~[FMLIndexedMessageToMessageCodec.class:1.7.10-1614.25]
    at cpw.mods.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:17) ~[FMLIndexedMessageToMessageCodec.class:1.7.10-1614.25]
    at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81) ~[MessageToMessageCodec$2.class:?]
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89) ~[MessageToMessageDecoder.class:?]
    ... 13 more
Caused by: java.lang.IndexOutOfBoundsException: Index: 256, Size: 67
    at java.util.ArrayList.rangeCheck(Unknown Source) ~[?:1.8.0_60]
    at java.util.ArrayList.get(Unknown Source) ~[?:1.8.0_60]
    at cn.lambdalib.s11n.network.NetworkS11n.readTypeIndex(NetworkS11n.java:152) ~[NetworkS11n.class:?]
    at cn.lambdalib.s11n.network.NetworkS11n.deserialize(NetworkS11n.java:238) ~[NetworkS11n.class:?]
    at cn.lambdalib.s11n.network.NetworkMessage$Message.fromBytes(NetworkMessage.java:337) ~[NetworkMessage$Message.class:?]
    at cpw.mods.fml.common.network.simpleimpl.SimpleIndexedCodec.decodeInto(SimpleIndexedCodec.java:17) ~[SimpleIndexedCodec.class:1.7.10-1614.25]
    at cpw.mods.fml.common.network.simpleimpl.SimpleIndexedCodec.decodeInto(SimpleIndexedCodec.java:7) ~[SimpleIndexedCodec.class:1.7.10-1614.25]
    at cpw.mods.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:77) ~[FMLIndexedMessageToMessageCodec.class:1.7.10-1614.25]
    at cpw.mods.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:17) ~[FMLIndexedMessageToMessageCodec.class:1.7.10-1614.25]
    at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81) ~[MessageToMessageCodec$2.class:?]
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89) ~[MessageToMessageDecoder.class:?]
    ... 13 more
[11:48:13] [Server thread/ERROR]: SimpleChannelHandlerWrapper exception
io.netty.handler.codec.DecoderException: java.lang.RuntimeException: Error deserializing network message itn_query_init@cn.lambdalib.util.datapart.EntityData@693ab3d9
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:99) ~[MessageToMessageDecoder.class:?]
    at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[MessageToMessageCodec.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
    at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?]
    at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:1.7.10-1614.25]
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?]
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:999) [MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:817) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:675) [MinecraftServer.class:?]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_60]
Caused by: java.lang.RuntimeException: Error deserializing network message itn_query_init@cn.lambdalib.util.datapart.EntityData@693ab3d9
    at cn.lambdalib.s11n.network.NetworkMessage$Message.fromBytes(NetworkMessage.java:343) ~[NetworkMessage$Message.class:?]
    at cpw.mods.fml.common.network.simpleimpl.SimpleIndexedCodec.decodeInto(SimpleIndexedCodec.java:17) ~[SimpleIndexedCodec.class:1.7.10-1614.25]
    at cpw.mods.fml.common.network.simpleimpl.SimpleIndexedCodec.decodeInto(SimpleIndexedCodec.java:7) ~[SimpleIndexedCodec.class:1.7.10-1614.25]
    at cpw.mods.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:77) ~[FMLIndexedMessageToMessageCodec.class:1.7.10-1614.25]
    at cpw.mods.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:17) ~[FMLIndexedMessageToMessageCodec.class:1.7.10-1614.25]
    at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81) ~[MessageToMessageCodec$2.class:?]
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89) ~[MessageToMessageDecoder.class:?]
    ... 13 more
Caused by: java.lang.IndexOutOfBoundsException: Index: 256, Size: 67
    at java.util.ArrayList.rangeCheck(Unknown Source) ~[?:1.8.0_60]
    at java.util.ArrayList.get(Unknown Source) ~[?:1.8.0_60]
    at cn.lambdalib.s11n.network.NetworkS11n.readTypeIndex(NetworkS11n.java:152) ~[NetworkS11n.class:?]
    at cn.lambdalib.s11n.network.NetworkS11n.deserialize(NetworkS11n.java:238) ~[NetworkS11n.class:?]
    at cn.lambdalib.s11n.network.NetworkMessage$Message.fromBytes(NetworkMessage.java:337) ~[NetworkMessage$Message.class:?]
    at cpw.mods.fml.common.network.simpleimpl.SimpleIndexedCodec.decodeInto(SimpleIndexedCodec.java:17) ~[SimpleIndexedCodec.class:1.7.10-1614.25]
    at cpw.mods.fml.common.network.simpleimpl.SimpleIndexedCodec.decodeInto(SimpleIndexedCodec.java:7) ~[SimpleIndexedCodec.class:1.7.10-1614.25]
    at cpw.mods.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:77) ~[FMLIndexedMessageToMessageCodec.class:1.7.10-1614.25]
    at cpw.mods.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:17) ~[FMLIndexedMessageToMessageCodec.class:1.7.10-1614.25]
    at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81) ~[MessageToMessageCodec$2.class:?]
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89) ~[MessageToMessageDecoder.class:?]
    ... 13 more
[11:48:13] [Server thread/ERROR]: SimpleChannelHandlerWrapper exception
io.netty.handler.codec.DecoderException: java.lang.RuntimeException: Error deserializing network message itn_query_init@cn.lambdalib.util.datapart.EntityData@693ab3d9
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:99) ~[MessageToMessageDecoder.class:?]
    at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[MessageToMessageCodec.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
    at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?]
    at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:1.7.10-1614.25]
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?]
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:999) [MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:817) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:675) [MinecraftServer.class:?]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_60]
Caused by: java.lang.RuntimeException: Error deserializing network message itn_query_init@cn.lambdalib.util.datapart.EntityData@693ab3d9
    at cn.lambdalib.s11n.network.NetworkMessage$Message.fromBytes(NetworkMessage.java:343) ~[NetworkMessage$Message.class:?]
    at cpw.mods.fml.common.network.simpleimpl.SimpleIndexedCodec.decodeInto(SimpleIndexedCodec.java:17) ~[SimpleIndexedCodec.class:1.7.10-1614.25]
    at cpw.mods.fml.common.network.simpleimpl.SimpleIndexedCodec.decodeInto(SimpleIndexedCodec.java:7) ~[SimpleIndexedCodec.class:1.7.10-1614.25]
    at cpw.mods.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:77) ~[FMLIndexedMessageToMessageCodec.class:1.7.10-1614.25]
    at cpw.mods.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:17) ~[FMLIndexedMessageToMessageCodec.class:1.7.10-1614.25]
    at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81) ~[MessageToMessageCodec$2.class:?]
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89) ~[MessageToMessageDecoder.class:?]
    ... 13 more
Caused by: java.lang.IndexOutOfBoundsException: Index: 256, Size: 67
    at java.util.ArrayList.rangeCheck(Unknown Source) ~[?:1.8.0_60]
    at java.util.ArrayList.get(Unknown Source) ~[?:1.8.0_60]
    at cn.lambdalib.s11n.network.NetworkS11n.readTypeIndex(NetworkS11n.java:152) ~[NetworkS11n.class:?]
    at cn.lambdalib.s11n.network.NetworkS11n.deserialize(NetworkS11n.java:238) ~[NetworkS11n.class:?]
    at cn.lambdalib.s11n.network.NetworkMessage$Message.fromBytes(NetworkMessage.java:337) ~[NetworkMessage$Message.class:?]
    at cpw.mods.fml.common.network.simpleimpl.SimpleIndexedCodec.decodeInto(SimpleIndexedCodec.java:17) ~[SimpleIndexedCodec.class:1.7.10-1614.25]
    at cpw.mods.fml.common.network.simpleimpl.SimpleIndexedCodec.decodeInto(SimpleIndexedCodec.java:7) ~[SimpleIndexedCodec.class:1.7.10-1614.25]
    at cpw.mods.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:77) ~[FMLIndexedMessageToMessageCodec.class:1.7.10-1614.25]
    at cpw.mods.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:17) ~[FMLIndexedMessageToMessageCodec.class:1.7.10-1614.25]
    at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81) ~[MessageToMessageCodec$2.class:?]
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89) ~[MessageToMessageDecoder.class:?]
    ... 13 more
[11:48:13] [Server thread/ERROR]: SimpleChannelHandlerWrapper exception
io.netty.handler.codec.DecoderException: java.lang.RuntimeException: Error deserializing network message itn_query_init@cn.lambdalib.util.datapart.EntityData@693ab3d9
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:99) ~[MessageToMessageDecoder.class:?]
    at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[MessageToMessageCodec.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
    at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?]
    at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:1.7.10-1614.25]
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?]
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:999) [MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:817) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:675) [MinecraftServer.class:?]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_60]
Caused by: java.lang.RuntimeException: Error deserializing network message itn_query_init@cn.lambdalib.util.datapart.EntityData@693ab3d9
    at cn.lambdalib.s11n.network.NetworkMessage$Message.fromBytes(NetworkMessage.java:343) ~[NetworkMessage$Message.class:?]
    at cpw.mods.fml.common.network.simpleimpl.SimpleIndexedCodec.decodeInto(SimpleIndexedCodec.java:17) ~[SimpleIndexedCodec.class:1.7.10-1614.25]
    at cpw.mods.fml.common.network.simpleimpl.SimpleIndexedCodec.decodeInto(SimpleIndexedCodec.java:7) ~[SimpleIndexedCodec.class:1.7.10-1614.25]
    at cpw.mods.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:77) ~[FMLIndexedMessageToMessageCodec.class:1.7.10-1614.25]
    at cpw.mods.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:17) ~[FMLIndexedMessageToMessageCodec.class:1.7.10-1614.25]
    at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81) ~[MessageToMessageCodec$2.class:?]
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89) ~[MessageToMessageDecoder.class:?]
    ... 13 more
Caused by: java.lang.IndexOutOfBoundsException: Index: 256, Size: 67
    at java.util.ArrayList.rangeCheck(Unknown Source) ~[?:1.8.0_60]
    at java.util.ArrayList.get(Unknown Source) ~[?:1.8.0_60]
    at cn.lambdalib.s11n.network.NetworkS11n.readTypeIndex(NetworkS11n.java:152) ~[NetworkS11n.class:?]
    at cn.lambdalib.s11n.network.NetworkS11n.deserialize(NetworkS11n.java:238) ~[NetworkS11n.class:?]
    at cn.lambdalib.s11n.network.NetworkMessage$Message.fromBytes(NetworkMessage.java:337) ~[NetworkMessage$Message.class:?]
    at cpw.mods.fml.common.network.simpleimpl.SimpleIndexedCodec.decodeInto(SimpleIndexedCodec.java:17) ~[SimpleIndexedCodec.class:1.7.10-1614.25]
    at cpw.mods.fml.common.network.simpleimpl.SimpleIndexedCodec.decodeInto(SimpleIndexedCodec.java:7) ~[SimpleIndexedCodec.class:1.7.10-1614.25]
    at cpw.mods.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:77) ~[FMLIndexedMessageToMessageCodec.class:1.7.10-1614.25]
    at cpw.mods.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:17) ~[FMLIndexedMessageToMessageCodec.class:1.7.10-1614.25]
    at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81) ~[MessageToMessageCodec$2.class:?]
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89) ~[MessageToMessageDecoder.class:?]
    ... 13 more
[11:48:13] [Server thread/ERROR]: There was a critical exception handling a packet on channel LambdaLib
io.netty.handler.codec.DecoderException: java.lang.RuntimeException: Error deserializing network message itn_query_init@cn.lambdalib.util.datapart.EntityData@693ab3d9
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:99) ~[MessageToMessageDecoder.class:?]
    at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[MessageToMessageCodec.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[DefaultChannelPipeline.class:?]
    at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[EmbeddedChannel.class:?]
    at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:1.7.10-1614.25]
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?]
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:999) [MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:817) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:675) [MinecraftServer.class:?]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_60]
Caused by: java.lang.RuntimeException: Error deserializing network message itn_query_init@cn.lambdalib.util.datapart.EntityData@693ab3d9
    at cn.lambdalib.s11n.network.NetworkMessage$Message.fromBytes(NetworkMessage.java:343) ~[NetworkMessage$Message.class:?]
    at cpw.mods.fml.common.network.simpleimpl.SimpleIndexedCodec.decodeInto(SimpleIndexedCodec.java:17) ~[SimpleIndexedCodec.class:1.7.10-1614.25]
    at cpw.mods.fml.common.network.simpleimpl.SimpleIndexedCodec.decodeInto(SimpleIndexedCodec.java:7) ~[SimpleIndexedCodec.class:1.7.10-1614.25]
    at cpw.mods.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:77) ~[FMLIndexedMessageToMessageCodec.class:1.7.10-1614.25]
    at cpw.mods.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:17) ~[FMLIndexedMessageToMessageCodec.class:1.7.10-1614.25]
    at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81) ~[MessageToMessageCodec$2.class:?]
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89) ~[MessageToMessageDecoder.class:?]
    ... 13 more
Caused by: java.lang.IndexOutOfBoundsException: Index: 256, Size: 67
    at java.util.ArrayList.rangeCheck(Unknown Source) ~[?:1.8.0_60]
    at java.util.ArrayList.get(Unknown Source) ~[?:1.8.0_60]
    at cn.lambdalib.s11n.network.NetworkS11n.readTypeIndex(NetworkS11n.java:152) ~[NetworkS11n.class:?]
    at cn.lambdalib.s11n.network.NetworkS11n.deserialize(NetworkS11n.java:238) ~[NetworkS11n.class:?]
    at cn.lambdalib.s11n.network.NetworkMessage$Message.fromBytes(NetworkMessage.java:337) ~[NetworkMessage$Message.class:?]
    at cpw.mods.fml.common.network.simpleimpl.SimpleIndexedCodec.decodeInto(SimpleIndexedCodec.java:17) ~[SimpleIndexedCodec.class:1.7.10-1614.25]
    at cpw.mods.fml.common.network.simpleimpl.SimpleIndexedCodec.decodeInto(SimpleIndexedCodec.java:7) ~[SimpleIndexedCodec.class:1.7.10-1614.25]
    at cpw.mods.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:77) ~[FMLIndexedMessageToMessageCodec.class:1.7.10-1614.25]
    at cpw.mods.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:17) ~[FMLIndexedMessageToMessageCodec.class:1.7.10-1614.25]
    at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81) ~[MessageToMessageCodec$2.class:?]
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89) ~[MessageToMessageDecoder.class:?]
    ... 13 more
[11:48:13] [Server thread/INFO]: KSkun lost connection: A fatal error has occured, this connection is terminated
[11:48:13] [Server thread/INFO]: KSkun left the game.
```

**Comment by Paindar** [comment]
自古thermos崩溃多,close.
