### ISSUE TITLE
[1.0.1]Crash while opening the portable ability developer.

### ISSUE THREAD

**Issue by nirvanaxiao6** [LambdaInnovation/AcademyCraft#430]
Crash-report is below.
Description: Unexpected error

java.lang.ExceptionInInitializerError
at cn.academy.ability.client.ui.DeveloperUI$.cn$academy$ability$client$ui$DeveloperUI$$build$1(SkillTree.scala:70)
at cn.academy.ability.client.ui.DeveloperUI$.apply(SkillTree.scala:77)
at cn.academy.ability.client.ui.DeveloperUI.apply(SkillTree.scala)
at cn.academy.ability.item.ItemDeveloper.displayGui(ItemDeveloper.java:49)
at cn.academy.ability.item.ItemDeveloper.func_77659_a(ItemDeveloper.java:41)
at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:146)
at net.minecraft.client.multiplayer.PlayerControllerMP.func_78769_a(PlayerControllerMP.java:377)
at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1475)
at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1953)
at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
at net.minecraft.client.main.Main.main(SourceFile:148)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.jackhuang.hellominecraft.launcher.Launcher.main(Launcher.java:115)
Caused by: java.lang.IllegalStateException: Function is not supported
at org.lwjgl.BufferChecks.checkFunctionAddress(BufferChecks.java:58)
at org.lwjgl.opengl.GL30.glGenerateMipmap(GL30.java:1238)
at cn.academy.core.client.Resources$1.<init>(Resources.java:131)
at cn.academy.core.client.Resources.preloadMipmapTexture(Resources.java:111)
at cn.academy.ability.client.ui.Common$.<init>(SkillTree.scala:174)
at cn.academy.ability.client.ui.Common$.<clinit>(SkillTree.scala)
... 23 more

**Comment by WeAthFoLD** [comment]
Wontfix: Video card or video card driver is too old to support `glGenerateMipmap`.

**Comment by KSkun** [comment]
@WeAthFoLD Maybe supported GL version is too old. <- This is the main reason guys!
