### ISSUE TITLE
[1.0.2] Crash when MC loading.

### ISSUE THREAD

**Issue by KSkun** [LambdaInnovation/AcademyCraft#436]
前几天游戏运行正常，现在不知为什么进不去游戏，在显示出MOJANG的logo时闪退。去掉AcademyCraft及其前置就能进入游戏，只留下AcademyCraft及其前置也无法进入游戏。没有在游戏中崩溃过。
确定在64位Java8下运行游戏，64位Windows7，正版客户端，多个存档一起玩。

目前收集到的信息：
MC版本：1.7.10
Forge版本：10.13.4.1558
最近一次崩溃报告（附件不能上传）：
```
---- Minecraft Crash Report ----
// I feel sad now :(

Time: 16-7-22 上午9:40
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: cn/academy/vanilla/electromaster/CatElectromaster
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:559)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: cn/academy/vanilla/electromaster/CatElectromaster
	at cn.academy.vanilla.ModuleVanilla.<clinit>(ModuleVanilla.java:60)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:260)
	at cn.lambdalib.annoreg.core.RegistrationManager.prepareClass(RegistrationManager.java:52)
	at cn.lambdalib.annoreg.core.RegistrationManager.loadClasses(RegistrationManager.java:44)
	at cn.lambdalib.annoreg.core.RegistrationManager.registerAll(RegistrationManager.java:142)
	at cn.lambdalib.annoreg.core.RegistrationManager.registerAll(RegistrationManager.java:155)
	at cn.lambdalib.core.LambdaLib.preInit(LambdaLib.java:69)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
	... 10 more
Caused by: java.lang.ClassNotFoundException: cn.academy.vanilla.electromaster.CatElectromaster
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 44 more
Caused by: java.lang.ArrayIndexOutOfBoundsException


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 340158216 bytes (324 MB) / 1222451200 bytes (1165 MB) up to 2040135680 bytes (1945 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn1024M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 Optifine OptiFine_1.7.10_HD_U_C1 44 mods loaded, 44 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
	UCH	Forge{10.13.4.1558} [Minecraft Forge] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
	UCH	InputFix{1.7.x-v2} [InputFix] (minecraft.jar) 
	UCH	LambdaLib|Core{1.2.1} [LambdaLib|Core] (minecraft.jar) 
	UCH	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCH	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCE	LambdaLib{1.2.1} [LambdaLib] (【AcademyCraft】LambdaLib-1.2.1.jar) 
	UCE	academy-craft{1.0.2} [Academy Craft] (【AcademyCraft】AcademyCraft-1.0.2.jar) 
	UCH	CoFHCore{1.7.10R3.0.3} [CoFH Core] (【TE核心】CoFHCore-[1.7.10]3.0.3-303.jar) 
	UCH	flansmod{4.10.0} [Flan's Mod] (【Flan】Flans Mod-1.7.10-4.10.0.jar) 
	UCH	ThermalFoundation{1.7.10R1.2.0} [Thermal Foundation] (【TE基础】ThermalFoundation-[1.7.10]1.2.0-102.jar) 
	UCH	ThermalExpansion{1.7.10R4.0.3B1} [Thermal Expansion] (【TE】ThermalExpansion-[1.7.10]4.0.3B1-218.jar) 
	UCH	ThermalDynamics{1.7.10R1.1.0} [Thermal Dynamics] (【TE管道】ThermalDynamics-[1.7.10]1.1.0-161.jar) 
	UCH	IC2{2.2.822-experimental} [IndustrialCraft 2] (【工业实验】industrialcraft-2-2.2.822-experimental.jar) 
	UCH	BuildCraft|Core{7.1.16} [BuildCraft] (【建筑7.1】buildcraft-7.1.16.jar) 
	UCH	BuildCraft|Builders{7.1.16} [BC Builders] (【建筑7.1】buildcraft-7.1.16.jar) 
	UCH	BuildCraft|Transport{7.1.16} [BC Transport] (【建筑7.1】buildcraft-7.1.16.jar) 
	UCH	BuildCraft|Energy{7.1.16} [BC Energy] (【建筑7.1】buildcraft-7.1.16.jar) 
	UCH	BuildCraft|Silicon{7.1.16} [BC Silicon] (【建筑7.1】buildcraft-7.1.16.jar) 
	UCH	BuildCraft|Robotics{7.1.16} [BC Robotics] (【建筑7.1】buildcraft-7.1.16.jar) 
	UCH	BuildCraft|Factory{7.1.16} [BC Factory] (【建筑7.1】buildcraft-7.1.16.jar) 
	UCH	openmodularturrets{2.1.4-183} [Open Modular Turrets] (【开放式炮塔】OpenModularTurrets-1.7.10-2.1.4-183（界面汉化）.jar) 
	UCH	FastCraft{1.21} [FastCraft] (【快速工艺】fastcraft-1.21.jar) 
	UCH	MonsterSwarm{1.0.4} [Monster Swarm] (【怪物云集】MonsterSwarm-1.0.4.jar) 
	UCH	deconstruction{2.2.5} [The Deconstruction Mod] (【拆解台】拆解台[1.7.10].jar) 
	UCH	Waila{1.5.10} [Waila] (【方块显示MOD】[1.7.10].jar) 
	UCH	ForgeMultipart{1.1.2.331} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) 
	UCH	WR-CBE|Core{1.4.1.9} [WR-CBE Core] (【无线红石】WR-CBE-1.7.10-1.4.1.9-universal.jar) 
	UCH	WR-CBE|Addons{1.4.1.9} [WR-CBE Addons] (【无线红石】WR-CBE-1.7.10-1.4.1.9-universal.jar) 
	UCH	WR-CBE|Logic{1.4.1.9} [WR-CBE Logic] (【无线红石】WR-CBE-1.7.10-1.4.1.9-universal.jar) 
	UCH	TwilightForest{2.3.7} [The Twilight Forest] (【暮色森林】twilightforest-1.7.10-2.3.7.jar) 
	UCH	etfuturum{1.3.2} [Et Futurum] (【未来】[1.7.10]Et Futurum-1.3.2.jar) 
	UCH	IC2NuclearControl{2.2.1a-Yolo} [Nuclear Control 2] (【核电控制】IC2NuclearControl-2.2.1a-Yolo.jar) 
	UCH	InfernalMobs{1.6.6} [Infernal Mobs] (【精英怪】InfernalMobs-1.7.10.jar) 
	UCH	Railcraft{9.12.2.0} [Railcraft] (【铁路】Railcraft_1.7.10-9.12.2.0.jar) 
	UCH	PowerConverters{1.7.10_3.3.0-jenkins.76} [Power Converters] (【能量转换】PowerConverters-1.7.10_3.3.0-jenkins.76.jar) 
	UCH	DeadlyWorld{1.0.2} [Deadly World] (【致命世界】DeadlyWorld-1.7.10-1.0.2.jar) 
	UCH	AS_Ruins{14.7} [Ruins Spawning System] (【遗迹】Ruins-1.7.10.jar) 
	UCH	bdlib{1.9.4.109} [BD Lib] (【高级发电机前置】bdlib-1.9.4.109-mc1.7.10.jar) 
	UCH	advgenerators{0.9.19.120} [Advanced Generators] (【高级发电机】generators-0.9.19.120-mc1.7.10.jar) 
	UCH	AdvancedSolarPanel{1.7.10-3.5.1} [Advanced Solar Panels] (【高级太阳能】AdvancedSolarPanel-1.7.10-3.5.1[TFCN].jar) 
	UCH	McMultipart{1.1.2.331} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) 
	UCH	ForgeMicroblock{1.1.2.331} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) 
	CoFHCore: -[1.7.10]3.0.3-303
	ThermalFoundation: -[1.7.10]1.2.0-102
	ThermalExpansion: -[1.7.10]4.0.3B1-218
	ThermalDynamics: -[1.7.10]1.1.0-161
	List of loaded APIs: 
		* Baubles|API (1.0.1.10) from 【TE基础】ThermalFoundation-[1.7.10]1.2.0-102.jar
		* BuildCraftAPI|blocks (1.0) from 【建筑7.1】buildcraft-7.1.16.jar
		* BuildCraftAPI|blueprints (1.5) from 【建筑7.1】buildcraft-7.1.16.jar
		* BuildCraftAPI|boards (2.0) from 【建筑7.1】buildcraft-7.1.16.jar
		* BuildCraftAPI|core (2.0) from 【建筑7.1】buildcraft-7.1.16.jar
		* BuildCraftAPI|crops (1.1) from 【建筑7.1】buildcraft-7.1.16.jar
		* BuildCraftAPI|events (2.0) from 【建筑7.1】buildcraft-7.1.16.jar
		* BuildCraftAPI|facades (1.1) from 【建筑7.1】buildcraft-7.1.16.jar
		* BuildCraftAPI|filler (4.0) from 【建筑7.1】buildcraft-7.1.16.jar
		* BuildCraftAPI|fuels (2.0) from 【建筑7.1】buildcraft-7.1.16.jar
		* BuildCraftAPI|gates (4.1) from 【建筑7.1】buildcraft-7.1.16.jar
		* BuildCraftAPI|items (1.1) from 【铁路】Railcraft_1.7.10-9.12.2.0.jar
		* BuildCraftAPI|library (2.0) from 【铁路】Railcraft_1.7.10-9.12.2.0.jar
		* BuildCraftAPI|lists (1.0) from 【建筑7.1】buildcraft-7.1.16.jar
		* BuildCraftAPI|power (1.3) from 【建筑7.1】buildcraft-7.1.16.jar
		* BuildCraftAPI|recipes (4.0) from 【建筑7.1】buildcraft-7.1.16.jar
		* BuildCraftAPI|robotics (3.0) from 【建筑7.1】buildcraft-7.1.16.jar
		* BuildCraftAPI|statements (1.1) from 【建筑7.1】buildcraft-7.1.16.jar
		* BuildCraftAPI|tablet (1.0) from 【建筑7.1】buildcraft-7.1.16.jar
		* BuildCraftAPI|tiles (1.2) from 【建筑7.1】buildcraft-7.1.16.jar
		* BuildCraftAPI|tools (1.0) from 【铁路】Railcraft_1.7.10-9.12.2.0.jar
		* BuildCraftAPI|transport (4.1) from 【建筑7.1】buildcraft-7.1.16.jar
		* CoFHAPI (1.7.10R1.0.2) from 【建筑7.1】buildcraft-7.1.16.jar
		* CoFHAPI|block (1.7.10R1.0.13) from 【TE核心】CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHAPI|core (1.7.10R1.0.13) from 【TE核心】CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHAPI|energy (1.7.10R1.0.2) from 【Flan】Flans Mod-1.7.10-4.10.0.jar
		* CoFHAPI|fluid (1.7.10R1.0.13) from 【TE核心】CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHAPI|inventory (1.7.10R1.0.13) from 【TE核心】CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHAPI|item (1.7.10R1.0.13) from 【TE核心】CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHAPI|modhelpers (1.7.10R1.0.13) from 【TE核心】CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHAPI|tileentity (1.7.10R1.0.13) from 【TE核心】CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHAPI|transport (1.7.10R1.0.13) from 【TE核心】CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHAPI|world (1.7.10R1.0.13) from 【TE核心】CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib (1.7.10R1.0.3) from 【TE核心】CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|audio (1.7.10R1.0.3) from 【TE核心】CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|gui (1.7.10R1.0.3) from 【TE核心】CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|gui|container (1.7.10R1.0.3) from 【TE核心】CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|gui|element (1.7.10R1.0.3) from 【TE核心】CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|gui|element|listbox (1.7.10R1.0.3) from 【TE核心】CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|gui|slot (1.7.10R1.0.3) from 【TE核心】CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|inventory (1.7.10R1.0.3) from 【TE核心】CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|render (1.7.10R1.0.3) from 【TE核心】CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|render|particle (1.7.10R1.0.3) from 【TE核心】CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|util (1.7.10R1.0.3) from 【TE核心】CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|util|helpers (1.7.10R1.0.3) from 【TE核心】CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|util|position (1.7.10R1.0.3) from 【TE核心】CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|world (1.7.10R1.0.3) from 【TE核心】CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|world|feature (1.7.10R1.0.3) from 【TE核心】CoFHCore-[1.7.10]3.0.3-303.jar
		* IC2API (1.0) from 【工业实验】industrialcraft-2-2.2.822-experimental.jar
		* NuclearControlAPI (v1.0.5) from 【核电控制】IC2NuclearControl-2.2.1a-Yolo.jar
		* RailcraftAPI|bore (1.0.0) from 【铁路】Railcraft_1.7.10-9.12.2.0.jar
		* RailcraftAPI|carts (1.6.0) from 【铁路】Railcraft_1.7.10-9.12.2.0.jar
		* RailcraftAPI|core (1.5.0) from 【铁路】Railcraft_1.7.10-9.12.2.0.jar
		* RailcraftAPI|crafting (1.0.0) from 【铁路】Railcraft_1.7.10-9.12.2.0.jar
		* RailcraftAPI|electricity (2.0.0) from 【铁路】Railcraft_1.7.10-9.12.2.0.jar
		* RailcraftAPI|events (1.0.0) from 【铁路】Railcraft_1.7.10-9.12.2.0.jar
		* RailcraftAPI|fuel (1.0.0) from 【铁路】Railcraft_1.7.10-9.12.2.0.jar
		* RailcraftAPI|helpers (1.1.0) from 【铁路】Railcraft_1.7.10-9.12.2.0.jar
		* RailcraftAPI|items (1.0.0) from 【铁路】Railcraft_1.7.10-9.12.2.0.jar
		* RailcraftAPI|locomotive (1.1.0) from 【铁路】Railcraft_1.7.10-9.12.2.0.jar
		* RailcraftAPI|signals (2.3.0) from 【铁路】Railcraft_1.7.10-9.12.2.0.jar
		* RailcraftAPI|tracks (2.3.0) from 【铁路】Railcraft_1.7.10-9.12.2.0.jar
		* Thaumcraft|API (4.2.2.0) from 【铁路】Railcraft_1.7.10-9.12.2.0.jar
		* WailaAPI (1.2) from 【方块显示MOD】[1.7.10].jar
```
----------------------------------------------------------------------------------------------------------------------------
只有AcademyCraft及其前置时的崩溃报告：
```
---- Minecraft Crash Report ----
// My bad.

Time: 16-7-22 上午10:06
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: cn/academy/vanilla/electromaster/CatElectromaster
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:559)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: cn/academy/vanilla/electromaster/CatElectromaster
	at cn.academy.vanilla.ModuleVanilla.<clinit>(ModuleVanilla.java:60)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:260)
	at cn.lambdalib.annoreg.core.RegistrationManager.prepareClass(RegistrationManager.java:52)
	at cn.lambdalib.annoreg.core.RegistrationManager.loadClasses(RegistrationManager.java:44)
	at cn.lambdalib.annoreg.core.RegistrationManager.registerAll(RegistrationManager.java:142)
	at cn.lambdalib.annoreg.core.RegistrationManager.registerAll(RegistrationManager.java:155)
	at cn.lambdalib.core.LambdaLib.preInit(LambdaLib.java:69)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
	... 10 more
Caused by: java.lang.ClassNotFoundException: cn.academy.vanilla.electromaster.CatElectromaster
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 45 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 6
	at org.objectweb.asm.ClassReader.readShort(Unknown Source)
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at cpw.mods.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper.findAndMergeSuperMaps(FMLDeobfuscatingRemapper.java:345)
	at cpw.mods.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper.getFieldMap(FMLDeobfuscatingRemapper.java:304)
	at cpw.mods.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper.mapFieldName(FMLDeobfuscatingRemapper.java:245)
	at cpw.mods.fml.common.asm.transformers.deobf.FMLRemappingAdapter$StaticFixingMethodVisitor.visitFieldInsn(FMLRemappingAdapter.java:59)
	at org.objectweb.asm.ClassReader.a(Unknown Source)
	at org.objectweb.asm.ClassReader.b(Unknown Source)
	at org.objectweb.asm.ClassReader.accept(Unknown Source)
	at org.objectweb.asm.ClassReader.accept(Unknown Source)
	at cpw.mods.fml.common.asm.transformers.DeobfuscationTransformer.transform(DeobfuscationTransformer.java:37)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 47 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 627149680 bytes (598 MB) / 1132343296 bytes (1079 MB) up to 2040135680 bytes (1945 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn1024M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 9 mods loaded, 9 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
	UCH	Forge{10.13.4.1558} [Minecraft Forge] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
	UCH	LambdaLib|Core{1.2.1} [LambdaLib|Core] (minecraft.jar) 
	UCE	LambdaLib{1.2.1} [LambdaLib] (【AcademyCraft】LambdaLib-1.2.1.jar) 
	UCE	academy-craft{1.0.2} [Academy Craft] (【AcademyCraft】AcademyCraft-1.0.2.jar) 
	UCH	ForgeMultipart{1.1.2.331} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) 
	UCH	McMultipart{1.1.2.331} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) 
	UCH	ForgeMicroblock{1.1.2.331} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) 
```
-------------------------------------------------------------------------------------------------------------------------------------
安装的MOD（这些MOD都可以进入游戏）：
【TE基础】ThermalFoundation-[1.7.10]1.2.0-102.jar
【TE核心】CoFHCore-[1.7.10]3.0.3-303.jar
【TE】ThermalExpansion-[1.7.10]4.0.3B1-218.jar
【TE管道】ThermalDynamics-[1.7.10]1.1.0-161.jar
【工业实验】industrialcraft-2-2.2.822-experimental.jar
【核电控制】IC2NuclearControl-2.2.1a-Yolo.jar
【高级太阳能】AdvancedSolarPanel-1.7.10-3.5.1[TFCN].jar
【高级发电机前置】bdlib-1.9.4.109-mc1.7.10.jar
【高级发电机】generators-0.9.19.120-mc1.7.10.jar
【建筑7.1】buildcraft-7.1.16.jar
【铁路】Railcraft_1.7.10-9.12.2.0.jar
【能量转换】PowerConverters-1.7.10_3.3.0-jenkins.76.jar
【Flan】Flans Mod-1.7.10-4.10.0.jar
【AcademyCraft】AcademyCraft-1.0.2.jar
【AcademyCraft】LambdaLib-1.2.1.jar
【开放式炮塔】OpenModularTurrets-1.7.10-2.1.4-183（界面汉化）.jar
【怪物云集】MonsterSwarm-1.0.4.jar
【精英怪】InfernalMobs-1.7.10.jar
【遗迹】Ruins-1.7.10.jar
【致命世界】DeadlyWorld-1.7.10-1.0.2.jar
【无线红石】WR-CBE-1.7.10-1.4.1.9-universal.jar
【未来】[1.7.10]Et Futurum-1.3.2.jar
【暮色森林】twilightforest-1.7.10-2.3.7.jar
【鸡骨头 (NEI)】CodeChickenCore-1.7.10-1.0.7.47-universal.jar
【方块显示MOD】[1.7.10].jar
【更好的FPS】BetterFps-1.0.1.jar
【快速工艺】fastcraft-1.21.jar
【OptiFine】OptiFine_1.7.10_HD_U_C1[hukk汉化].jar
【1.7.10输入补丁】InputFix 输入修正 1.7.x-v2.jar
【拆解台】拆解台[1.7.10].jar

**Comment by KSkun** [comment]
1.0.3 Redo the CatElectroMaster#<clinit>. This issue is out-of-date.
