### ISSUE TITLE
[1.0.3] 磁场控制服务器行为异常

### ISSUE THREAD

**Issue by 867163314** [LambdaInnovation/AcademyCraft#457]
在服务器里没法扔方块，但是消耗物品和cp，而且不增加熟练度，音效不消失

**Comment by KSkun** [comment]
请注明你的服务端、Forge版本等信息。如果有崩溃或者异常信息也请附上。

**Comment by 867163314** [comment]
服务端forge1558，用了磁场控制之后服务端开始刷代码，而且音效不消失

**Comment by KSkun** [comment]
请问服务端是Thermos吗？刷代码的内容能贴一部分出来吗？

**Comment by 867163314** [comment]
服务端thermos1558

**Comment by 867163314** [comment]
而且关联技能熟练度不增加

**Comment by KSkun** [comment]
刷代码的内容能贴一部分出来吗？

**Comment by 867163314** [comment]
明天可以吗？

**Comment by 867163314** [comment]
[18:41:59] [Server thread/INFO]: False issued server command: /give False 42
[18:42:09] [Server thread/FATAL]: Error during network message.
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_101]
	at cn.lambdalib.s11n.network.NetworkMessage$1.invoke(NetworkMessage.java:290) ~[NetworkMessage$1.class:?]
	at cn.lambdalib.s11n.network.NetworkMessage.invokeListener(NetworkMessage.java:218) [NetworkMessage.class:?]
	at cn.lambdalib.s11n.network.NetworkMessage.processMessage(NetworkMessage.java:199) [NetworkMessage.class:?]
	at cn.lambdalib.s11n.network.NetworkMessage.sendToSelf(NetworkMessage.java:121) [NetworkMessage.class:?]
	at cn.academy.ability.api.context.ContextManager$ServerManager.hBeginLink(ContextManager.java:428) [ContextManager$ServerManager.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_101]
	at cn.lambdalib.s11n.network.NetworkMessage$1.invoke(NetworkMessage.java:290) [NetworkMessage$1.class:?]
	at cn.lambdalib.s11n.network.NetworkMessage.invokeListener(NetworkMessage.java:218) [NetworkMessage.class:?]
	at cn.lambdalib.s11n.network.NetworkMessage.processMessage(NetworkMessage.java:199) [NetworkMessage.class:?]
	at cn.lambdalib.s11n.network.NetworkMessage.access$000(NetworkMessage.java:56) [NetworkMessage.class:?]
	at cn.lambdalib.s11n.network.NetworkMessage$Handler.onMessage(NetworkMessage.java:355) [NetworkMessage$Handler.class:?]
	at cn.lambdalib.s11n.network.NetworkMessage$Handler.onMessage(NetworkMessage.java:349) [NetworkMessage$Handler.class:?]
	at cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:37) [SimpleChannelHandlerWrapper.class:1.7.10-1614.57]
	at cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:17) [SimpleChannelHandlerWrapper.class:1.7.10-1614.57]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) [SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [MessageToMessageDecoder.class:?]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) [MessageToMessageCodec.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:1.7.10-1614.57]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1023) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
Caused by: java.lang.ClassCastException: gnu.trove.decorator.TIntObjectMapDecorator cannot be cast to java.util.HashMap
	at cn.lambdalib.util.helper.EntitySyncer.<init>(EntitySyncer.java:146) ~[EntitySyncer.class:?]
	at cn.academy.vanilla.electromaster.MagManipEntityBlock.func_70088_a(MagManip.scala:248) ~[MagManipEntityBlock.class:?]
	at net.minecraft.entity.Entity.<init>(Entity.java:231) ~[sa.class:?]
	at cn.lambdalib.util.entityx.EntityAdvanced.<init>(EntityAdvanced.java:22) ~[EntityAdvanced.class:?]
	at cn.academy.core.entity.EntityBlock.<init>(EntityBlock.java:82) ~[EntityBlock.class:?]
	at cn.academy.vanilla.electromaster.MagManipEntityBlock.<init>(MagManip.scala:205) ~[MagManipEntityBlock.class:?]
	at cn.academy.vanilla.electromaster.MagManipEntityBlock.<init>(MagManip.scala:229) ~[MagManipEntityBlock.class:?]
	at cn.academy.vanilla.electromaster.MagManipContext.s_makeAlive(MagManip.scala:91) ~[MagManipContext.class:?]
	... 38 more
[18:42:10] [Server thread/FATAL]: Error during network message.
java.lang.reflect.InvocationTargetException

**Comment by 867163314** [comment]
然后开始刷这个
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_101]
	at cn.lambdalib.s11n.network.NetworkMessage$1.invoke(NetworkMessage.java:290) ~[NetworkMessage$1.class:?]
	at cn.lambdalib.s11n.network.NetworkMessage.invokeListener(NetworkMessage.java:218) [NetworkMessage.class:?]
	at cn.lambdalib.s11n.network.NetworkMessage.processMessage(NetworkMessage.java:199) [NetworkMessage.class:?]
	at cn.lambdalib.s11n.network.NetworkMessage.sendToSelf(NetworkMessage.java:121) [NetworkMessage.class:?]
	at cn.academy.ability.api.context.ContextManager$ServerManager.__onServerTick(ContextManager.java:481) [ContextManager$ServerManager.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_52_ServerManager___onServerTick_ServerTickEvent.invoke(.dynamic) [?:1.7.10-1614.57]

**Comment by 867163314** [comment]
一段时间后刷这个
at sun.reflect.GeneratedMethodAccessor118.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_101]
	at cn.lambdalib.s11n.network.NetworkMessage$1.invoke(NetworkMessage.java:290) ~[NetworkMessage$1.class:?]
	at cn.lambdalib.s11n.network.NetworkMessage.invokeListener(NetworkMessage.java:218) [NetworkMessage.class:?]
	at cn.lambdalib.s11n.network.NetworkMessage.processMessage(NetworkMessage.java:199) [NetworkMessage.class:?]
	at cn.lambdalib.s11n.network.NetworkMessage.sendToSelf(NetworkMessage.java:121) [NetworkMessage.class:?]
	at cn.academy.ability.api.context.ContextManager$ServerManager.__onServerTick(ContextManager.java:481) [ContextManager$ServerManager.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_52_ServerManager___onServerTick_ServerTickEvent.invoke(.dynamic) [?:1.7.10-1614.57]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) [ASMEventHandler.class:1.7.10-1614.57]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:1.7.10-1614.57]
	at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:251) [FMLCommonHandler.class:1.7.10-1614.57]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:894) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
Caused by: java.lang.NullPointerException
	at cn.academy.vanilla.electromaster.MagManipContext.updateMoveTo(MagManip.scala:170) ~[MagManipContext.class:?]
	at cn.academy.vanilla.electromaster.MagManipContext.s_tick(MagManip.scala:127) ~[MagManipContext.class:?]
	... 15 more
[18:42:13] [Server thread/FATAL]: Error during network message.
java.lang.reflect.InvocationTargetException
