### ISSUE TITLE
[1.0.3] Vector Deviation/Reflection crash

### ISSUE THREAD

**Issue by KillerDawg334** [LambdaInnovation/AcademyCraft#458]
I would like to report something thats been happening with my game:
Ever since I've updated to 1.0.3, every time I use either Reflection or Deviation, my game would suddenly hang and crash! I've repeated this many times using other abilities in the VecManip skill tree and they all work as intended except the two I've mentioned. I have other mods installed with Academycraft and at this point I'm not sure if I've installed the mod wrong or there's a conflict with the other mods.

Note: I have not added any other mods after updating Academycraft and was using 1.0.1 before 1.0.3

**Comment by KSkun** [comment]
Could you give us the crash-report. It's usually in /.minecraft/crash-reports/ folder.

**Comment by KillerDawg334** [comment]
Here's the crash report from my last game:

[crash-2016-07-30_21.05.01-client.txt](https://github.com/LambdaInnovation/AcademyCraft/files/392248/crash-2016-07-30_21.05.01-client.txt)

Also thanks for your hard work and effort put into the mod

**Comment by KSkun** [comment]
```
---- Minecraft Crash Report ----
// I feel sad now :(

Time: 7/30/16 9:05 PM
Description: Unexpected error

java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.google.common.base.Throwables.propagate(Throwables.java:160)
	at cn.academy.ability.api.context.ClientContextRegistry.lambda$registerClass$22(ClientContextRegistry.java:33)
	at cn.academy.ability.api.context.Context.constructClientContexts(Context.java:83)
	at cn.academy.ability.api.context.Context.<init>(Context.java:76)
	at cn.academy.vanilla.vecmanip.skills.VecDeviationContext.<init>(VecDeviation.scala:61)
	at cn.academy.vanilla.vecmanip.skills.VecDeviation$$anonfun$activate$1.apply(VecDeviation.scala:31)
	at cn.academy.vanilla.vecmanip.skills.VecDeviation$$anonfun$activate$1.apply(VecDeviation.scala:31)
	at cn.academy.ability.api.ctrl.KeyDelegates$$anon$1.onKeyDown(KeyDelegates.scala:25)
	at cn.academy.ability.api.context.ClientRuntime$Events.onClientTick(ClientRuntime.java:299)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_272_Events_onClientTick_ClientTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at cpw.mods.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:325)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1587)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at cn.academy.ability.api.context.ClientContextRegistry.lambda$registerClass$22(ClientContextRegistry.java:31)
	... 21 more
Caused by: cn.lambdalib.pipeline.api.ProgramCreationException: COMPILE: ERROR: 0:1: '' :  version '330' is not supported
ERROR: 0:6: 'layout' : syntax error: syntax error

	at cn.lambdalib.pipeline.api.ShaderProgram.linkShader(ShaderProgram.java:48)
	at cn.lambdalib.pipeline.api.ShaderProgram.load(ShaderProgram.java:17)
	at cn.lambdalib.pipeline.api.ShaderProgram.load(ShaderProgram.java:33)
	at cn.academy.vanilla.vecmanip.client.effect.WaveEffectUI.<init>(WaveEffectUI.scala:49)
	at cn.academy.vanilla.vecmanip.skills.VecDeviationContextC.<init>(VecDeviation.scala:139)
	... 26 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.google.common.base.Throwables.propagate(Throwables.java:160)
	at cn.academy.ability.api.context.ClientContextRegistry.lambda$registerClass$22(ClientContextRegistry.java:33)
	at cn.academy.ability.api.context.Context.constructClientContexts(Context.java:83)
	at cn.academy.ability.api.context.Context.<init>(Context.java:76)
	at cn.academy.vanilla.vecmanip.skills.VecDeviationContext.<init>(VecDeviation.scala:61)
	at cn.academy.vanilla.vecmanip.skills.VecDeviation$$anonfun$activate$1.apply(VecDeviation.scala:31)
	at cn.academy.vanilla.vecmanip.skills.VecDeviation$$anonfun$activate$1.apply(VecDeviation.scala:31)
	at cn.academy.ability.api.ctrl.KeyDelegates$$anon$1.onKeyDown(KeyDelegates.scala:25)
	at cn.academy.ability.api.context.ClientRuntime$Events.onClientTick(ClientRuntime.java:299)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_272_Events_onClientTick_ClientTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at cpw.mods.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:325)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1587)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['KillerDawg334'/268, l='MpServer', x=-190.56, y=85.62, z=91.64]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-232,64,36), Chunk: (at 8,4,4 in -15,2; contains blocks -240,0,32 to -225,255,47), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 3395177 game time, 4616897 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 138 total; [EntityZombie['Zombie'/12547, l='MpServer', x=-266.59, y=50.00, z=154.94], EntityZombie['Zombie'/12548, l='MpServer', x=-268.16, y=51.00, z=160.91], EntityCreeper['Creeper'/7429, l='MpServer', x=-201.63, y=61.00, z=135.16], EntityBat['Bat'/7941, l='MpServer', x=-200.25, y=62.20, z=132.94], EntityZombie['Zombie'/12549, l='MpServer', x=-266.31, y=51.00, z=159.31], EntityBat['Bat'/7942, l='MpServer', x=-209.50, y=61.00, z=137.88], EntityCreeper['Creeper'/7431, l='MpServer', x=-204.50, y=61.00, z=133.50], EntityZombie['Zombie'/7435, l='MpServer', x=-200.50, y=62.00, z=140.06], EntityZombie['Zombie'/7436, l='MpServer', x=-201.63, y=61.00, z=136.03], SmokeEffect['unknown'/19735, l='MpServer', x=-185.54, y=85.91, z=88.27], EntitySkeleton['Skeleton'/5147, l='MpServer', x=-211.66, y=28.00, z=32.00], SmokeEffect['unknown'/19740, l='MpServer', x=-181.71, y=84.73, z=84.10], EntityCreeper['Creeper'/5150, l='MpServer', x=-201.00, y=28.00, z=33.63], SmokeEffect['unknown'/19998, l='MpServer', x=-185.22, y=86.05, z=91.84], EntitySkeleton['Skeleton'/13855, l='MpServer', x=-256.50, y=29.00, z=151.50], EntityWitch['Witch'/5151, l='MpServer', x=-120.50, y=42.00, z=98.50], EntitySkeleton['Skeleton'/13856, l='MpServer', x=-250.09, y=28.00, z=163.53], SmokeEffect['unknown'/19747, l='MpServer', x=-180.47, y=84.89, z=78.41], SmokeEffect['unknown'/19757, l='MpServer', x=-186.37, y=85.56, z=88.24], EntityBat['Bat'/5938, l='MpServer', x=-182.45, y=33.90, z=13.97], EntityBat['Bat'/11827, l='MpServer', x=-220.92, y=27.26, z=21.73], EntityBat['Bat'/11829, l='MpServer', x=-216.58, y=20.07, z=18.48], EntitySkeleton['Skeleton'/4150, l='MpServer', x=-212.50, y=61.00, z=138.50], EntityBat['Bat'/11831, l='MpServer', x=-202.60, y=28.84, z=29.43], SmokeEffect['unknown'/19771, l='MpServer', x=-188.66, y=85.99, z=90.20], EntitySkeleton['Skeleton'/6460, l='MpServer', x=-262.50, y=46.00, z=106.50], EntityZombie['Zombie'/20029, l='MpServer', x=-261.50, y=45.00, z=123.50], EntityClientPlayerMP['KillerDawg334'/268, l='MpServer', x=-190.56, y=85.62, z=91.64], SmokeEffect['unknown'/19776, l='MpServer', x=-180.11, y=84.80, z=81.54], EntitySkeleton['Skeleton'/15179, l='MpServer', x=-125.50, y=47.00, z=103.50], EntitySkeleton['Skeleton'/15180, l='MpServer', x=-124.41, y=46.00, z=100.94], EntityZombie['Zombie'/3917, l='MpServer', x=-214.50, y=62.00, z=129.50], SmokeEffect['unknown'/19789, l='MpServer', x=-179.11, y=86.51, z=84.54], EntitySkeleton['Skeleton'/9806, l='MpServer', x=-272.41, y=41.00, z=98.53], EntityItem['item.item.feather'/2896, l='MpServer', x=-253.31, y=69.13, z=87.13], SmokeEffect['unknown'/19794, l='MpServer', x=-180.92, y=86.43, z=85.49], EntityZombie['Zombie'/87, l='MpServer', x=-271.00, y=37.00, z=85.44], SmokeEffect['unknown'/19799, l='MpServer', x=-178.88, y=85.98, z=82.07], SmokeEffect['unknown'/19807, l='MpServer', x=-189.35, y=85.56, z=91.44], EntityZombie['Zombie'/107, l='MpServer', x=-272.00, y=36.00, z=76.56], EntityZombie['Zombie'/112, l='MpServer', x=-271.50, y=18.00, z=144.03], EntityZombie['Zombie'/7026, l='MpServer', x=-247.91, y=22.00, z=32.47], EntitySquid['Squid'/7541, l='MpServer', x=-253.91, y=58.00, z=45.50], EntityZombie['Zombie'/9846, l='MpServer', x=-135.50, y=23.00, z=53.50], SmokeEffect['unknown'/19830, l='MpServer', x=-178.84, y=86.00, z=83.54], EntityItem['item.item.dyePowder.black'/122, l='MpServer', x=-252.22, y=59.13, z=46.59], EntityChicken['Chicken'/125, l='MpServer', x=-253.69, y=70.00, z=83.75], EntityZombie['Zombie'/126, l='MpServer', x=-245.74, y=44.00, z=119.42], EntityZombie['Zombie'/14462, l='MpServer', x=-259.50, y=32.00, z=141.50], EntityItem['item.item.bone'/128, l='MpServer', x=-255.72, y=45.13, z=127.59], SmokeEffect['unknown'/19842, l='MpServer', x=-185.31, y=86.36, z=90.79], EntitySpider['Spider'/9859, l='MpServer', x=-230.91, y=26.00, z=136.13], SmokeEffect['unknown'/19854, l='MpServer', x=-189.31, y=84.90, z=92.63], EntityCreeper['Creeper'/6546, l='MpServer', x=-158.50, y=25.00, z=58.50], EntityHorse['Donkey'/147, l='MpServer', x=-226.72, y=83.00, z=114.00], EntityCreeper['Creeper'/6547, l='MpServer', x=-158.50, y=25.00, z=59.50], EntityBat['Bat'/7576, l='MpServer', x=-238.75, y=38.58, z=140.51], SmokeEffect['unknown'/19864, l='MpServer', x=-184.47, y=85.25, z=85.39], EntityCreeper['Creeper'/8857, l='MpServer', x=-215.50, y=9.00, z=104.50], EntitySquid['Squid'/14745, l='MpServer', x=-249.41, y=61.34, z=49.19], EntityZombie['Zombie'/4511, l='MpServer', x=-221.50, y=23.00, z=117.50], EntityArrow['arrow'/159, l='MpServer', x=-206.94, y=63.13, z=142.31], SmokeEffect['unknown'/19875, l='MpServer', x=-180.04, y=84.94, z=80.53], EntityChicken['Chicken'/168, l='MpServer', x=-181.16, y=87.00, z=98.81], EntityCow['Cow'/169, l='MpServer', x=-181.86, y=87.00, z=103.39], SmokeEffect['unknown'/19881, l='MpServer', x=-184.62, y=86.64, z=88.72], EntityChicken['Chicken'/170, l='MpServer', x=-181.73, y=87.00, z=98.66], EntityChicken['Chicken'/171, l='MpServer', x=-180.94, y=87.00, z=101.17], EntityCow['Cow'/172, l='MpServer', x=-173.50, y=87.00, z=102.47], EntitySheep['Sheep'/173, l='MpServer', x=-180.77, y=87.00, z=103.32], EntityChicken['Chicken'/174, l='MpServer', x=-182.29, y=87.00, z=99.32], EntitySkeleton['Skeleton'/14254, l='MpServer', x=-161.50, y=35.00, z=157.50], EntityCow['Cow'/175, l='MpServer', x=-177.91, y=87.00, z=100.34], EntityItem['item.item.feather'/431, l='MpServer', x=-182.03, y=87.13, z=100.50], EntitySkeleton['Skeleton'/14255, l='MpServer', x=-163.50, y=35.00, z=156.50], EntitySheep['Sheep'/176, l='MpServer', x=-181.93, y=87.00, z=102.14], EntitySheep['Sheep'/177, l='MpServer', x=-177.70, y=87.00, z=101.94], EntityCow['Cow'/178, l='MpServer', x=-175.66, y=87.00, z=100.75], EntityCow['Cow'/179, l='MpServer', x=-181.80, y=87.00, z=104.55], EntityPig['Pig'/180, l='MpServer', x=-176.24, y=87.00, z=99.14], EntityZombie['Zombie'/19636, l='MpServer', x=-164.50, y=31.00, z=131.50], EntitySheep['Sheep'/181, l='MpServer', x=-181.73, y=87.00, z=99.45], EntityZombie['Zombie'/16821, l='MpServer', x=-200.50, y=61.00, z=135.50], EntityCreeper['Creeper'/19637, l='MpServer', x=-162.86, y=31.00, z=132.57], EntityZombie['Zombie'/16822, l='MpServer', x=-199.50, y=61.00, z=133.50], SmokeEffect['unknown'/19894, l='MpServer', x=-190.57, y=85.57, z=90.65], EntitySkeleton['Skeleton'/16823, l='MpServer', x=-203.50, y=61.00, z=134.50], EntitySpider['Spider'/19639, l='MpServer', x=-253.91, y=35.00, z=159.40], EntitySheep['Sheep'/184, l='MpServer', x=-177.42, y=87.00, z=99.16], EntityBat['Bat'/7352, l='MpServer', x=-114.45, y=33.27, z=94.67], EntityZombie['Zombie'/9913, l='MpServer', x=-206.50, y=31.00, z=32.50], EntitySkeleton['Skeleton'/16825, l='MpServer', x=-204.50, y=61.00, z=132.50], EntityCow['Cow'/186, l='MpServer', x=-179.56, y=87.00, z=99.16], EntitySkeleton['Skeleton'/16826, l='MpServer', x=-207.50, y=61.00, z=133.50], EntitySheep['Sheep'/187, l='MpServer', x=-181.93, y=87.00, z=100.78], EntitySkeleton['Skeleton'/16827, l='MpServer', x=-212.50, y=61.00, z=131.50], EntityPig['Pig'/188, l='MpServer', x=-179.29, y=87.00, z=101.30], EntitySkeleton['Skeleton'/16828, l='MpServer', x=-214.50, y=61.00, z=132.50], EntityZombie['Zombie'/8380, l='MpServer', x=-128.50, y=84.00, z=72.50], EntityPig['Pig'/189, l='MpServer', x=-180.72, y=87.00, z=102.20], EntityZombie['Zombie'/14013, l='MpServer', x=-253.50, y=23.00, z=157.50], EntityCow['Cow'/190, l='MpServer', x=-179.77, y=87.00, z=103.55], EntityZombie['Zombie'/14014, l='MpServer', x=-262.50, y=23.00, z=165.50], SmokeEffect['unknown'/19902, l='MpServer', x=-178.54, y=85.92, z=81.85], EntityZombie['Zombie'/12737, l='MpServer', x=-263.50, y=46.00, z=106.50], EntitySkeleton['Skeleton'/12740, l='MpServer', x=-265.69, y=45.00, z=101.94], EntityXPOrb['Experience Orb'/197, l='MpServer', x=-173.19, y=19.25, z=7.69], SmokeEffect['unknown'/19909, l='MpServer', x=-179.81, y=86.09, z=82.13], EntityChicken['Chicken'/198, l='MpServer', x=-172.81, y=88.00, z=101.47], EntityCreeper['Creeper'/9670, l='MpServer', x=-244.50, y=44.00, z=120.50], EntityChicken['Chicken'/199, l='MpServer', x=-173.16, y=87.00, z=100.66], EntityCreeper['Creeper'/9671, l='MpServer', x=-245.50, y=44.00, z=123.50], EntitySheep['Sheep'/200, l='MpServer', x=-180.50, y=87.00, z=100.32], EntityChicken['Chicken'/201, l='MpServer', x=-175.16, y=87.00, z=99.78], EntityCreeper['Creeper'/9673, l='MpServer', x=-243.50, y=44.00, z=121.50], EntitySheep['Sheep'/202, l='MpServer', x=-179.53, y=87.00, z=102.34], EntityBat['Bat'/20170, l='MpServer', x=-142.44, y=35.33, z=128.84], EntityPig['Pig'/203, l='MpServer', x=-178.54, y=87.00, z=103.54], BlueSlime['Blue Slime'/204, l='MpServer', x=-158.31, y=33.00, z=137.38], EntityZombie['Zombie'/207, l='MpServer', x=-169.08, y=32.00, z=154.31], EntitySkeleton['Skeleton'/12239, l='MpServer', x=-257.50, y=54.00, z=171.50], EntitySkeleton['Skeleton'/3793, l='MpServer', x=-121.50, y=31.00, z=64.50], EntityBat['Bat'/215, l='MpServer', x=-138.31, y=47.00, z=76.47], EntityCreeper['Creeper'/13274, l='MpServer', x=-122.50, y=33.00, z=63.50], SmokeEffect['unknown'/19931, l='MpServer', x=-185.75, y=86.88, z=90.61], EntityBat['Bat'/222, l='MpServer', x=-143.91, y=48.00, z=80.88], EntityZombie['Zombie'/223, l='MpServer', x=-135.97, y=48.00, z=75.56], EntityBat['Bat'/13794, l='MpServer', x=-263.48, y=29.24, z=151.69], SmokeEffect['unknown'/19685, l='MpServer', x=-180.80, y=86.64, z=84.02], SmokeEffect['unknown'/19944, l='MpServer', x=-185.88, y=85.24, z=86.60], EntitySkeleton['Skeleton'/20202, l='MpServer', x=-262.50, y=35.00, z=160.50], EntityZombie['Zombie'/236, l='MpServer', x=-123.06, y=37.00, z=89.38], EntityCow['Cow'/237, l='MpServer', x=-122.50, y=78.00, z=156.38], SmokeEffect['unknown'/19949, l='MpServer', x=-183.96, y=84.90, z=83.06], SmokeEffect['unknown'/19701, l='MpServer', x=-182.93, y=86.81, z=85.86], SmokeEffect['unknown'/19957, l='MpServer', x=-180.26, y=84.50, z=79.60], SmokeEffect['unknown'/19708, l='MpServer', x=-182.23, y=85.87, z=87.78], EntitySquid['Squid'/3326, l='MpServer', x=-256.56, y=59.00, z=128.53]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:927)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Mac OS X (x86_64) version 10.11.3
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 123755848 bytes (118 MB) / 1060372480 bytes (1011 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 5 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 9, tcache: 0, allocated: 15, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 58 mods loaded, 58 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1558} [Minecraft Forge] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	LambdaLib|Core{1.2.2} [LambdaLib|Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UCHIJAAAA	OpenComputers|Core{1.5.22.46} [OpenComputers (Core)] (minecraft.jar) 
	UCHIJAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAAAA	FastCraft{1.23} [FastCraft] (fastcraft-1.23.jar) 
	UCHIJAAAA	LambdaLib{1.2.2} [LambdaLib] (LambdaLib-1.2.2.jar) 
	UCHIJAAAA	CoFHCore{1.7.10R3.1.2} [CoFH Core] (CoFHCore-[1.7.10]3.1.2-325.jar) 
	UCHIJAAAA	academy-craft{1.0.3} [Academy Craft] (AcademyCraft-1.0.3.jar) 
	UCHIJAAAA	AgriCraft{1.7.10-1.3.1} [AgriCraft] (AgriCraft-1.7.10-1.3.1.jar) 
	UCHIJAAAA	MovingWorld{1.7.10-1.8} [Moving World] (movingworld-1.7.10-1.8.jar) 
	UCHIJAAAA	ArchimedesShipsPlus{1.7.10-1.8} [Archimedes' Ships Plus] (archimedesshipsplus-1.7.10-1.8.jar) 
	UCHIJAAAA	armourersWorkshop{1.7.10-0.39.4.105} [Armourer's Workshop] (Armourers-Workshop-1.7.10-0.39.4.105.jar) 
	UCHIJAAAA	plushieWrapper{0.0.0} [Plushie Wrapper] (Armourers-Workshop-1.7.10-0.39.4.105.jar) 
	UCHIJAAAA	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCHIJAAAA	BiblioCraft{1.11.5} [BiblioCraft] (BiblioCraft[v1.11.5][MC1.7.10].jar) 
	UCHIJAAAA	Botania{r1.8-249} [Botania] (Botania r1.8-249.jar) 
	UCHIJAAAA	BuildCraft|Core{7.1.17} [BuildCraft] (buildcraft-7.1.17.jar) 
	UCHIJAAAA	BuildCraft|Silicon{7.1.17} [BC Silicon] (buildcraft-7.1.17.jar) 
	UCHIJAAAA	BuildCraft|Transport{7.1.17} [BC Transport] (buildcraft-7.1.17.jar) 
	UCHIJAAAA	BuildCraft|Builders{7.1.17} [BC Builders] (buildcraft-7.1.17.jar) 
	UCHIJAAAA	BuildCraft|Energy{7.1.17} [BC Energy] (buildcraft-7.1.17.jar) 
	UCHIJAAAA	BuildCraft|Robotics{7.1.17} [BC Robotics] (buildcraft-7.1.17.jar) 
	UCHIJAAAA	BuildCraft|Factory{7.1.17} [BC Factory] (buildcraft-7.1.17.jar) 
	UCHIJAAAA	ComputerCraft{1.75} [ComputerCraft] (ComputerCraft1.75.jar) 
	UCHIJAAAA	PTRModelLib{1.0.0} [PTRModelLib] (Decocraft-2.2.1_1.7.10.jar) 
	UCHIJAAAA	props{2.2.1} [Decocraft] (Decocraft-2.2.1_1.7.10.jar) 
	UCHIJAAAA	flansmod{4.10.0} [Flan's Mod] (Flans Mod-1.7.10-4.10.0.jar) 
	UCHIJAAAA	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) 
	UCHIJAAAA	JABBA{1.2.2} [JABBA] (Jabba-1.2.2_1.7.10.jar) 
	UCHIJAAAA	magicalcrops{1.7.2 - 0.1 ALPHA} [Magical Crops] (magicalcrops-1.7.10_0.1.jar) 
	UCHIJAAAA	Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (Mantle-1.7.10-0.3.2b.jar) 
	UCHIJAAAA	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAA	Mekanism{9.1.0} [Mekanism] (Mekanism-1.7.10-9.1.0.281.jar) 
	UCHIJAAAA	MekanismGenerators{9.1.0} [MekanismGenerators] (MekanismGenerators-1.7.10-9.1.0.281.jar) 
	UCHIJAAAA	MekanismTools{9.1.0} [MekanismTools] (MekanismTools-1.7.10-9.1.0.281.jar) 
	UCHIJAAAA	MrTJPCoreMod{1.1.0.33} [MrTJPCore] (MrTJPCore-1.1.0.33-universal.jar) 
	UCHIJAAAA	ProjRed|Core{4.7.0pre12.95} [ProjectRed Core] (ProjectRed-1.7.10-4.7.0pre12.95-Base.jar) 
	UCHIJAAAA	ProjRed|Transmission{4.7.0pre12.95} [ProjectRed Transmission] (ProjectRed-1.7.10-4.7.0pre12.95-Integration.jar) 
	UCHIJAAAA	ThermalFoundation{1.7.10R1.2.4} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.4-114.jar) 
	UCHIJAAAA	ThermalExpansion{1.7.10R4.1.2} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.1.2-240.jar) 
	UCHIJAAAA	OpenComputers{1.5.22.46} [OpenComputers] (OpenComputers-MC1.7.10-1.5.22.46-universal.jar) 
	UCHIJAAAA	ProjRed|Transportation{4.7.0pre12.95} [ProjectRed Transportation] (ProjectRed-1.7.10-4.7.0pre12.95-Mechanical.jar) 
	UCHIJAAAA	TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct] (TConstruct-1.7.10-1.8.8.jar) 
	UCHIJAAAA	ProjRed|Compatibility{4.7.0pre12.95} [ProjectRed Compatibility] (ProjectRed-1.7.10-4.7.0pre12.95-Compat.jar) 
	UCHIJAAAA	ProjRed|Integration{4.7.0pre12.95} [ProjectRed Integration] (ProjectRed-1.7.10-4.7.0pre12.95-Integration.jar) 
	UCHIJAAAA	ProjRed|Fabrication{4.7.0pre12.95} [ProjectRed Fabrication] (ProjectRed-1.7.10-4.7.0pre12.95-Fabrication.jar) 
	UCHIJAAAA	ProjRed|Illumination{4.7.0pre12.95} [ProjectRed Illumination] (ProjectRed-1.7.10-4.7.0pre12.95-Lighting.jar) 
	UCHIJAAAA	ProjRed|Expansion{4.7.0pre12.95} [ProjectRed Expansion] (ProjectRed-1.7.10-4.7.0pre12.95-Mechanical.jar) 
	UCHIJAAAA	TMechworks{0.2.15.106} [Tinkers' Mechworks] (TMechworks-1.7.10-0.2.15.106.jar) 
	UCHIJAAAA	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAA	ForgeRelocation{0.0.1.4} [ForgeRelocation] (ForgeRelocation-1.7.10-0.0.1.4-universal.jar) 
	UCHIJAAAA	MCFrames{1.0} [MCFrames] (ForgeRelocation-1.7.10-0.0.1.4-universal.jar) 
	UCHIJAAAA	RelocationFMP{0.0.1.2} [RelocationFMP] (ForgeRelocationFMP-1.7.10-0.0.1.2-universal.jar) 
	UCHIJAAAA	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	CoFHCore: -[1.7.10]3.1.2-325
	Mantle Environment: Environment healthy.
	ThermalFoundation: -[1.7.10]1.2.4-114
	ThermalExpansion: -[1.7.10]4.1.2-240
	TConstruct Environment: Environment healthy.
	Launched Version: 1.7.10-Forge10.13.4.1558-1.7.10
	LWJGL: 2.9.1
	OpenGL: NVIDIA GeForce GT 630 OpenGL Engine GL version 2.1 NVIDIA-10.8.14 310.42.15f01, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)
```
We will check it soon. Thanks for your feedback.

**Comment by KSkun** [comment]
Hi, there.
I found that your graphics card driver can only support GL version 2.1.0.
You can try to update your graphics card driver.
If it still crashed, please send your latest crash report to us.
Thanks.

**Comment by KillerDawg334** [comment]
I see...well thank you very much for the information. Good luck with the mod's future endeavours! :)
