### ISSUE TITLE
为什么启动游戏会崩溃

### ISSUE THREAD

**Issue by VectorCtrl** [LambdaInnovation/AcademyCraft#462]
版本比10.13.4.1517-1.7.10高
崩溃日志↓
```
*** Launching Game ***
[11:43:33] [launcher/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[11:43:33] [launcher/INFO] [LaunchWrapper]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[11:43:33] [launcher/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
[11:43:33] [launcher/INFO] [FML]: Forge Mod Loader version 7.99.40.1614 for Minecraft 1.7.10 loading
[11:43:33] [launcher/INFO] [FML]: Java is Java HotSpot(TM) Client VM, version 1.7.0_71, running on Windows 7:x86:6.1, installed at C:\Program Files\Java\jre7
[11:43:33] [launcher/WARN] [FML]: The coremod codechicken.core.launch.CodeChickenCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[11:43:34] [launcher/WARN] [FML]: The coremod lain.mods.inputfix.InputFix does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[11:43:34] [launcher/WARN] [FML]: The coremod invtweaks.forge.asm.FMLPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[11:43:34] [launcher/WARN] [FML]: The coremod codechicken.nei.asm.NEICorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[11:43:34] [launcher/INFO] [FML]: Loading tweaker com.mumfrey.liteloader.launch.LiteLoaderTweaker from API.jar
[11:43:34] [launcher/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.UnsupportedClassVersionError: cn/lambdalib/core/LLCorePlugin : Unsupported major.minor version 52.0
[11:43:34] [launcher/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at java.lang.ClassLoader.defineClass1(Native Method)
[11:43:34] [launcher/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at java.lang.ClassLoader.defineClass(Unknown Source)
[11:43:34] [launcher/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at java.security.SecureClassLoader.defineClass(Unknown Source)
[11:43:34] [launcher/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at java.net.URLClassLoader.defineClass(Unknown Source)
[11:43:34] [launcher/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at java.net.URLClassLoader.access$100(Unknown Source)
[11:43:34] [launcher/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at java.net.URLClassLoader$1.run(Unknown Source)
[11:43:34] [launcher/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at java.net.URLClassLoader$1.run(Unknown Source)
[11:43:34] [launcher/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at java.security.AccessController.doPrivileged(Native Method)
[11:43:34] [launcher/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at java.net.URLClassLoader.findClass(Unknown Source)
[11:43:34] [launcher/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117)
[11:43:34] [launcher/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at java.lang.ClassLoader.loadClass(Unknown Source)
[11:43:34] [launcher/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at java.lang.ClassLoader.loadClass(Unknown Source)
[11:43:34] [launcher/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at java.lang.Class.forName0(Native Method)
[11:43:34] [launcher/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at java.lang.Class.forName(Unknown Source)
[11:43:34] [launcher/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:460)
[11:43:34] [launcher/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:389)
[11:43:34] [launcher/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:221)
[11:43:34] [launcher/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90)
[11:43:34] [launcher/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67)
[11:43:34] [launcher/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34)
[11:43:34] [launcher/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126)
[11:43:34] [launcher/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[11:43:34] [launcher/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[11:43:34] [launcher/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[11:43:34] [launcher/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[11:43:34] [launcher/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[11:43:34] [launcher/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at java.lang.reflect.Method.invoke(Unknown Source)
[11:43:34] [launcher/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at org.jackhuang.hellominecraft.launcher.Launcher.main(SourceFile:122)
[11:43:34] [launcher/ERROR] [FML]: An error occurred trying to configure the minecraft home at C:\Users\Administrator\Documents\minecarft\高级实验客户端\1.7.10 客户端\.minecraft for Forge Mod Loader
java.lang.UnsupportedClassVersionError: cn/lambdalib/core/LLCorePlugin : Unsupported major.minor version 52.0
    at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.7.0_71]
    at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.7.0_71]
    at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.7.0_71]
    at java.net.URLClassLoader.defineClass(Unknown Source) ~[?:1.7.0_71]
    at java.net.URLClassLoader.access$100(Unknown Source) ~[?:1.7.0_71]
    at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.7.0_71]
    at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.7.0_71]
    at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_71]
    at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.7.0_71]
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117) ~[launchwrapper-1.12.jar:?]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_71]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_71]
    at java.lang.Class.forName0(Native Method) ~[?:1.7.0_71]
    at java.lang.Class.forName(Unknown Source) ~[?:1.7.0_71]
    at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:460) ~[forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
    at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:389) ~[forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
    at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:221) ~[forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
    at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
    at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
    at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
    at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_71]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_71]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_71]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_71]
    at org.jackhuang.hellominecraft.launcher.Launcher.main(SourceFile:122) [%e5%ae%a2%e6%88%b7%e7%ab%af%e5%90%af%e5%8a%a8%e5%99%a8.exe:?]
[11:43:34][launcher/ERROR] Cought exception!
Minecraft崩溃了！请认真阅读建议。
可能是Mod或其他问题。
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.jackhuang.hellominecraft.launcher.Launcher.main(SourceFile:122)
Caused by: java.lang.UnsupportedClassVersionError: cn/lambdalib/core/LLCorePlugin : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:460)
	at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:389)
	at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:221)
	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90)
	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67)
	at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34)
	at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	... 5 more

[11:43:37] [launcher/INFO] [STDOUT]: [org.jackhuang.hellominecraft.launcher.Launcher:a:48]: *** Game Exited ***
```
望解答，谢谢

**Comment by KSkun** [comment]
你好。你没有使用Java 8启动，造成了这个崩溃。
你应该换用Java 8来启动Minecraft。
希望我的建议能够帮助你，如果还有问题请告知我们。
