### ISSUE TITLE
[1.0.3] Crash when installed TiCTooltips Mod

### ISSUE THREAD

**Issue by KSkun** [LambdaInnovation/AcademyCraft#465]
```
[14:26:02] [Client thread/ERROR] [FML/]: Fatal errors were detected during the transition from CONSTRUCTING to PREINITIALIZATION. Loading cannot continue
[14:26:02] [Client thread/ERROR] [FML/]: 
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UC	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UC	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1517-1.7.10.jar) 
	UC	Forge{10.13.4.1517} [Minecraft Forge] (forge-1.7.10-10.13.4.1517-1.7.10.jar) 
	UC	AppleMilkCore{1.1.0} [AppleMilkCore] (minecraft.jar) 
	UC	appliedenergistics2-core{rv2-stable-3} [AppliedEnergistics2 Core] (minecraft.jar) 
	UC	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UC	InputFix{1.7.10-v5} [InputFix] (minecraft.jar) 
	UC	LambdaLib|Core{1.2.2} [LambdaLib|Core] (minecraft.jar) 
	UC	NotEnoughItems{1.0.5.118} [Not Enough Items] (NotEnoughItems.jar) 
	UC	PotionExtensionCore{1.7.10-1.1.0} [PotionExtensionCore] (minecraft.jar) 
	UC	ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core] (minecraft.jar) 
	UC	DamageIndicatorsMod{3.2.0} [Damage Indicators] ([1.7.0]DamageIndicatorsMod.jar) 
	UC	Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (Mantle-1.7.10-0.3.2b（匠魂手册）.jar) 
	UC	Waila{1.5.10} [Waila] (Waila.jar) 
	UE	TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct] (TConstruct-1.7.10-1.8.8（匠魂）.jar) 
	UE	TiCTooltips{1.2.5} [TiC Tooltips] ([匠魂工具提示]TiCTooltips-mc1.7.10-1.2.5.jar) 
	UC	TiConAutoToolStation{1.1.1} [Tinkers Construct Auto Tool Station] ([匠魂附属-自动工具台]TiConAutoToolStation-1.7.10-1.1.1.jar) 
	UC	LambdaLib{1.2.2} [LambdaLib] (LambdaLib-1.2.2.jar) 
	UC	academy-craft{1.0.3} [Academy Craft] (AcademyCraft-1.0.3.jar) 
	UC	IC2{2.2.821-experimental} [IndustrialCraft 2] (industrialcraft-experimental.jar) 
	UC	ImmibisCore{59.1.2} [Immibis Core] (immibis-core.jar) 
	UC	AdvancedMachines{59.0.2} [Advanced Machines] (advanced-machines.jar) 
	UC	AdvancedSolarPanel{1.7.10-3.5.1} [Advanced Solar Panels] (AdvancedSolarPanel.jar) 
	UC	AntiCheat3{AntiCheat 3 Mod} [AntiCheat 3 Mod] (AntiCheat.jar) 
	UC	DCsAppleMilk{1.7.10_2.9m} [Apple&Milk&Tea!] (AppleMilkTea2-1.7.10_2.9m.jar) 
	UC	DCsNEIPluginAMT{1.7.10_1.0a} [NEIPluginForAMT] (AppleMilkTea2-1.7.10_2.9m.jar) 
	UC	appliedenergistics2{rv2-stable-3} [Applied Energistics 2] (appliedenergistics2-rv2-stable-3（应用能源）.jar) 
	UC	BambooMod{Minecraft@MC_VERSION@ var@VERSION@} [BambooMod] (Bamboo.jar) 
	UC	ChunkAnimator{@VERSION@} [Chunk Animator] (ChunkAnimator.jar) 
	UC	DummyCore{1.13} [DummyCore] (DummyCore1.13（神秘基础学&源质魔法前置）.jar) 
	UC	FastCraft{1.21} [FastCraft] (fastcraft.jar) 
	UC	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UC	Thaumcraft{4.2.3.5} [Thaumcraft] (M-Thaumcraft-1.7.10-4.2.3.5-SaraFix-a1.jar) 
	UC	ThaumicTinkerer{unspecified} [Thaumic Tinkerer] (ThaumicTinkerer-2.5-1.7.10-164（神秘工匠）.jar) 
	UC	ForbiddenMagic{1.7.10-0.57} [Forbidden Magic] (Forbidden Magic-1.7.10-0.57（禁忌魔法）.jar) 
	UC	GraviSuite{1.7.10-2.0.3} [Graviation Suite] (GraviSuite.jar) 
	UC	IC2LaserFix{2.0} [IC2 Laser Fix] (IC2LaserFix-1.7.10.jar) 
	UC	InfusionBrewing{1.7.10-1.3} [InfusionBrewing] (InfusionBrewing-1.7.10-1.3（注魔酿造）.jar) 
	UC	inventorytweaks{1.58-147-645ca10} [Inventory Tweaks] (InventoryTweaks.jar) 
	UC	numina{0.4.0.131} [Numina] (Numina-0.4.0.131.jar) 
	UE	powersuits{0.11.0.301} [MachineMuse's Modular Powersuits] (ModularPowersuits-0.11.0.301.jar) 
	UC	MouseTweaks{2.4.4} [Mouse Tweaks] (MouseTweaks.jar) 
	UC	NBTEdit{1.7.2.2} [In-game NBTEdit] (NBTEdit_1.7.10.jar) 
	UC	NEIAddons{1.12.14.40} [NEI Addons] (neiaddons.jar) 
	UC	NEIAddons|Developer{1.12.14.40} [NEI Addons: Developer Tools] (neiaddons.jar) 
	UC	NEIAddons|AppEng{1.12.14.40} [NEI Addons: Applied Energistics 2] (neiaddons.jar) 
	UC	NEIAddons|Botany{1.12.14.40} [NEI Addons: Botany] (neiaddons.jar) 
	UC	NEIAddons|Forestry{1.12.14.40} [NEI Addons: Forestry] (neiaddons.jar) 
	UC	NEIAddons|CraftingTables{1.12.14.40} [NEI Addons: Crafting Tables] (neiaddons.jar) 
	UC	NEIAddons|ExNihilo{1.12.14.40} [NEI Addons: Ex Nihilo] (neiaddons.jar) 
	UC	neiintegration{1.0.13} [NEI Integration] (NEIIntegration.jar) 
	UC	NodalMechanics{1.7.10R1.0} [NodalMechanics] (NodalMechanics-1.7-1.0-7(节点学）.jar) 
	UC	flammpfeil.slashblade{mc1.7.10-r75} [SlashBlade] (SlashBlade.jar) 
	UC	TaintedMagic{1.1.5.7} [Tainted Magic] (TaintedMagic-1.1.5.7（污秽魔法）.jar) 
	UC	tcinventoryscan{1.0.10} [TC Inventory Scanning] (tcinventoryscan.jar) 
	UC	thaumcraftneiplugin{@VERSION@} [Thaumcraft NEI Plugin] (thaumcraftneiplugin.jar) 
	UC	thaumicbases{1.3.1710.2} [Thaumic Bases] (ThaumicBases-1.3.1710.4（神秘基础学）.jar) 
	UC	thaumicenergistics{0.8.10.5} [Thaumic Energistics] (thaumicenergistics-0.8.10.5（神秘能源）.jar) 
	UC	ThaumicHorizons{1.1.5} [Thaumic Horizons] (thaumichorizons-1.7.10-1.1.6（神秘视界）.jar) 
	UC	thaumicinfusion{4.05} [Thaumic Infusion] (ThaumicInfusion-4.06（神秘注魔）.jar) 
	UE	TMechworks{1.7.10-67.34d1d9b} [Tinkers' Mechworks] (TMechworks_mc1.7.10_0.2.8（匠魂附属：机械机关）.jar) 
	UC	TofuCraft{2.1.6-MC1.7.10} [TofuCraft] (TofuCraft-2.1.6-MC1.7.10.jar) 
	UC	TwilightForest{2.3.7} [The Twilight Forest] (twilightforest-1.7.10-2.3.7（暮色森林）.jar) 
	UC	UnicodeFontFixer{1.1.12-mc1.7.10} [UnicodeFontFixer] (UnicodeFontFixer.jar) 
	UC	flammpfeil.nihil{mc1.7.x-r6} [Nihil] (似蛭-Nihil-mc1.7.x-r6.jar) 
	UC	flammpfeil.fluorescentbar{mc1.7.2-r3} [fluorescentbar] (荧光-fluorescentbar-mc1.7.2-r3.jar) 
	UE	IguanaTweaksTConstruct{1.7.10-2.1.5.140} [Iguana Tinker Tweaks] (IguanaTinkerTweaks-1.7.10-2.1.5（匠魂强化）.jar) 
[14:26:02] [Client thread/ERROR] [FML/]: The following problems were captured during this phase
[14:26:02] [Client thread/ERROR] [FML/]: Caught exception from powersuits
java.lang.NoClassDefFoundError: net/machinemuse/powersuits/item/ItemPowerFist
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_60]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_60]
	at cpw.mods.fml.common.ILanguageAdapter$ScalaAdapter.setInternalProxies(ILanguageAdapter.java:139) ~[forge-1.7.10-10.13.4.1517-1.7.10.jar:?]
	at cpw.mods.fml.common.ProxyInjector.inject(ProxyInjector.java:81) ~[forge-1.7.10-10.13.4.1517-1.7.10.jar:?]
	at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:512) ~[forge-1.7.10-10.13.4.1517-1.7.10.jar:?]
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_60]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_60]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) ~[forge-1.7.10-10.13.4.1517-1.7.10.jar:?]
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) ~[forge-1.7.10-10.13.4.1517-1.7.10.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_60]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_60]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_60]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119) [LoadController.class:?]
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:513) [Loader.class:?]
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:208) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_60]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_60]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_60]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_60]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_60]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_60]
	at org.jackhuang.hellominecraft.launcher.Launcher.main(Launcher.java:114) [HMCL-2.3.5.4.exe:?]
Caused by: java.lang.ClassNotFoundException: net.machinemuse.powersuits.item.ItemPowerFist
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_60]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_60]
	... 41 more
Caused by: java.lang.NoClassDefFoundError: net/machinemuse/powersuits/item/ItemElectricTool
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_60]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_60]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_60]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_60]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_60]
	... 41 more
Caused by: java.lang.ClassNotFoundException: net.machinemuse.powersuits.item.ItemElectricTool
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_60]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_60]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_60]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_60]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_60]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_60]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_60]
	... 41 more
[14:26:02] [Client thread/ERROR] [FML/]: Caught exception from TConstruct
java.lang.NoClassDefFoundError: tconstruct/weaponry/items/GlassArrows
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_60]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_60]
	at cpw.mods.fml.common.ProxyInjector.inject(ProxyInjector.java:42) ~[forge-1.7.10-10.13.4.1517-1.7.10.jar:?]
	at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:512) ~[forge-1.7.10-10.13.4.1517-1.7.10.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_60]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_60]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_60]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) ~[forge-1.7.10-10.13.4.1517-1.7.10.jar:?]
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) ~[forge-1.7.10-10.13.4.1517-1.7.10.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_60]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_60]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_60]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119) [LoadController.class:?]
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:513) [Loader.class:?]
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:208) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_60]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_60]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_60]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_60]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_60]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_60]
	at org.jackhuang.hellominecraft.launcher.Launcher.main(Launcher.java:114) [HMCL-2.3.5.4.exe:?]
Caused by: java.lang.ClassNotFoundException: tconstruct.weaponry.items.GlassArrows
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_60]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_60]
	... 41 more
Caused by: java.lang.NoClassDefFoundError: tconstruct/weaponry/ammo/ArrowAmmo
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_60]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_60]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_60]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_60]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_60]
	... 41 more
Caused by: java.lang.ClassNotFoundException: tconstruct.weaponry.ammo.ArrowAmmo
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_60]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_60]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_60]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_60]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_60]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_60]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_60]
	... 41 more
```

**Comment by 3TUSK** [comment]
目测这bug是没有办法修复的...解决方法（虽然只是work around）是安装CoFH Core。
Ref: SlimeKnights/TinkersConstruct#1662, SlimeKnights/TinkersConstruct#1722
> bonii-xx: 
> Extra utilities ships the RF API but gets loaded after TCon so it crashes. Adding CofhCore ensures the correct load order. It's basically an unfixable problem because of how APIs work.
So the gist of it: If anything in your modpack has RF, add CofhCore.

**Comment by KSkun** [comment]
@3TUSK 感谢提供信息。
