### ISSUE TITLE
[1.0.4] 加入AB后服务器崩溃

### ISSUE THREAD

**Issue by KSkun** [LambdaInnovation/AcademyCraft#472]
```
---- Minecraft Crash Report ----
// Don't be sad. I'll do better next time, I promise!

Time: 8/8/16 12:12 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
    at cn.academy.core.entity.EntityBlock$1.onEvent(EntityBlock.java:158)
    at cn.academy.core.entity.EntityBlock$1.onEvent(EntityBlock.java:140)
    at cn.lambdalib.util.entityx.EntityX.postEvent(EntityX.java:113)
    at cn.lambdalib.util.entityx.handlers.Rigidbody.onUpdate(Rigidbody.java:75)
    at cn.lambdalib.util.entityx.EntityX.update(EntityX.java:51)
    at cn.lambdalib.util.entityx.EntityAdvanced.func_70071_h_(EntityAdvanced.java:37)
    at cn.academy.core.entity.EntityBlock.func_70071_h_(EntityBlock.java:119)
    at cn.academy.vanilla.electromaster.MagManipEntityBlock.func_70071_h_(MagManip.scala:276)
    at net.minecraft.world.World.func_72866_a(World.java:2674)
    at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:800)
    at net.minecraft.world.World.func_72870_g(World.java:2623)
    at net.minecraft.world.World.func_72939_s(World.java:2423)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:633)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:954)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
    at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
    at cn.academy.core.entity.EntityBlock$1.onEvent(EntityBlock.java:158)
    at cn.academy.core.entity.EntityBlock$1.onEvent(EntityBlock.java:140)
    at cn.lambdalib.util.entityx.EntityX.postEvent(EntityX.java:113)
    at cn.lambdalib.util.entityx.handlers.Rigidbody.onUpdate(Rigidbody.java:75)
    at cn.lambdalib.util.entityx.EntityX.update(EntityX.java:51)
    at cn.lambdalib.util.entityx.EntityAdvanced.func_70071_h_(EntityAdvanced.java:37)
    at cn.academy.core.entity.EntityBlock.func_70071_h_(EntityBlock.java:119)
    at cn.academy.vanilla.electromaster.MagManipEntityBlock.func_70071_h_(MagManip.scala:276)
    at net.minecraft.world.World.func_72866_a(World.java:2674)
    at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:800)
    at net.minecraft.world.World.func_72870_g(World.java:2623)

-- Entity being ticked --
Details:
    Entity Type: academy-craft.ac_Entity_MagManipEntityBlock (cn.academy.vanilla.electromaster.MagManipEntityBlock)
    Entity ID: 608
    Entity Name: entity.academy-craft.ac_Entity_MagManipEntityBlock.name
    Entity's Exact location: -1785.57, 59.65, -9411.39
    Entity's Block location: World: (-1786,59,-9412), Chunk: (at 6,3,12 in -112,-589; contains blocks -1792,0,-9424 to -1777,255,-9409), Region: (-4,-19; contains chunks -128,-608 to -97,-577, blocks -2048,0,-9728 to -1537,255,-9217)
    Entity's Momentum: -0.08, -0.06, -0.50
Stacktrace:
    at net.minecraft.world.World.func_72939_s(World.java:2423)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:633)

-- Affected level --
Details:
    Level name: world
    All players: 2 total; [EntityPlayerMP['Alduin_Lolita'/356, l='world', x=-1785.57, y=59.00, z=-9409.15](Alduin_Lolita at -1785.5708396286152,59.0,-9409.154600156186), EntityPlayerMP['YuanShou'/471, l='world', x=40362.00, y=84.78, z=-2457.92](YuanShou at 40361.999416420695,84.78075955763866,-2457.919329993336)]
    Chunk stats: ServerChunkCache: 1292 Drop: 690
    Level seed: 7641168823035356155
    Level generator: ID 00 - default, ver 1. Features enabled: true
    Level generator options: 
    Level spawn location: World: (-570,65,-684), Chunk: (at 6,4,4 in -36,-43; contains blocks -576,0,-688 to -561,255,-673), Region: (-2,-2; contains chunks -64,-64 to -33,-33, blocks -1024,0,-1024 to -513,255,-513)
    Level time: 51672942 game time, 54028501 day time
    Level dimension: 0
    Level storage version: 0x04ABD - Anvil
    Level weather: Rain time: 59356 (now: false), thunder time: 826 (now: true)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:954)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
    at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    KCauldron Version: pw.prok:KCauldron:1.7.10-1614.201 Official
    Plugins: CoreProtect, WorldEdit, CustomServerMessages, Essentials, EssentialsProtect, EssentialsChat, GroupManager, EssentialsAntiBuild, RPG_Items, ProtectPlugin, DcBanItem, mcMMO, ChopTreeW, Vault, EssentialsSpawn, Multiverse-Core, Residence, AcademyBukkit, AuthMe, LWC, QuickShop
    Disabled Plugins: 
    Operating System: Windows 2003 (amd64) version 5.2
    Java Version: 1.8.0_60, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 1380031824 bytes (1316 MB) / 1891106816 bytes (1803 MB) up to 1891106816 bytes (1803 MB)
    JVM Flags: 2 total; -Xms1900M -Xmx1900M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 16 mods loaded, 16 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
    UCHIJAAAA   FML{7.10.99.99} [Forge Mod Loader] (KCauldron-1.7.10-1614.201.jar) 
    UCHIJAAAA   Forge{10.13.4.1614} [Minecraft Forge] (KCauldron-1.7.10-1614.201.jar) 
    UCHIJAAAA   kimagine{0.2} [KImagine] (minecraft.jar) 
    UCHIJAAAA   CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar) 
    UCHIJAAAA   LambdaLib|Core{1.2.2} [LambdaLib|Core] (minecraft.jar) 
    UCHIJAAAA   NotEnoughItems{1.0.3.67} [Not Enough Items] (NotEnoughItems 物品管理器 1.0.3.67.jar) 
    UCHIJAAAA   PlayerAPI{1.0} [Player API] (minecraft.jar) 
    UCHIJAAAA   LambdaLib{1.2.2} [LambdaLib] (LambdaLib-1.2.2.jar) 
    UCHIJAAAA   academy-craft{1.0.3} [Academy Craft] (AcademyCraft-1.0.3.jar) 
    UCHIJAAAA   AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI-1.7.10-1.2.4.jar) 
    UCHIJAAAA   customnpcs{1.7.10c} [CustomNpcs] (CustomNPCs_1.7.10c.jar) 
    UCHIJAAAA   IC2{2.2.821-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.821-experimental.jar) 
    UCHIJAAAA   InfernalMobs{1.5.4} [Infernal Mobs] (InfernalMobs-1.7.10.jar) 
    UCHIJAAAA   MoreBows2{1.1} [More Bows 2] (MoreBows2-1.1【IcyCrystal汉化】.jar) 
    UCHIJAAAA   MutantCreatures{1.4.8} [Mutant Creatures] (MutantCreatures-1.7.10-1.4.8-CN.jar) 
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Player Count: 2 / 40; [EntityPlayerMP['Alduin_Lolita'/356, l='world', x=-1785.57, y=59.00, z=-9409.15](Alduin_Lolita at -1785.5708396286152,59.0,-9409.154600156186), EntityPlayerMP['YuanShou'/471, l='world', x=40362.00, y=84.78, z=-2457.92](YuanShou at 40361.999416420695,84.78075955763866,-2457.919329993336)]
    Is Modded: Definitely; Server brand changed to 'kcauldron,cauldron,craftbukkit,mcpc,fml,forge'
    Type: Dedicated Server (map_server.txt)
```

**Comment by k0to** [comment]
同，加入服务器崩溃无限重启

**Comment by Paindar** [comment]
We need a new Academy Bukkit, and we'll get it soon.
