### ISSUE TITLE
[1.0.4] 坐标传送崩溃

### ISSUE THREAD

**Issue by KSkun** [LambdaInnovation/AcademyCraft#496]
```
[20:41:20] [Server thread/FATAL]: Error during network message.
java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_102]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_102]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_102]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_102]
    at cn.lambdalib.s11n.network.NetworkMessage$1.invoke(NetworkMessage.java:290) ~[NetworkMessage$1.class:?]
    at cn.lambdalib.s11n.network.NetworkMessage.invokeListener(NetworkMessage.java:218) [NetworkMessage.class:?]
    at cn.lambdalib.s11n.network.NetworkMessage.processMessage(NetworkMessage.java:199) [NetworkMessage.class:?]
    at cn.lambdalib.s11n.network.NetworkMessage.access$000(NetworkMessage.java:56) [NetworkMessage.class:?]
    at cn.lambdalib.s11n.network.NetworkMessage$Handler.onMessage(NetworkMessage.java:355) [NetworkMessage$Handler.class:?]
    at cn.lambdalib.s11n.network.NetworkMessage$Handler.onMessage(NetworkMessage.java:349) [NetworkMessage$Handler.class:?]
    at cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:37) [SimpleChannelHandlerWrapper.class:1.7.10-1614.57]
    at cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:17) [SimpleChannelHandlerWrapper.class:1.7.10-1614.57]
    at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) [SimpleChannelInboundHandler.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [MessageToMessageDecoder.class:?]
    at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) [MessageToMessageCodec.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
    at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?]
    at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:1.7.10-1614.57]
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?]
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181) [nc.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1023) [MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_102]
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
    at java.util.ArrayList.rangeCheck(Unknown Source) ~[?:1.8.0_102]
    at java.util.ArrayList.remove(Unknown Source) ~[?:1.8.0_102]
    at cn.academy.vanilla.teleporter.skill.LocTeleportData.remove(LocationTeleport.scala:533) ~[LocTeleportData.class:?]
    at cn.academy.vanilla.teleporter.skill.LTNetDelegate$.hRemove(LocationTeleport.scala:70) ~[LTNetDelegate$.class:?]
    ... 29 more
```

**Comment by Paindar** [comment]
无法重现+历史遗留。
