### ISSUE TITLE
[1.0.5]Crash every time first skill was ready to use

### ISSUE THREAD

**Issue by Ultipotence** [LambdaInnovation/AcademyCraft#539]
While attempting to play, I kept stumbling on the same old crashing bug every time I had my first skill set up and ready to use. I was wondering if this is common, and if theres any solution to it?

Thanks in advanced to anyone who manages to help.

---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 12/10/16 2:44 PM
XRay version: 43
Description: Ticking player

java.lang.IllegalStateException: Can only activate context at local.
	at com.google.common.base.Preconditions.checkState(Preconditions.java:176)
	at cn.academy.ability.api.context.ContextManager.activate(ContextManager.java:70)
	at cn.academy.ability.api.Skill$SingleKeyDelegate.onKeyDown(Skill.java:429)
	at cn.academy.ability.api.context.ClientRuntime$Events.onClientTick(ClientRuntime.java:300)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_147_Events_onClientTick_TickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at cpw.mods.fml.common.FMLCommonHandler.onPlayerPreTick(FMLCommonHandler.java:345)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:220)
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:295)
	at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:303)
	at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:137)
	at net.minecraft.network.play.client.C03PacketPlayer$C06PacketPlayerPosLook.func_148833_a(SourceFile:20)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.google.common.base.Preconditions.checkState(Preconditions.java:176)
	at cn.academy.ability.api.context.ContextManager.activate(ContextManager.java:70)
	at cn.academy.ability.api.Skill$SingleKeyDelegate.onKeyDown(Skill.java:429)
	at cn.academy.ability.api.context.ClientRuntime$Events.onClientTick(ClientRuntime.java:300)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_147_Events_onClientTick_TickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at cpw.mods.fml.common.FMLCommonHandler.onPlayerPreTick(FMLCommonHandler.java:345)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:220)
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:295)

-- Player being ticked --
Details:
	Entity Type: null (net.minecraft.entity.player.EntityPlayerMP)
	Entity ID: 130
	Entity Name: Alpha_Reality
	Entity's Exact location: 1584.18, 4.42, 854.36
	Entity's Block location: World: (1584,4,854), Chunk: (at 0,0,6 in 99,53; contains blocks 1584,0,848 to 1599,255,863), Region: (3,1; contains chunks 96,32 to 127,63, blocks 1536,0,512 to 2047,255,1023)
	Entity's Momentum: 0.00, 0.42, 0.00
Stacktrace:
	at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:303)
	at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:137)
	at net.minecraft.network.play.client.C03PacketPlayer$C06PacketPlayerPosLook.func_148833_a(SourceFile:20)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@4335b069
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 214804824 bytes (204 MB) / 913833984 bytes (871 MB) up to 954728448 bytes (910 MB)
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 1, tallocated: 14
	FML: Minecraft 1.7.10 MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 33 mods loaded, 33 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.5.37} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	LambdaLib|Core{1.2.3} [LambdaLib|Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.4.90} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.4.90-universal.jar) 
	UCHIJAAAA	FastCraft{1.23} [FastCraft] (fastcraft-1.23.jar) 
	UCHIJAAAA	Backpack{2.0.0} [Backpack] (14174871878_Backpacks-Mod (2).jar) 
	UCHIJAAAA	More Crafting Recipes Mod{Minecraft 1.7.2} [More Crafting Recipes Mod] ([2.2.0] More Crafting Recipes Mod.jar) 
	UCHIJAAAA	LambdaLib{1.2.3} [LambdaLib] (LambdaLib-1.2.3.jar) 
	UCHIJAAAA	academy-craft{1.0.5} [Academy Craft] (AcademyCraft-1.0.5.jar) 
	UCHIJAAAA	ArchitectureCraft{1.4.1} [ArchitectureCraft] (ArchitectureCraft-Mod-1.7.10.jar) 
	UCHIJAAAA	BiblioCraft{1.11.5} [BiblioCraft] (BiblioCraft[v1.11.5][MC1.7.10].jar) 
	UCHIJAAAA	cfm{3.4.8} [§9MrCrayfish's Furniture Mod] (cfm-3.4.8-mc1.7.10.jar) 
	UCHIJAAAA	chisel{1.5.7} [Chisel] (Chisel-1.7.10-1.5.7.jar) 
	UCHIJAAAA	craftablehorsearmour{1.1} [Craftable Horse Armour [CHA&S]] (Craftable-Horse-Armour-and-Saddle-Mod-1.7.10.jar) 
	UCHIJAAAA	customnpcs{1.7.10d} [CustomNpcs] (CustomNPCs_1.7.10d(21feb16).jar) 
	UCHIJAAAA	DamageIndicatorsMod{3.2.0} [Damage Indicators] (Damage-Indicators-Mod-1.7.10.jar) 
	UCHIJAAAA	decorativemarble{Beta 1.1710.3} [Decorative Marble] (decorativemarble-1.1710.3.jar) 
	UCHIJAAAA	decorativechimney{Beta 1.1710.3} [Decorative Chimney] (decorativechimney-1.1710.3.jar) 
	UCHIJAAAA	jinryuujrmcore{1.2.22} [JinRyuu's JRMCore] (JRMCore-v1.2.22.jar) 
	UCHIJAAAA	jinryuudragonblockc{1.4.19} [Dragon Block C] (DragonBlockC-v1.4.19.jar) 
	UCHIJAAAA	grim3212core{V0.2 - 1.7.10} [Grim3212 Core] (Grim3212-Core-1.7.10.jar) 
	UCHIJAAAA	fireplaces{V0.1 - 1.7.10} [Fireplaces] (Fireplace-Mod-1.7.10.jar) 
	UCHIJAAAA	F2L{1.7.10b} [Flesh2Leather] (Flesh2Lether [1.7.10b].jar) 
	UCHIJAAAA	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) 
	UCHIJAAAA	jinryuubetterrenderaddon{1.6.11} [JinRyuu's Better Render Addon] (JBRA-Client-v1.6.11.jar) 
	UCHIJAAAA	jinryuufamilyc{1.2.13} [JinRyuu's Family C] (JFamilyC-v1.2.13.jar) 
	UCHIJAAAA	jinryuuhdskinsextended{1.3} [JinRyuu's HD Skins Extended] (JinRyuu%27s-HDSkins-Mod-1.7.10-v1.3.jar) 
	UCHIJAAAA	jinryuuyearsc{1.2.2} [JinRyuu's Years C] (JYearsC-v1.2.2.jar) 
	UCHIJAAAA	malisiscore{1.7.10-0.14.3} [MalisisCore] (malisiscore-1.7.10-0.14.3.jar) 
	UCHIJAAAA	malisisdoors{1.7.10-1.13.2} [Malisis' Doors] (malisisdoors-1.7.10-1.13.2.jar) 
	UCHIJAAAA	wildcaves3{0.4.3.6} [Wild Caves 3] (Wild-Caves-Mod-1.7.10.jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [EntityPlayerMP['Alpha_Reality'/130, l='New World', x=1584.18, y=4.42, z=854.36]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by Paindar** [comment]
Thank you for reporting this bug.
It's my fault, because I uploaded an **unnormal** AcademyCraft.jar. 
Temporary solution is to use 1.0.4. AcademyCraft 1.0.6 is comming soon, as fast as I can.
