### ISSUE TITLE
Crashes on serever

### ISSUE THREAD

**Issue by TooVeryIcey** [LambdaInnovation/AcademyCraft#543]
Hello, I have been trying to setup a modpack for my server, and well booting up the server, I noticed this mod crashed with this as the output:
```
---- Minecraft Crash Report ----
// I just don't know what went wrong :(

Time: 12/18/16 7:44 AM
Description: Exception in server tick loop

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: cn/academy/ability/api/context/ClientRuntime
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:559)
	at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:88)
	at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:314)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:117)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.NoClassDefFoundError: cn/academy/ability/api/context/ClientRuntime
	at java.lang.Class.getDeclaringClass0(Native Method)
	at java.lang.Class.getDeclaringClass(Unknown Source)
	at java.lang.Class.getEnclosingClass(Unknown Source)
	at java.lang.Class.getCanonicalName(Unknown Source)
	at cn.lambdalib.annoreg.core.RegistrationManager.findMod(RegistrationManager.java:97)
	at cn.lambdalib.annoreg.core.RegistryType.newData(RegistryType.java:50)
	at cn.lambdalib.annoreg.core.RegistryType.visitField(RegistryType.java:69)
	at cn.lambdalib.annoreg.core.RegistrationManager.prepareClass(RegistrationManager.java:69)
	at cn.lambdalib.annoreg.core.RegistrationManager.loadClasses(RegistrationManager.java:44)
	at cn.lambdalib.annoreg.core.RegistrationManager.registerAll(RegistrationManager.java:142)
	at cn.lambdalib.annoreg.core.RegistrationManager.registerAll(RegistrationManager.java:155)
	at cn.lambdalib.core.LambdaLib.preInit(LambdaLib.java:69)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
	... 5 more
Caused by: java.lang.ClassNotFoundException: cn.academy.ability.api.context.ClientRuntime
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 43 more
Caused by: java.lang.RuntimeException: Attempted to load class cn/academy/ability/api/context/ClientRuntime for invalid side SERVER
	at cpw.mods.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:50)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 45 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Linux (amd64) version 2.6.18-406.el5
	Java Version: 1.8.0_77, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 99308504 bytes (94 MB) / 518979584 bytes (494 MB) up to 518979584 bytes (494 MB)
	JVM Flags: 9 total; -Xms256M -Xmx512M -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+UseAdaptiveGCBoundary -XX:-UseGCOverheadLimit -XX:+DisableExplicitGC -XX:ErrorFile=/dev/null -XX:UseSSE=3
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 119 mods loaded, 118 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{7.10.99.99} [Forge Mod Loader] (Mod_Forge_1.7.10-10.13.4.1558.jar) 
	UCH	Forge{10.13.4.1558} [Minecraft Forge] (Mod_Forge_1.7.10-10.13.4.1558.jar) 
	UCH	AM2-Preloader{0.0.3} [AMCore] (minecraft.jar) 
	UCH	appliedenergistics2-core{rv3-beta-6} [Applied Energistics 2 Core] (minecraft.jar) 
	UCH	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCH	LambdaLib|Core{1.2.3} [LambdaLib|Core] (minecraft.jar) 
	UCH	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UCH	ThE-core{1.0.0.1} [Thaumic Energistics Core] (minecraft.jar) 
	UCH	ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core] (minecraft.jar) 
	UCH	WitchingGadgetsCore{1.1.10} [Witching Gadgets Core] (minecraft.jar) 
	UCH	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCH	ItemBlacklist{1.2.0.8} [ItemBlacklist] (ItemBlacklist-1.7.10-1.2.0.8.jar) 
	UCH	AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI-1.7.10-1.2.4.jar) 
	UCH	arsmagica2{1.4.0.009} [Ars Magica 2] (1.7.10_AM2-1.4.0.009.jar) 
	UCE	LambdaLib{1.2.3} [LambdaLib] (LambdaLib-1.2.3.jar) 
	UCH	CoFHCore{1.7.10R3.1.3} [CoFH Core] (CoFHCore-[1.7.10]3.1.3-327.jar) 
	UCE	academy-craft{1.0.5} [Academy Craft] (AcademyCraft-1.0.5.jar) 
	UCH	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCH	adventurebackpack{1.7.10-0.8b} [Adventure Backpack] (adventurebackpack-1.7.10-0.8c.jar) 
	UCH	Enchiridion{1.3} [Enchiridion] (Enchiridion 2-1.7.10-2.0.2a.jar) 
	UCH	adventurersamulets{1.7.10-1.5.0c} [Adventurer's Amulets] (AdventurersAmulets-1.7.10-1.5.0c.jar) 
	UCH	appliedenergistics2{rv3-beta-6} [Applied Energistics 2] (appliedenergistics2-rv3-beta-6.jar) 
	UCH	bdlib{1.9.4.109} [BD Lib] (bdlib-1.9.4.109-mc1.7.10.jar) 
	UCH	ae2stuff{0.5.0.56} [AE2 Stuff] (ae2stuff-0.5.0.56-mc1.7.10.jar) 
	UCH	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) 
	UCH	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCH	Automagy{0.28.2} [Automagy] (Automagy-1.7.10-0.28.2.jar) 
	UCH	FLabsBF{4.3} [Better Furnaces] (betterfurnaces-4.3.jar) 
	UCH	BiblioCraft{1.11.5} [BiblioCraft] (BiblioCraft[v1.11.5][MC1.7.10].jar) 
	UCH	BiomeTweaker{2.0.182} [BiomeTweaker] (BiomeTweaker-1.7.10-2.0.182.jar) 
	UCH	AWWayofTime{v1.3.3} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.7.10-1.3.3-17.jar) 
	UCH	Botania{r1.8-249} [Botania] (Botania r1.8-249.jar) 
	UCH	BuildCraft|Core{7.1.18} [BuildCraft] (buildcraft-7.1.18.jar) 
	UCH	redgear_core{2.2.2} [Red Gear Core] (RedGearCore-1.7.10-2.2.2.jar) 
	UCH	redgear_brewcraft{1.3.3} [Brewcraft] (Brewcraft-1.7.10-1.3.3.jar) 
	UCH	BuildCraft|Transport{7.1.18} [BC Transport] (buildcraft-7.1.18.jar) 
	UCH	BuildCraft|Silicon{7.1.18} [BC Silicon] (buildcraft-7.1.18.jar) 
	UCH	BuildCraft|Energy{7.1.18} [BC Energy] (buildcraft-7.1.18.jar) 
	UCH	BuildCraft|Factory{7.1.18} [BC Factory] (buildcraft-7.1.18.jar) 
	UCH	BuildCraft|Builders{7.1.18} [BC Builders] (buildcraft-7.1.18.jar) 
	UCH	BuildCraft|Robotics{7.1.18} [BC Robotics] (buildcraft-7.1.18.jar) 
	UCH	ThermalFoundation{1.7.10R1.2.6B1} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.6B1-116.jar) 
	UCH	ThermalExpansion{1.7.10R4.1.4} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.1.4-247.jar) 
	UCH	BuildCraft|Compat{7.1.5} [BuildCraft Compat] (buildcraft-compat-7.1.5.jar) 
	UCH	eureka{3.0.2} [Eureka] (Eureka-1.7.10-3.0.2.jar) 
	UCH	bcadditions{2.2.5} [BuildCraft Additions] (BuildcraftAdditions-1.7.10-2.2.5.jar) 
	UCH	EE3{0.3.0.547} [Equivalent Exchange 3] (EquivalentExchange3-1.7.10-0.3.0.547.jar) 
	UCH	chisel{2.9.5.11} [Chisel] (Chisel-2.9.5.11.jar) 
	UCH	CarpentersBlocks{3.3.8.1} [Carpenter's Blocks] (Carpenter's Blocks v3.3.8.1 - MC 1.7.10.jar) 
	UCH	ChiselFacades{1.7.10-2.12-chiselteam} [Chisel Facades] (ChiselFacades-1.7.10-2.12-chiselteam.jar) 
	UCH	climatecontrol{0.6.beta60} [Climate Control] (ClimateControl-0.6.61.jar) 
	UCH	clockworkphase{1.7.10_1.0f} [Clockwork Phase] (clockworkphase-1.7.10_1.0f.jar) 
	UCH	DummyCore{1.13} [DummyCore] (DummyCore1.13.jar) 
	UCH	eplus{3.0.2-d} [Enchanting Plus] (EnchantingPlus-1.7.10-3.0.2-d.jar) 
	UCH	Enchiridion2{2.0.2a} [Enchiridion 2] (Enchiridion 2-1.7.10-2.0.2a.jar) 
	UCH	extracells{2.3.14} [Extra Cells 2] (ExtraCells-1.7.10-2.3.14b197.jar) 
	UCH	ExtraUtilities{1.2.12} [Extra Utilities] (extrautilities-1.2.12.jar) 
	UCH	harvestcraft{1.7.10j} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10Lb.jar) 
	UCH	Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (Mantle-1.7.10-0.3.2b.jar) 
	UCH	TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct] (TConstruct-1.7.10-1.8.8.jar) 
	UCH	ExtraTiC{1.4.6} [ExtraTiC] (ExtraTiC-1.7.10-1.4.6.jar) 
	UCH	fairylights{1.4.0} [Fairy Lights] (fairylights-1.4.0-1.7.10.jar) 
	UCH	fastleafdecay{1.4} [Fast Leaf Decay] (FastLeafDecay-1.7.10-1.4.jar) 
	UCH	ThaumicTinkerer{unspecified} [Thaumic Tinkerer] (ThaumicTinkerer-2.5-1.7.10-164.jar) 
	UCH	ForbiddenMagic{1.7.10-0.575} [Forbidden Magic] (Forbidden Magic-1.7.10-0.575.jar) 
	UCH	FortuneOres{2.0.5} [FortuneOres] (FortuneOres-MC1.7.10-2.0.5.jar) 
	UCH	MineTweaker3{3.0.10} [MineTweaker 3] (MineTweaker3-1.7.10-3.0.10B.jar) 
	UCH	FTBL{1.0.18.2} [FTBLib] (FTBLib-1.7.10-1.0.18.3.jar) 
	UCH	FTBU{1.0.18.2} [FTBUtilities] (FTBUtilities-1.7.10-1.0.18.3.jar) 
	UCH	gadomancy{1.0.7.3} [Gadomancy] (gadomancy-1.7.10-1.0.7.3.jar) 
	UCH	guideapi{1.7.10-1.0.1-29} [Guide-API] (Guide-API-1.7.10-1.0.1-29.jar) 
	UCH	iChunUtil{4.0.0} [iChunUtil] (iChunUtil-4.0.0.jar) 
	UCH	IGWMod{1.1.11-32} [In-Game wiki Mod] (IGW-Mod-1.7.10-1.1.11-32-universal.jar) 
	UCH	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) 
	UCH	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) 
	UCH	JABBA{1.2.2} [JABBA] (Jabba-1.2.2_1.7.10.jar) 
	UCH	legendgear{2.b.2.1} [LegendGear 2] (legendgear-1.7.10-2.b.2.1.jar) 
	UCH	Login_Shield{1.2-10-gd36e6a4} [Login Shield] (Login_Shield-1.2-10-gd36e6a4.jar) 
	UCH	LogisticsPipes{0.9.3.128} [Logistics Pipes] (logisticspipes-0.9.3.128.jar) 
	UCH	magicalcrops{4.0.0_PUBLIC_BETA_4b} [Magical Crops: Core] (magicalcrops-4.0.0_PUBLIC_BETA_5.jar) 
	UCH	magicalcropsarmour{4.0.0_PUBLIC_BETA_4} [Magical Crops: Armoury] (magicalcropsarmoury-4.0.0_PUBLIC_BETA_4.jar) 
	UCH	magicalcropsdeco{4.0.0_PUBLIC_BETA_4a} [Magical Crops: Decorative] (magicalcropsdeco-4.0.0_PUBLIC_BETA_4a.jar) 
	UCH	modtweaker2{0.9.6} [Mod Tweaker 2] (ModTweaker2-0.9.6.jar) 
	UCH	Morph{0.9.3} [Morph] (Morph-Beta-0.9.3.jar) 
	UCH	mputils{1.0.0} [MPUtils] (mputils-1.7.10-1.0.8.jar) 
	UCH	cfm{3.4.7} [�9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.4.7(1.7.10).jar) 
	UCH	Mystcraft{0.12.3.03} [Mystcraft] (mystcraft-1.7.10-0.12.3.03.jar) 
	UCH	netherportalfix{1.0} [Nether Portal Fix] (netherportalfix-mc1.7.10-1.1.0.jar) 
	UCH	numina{0.4.1.103} [Numina] (Numina-0.4.1.103.jar) 
	UCH	SonarCore{1.1.3} [SonarCore] (SonarCore-1.7.10-1.1.3.jar) 
	UCH	PracticalLogistics{0.2.4} [Practical Logistics] (Practical-Logistics-1.7.10-0.2.4.jar) 
	UCH	RadixCore{2.1.3} [RadixCore] (RadixCore-1.7.10-2.1.3-universal.jar) 
	UCH	rftools{4.23} [RFTools] (rftools-4.23.jar) 
	UCH	RTG{1.7.10-1.1.1.3} [Realistic Terrain Generation] (RTG-1.7.10-1.1.1.3.jar) 
	UCH	Sanguimancy{1.7.10-1.1.9-35} [Sanguimancy] (Sanguimancy-1.7.10-1.1.9-35.jar) 
	UCH	spacore{01.05.12} [SpACore] (SpACore-1.7.10-01.05.12.jar) 
	UCH	StorageDrawers{1.7.10-1.10.1} [Storage Drawers] (StorageDrawers-1.7.10-1.10.1.jar) 
	UCH	storageSilo{1.2.2} [StorageSilo] (StorageSilo-1.7.10-1.2.2.jar) 
	UCH	thaumcraftneiplugin{@VERSION@} [Thaumcraft NEI Plugin] (thaumcraftneiplugin-1.7.10-1.7a.jar) 
	UCH	thaumicenergistics{1.0.0.5} [Thaumic Energistics] (thaumicenergistics-1.0.0.5.jar) 
	UCH	ThaumicExploration{0.6.0} [Thaumic Exploration] (ThaumicExploration-1.7.10-1.1-53.jar) 
	UCH	ThaumicHorizons{1.1.9} [Thaumic Horizons] (thaumichorizons-1.7.10-1.1.9.jar) 
	UCH	thaumicinfusion{4.32} [Thaumic Infusion] (ThaumicInfusion-4.32.jar) 
	UCH	TiCTooltips{1.2.5} [TiC Tooltips] (TiCTooltips-mc1.7.10-1.2.5.jar) 
	UCH	tinkersdefense{1.3.7} [Tinkers' Defense] (tinkersdefense-1.3.7.jar) 
	UCH	totemic{1.7.10-0.6.2} [Totemic] (Totemic-1.7.10-0.6.2.jar) 
	UCH	TravellersGear{1.16.6} [Traveller's Gear] (TravellersGear-1.7.10-1.16.6.jar) 
	UCH	VeinMiner{0.34.1_1.7.10-4d066f1} [Vein Miner] (VeinMiner-0.34.1-1.7.10r473+4d066f1.jar) 
	UCH	VeinMinerModSupport{0.34.1_1.7.10-4d066f1} [Mod Support] (VeinMiner-0.34.1-1.7.10r473+4d066f1.jar) 
	UCH	WailaHarvestability{1.1.6} [Waila Harvestability] (WailaHarvestability-mc1.7.10-1.1.6.jar) 
	UCH	wawla{1.3.1} [What Are We Looking At] (Wawla-1.0.5.120.jar) 
	UCH	witchery{0.24.1} [Witchery] (witchery-1.7.10-0.24.1.jar) 
	UCH	WitchingGadgets{1.1.10} [Witching Gadgets] (WitchingGadgets-1.7.10-1.1.10.jar) 
	UCH	XPT{1.2.9} [XP Teleporters] (XPTeleporters-1.7.10-1.2.9.jar) 
	UCH	ZDoctorBB{1.2} [Blood Baubles] (ZDoctorBB-1.7.10-Server.jar) 
	UCH	IguanaTweaksTConstruct{1.7.10-2.1.6.163} [Iguana Tinker Tweaks] (IguanaTinkerTweaks-1.7.10-2.1.6.jar) 
	UCH	NEI-Mystcraft-Plugin{02.01.09} [NEI Mystcraft Plugin] (MystNEI-Plugin-1.7.10-02.01.09.jar) 
	UD	BiomeTweakerCore{2.0.182} [BiomeTweaker Core] (minecraft.jar) 
	CoFHCore: -[1.7.10]3.1.3-327
	AE2 Version: beta rv3-beta-6 for Forge 10.13.4.1448
	ThermalFoundation: -[1.7.10]1.2.6B1-116
	ThermalExpansion: -[1.7.10]4.1.4-247
	Mantle Environment: Environment healthy.
	TConstruct Environment: Environment healthy.
	SpACore ASM Transformers: 
		GLStateManager: false
		GLStateManager debug output: false
		Debug screen replacer: true
	List of loaded APIs: 
		* appliedenergistics2|API (rv2) from ThaumicTinkerer-2.5-1.7.10-164.jar
		* BaublesAPI (1-princess) from AdventurersAmulets-1.7.10-1.5.0c.jar
		* Baubles|API (1.0.1.10) from Baubles-1.7.10-1.0.1.10.jar
		* bcadditionsAPI (2.1.1) from BuildcraftAdditions-1.7.10-2.2.5.jar
		* BiomeTweakerAPI (1.0.182) from BiomeTweaker-1.7.10-2.0.182.jar
		* BiomeTweakerAPI|event (1.0.182) from BiomeTweaker-1.7.10-2.0.182.jar
		* BiomeTweakerAPI|script|object (1.0.182) from BiomeTweaker-1.7.10-2.0.182.jar
		* BiomeTweakerAPI|script|pack (1.0.182) from BiomeTweaker-1.7.10-2.0.182.jar
		* BiomeTweakerAPI|script|wrapper (1.0.182) from BiomeTweaker-1.7.10-2.0.182.jar
		* BiomeTweakerAPI|util (1.0.182) from BiomeTweaker-1.7.10-2.0.182.jar
		* BloodMagicAPI (1.3.3-13) from BloodMagic-1.7.10-1.3.3-17.jar
		* BotaniaAPI (76) from Botania r1.8-249.jar
		* BuildCraftAPI|blocks (1.0) from buildcraft-7.1.18.jar
		* BuildCraftAPI|blueprints (1.5) from buildcraft-7.1.18.jar
		* BuildCraftAPI|boards (2.0) from buildcraft-7.1.18.jar
		* BuildCraftAPI|core (2.0) from buildcraft-7.1.18.jar
		* BuildCraftAPI|crops (1.1) from buildcraft-7.1.18.jar
		* BuildCraftAPI|events (2.0) from buildcraft-7.1.18.jar
		* BuildCraftAPI|facades (1.1) from buildcraft-7.1.18.jar
		* BuildCraftAPI|filler (4.0) from buildcraft-7.1.18.jar
		* BuildCraftAPI|fuels (2.0) from buildcraft-7.1.18.jar
		* BuildCraftAPI|gates (4.1) from buildcraft-7.1.18.jar
		* BuildCraftAPI|items (1.1) from buildcraft-7.1.18.jar
		* BuildCraftAPI|library (2.0) from buildcraft-7.1.18.jar
		* BuildCraftAPI|lists (1.0) from buildcraft-7.1.18.jar
		* BuildCraftAPI|power (1.3) from buildcraft-7.1.18.jar
		* BuildCraftAPI|recipes (3.0) from buildcraft-7.1.18.jar
		* BuildCraftAPI|robotics (3.0) from buildcraft-7.1.18.jar
		* BuildCraftAPI|statements (1.1) from buildcraft-7.1.18.jar
		* BuildCraftAPI|tablet (1.0) from buildcraft-7.1.18.jar
		* BuildCraftAPI|tiles (1.2) from buildcraft-7.1.18.jar
		* BuildCraftAPI|tools (1.0) from buildcraft-7.1.18.jar
		* BuildCraftAPI|transport (4.1) from buildcraft-7.1.18.jar
		* CarpentersBlocks|API (3.3.7) from Carpenter's Blocks v3.3.8.1 - MC 1.7.10.jar
		* ChiselAPI (0.1.1) from Chisel-2.9.5.11.jar
		* ChiselAPI|Carving (0.1.1) from Chisel-2.9.5.11.jar
		* ChiselAPI|Rendering (0.1.1) from Chisel-2.9.5.11.jar
		* CoFHAPI (1.7.10R1.0.2) from AcademyCraft-1.0.5.jar
		* CoFHAPI|block (1.7.10R1.0.3) from RedGearCore-1.7.10-2.2.2.jar
		* CoFHAPI|core (1.7.10R1.3.1) from CoFHCore-[1.7.10]3.1.3-327.jar
		* CoFHAPI|energy (1.7.10R1.0.2) from buildcraft-7.1.18.jar
		* CoFHAPI|fluid (1.7.10R1.1.0) from SonarCore-1.7.10-1.1.3.jar
		* CoFHAPI|inventory (1.7.10R1.1.0) from SonarCore-1.7.10-1.1.3.jar
		* CoFHAPI|item (1.7.10R1.1.0) from SonarCore-1.7.10-1.1.3.jar
		* CoFHAPI|modhelpers (1.7.10R1.3.1) from CoFHCore-[1.7.10]3.1.3-327.jar
		* CoFHAPI|tileentity (1.7.10R1.0.3) from RedGearCore-1.7.10-2.2.2.jar
		* CoFHAPI|transport (1.7.10R1.0.1) from buildcraft-compat-7.1.5.jar
		* CoFHAPI|world (1.7.10R1.3.1) from CoFHCore-[1.7.10]3.1.3-327.jar
		* CoFHLib (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.3-327.jar
		* CoFHLib|audio (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.3-327.jar
		* CoFHLib|gui (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.3-327.jar
		* CoFHLib|gui|container (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.3-327.jar
		* CoFHLib|gui|element (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.3-327.jar
		* CoFHLib|gui|element|listbox (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.3-327.jar
		* CoFHLib|gui|slot (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.3-327.jar
		* CoFHLib|inventory (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.3-327.jar
		* CoFHLib|render (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.3-327.jar
		* CoFHLib|render|particle (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.3-327.jar
		* CoFHLib|util (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.3-327.jar
		* CoFHLib|util|helpers (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.3-327.jar
		* CoFHLib|util|position (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.3-327.jar
		* CoFHLib|world (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.3-327.jar
		* CoFHLib|world|feature (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.3-327.jar
		* EE3-API|array (1.4.0) from EquivalentExchange3-1.7.10-0.3.0.547.jar
		* EE3-API|blacklist (@API_VERSION@) from EquivalentExchange3-1.7.10-0.3.0.547.jar
		* EE3-API|core (1.4.0) from EquivalentExchange3-1.7.10-0.3.0.547.jar
		* EE3-API|event (1.4.0) from EquivalentExchange3-1.7.10-0.3.0.547.jar
		* EE3-API|exchange (1.4.0) from EquivalentExchange3-1.7.10-0.3.0.547.jar
		* EE3-API|knowledge (1.4.0) from EquivalentExchange3-1.7.10-0.3.0.547.jar
		* EE3-API|recipe (1.4.0) from EquivalentExchange3-1.7.10-0.3.0.547.jar
		* EE3-API|util (1.4.0) from EquivalentExchange3-1.7.10-0.3.0.547.jar
		* Guide-API|API (1.7.10-1.0.1-29) from Guide-API-1.7.10-1.0.1-29.jar
		* IC2API (1.0) from SonarCore-1.7.10-1.1.3.jar
		* McJtyLib (1.8.1) from mcjtylib-1.8.1.jar
		* Mystcraft|API (0.1) from mystcraft-1.7.10-0.12.3.03.jar
		* PracticalLogisticsAPI (1.4) from Practical-Logistics-1.7.10-0.2.4.jar
		* Sanguimancy|API (@VERSION@) from Sanguimancy-1.7.10-1.1.9-35.jar
		* StorageDrawersAPI (1.7.10-1.2.0) from StorageDrawers-1.7.10-1.10.1.jar
		* StorageDrawersAPI|config (1.7.10-1.2.0) from StorageDrawers-1.7.10-1.10.1.jar
		* StorageDrawersAPI|event (1.7.10-1.2.0) from StorageDrawers-1.7.10-1.10.1.jar
		* StorageDrawersAPI|inventory (1.7.10-1.2.0) from StorageDrawers-1.7.10-1.10.1.jar
		* StorageDrawersAPI|pack (1.7.10-1.2.0) from StorageDrawers-1.7.10-1.10.1.jar
		* StorageDrawersAPI|registry (1.7.10-1.2.0) from StorageDrawers-1.7.10-1.10.1.jar
		* StorageDrawersAPI|render (1.7.10-1.2.0) from StorageDrawers-1.7.10-1.10.1.jar
		* StorageDrawersAPI|storage (1.7.10-1.2.0) from StorageDrawers-1.7.10-1.10.1.jar
		* StorageDrawersAPI|storage-attribute (1.7.10-1.2.0) from StorageDrawers-1.7.10-1.10.1.jar
		* SuperScript (1.0.182) from BiomeTweaker-1.7.10-2.0.182.jar
		* SuperScript|command (1.0.182) from BiomeTweaker-1.7.10-2.0.182.jar
		* SuperScript|object (1.0.182) from BiomeTweaker-1.7.10-2.0.182.jar
		* SuperScript|util (1.0.182) from BiomeTweaker-1.7.10-2.0.182.jar
		* Thaumcraft|API (4.2.2.0) from Thaumcraft-1.7.10-4.2.3.5.jar
		* thaumicenergistics|API (1.1) from thaumicenergistics-1.0.0.5.jar
		* totemic|API (1.0.0) from Totemic-1.7.10-0.6.2.jar
		* TravellersGear|API (1.0) from TravellersGear-1.7.10-1.16.6.jar
		* VeinMinerApi (0.3) from VeinMiner-0.34.1-1.7.10r473+4d066f1.jar
		* WailaAPI (1.2) from Waila-1.5.10_1.7.10.jar
	Chisel: Errors like "[FML]: Unable to lookup ..." are NOT the cause of this crash. You can safely ignore these errors. And update forge while you're at it.
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)
```

**Comment by Paindar** [comment]
There is something wrong with 1.0.5, may you can try 1.0.4 or 1.0.6.

**Comment by 2veryicey** [comment]
alright, will try it :)
