### ISSUE TITLE
AcademyCraft1.0.6启动崩溃

### ISSUE THREAD

**Issue by zyx78935** [LambdaInnovation/AcademyCraft#550]
错误报告↓
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 17-1-3 上午10:30
Description: Initializing game

java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.google.common.base.Throwables.propagate(Throwables.java:160)
	at cn.lambdalib.annoreg.core.RegistryType.registerAll(RegistryType.java:164)
	at cn.lambdalib.annoreg.core.RegistrationManager.registerAll(RegistrationManager.java:149)
	at cn.lambdalib.annoreg.core.RegistrationManager.registerAll(RegistrationManager.java:155)
	at cn.lambdalib.annoreg.core.RegistryType.registerAll(RegistryType.java:83)
	at cn.lambdalib.annoreg.core.RegistrationManager.registerAll(RegistrationManager.java:149)
	at cn.lambdalib.annoreg.core.RegistrationManager.registerAll(RegistrationManager.java:155)
	at cn.academy.core.AcademyCraft.init(AcademyCraft.java:98)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:737)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cn.lambdalib.annoreg.mc.InitCallbackRegistration.register(InitCallbackRegistration.java:30)
	at cn.lambdalib.annoreg.mc.InitCallbackRegistration.register(InitCallbackRegistration.java:20)
	at cn.lambdalib.annoreg.base.RegistrationMethodSimple.registerMethod(RegistrationMethodSimple.java:28)
	at cn.lambdalib.annoreg.core.RegistryType.registerAll(RegistryType.java:159)
	... 42 more
Caused by: java.lang.IllegalStateException: Function is not supported
	at org.lwjgl.BufferChecks.checkFunctionAddress(BufferChecks.java:58)
	at org.lwjgl.opengl.GL20.glCreateProgram(GL20.java:255)
	at cn.lambdalib.util.client.shader.ShaderProgram.<init>(ShaderProgram.java:40)
	at cn.academy.vanilla.vecmanip.client.effect.PlasmaBodyRenderer.<init>(PlasmaBodyEffect.scala:109)
	at cn.academy.vanilla.vecmanip.client.effect.PlasmaBodyEffect_$.init(PlasmaBodyEffect.scala:34)
	at cn.academy.vanilla.vecmanip.client.effect.PlasmaBodyEffect_.init(PlasmaBodyEffect.scala)
	... 50 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.google.common.base.Throwables.propagate(Throwables.java:160)
	at cn.lambdalib.annoreg.core.RegistryType.registerAll(RegistryType.java:164)
	at cn.lambdalib.annoreg.core.RegistrationManager.registerAll(RegistrationManager.java:149)
	at cn.lambdalib.annoreg.core.RegistrationManager.registerAll(RegistrationManager.java:155)
	at cn.lambdalib.annoreg.core.RegistryType.registerAll(RegistryType.java:83)
	at cn.lambdalib.annoreg.core.RegistrationManager.registerAll(RegistrationManager.java:149)
	at cn.lambdalib.annoreg.core.RegistrationManager.registerAll(RegistrationManager.java:155)
	at cn.academy.core.AcademyCraft.init(AcademyCraft.java:98)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:737)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows XP (x86) version 5.1
	Java Version: 1.8.0_73, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 126087464 bytes (120 MB) / 398458880 bytes (380 MB) up to 536870912 bytes (512 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx512m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_U_D6 35 mods loaded, 35 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHI	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHI	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHI	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHI	CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar) 
	UCHI	NotEnoughItems{1.0.3.74} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.3.74-universal.jar) 
	UCHI	InputFix{1.7.10-v5} [InputFix] (minecraft.jar) 
	UCHI	ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core] (minecraft.jar) 
	UCHI	LambdaLib|Core{1.2.3} [LambdaLib|Core] (minecraft.jar) 
	UCHI	FastCraft{1.23} [FastCraft] (公共类-fastcraft-1.23.jar) 
	UCHI	DamageIndicatorsMod{3.2.0} [Damage Indicators] ([1.7.10]DamageIndicatorsMod-3.2.0.jar) 
	UCHI	LambdaLib{1.2.3} [LambdaLib] (科幻类-学园都市前置-LambdaLib-1.2.3.jar) 
	UCHE	academy-craft{1.0.6} [Academy Craft] (AcademyCraft-1.0.6.jar) 
	UCHI	UnicodeFontFixer{1.1.9-mc1.7.10} [UnicodeFontFixer] (Mcmap.cc-[通用字体修复MOD][1.7.10].jar) 
	UCHI	craftguide{1.6.8.2} [CraftGuide] (公共类-CraftGuide-1.6.8.2-forge[hukk汉化].jar) 
	UCHI	customnpcs{1.7.10d} [CustomNpcs] (公共类-CustomNPCs_1.7.10d(21feb16).jar) 
	UCHI	davincing{1710.1.8} [DaVincing] (异建类-达芬奇的方块-DaVincing-1710.1.8.jar) 
	UCHI	flansmod{4.10.0} [Flan's Mod] (战争类-Flans Mod Plus-1.7.10-4.10.0-1.0.3.jar) 
	UCHI	MapWriter{2.1.1} [MapWriter] (战争类-Flans Mod Plus-1.7.10-4.10.0-1.0.3.jar) 
	UCHI	BambooMod{Minecraft@MC_VERSION@ var@VERSION@} [BambooMod] (物语类-拔刀剑-竹Bamboo-2.6.8.5.jar) 
	UCHI	flammpfeil.slashblade{mc1.7.10-r82} [SlashBlade] (物语类-拔刀剑SlashBlade-mc1.7.10-r82.jar) 
	UCHI	FoodCraft{1.2.0} [FoodCraft(FoodCraft)] (物语类-食物工艺-FoodCraft-16.8.9-1.2.1-1.7.10.jar) 
	UCHI	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCHI	Thaumcraft{4.2.3.5} [Thaumcraft] (神秘类-神秘时代4-Thaumcraft-1.7.10-4.2.3.5 (1).jar) 
	UCHI	IC2{2.2.817-experimental} [IndustrialCraft 2] (科技类-工业2实验版-industrialcraft-2-2.2.817-experimental.jar) 
	UCHI	ThaumicTinkerer{unspecified} [Thaumic Tinkerer] (神秘类-神秘扩展-神秘工匠-ThaumicTinkerer-2.5-1.7.10-164.jar) 
	UCHI	TaintedMagic{1.1.6.3} [Tainted Magic] (神秘类-神秘扩展-污秽魔法-TaintedMagic-1.1.6.3.jar) 
	UCHI	BuildCraft|Core{7.1.18} [BuildCraft] (科技类-buildcraft-7.1.18.jar) 
	UCHI	BuildCraft|Transport{7.1.18} [BC Transport] (科技类-buildcraft-7.1.18.jar) 
	UCHI	BuildCraft|Silicon{7.1.18} [BC Silicon] (科技类-buildcraft-7.1.18.jar) 
	UCHI	BuildCraft|Energy{7.1.18} [BC Energy] (科技类-buildcraft-7.1.18.jar) 
	UCHI	BuildCraft|Factory{7.1.18} [BC Factory] (科技类-buildcraft-7.1.18.jar) 
	UCHI	BuildCraft|Builders{7.1.18} [BC Builders] (科技类-buildcraft-7.1.18.jar) 
	UCHI	BuildCraft|Robotics{7.1.18} [BC Robotics] (科技类-buildcraft-7.1.18.jar) 
	UCHI	AdvancedSolarPanel{1.7.10-3.5.1} [Advanced Solar Panels] (科技类-工业附属-高级太阳能-AdvancedSolarPanel-1.7.10-3.5.1.jar) 
	UCHI	Botania{r1.8-247} [Botania] (魔法类-植物魔法-Botania r1.8-247.jar) 
	GL info: ' Vendor: 'Intel' Version: '1.4.0 - Build 7.14.10.4957' Renderer: 'Intel Bear Lake B'
	Launched Version: HMCL 2.5.3.88
	LWJGL: 2.9.1
	OpenGL: Intel Bear Lake B GL version 1.4.0 - Build 7.14.10.4957, Intel
	GL Caps: Using GL 1.3 multitexturing.
Not using framebuffer objects because OpenGL 1.4 is not supported, EXT_blend_func_separate is supported, OpenGL 3.0 is not supported, ARB_framebuffer_object is not supported, and EXT_framebuffer_object is not supported.
Anisotropic filtering is supported and maximum anisotropy is 4.
Shaders are not available because OpenGL 2.1 is not supported, ARB_shader_objects is not supported, ARB_vertex_shader is not supported, and ARB_fragment_shader is not supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: 简体中文 (中国)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)
	OptiFine Version: OptiFine_1.7.10_HD_U_D6
	Render Distance Chunks: 2
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	OpenGlVersion: 1.4.0 - Build 7.14.10.4957
	OpenGlRenderer: Intel Bear Lake B
	OpenGlVendor: Intel
	CpuCount: 2

**Comment by Paindar** [comment]
初步怀疑是GL版本过低。
参见wiki：
另外，如果你的显卡不支持GL 3.3或以上版本，有可能在使用过程中出现崩溃。很老的显卡或者很旧的显卡驱动都可能导致这一问题。
