### ISSUE TITLE
[1.0.6] Concurrent Modification

### ISSUE THREAD

**Issue by loveyanbei** [LambdaInnovation/AcademyCraft#552]
Player got Message: Internal Server Error
java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437) ~[?:1.8.0_111]
        at java.util.HashMap$ValueIterator.next(HashMap.java:1466) ~[?:1.8.0_111]
        at cn.lambdalib.util.datapart.EntityData.tick(EntityData.java:209) ~[EntityData.class:?]
        at cn.lambdalib.util.datapart.EntityData.access$000(EntityData.java:34) ~[EntityData.class:?]
        at cn.lambdalib.util.datapart.EntityData$EventListener.onLivingUpdate(EntityData.java:223) ~[EntityData$EventListener.class:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_379_EventListener_onLivingUpdate_LivingUpdateEvent.invoke(.dynamic) ~[?:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:1.7.10-R0.1-SNAPSHOT]
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:1.7.10-R0.1-SNAPSHOT]
        at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:297) [ForgeHooks.class:1.7.10-R0.1-SNAPSHOT]
        at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1846) [sv.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_70071_h_(Unknown Source) [yz.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:393) [mw.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:482) [nh.class:?]
        at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(C03PacketPlayer.java:36) [jd.class:?]
        at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(C03PacketPlayer.java:101) [jd.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:991) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]

**Comment by Zsashas** [comment]
I just got this same thing...what triggered it for you? For me, it happened right when it was about to determine my ability type...
