### ISSUE TITLE
[1.0.6] SMP issue, can't launch a server

### ISSUE THREAD

**Issue by Kenryuu** [LambdaInnovation/AcademyCraft#553]
When I try to launch a server using the 1.0.6 version and 1.2.3 LambdaLib, it just start and close right away, and nothing shows up in the log. Weird thing is that I've got the same issue using every version to the 1.0.0 (with the correct LambdaLib), and in singleplayer, it works just fine. I'm using a server on omgserv with the latest build of forge (10.13.4.1614.1.7.10). I got a crash using KCauldron however. Here : 
 
[23:32:04] [main/ERROR]: An error occurred trying to configure the minecraft home at /var/directory_serv/minecraft_107652/. for Forge Mod Loader
java.lang.UnsupportedClassVersionError: cn/lambdalib/core/LLCorePlugin : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.7.0]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:791) ~[?:1.7.0]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.7.0]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449) ~[?:1.7.0]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71) ~[?:1.7.0]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[?:1.7.0]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[?:1.7.0]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[?:1.7.0]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:423) ~[?:1.7.0]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:356) ~[?:1.7.0]
	at java.lang.Class.forName0(Native Method) ~[?:1.7.0]
	at java.lang.Class.forName(Class.java:264) ~[?:1.7.0]
	at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:485) ~[KCauldron-1.7.10-1614.201.jar:1.7.10-R0.1-SNAPSHOT]
	at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:414) ~[KCauldron-1.7.10-1614.201.jar:1.7.10-R0.1-SNAPSHOT]
	at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:225) ~[KCauldron-1.7.10-1614.201.jar:1.7.10-R0.1-SNAPSHOT]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90) [KCauldron-1.7.10-1614.201.jar:1.7.10-R0.1-SNAPSHOT]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupServer(FMLLaunchHandler.java:74) [KCauldron-1.7.10-1614.201.jar:1.7.10-R0.1-SNAPSHOT]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForServerLaunch(FMLLaunchHandler.java:39) [KCauldron-1.7.10-1614.201.jar:1.7.10-R0.1-SNAPSHOT]
	at cpw.mods.fml.common.launcher.FMLServerTweaker.injectIntoClassLoader(FMLServerTweaker.java:23) [KCauldron-1.7.10-1614.201.jar:1.7.10-R0.1-SNAPSHOT]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0]
	at java.lang.reflect.Method.invoke(Method.java:601) ~[?:1.7.0]
	at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43) [KCauldron-1.7.10-1614.201.jar:1.7.10-R0.1-SNAPSHOT]
	at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12) [KCauldron-1.7.10-1614.201.jar:1.7.10-R0.1-SNAPSHOT]

Do you have a idea of what might be responsible for this, and if it's possible to get it to work, how would I have to do it ? Thanks in any case !

**Comment by 3TUSK** [comment]
> java.lang.UnsupportedClassVersionError: cn/lambdalib/core/LLCorePlugin : Unsupported major.minor version 52.0

AcademyCraft requires Java 8 to run. Contact your server admin to see if they can update, or just update it if you own the server.

**Comment by Kenryuu** [comment]
Well, that's what I get for not checking properties when taking a new server. Thanks !
