### ISSUE TITLE
[1.0.6] 能力开发导致崩溃

### ISSUE THREAD

**Issue by ghost** [LambdaInnovation/AcademyCraft#572]
---- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 17-3-11 上午2:59
XRay version: 33
Description: Ticking player

java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(Unknown Source)
	at java.util.HashMap$ValueIterator.next(Unknown Source)
	at cn.lambdalib.util.datapart.EntityData.tick(EntityData.java:209)
	at cn.lambdalib.util.datapart.EntityData.access$000(EntityData.java:34)
	at cn.lambdalib.util.datapart.EntityData$EventListener.onLivingUpdate(EntityData.java:223)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_302_EventListener_onLivingUpdate_LivingUpdateEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:287)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1560)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:288)
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:295)
	at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:303)
	at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:137)
	at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:8)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.util.HashMap$HashIterator.nextNode(Unknown Source)
	at java.util.HashMap$ValueIterator.next(Unknown Source)
	at cn.lambdalib.util.datapart.EntityData.tick(EntityData.java:209)
	at cn.lambdalib.util.datapart.EntityData.access$000(EntityData.java:34)
	at cn.lambdalib.util.datapart.EntityData$EventListener.onLivingUpdate(EntityData.java:223)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_302_EventListener_onLivingUpdate_LivingUpdateEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:287)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1560)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:288)

-- Player being ticked --
Details:
	Entity Type: null (net.minecraft.entity.player.EntityPlayerMP)
	Entity ID: 508
	Entity Name: mywordplayer55
	Entity's Exact location: -26.30, 64.00, 339.70
	Entity's Block location: World: (-27,64,339), Chunk: (at 5,4,3 in -2,21; contains blocks -32,0,336 to -17,255,351), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.00, -0.08, -0.10
Stacktrace:
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:295)
	at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:303)
	at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:137)
	at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:8)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@6dbd8c70
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_121, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 580869640 bytes (553 MB) / 1627283456 bytes (1551 MB) up to 2130051072 bytes (2031 MB)
	JVM Flags: 4 total; -Xmx2048m -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 3, tcache: 0, allocated: 12, tallocated: 96
	FML: Minecraft 1.7.10 MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_U_D7_pre 59 mods loaded, 59 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	InputFix{1.7.10-v5} [InputFix] (minecraft.jar) 
	UCHIJAAAA	LambdaLib|Core{1.2.3} [LambdaLib|Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UCHIJAAAA	ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core] (minecraft.jar) 
	UCHIJAAAA	ChestTransporter{2.0.6} [Chest Transporter] (%5B1.7.10%5DChest+Transporter+-+2.0.6.jar) 
	UCHIJAAAA	bookshelf{1.0.4.187} [Bookshelf] (%5B更好的附魔%5D%5B前置%5DBookshelf-1.7.10-1.0.4.187.jar) 
	UCHIJAAAA	eplus{4.0.0..73} [Enchanting Plus] (%5B更好的附魔%5D%5B本体%5DEnchantingPlus-1.7.10-4.0.0.74.jar) 
	UCHIJAAAA	endercompass{1.2} [Ender Compass] (%5B末影指南针%5DEnderCompass-1.7.10-1.2.jar) 
	UCHIJAAAA	YALSM{2.1.3} [Yet Another Leather Smelting Mod] (%5B皮革冶炼%5Dyalsm-2.1.3.jar) 
	UCHIJAAAA	Stacksize{1.0} [Stacksize Mod] (%5B重置堆放数量%5Dstacksize-1.7.10-1.2.jar) 
	UCHIJAAAA	Apocalypse{0.0.6} [Apocalypse] ([1.7.10]启示录——Apocalypse心殇汉化]-V0.0.6.jar) 
	UCHIJAAAA	recipehandler{1.7.10} [NoMoreRecipeConflict] ([不再有合成冲突]NoMoreRecipeConflict-1.7.10-0.3-CN.jar) 
	UCHIJAAAA	Torcherino{2.2s} [Torcherino] ([加速火把]Torcherino-TehNut-1.7.10-2.2.jar) 
	UCHIJAAAA	LambdaLib{1.2.3} [LambdaLib] (LambdaLib-1.2.3.jar) 
	UCHIJAAAA	academy-craft{1.0.6} [Academy Craft] (AcademyCraft-1.0.6.jar) 
	UCHIJAAAA	AutoSapling{1.0} [AutoSapling] (AutoSapling-1.1.jar) 
	UCHIJAAAA	BambooMod{Minecraft@MC_VERSION@ var@VERSION@} [BambooMod] (Bamboo-2.6.8.5.jar) 
	UCHIJAAAA	BBG{1.0.0} [BetterBedrockGen] (BBG-1.0.0.jar) 
	UCHIJAAAA	BuildCraft|Core{7.1.20} [BuildCraft] (buildcraft-7.1.20.jar) 
	UCHIJAAAA	BuildCraft|Robotics{7.1.20} [BC Robotics] (buildcraft-7.1.20.jar) 
	UCHIJAAAA	BuildCraft|Factory{7.1.20} [BC Factory] (buildcraft-7.1.20.jar) 
	UCHIJAAAA	BuildCraft|Transport{7.1.20} [BC Transport] (buildcraft-7.1.20.jar) 
	UCHIJAAAA	BuildCraft|Energy{7.1.20} [BC Energy] (buildcraft-7.1.20.jar) 
	UCHIJAAAA	BuildCraft|Silicon{7.1.20} [BC Silicon] (buildcraft-7.1.20.jar) 
	UCHIJAAAA	BuildCraft|Builders{7.1.20} [BC Builders] (buildcraft-7.1.20.jar) 
	UCHIJAAAA	ClockHUD{1.7.10-1.0} [Clock HUD] (ClockHUD-1.7.10-1.1.jar) 
	UCHIJAAAA	DummyCore{1.13} [DummyCore] (DummyCore1.13.jar) 
	UCHIJAAAA	endercore{1.7.10-0.2.0.39_beta} [EnderCore] (EnderCore-1.7.10-0.2.0.39_beta.jar) 
	UCHIJAAAA	EnderIO{2.0_beta} [Ender IO] (enderio-2.0_beta.124.jar) 
	UCHIJAAAA	fastleafdecay{1.4} [Fast Leaf Decay] (FastLeafDecay-1.7.10-1.4.jar) 
	UCHIJAAAA	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCHIJAAAA	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) 
	UCHIJAAAA	IC2{2.2.827-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.827-experimental.jar) 
	UCHIJAAAA	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCHIJAAAA	ThaumicTinkerer{unspecified} [Thaumic Tinkerer] (ThaumicTinkerer-2.5-1.7.10-164.jar) 
	UCHIJAAAA	ForbiddenMagic{1.7.10-0.57} [Forbidden Magic] (Forbidden Magic-1.7.10-0.57.jar) 
	UCHIJAAAA	ModGeochests{1.2.3} [Geochests] (geochests-1.7.10-v1.2.3.jar) 
	UCHIJAAAA	ImmersiveEngineering{0.7.7} [Immersive Engineering] (ImmersiveEngineering-0.7.7.jar) 
	UCHIJAAAA	samsinvcrafting{1.7.10-1.0.0} [Inventory Crafting] (InventoryCrafting-1.7.10-1.0.0.jar) 
	UCHIJAAAA	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) 
	UCHIJAAAA	journeymap{5.1.4p2} [JourneyMap] (journeymap-1.7.10-5.1.4p2-unlimited.jar) 
	UCHIJAAAA	meteors{2.14.3} [Falling Meteors] (meteors-1.7.10-2.14.3.jar) 
	UCHIJAAAA	MyHome{2.0.0} [MyHome] (myHome-2.0.0.jar) 
	UCHIJAAAA	neiintegration{1.1.2} [NEI Integration] (NEIIntegration-MC1.7.10-1.1.2.jar) 
	UCHIJAAAA	NEIPlugins{1.1.0.11-unofficial} [NEI Plugins Unofficial] (NEIPlugins-1.1.0.11.jar) 
	UCHIJAAAA	flammpfeil.slashblade{mc1.7.10-r87} [SlashBlade] (SlashBlade-mc1.7.10-r87.jar) 
	UCHIJAAAA	chunkbase_slimemod_ssp{2.1} [Slime Mod (SSP)] (SlimeModSSP-1.7.10-2.1.jar) 
	UCHIJAAAA	tchelper{1.7.10-1.4} [TC Research-Helper] (tchelper-1.7.10-1.4.jar) 
	UCHIJAAAA	thaumcraftneiplugin{1.7.10-1.6a} [Thaumcraft NEI Plugin] (thaumcraftneiplugin-1.7.10-1.6a.jar) 
	UCHIJAAAA	TwilightForest{2.3.7} [The Twilight Forest] (twilightforest-1.7.10-2.3.7.jar) 
	UCHIJAAAA	UnicodeFontFixer{1.1.12-mc1.7.10} [UnicodeFontFixer] (UnicodeFontFixer-1.1.12-mc1.7.10.jar) 
	UCHIJAAAA	VeinMiner{0.35.2_1.7.10-e134bd4} [Vein Miner] (VeinMiner-1.7.10-0.35.2.487%2Be134bd4.jar) 
	UCHIJAAAA	VeinMinerModSupport{0.35.2_1.7.10-e134bd4} [Mod Support] (VeinMiner-1.7.10-0.35.2.487%2Be134bd4.jar) 
	UCHIJAAAA	chunkbase_villageinfo_ssp{2.1} [Village Info (SSP)] (VillageInfoSSP-1.7.10-2.1.jar) 
	UCHIJAAAA	worldedit{6.1.1} [WorldEdit] (worldedit-forge-mc1.7.10-6.1.1-dist.jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [EntityPlayerMP['mywordplayer55'/508, l='test', x=-26.30, y=64.00, z=339.70]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.7.10_HD_U_D7_pre
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 NVIDIA 376.54
	OpenGlRenderer: GeForce GT 620/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 2

**Comment by Paindar** [comment]
这个现象一直不怎么好捕捉。。不过据我体验到话好像只会有概率地发生在第一次开发？

**Comment by LaoDongLD** [comment]
@Paindar 对，只有第一次开发会崩溃，当天有点晚了，着急没写清楚
