### ISSUE TITLE
A bug?

### ISSUE THREAD

**Issue by proren** [LambdaInnovation/AcademyCraft#595]
闪退
---- Minecraft Crash Report ----
// Sorry :(

Time: 17-8-28 下午9:05
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at cpw.mods.fml.common.versioning.VersionRange.getLowerBoundString(VersionRange.java:573)
	at cpw.mods.fml.client.GuiModsMissing.func_73863_a(GuiModsMissing.java:54)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1358)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at cpw.mods.fml.common.versioning.VersionRange.getLowerBoundString(VersionRange.java:573)
	at cpw.mods.fml.client.GuiModsMissing.func_73863_a(GuiModsMissing.java:54)

-- Screen render details --
Details:
	Screen name: cpw.mods.fml.client.GuiModsMissing
	Mouse location: Scaled: (292, 69). Absolute: (585, 341)
	Screen size: Scaled: (427, 240). Absolute: (854, 480). Scale factor of 2
Stacktrace:
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1358)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows XP (x86) version 5.1
	Java Version: 1.7.0_67, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 172629296 bytes (164 MB) / 402653184 bytes (384 MB) up to 1073741824 bytes (1024 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx1024m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 
0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_U_C1 50 mods loaded, 50 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	U	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	U	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	U	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	U	appliedenergistics2-core{rv3-beta-6} [Applied Energistics 2 Core] (minecraft.jar) 
	U	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	U	InputFix{1.7.10-v5} [InputFix] (minecraft.jar) 
	U	OpenEye{0.6} [OpenEye] ([信息采集]OpenEye-0.6-1.7.10.jar) 
	U	NotEnoughItems{1.0.5.120} [Not Enough Items] ([物品管理器]NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	U	betterfps{1.0.0} [BetterFps] (minecraft.jar) 
	U	academy-craft{1.0.6} [Academy Craft] ([AC]学园都市.jar) 
	U	appliedenergistics2{rv3-beta-6} [Applied Energistics 2] ([AE2]应用能源2.jar) 
	U	BuildCraft|Compat{7.1.6} [BuildCraft Compat] ([BC]BC兼容.jar) 
	U	BuildCraft|Core{7.1.22} [BuildCraft] ([BC]建筑.jar) 
	U	BuildCraft|Transport{7.1.22} [BC Transport] ([BC]建筑.jar) 
	U	BuildCraft|Factory{7.1.22} [BC Factory] ([BC]建筑.jar) 
	U	BuildCraft|Silicon{7.1.22} [BC Silicon] ([BC]建筑.jar) 
	U	BuildCraft|Robotics{7.1.22} [BC Robotics] ([BC]建筑.jar) 
	U	BuildCraft|Energy{7.1.22} [BC Energy] ([BC]建筑.jar) 
	U	BuildCraft|Builders{7.1.22} [BC Builders] ([BC]建筑.jar) 
	U	craftguide{1.6.8.2} [CraftGuide] ([G键合成]CraftGuide-1.6.8.2-forge[hukk汉化].jar) 
	U	IC2{2.2.828-experimental} [IndustrialCraft 2] ([IC2]工业2实验版.jar) 
	U	ImmersiveEngineering{0.7.7} [Immersive Engineering] ([IE]沉浸科技.jar) 
	U	LunatriusCore{1.1.2.21} [LunatriusCore] ([Mod依赖]LunatriusCore-1.7.10-1.1.2.21-universal.jar) 
	U	AS_UpdateCheck{1.1.7} [AtomicStryker Update Check Mod] ([Mod依赖]UpdateCheckerMod-1.7.10.jar) 
	U	NEIAddons{1.12.14.40} [NEI Addons] ([NEI扩展]neiaddons-1.12.14.40-mc1.7.10.jar) 
	U	NEIAddons|Developer{1.12.14.40} [NEI Addons: Developer Tools] ([NEI扩展]neiaddons-1.12.14.40-mc1.7.10.jar) 
	U	NEIAddons|AppEng{1.12.14.40} [NEI Addons: Applied Energistics 2] ([NEI扩展]neiaddons-1.12.14.40-mc1.7.10.jar) 
	U	NEIAddons|Botany{1.12.14.40} [NEI Addons: Botany] ([NEI扩展]neiaddons-1.12.14.40-mc1.7.10.jar) 
	U	NEIAddons|Forestry{1.12.14.40} [NEI Addons: Forestry] ([NEI扩展]neiaddons-1.12.14.40-mc1.7.10.jar) 
	U	NEIAddons|CraftingTables{1.12.14.40} [NEI Addons: Crafting Tables] ([NEI扩展]neiaddons-1.12.14.40-mc1.7.10.jar) 
	U	NEIAddons|ExNihilo{1.12.14.40} [NEI Addons: Ex Nihilo] ([NEI扩展]neiaddons-1.12.14.40-mc1.7.10.jar) 
	U	neiintegration{1.1.1} [NEI Integration] ([NEI扩展]NEIIntegration-MC1.7.10-1.1.1.jar) 
	U	DynamicLights{1.3.9} [Dynamic Lights] ([动态光源]DynamicLights-1.7.10.jar) 
	U	DynamicLights_onFire{1.0.5} [Dynamic Lights Burning Entity Module] ([动态光源]DynamicLights-1.7.10.jar) 
	U	DynamicLights_creepers{1.0.4} [Dynamic Lights Creeper Module] ([动态光源]DynamicLights-1.7.10.jar) 
	U	DynamicLights_dropItems{1.0.8} [Dynamic Lights EntityItem Module] ([动态光源]DynamicLights-1.7.10.jar) 
	U	DynamicLights_entityClasses{1.0.1} [Dynamic Lights Entity Light Module] ([动态光源]DynamicLights-1.7.10.jar) 
	U	DynamicLights_mobEquipment{1.0.8} [Dynamic Lights Mob Equipment Light Module] ([动态光源]DynamicLights-1.7.10.jar) 
	U	DynamicLights_flameArrows{1.0.0} [Dynamic Lights Fiery Arrows Light Module] ([动态光源]DynamicLights-1.7.10.jar) 
	U	DynamicLights_floodLights{1.0.2} [Dynamic Lights Flood Light] ([动态光源]DynamicLights-1.7.10.jar) 
	U	DynamicLights_otherPlayers{1.0.8} [Dynamic Lights OtherPlayers Light Module] ([动态光源]DynamicLights-1.7.10.jar) 
	U	DynamicLights_thePlayer{1.1.4} [Dynamic Lights Player Light Module] ([动态光源]DynamicLights-1.7.10.jar) 
	U	Waila{1.5.10} [Waila] ([方块信息显示]Waila-1.5.10_1.7.10.jar) 
	U	FastCraft{1.21} [FastCraft] ([游戏优化]fastcraft-1.21.jar) 
	U	InGameInfoXML{2.8.1.82} [InGame Info XML] ([游戏信息显示]InGameInfoXML-1.7.10-2.8.1.82-universal.jar) 
	U	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] ([物品整理]InventoryTweaks-1.59-dev-152.jar) 
	U	ArmorStatusHUD{1.28} [ArmorStatusHUD] ([耐久显示]ArmorStatusHUD.jar) 
	U	TofuCraft{2.1.5-MC1.7.10} [TofuCraft] ([豆腐]TofuCraft.jar) 
	U	WailaHarvestability{1.1.6} [Waila Harvestability] ([采掘信息显示]WailaHarvestability-mc1.7.10-1.1.6.jar) 
	U	bspkrsCore{6.16} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.16.jar) 
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.2.11954 Compatibility Profile Context' Renderer: 'AMD Radeon HD 5450'
	Launched Version: HMCL 2.5.3.88
	LWJGL: 2.9.1
	OpenGL: AMD Radeon HD 5450 GL version 4.2.11954 Compatibility Profile Context, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: 简体中文 (中国)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by Philosyang** [comment]
It seems to be impossible to launch the JVM with such a small allocation of RAM because there were actually no mods loaded when the crash report is generated. Try at least 2GB of allocated RAM.
看起来你给MC分配的内存太少了，至少分配2GB吧。
如何分配：

**Comment by proren** [comment]
thanks for reply.
