### ISSUE TITLE
1.7.10加载mod后崩溃

### ISSUE THREAD

**Issue by hyt658** [LambdaInnovation/AcademyCraft#618]
打开加载页面一会就闪退了，红色报错代码：
[23:31:56] [Client thread/ERROR] [FML]: Error when linking shader 'lambdalib:shaders/simple.vert'. code: 0, Error string: 
(6) : fatal error C9999: *** exception during compilation ***

[23:31:56] [Client thread/ERROR] [FML]: Error when linking shader 'academy:shaders/cpbar_cp.frag'. code: 0, Error string: 
0(20) : error C1008: undefined variable "texture2D"
0(23) : error C1008: undefined variable "texture2D"

[23:31:56] [Client thread/ERROR] [FML]: Error when linking program #1. Error code: 0, Error string: 
[23:31:56] [Client thread/ERROR] [FML]: 
[23:31:56] [Client thread/ERROR] [FML]: Error when linking shader 'lambdalib:shaders/simple.vert'. code: 0, Error string: 
(6) : fatal error C9999: *** exception during compilation ***

[23:31:56] [Client thread/ERROR] [FML]: Error when linking shader 'academy:shaders/cpbar_overload.frag'. code: 0, Error string: 
0(10) : error C1008: undefined variable "texture2D"
0(11) : error C1008: undefined variable "texture2D"

[23:31:56] [Client thread/ERROR] [FML]: Error when linking program #4. Error code: 0, Error string: 
[23:31:56] [Client thread/ERROR] [FML]: 
[23:31:57] [Client thread/INFO] [AcademyCraft]: Starting AcademyCraft
[23:31:57] [Client thread/INFO] [AcademyCraft]: Copyright (c) Lambda Innovation, 2013-2018
[23:31:57] [Client thread/INFO] [AcademyCraft]: http://ac.li-dev.cn/
[23:31:57] [Client thread/INFO] [FML]: Applying holder lookups
[23:31:57] [Client thread/INFO] [FML]: Holder lookups applied
[23:31:57] [Client thread/INFO] [FML]: Injecting itemstacks
[23:31:57] [Client thread/INFO] [FML]: Itemstack injection complete
[23:31:57] [Client thread/ERROR] [FML]: Fatal errors were detected during the transition from PREINITIALIZATION to INITIALIZATION. Loading cannot continue
[23:31:57] [Client thread/ERROR] [FML]: 
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1558-1.7.10-universal.jar) 
	UCH	Forge{10.13.4.1558} [Minecraft Forge] (forge-1.7.10-10.13.4.1558-1.7.10-universal.jar) 
	UCH	LambdaLib|Core{1.2.3} [LambdaLib|Core] (minecraft.jar) 
	UCH	LambdaLib{1.2.3} [LambdaLib] (LambdaLib-1.2.3.jar) 
	UCE	academy-craft{1.0.7} [Academy Craft] (AcademyCraft-1.0.7.jar) 
[23:31:57] [Client thread/ERROR] [FML]: The following problems were captured during this phase
[23:31:57] [Client thread/ERROR] [FML]: Caught exception from academy-craft
java.lang.OutOfMemoryError
	at sun.misc.Unsafe.allocateMemory(Native Method) ~[?:1.8.0_181]
	at java.nio.DirectByteBuffer.<init>(Unknown Source) ~[?:1.8.0_181]
	at java.nio.ByteBuffer.allocateDirect(Unknown Source) ~[?:1.8.0_181]
	at net.minecraft.client.renderer.GLAllocation.func_74524_c(SourceFile:34) ~[ban.class:?]
	at net.minecraft.client.renderer.Tessellator.<clinit>(Tessellator.java:26) ~[bmh.class:?]
	at cn.lambdalib.template.client.render.item.RenderModelItem.<init>(RenderModelItem.java:41) ~[RenderModelItem.class:?]
	at cn.academy.ability.client.render.RenderDeveloperPortable.<init>(RenderDeveloperPortable.java:20) ~[RenderDeveloperPortable.class:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_181]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_181]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_181]
	at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_181]
	at cn.lambdalib.annoreg.core.RegistryHelper.getFieldFromObject(RegistryHelper.java:109) ~[RegistryHelper.class:?]
	at cn.lambdalib.annoreg.mc.ItemRegistration$3.invoke(ItemRegistration.java:49) ~[ItemRegistration$3.class:?]
	at cn.lambdalib.annoreg.mc.ItemRegistration$3.invoke(ItemRegistration.java:44) ~[ItemRegistration$3.class:?]
	at cn.lambdalib.annoreg.core.RegistrationWithPostWork.doPostRegWork(RegistrationWithPostWork.java:47) ~[RegistrationWithPostWork.class:?]
	at cn.lambdalib.annoreg.base.RegistrationFieldSimple.registerField(RegistrationFieldSimple.java:59) ~[RegistrationFieldSimple.class:?]
	at cn.lambdalib.annoreg.core.RegistryType.registerAll(RegistryType.java:148) ~[RegistryType.class:?]
	at cn.lambdalib.annoreg.core.RegistrationManager.registerAll(RegistrationManager.java:149) ~[RegistrationManager.class:?]
	at cn.lambdalib.annoreg.core.RegistrationManager.registerAll(RegistrationManager.java:155) ~[RegistrationManager.class:?]
	at cn.lambdalib.annoreg.core.RegistryType.registerAll(RegistryType.java:83) ~[RegistryType.class:?]
	at cn.lambdalib.annoreg.core.RegistrationManager.registerAll(RegistrationManager.java:149) ~[RegistrationManager.class:?]
	at cn.lambdalib.annoreg.core.RegistrationManager.registerAll(RegistrationManager.java:155) ~[RegistrationManager.class:?]
	at cn.academy.core.AcademyCraft.preInit(AcademyCraft.java:93) ~[AcademyCraft.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_181]
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532) ~[forge-1.7.10-10.13.4.1558-1.7.10-universal.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_181]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) ~[forge-1.7.10-10.13.4.1558-1.7.10-universal.jar:?]
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) ~[forge-1.7.10-10.13.4.1558-1.7.10-universal.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_181]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119) [LoadController.class:?]
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556) [Loader.class:?]
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_181]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_181]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[23:31:57] [Client thread/INFO] [STDOUT]: [net.minecraft.client.Minecraft:func_71377_b:349]: ---- Minecraft Crash Report ----
// I'm sorry, Dave.

Time: 8/13/18 11:31 PM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.OutOfMemoryError
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:559)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.OutOfMemoryError
	at sun.misc.Unsafe.allocateMemory(Native Method)
	at java.nio.DirectByteBuffer.<init>(Unknown Source)
	at java.nio.ByteBuffer.allocateDirect(Unknown Source)
	at net.minecraft.client.renderer.GLAllocation.func_74524_c(SourceFile:34)
	at net.minecraft.client.renderer.Tessellator.<clinit>(Tessellator.java:26)
	at cn.lambdalib.template.client.render.item.RenderModelItem.<init>(RenderModelItem.java:41)
	at cn.academy.ability.client.render.RenderDeveloperPortable.<init>(RenderDeveloperPortable.java:20)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.lang.Class.newInstance(Unknown Source)
	at cn.lambdalib.annoreg.core.RegistryHelper.getFieldFromObject(RegistryHelper.java:109)
	at cn.lambdalib.annoreg.mc.ItemRegistration$3.invoke(ItemRegistration.java:49)
	at cn.lambdalib.annoreg.mc.ItemRegistration$3.invoke(ItemRegistration.java:44)
	at cn.lambdalib.annoreg.core.RegistrationWithPostWork.doPostRegWork(RegistrationWithPostWork.java:47)
	at cn.lambdalib.annoreg.base.RegistrationFieldSimple.registerField(RegistrationFieldSimple.java:59)
	at cn.lambdalib.annoreg.core.RegistryType.registerAll(RegistryType.java:148)
	at cn.lambdalib.annoreg.core.RegistrationManager.registerAll(RegistrationManager.java:149)
	at cn.lambdalib.annoreg.core.RegistrationManager.registerAll(RegistrationManager.java:155)
	at cn.lambdalib.annoreg.core.RegistryType.registerAll(RegistryType.java:83)
	at cn.lambdalib.annoreg.core.RegistrationManager.registerAll(RegistrationManager.java:149)
	at cn.lambdalib.annoreg.core.RegistrationManager.registerAll(RegistrationManager.java:155)
	at cn.academy.core.AcademyCraft.preInit(AcademyCraft.java:93)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
	... 18 more

**Comment by WeAthFoLD** [comment]
请问您使用的显卡是？
