### ISSUE TITLE
使用技能会报错

### ISSUE THREAD

**Issue by sheng-ri** [LambdaInnovation/AcademyCraft#620]
使用电磁牵引(应该是这个名字)有时会发生报错
[22:05:10] [Server thread/FATAL]: Error during network message.
java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor50.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at cn.lambdalib.s11n.network.NetworkMessage$1.invoke(NetworkMessage.java:290) ~[NetworkMessage$1.class:?]
	at cn.lambdalib.s11n.network.NetworkMessage.invokeListener(NetworkMessage.java:218) [NetworkMessage.class:?]
	at cn.lambdalib.s11n.network.NetworkMessage.processMessage(NetworkMessage.java:199) [NetworkMessage.class:?]
	at cn.lambdalib.s11n.network.NetworkMessage.sendToSelf(NetworkMessage.java:121) [NetworkMessage.class:?]
	at cn.academy.ability.api.context.ContextManager$ServerManager.hBeginLink(ContextManager.java:431) [ContextManager$ServerManager.class:?]
	at sun.reflect.GeneratedMethodAccessor20.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at cn.lambdalib.s11n.network.NetworkMessage$1.invoke(NetworkMessage.java:290) [NetworkMessage$1.class:?]
	at cn.lambdalib.s11n.network.NetworkMessage.invokeListener(NetworkMessage.java:218) [NetworkMessage.class:?]
	at cn.lambdalib.s11n.network.NetworkMessage.processMessage(NetworkMessage.java:199) [NetworkMessage.class:?]
	at cn.lambdalib.s11n.network.NetworkMessage.access$000(NetworkMessage.java:56) [NetworkMessage.class:?]
	at cn.lambdalib.s11n.network.NetworkMessage$Handler.onMessage(NetworkMessage.java:355) [NetworkMessage$Handler.class:?]
	at cn.lambdalib.s11n.network.NetworkMessage$Handler.onMessage(NetworkMessage.java:349) [NetworkMessage$Handler.class:?]
	at cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:47) [SimpleChannelHandlerWrapper.class:1.7.10-R0.1-SNAPSHOT]
	at cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:20) [SimpleChannelHandlerWrapper.class:1.7.10-R0.1-SNAPSHOT]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) [SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [MessageToMessageDecoder.class:?]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) [MessageToMessageCodec.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:1.7.10-R0.1-SNAPSHOT]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:176) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:989) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:458) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:806) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:665) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.NullPointerException
	at cn.academy.vanilla.electromaster.CatElectromaster.isEntityMetallic(CatElectromaster.java:183) ~[CatElectromaster.class:?]
	at cn.academy.vanilla.electromaster.skill.MagMovement$.toTarget(MagMovement.scala:46) ~[MagMovement$.class:?]
	at cn.academy.vanilla.electromaster.skill.MovementContext.g_onStart(MagMovement.scala:101) ~[MovementContext.class:?]
	... 36 more

**Comment by WeAthFoLD** [comment]
你好，由于我们目前没有1.7.10版本的更新计划，暂时先将这个issue关闭。如果在即将发布的1.1版本中仍然遇到同样问题，请开一个新的issue，感谢！
