### ISSUE TITLE
[Bug] Using Scattering Bomb has chance to crash the game

### ISSUE THREAD

**Issue by WeAthFoLD** [LambdaInnovation/AcademyCraft#636]
**Describe the bug**
[1.1 rev4 QA]使用电子弹散射概率性导致游戏崩溃

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Version [1.1 rev4 QA]

**Additional context**

**Comment by WeAthFoLD** [comment]
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CorePlugin (LambdaLib2-0.1.jar)
Contact their authors BEFORE contacting forge

// Ouch. That hurt :(

Time: 12/19/18 11:06 PM
Description: Unexpected error

java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
	at java.util.ArrayList$Itr.next(Unknown Source)
	at com.google.common.collect.Iterators$3.next(Iterators.java:174)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:616)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1347)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1062)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1118)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
	at java.util.ArrayList$Itr.next(Unknown Source)
	at com.google.common.collect.Iterators$3.next(Iterators.java:174)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:616)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1347)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259)
```

**Comment by nirvanaxiao6** [comment]
Used the skill many times and no crash occurred. Maybe it was fixed.
