### ISSUE TITLE
[Bug] Teleporter crache

### ISSUE THREAD

**Issue by ThalesLemosz** [LambdaInnovation/AcademyCraft#653]
Well, the bug was this, when you get the Portable Developer and get the ability to teleporter inductor and try to use it with portable developer the game closes !!

this is the log;
```
---- Minecraft Crash Report ---- WARNING: coremods are present: CorePlugin (LambdaLib2-0.1.1.jar) Contact their authors BEFORE contacting forge // Why is it breaking :( Time: 12/24/18 12:25 AM Description: Ticking player java.lang.NullPointerException: The validated object is null at org.apache.commons.lang3.Validate.notNull(Validate.java:225) 
at org.apache.commons.lang3.Validate.notNull(Validate.java:206) 
at net.minecraft.util.NonNullList.set(SourceFile:49)
 at net.minecraft.entity.player.InventoryPlayer.func_70299_a(InventoryPlayer.java:575) 
at cn.academy.ability.develop.action.DevelopActionLevel.chooseCategory(DevelopActionLevel.java:46) 
at cn.academy.ability.develop.action.DevelopActionLevel.onLearned(DevelopActionLevel.java:35) 
at cn.academy.ability.develop.DevelopData.tick(DevelopData.java:156) at cn.lambdalib2.datapart.DataPart.callTick(DataPart.java:224) 
at cn.lambdalib2.datapart.EntityData.tick(EntityData.java:225) 
at cn.lambdalib2.datapart.EntityData.access$000(EntityData.java:32) 
at cn.lambdalib2.datapart.EntityData$EventListener.onLivingUpdate(EntityData.java:241) 
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_31_EventListener_onLivingUpdate_LivingUpdateEvent.invoke(.dynamic) 
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) 
at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) 
at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:566) 
at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2095) 
at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234) 
at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382) 
at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173) 
at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) 
at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) 
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790) 
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) 
at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) 
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) 
at java.lang.Thread.run(Unknown Source) 

A detailed walkthrough of the error, its code path and all known details is as follows: --------------------------------------------------------------------------------------- 
-- Head -- 
Thread: Server thread Stacktrace: 
at org.apache.commons.lang3.Validate.notNull(Validate.java:225) 
at org.apache.commons.lang3.Validate.notNull(Validate.java:206) 
at net.minecraft.util.NonNullList.set(SourceFile:49) 
at net.minecraft.entity.player.InventoryPlayer.func_70299_a(InventoryPlayer.java:575) 
at cn.academy.ability.develop.action.DevelopActionLevel.chooseCategory(DevelopActionLevel.java:46) 
at cn.academy.ability.develop.action.DevelopActionLevel.onLearned(DevelopActionLevel.java:35) 
at cn.academy.ability.develop.DevelopData.tick(DevelopData.java:156) 
at cn.lambdalib2.datapart.DataPart.callTick(DataPart.java:224) 
at cn.lambdalib2.datapart.EntityData.tick(EntityData.java:225) 
at cn.lambdalib2.datapart.EntityData.access$000(EntityData.java:32) 
at cn.lambdalib2.datapart.EntityData$EventListener.onLivingUpdate(EntityData.java:241) 
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_31_EventListener_onLivingUpdate_LivingUpdateEvent.invoke(.dynamic) 
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) 
at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) 
at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:566) 
at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2095) 
at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234) 
-- Player being ticked -- 
Details: Entity Type: null (net.minecraft.entity.player.EntityPlayerMP) Entity ID: 340 Entity Name: ThalesLemosz_ Entity's Exact location: -290.70, 72.00, -298.15 
Entity's Block location: World: (-291,72,-299), Chunk: (at 13,4,5 in -19,-19; contains blocks -304,0,-304 to -289,255,-289), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1) Entity's Momentum: 0.00, -0.08, 0.00 
Entity's Passengers: [] 
Entity's Vehicle: ~~ERROR~~ NullPointerException: null 
Stacktrace: 
at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382) 
at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173) 
at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) 
at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) 

-- Ticking connection -- 
Details: Connection: net.minecraft.network.NetworkManager@23cb361b 
Stacktrace: 
at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) 
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790) 
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) 
at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) 
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) 
at java.lang.Thread.run(Unknown Source) 

-- System Details -- 
Details: Minecraft Version: 1.12.2 Operating System: Windows 10 (amd64) version 10.0 Java Version: 1.8.0_191, Oracle Corporation Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), 
Oracle Corporation Memory: 337839688 bytes (322 MB) / 624971776 bytes (596 MB) up to 1060372480 bytes (1011 MB) JVM Flags: 6 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump 
IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94 FML: MCP 9.42 Powered by Forge 14.23.5.2796 7 mods loaded, 7 mods active States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored | State | ID | Version | Source 
| Signature | |:------ |:-------------- |:------------ |:----------------------------- |:---------------------------------------- | 
| LCHIJA | minecraft | 1.12.2 | minecraft.jar | None | | LCHIJA | mcp | 9.42 | minecraft.jar | None | | LCHIJA | FML | 8.0.99.99 | forge-1.12.2-14.23.5.2796.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 | | LCHIJA | forge | 14.23.5.2796 | forge-1.12.2-14.23.5.2796.jar | 
e3c3d50c7c986df74c645c0ac54639741c90a557 | 
| LCHIJA | LambdaLib|Core | 0.1 | minecraft.jar | None |
 | LCHIJA | lambdalib2 | 0.1 | LambdaLib2-0.1.1.jar | None |
 | LCHIJA | academy | 1.1.0 | AcademyCraft-1.1.0_beta1.jar | None | 

Loaded coremods (and transformers): CorePlugin (LambdaLib2-0.1.1.jar) 
cn.lambdalib2.render.mc.PipelineTransformer cn.lambdalib2.registry.impl.RegistryTransformer GL info: 

~~ERROR~~ RuntimeException: No OpenGL context found in the current thread. Profiler Position: N/A (disabled) Player Count: 1 / 8; [EntityPlayerMP['ThalesLemosz_'/340, l='New World', x=-290.70, y=72.00, z=-298.15]] Type: Integrated Server (map_client.txt) Is Modded: Definitely; Client brand changed to 'fml,forge'
```

**Comment by WeAthFoLD** [comment]
@Paindar 看起来是往inventory里set了一个null的ItemStack，交给你了（

**Comment by Gordoh1** [comment]
I'm not sure it's needed, but as I was actually going to mention this aswell, this crash happens with all of the transformation inductions, not just teleporters and also applies all developers.

**Comment by Paindar** [comment]
Fixed.

**Comment by nirvanaxiao6** [comment]
fixed
