### ISSUE TITLE
[Bug] Can't access UI for Solar Generator/Wind Generator

### ISSUE THREAD

**Issue by Darkveld** [LambdaInnovation/AcademyCraft#679]
When attempting to access the UI for a solar generator, it just corrupts the Client-Side display of their inventory, requiring a rejoin to fix.

**Comment by Darkveld** [comment]
This seems to exclusively a multiplayer issue, when connecting to a dedicated server you cannot access the gui of a solar or wind generator and attempting to do so corrupts your inventory causing items to duplicate and overwrite other items.

There are no mentions of anything happening at all in either client or server logs

**Comment by Darkveld** [comment]
Also occurs with the Metal Former, doesn't affect the energy bridge or wireless node.

**Comment by Darkveld** [comment]
Finally got an error of some kind:

Time: 2019-01-04 09:39:30 MST
Description: Error executing task

java.util.concurrent.ExecutionException: java.lang.NullPointerException
    at java.util.concurrent.FutureTask.report(Unknown Source)
    at java.util.concurrent.FutureTask.get(Unknown Source)
    at net.minecraft.util.Util.runTask(SourceFile:531)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1088)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NullPointerException
    at net.minecraft.client.network.NetHandlerPlayClient.handleChunkData(NetHandlerPlayClient.java:740)
    at net.minecraft.network.play.server.SPacketChunkData.processPacket(SourceFile:96)
    at net.minecraft.network.play.server.SPacketChunkData.processPacket(SourceFile:18)
    at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at net.minecraft.util.Util.runTask(SourceFile:529)
    ... 9 more

**Comment by Darkveld** [comment]
Confirmed on a dedicated server using no mods other then JEI, Mantle, and Journeymap installed.

Replication involves starting a dedicated server, joining with a client and attempting to access any machine from AcademyCraft.

**Comment by WeAthFoLD** [comment]
Fixed in next beta release.

**Comment by Darkveld** [comment]
Issue not resolved in beta3 release, can't open UI of wireless Imag node without corrupting inventory as before.
