### ISSUE TITLE
[Bug] Using Meltdowner abilities causes crash in dedicated server

### ISSUE THREAD

**Issue by Darkveld** [LambdaInnovation/AcademyCraft#680]
Crashlog is listed below:
```
Time: 2019-01-04 14:13:35 MST
Description: Ticking entity

java.lang.ClassCastException: java.lang.Float cannot be cast to java.lang.Integer
    at cn.academy.entity.EntityMdBall.onUpdate(EntityMdBall.java:128)
    at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1993)
    at net.minecraft.world.World.updateEntity(World.java:1955)
    at net.minecraft.world.World.redirect$updateEntity$zbc000(World.java:4117)
    at net.minecraft.world.World.updateEntities(World.java:1759)
    at net.minecraft.client.Minecraft.runTick(Minecraft.java:1847)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1098)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Entity being ticked --
  Entity Type: academy:entitymdball (cn.academy.entity.EntityMdBall)
  Entity ID: 376163
  Entity Name: entity.EntityMdBall.name
  Entity's Exact location: 174.90, 70.19, 122.14
  Entity's Block location: World: (174,70,122), Chunk: (at 14,4,10 in 10,7; contains blocks 160,0,112 to 175,255,127), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
  Entity's Momentum: 0.00, 0.00, 0.00
  Entity's Passengers: []
  Entity's Vehicle: ~~ERROR~~ NullPointerException: null
  Entity NBT: {Motion:[0.0d,0.0d,0.0d],UUIDLeast:-6331630234083926500L,Invulnerable:0b,Air:300s,OnGround:0b,Dimension:0,PortalCooldown:0,Rotation:[0.0f,0.0f],UpdateBlocked:0b,FallDistance:0.0f,UUIDMost:-6455473782035954620L,Pos:[174.90117720483838d,70.18566617965698d,122.1430541371421d],Fire:-1s,ForgeCaps:{"llibrary:extendedentitydatacapability":{}}}

-- Affected level --
  Level name: MpServer
  All players: 2 total; [EntityPlayerSP['Darkveld'/634, l='MpServer', x=174.29, y=69.00, z=121.36], EntityOtherPlayerMP['levineron'/5667, l='MpServer', x=171.73, y=69.00, z=121.51]]
  Chunk stats: MultiplayerChunkCache: 441, 441
  Level seed: 0
  Level generator: ID 00 - default, ver 1. Features enabled: false
  Level generator options: 
  Level spawn location: World: (96,64,208), Chunk: (at 0,4,0 in 6,13; contains blocks 96,0,208 to 111,255,223), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
  Level time: 1239312 game time, 1403753 day time
  Level dimension: 0
  Level storage version: 0x00000 - Unknown?
  Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
  Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
  Forced entities: 145 total; [EntityOtherPlayerMP['levineron'/5667, l='MpServer', x=54.94, y=71.00, z=256.60], EntityOtherPlayerMP['levineron'/5667, l='MpServer', x=49.14, y=69.96, z=345.05], EntityOtherPlayerMP['levineron'/5667, l='MpServer', x=49.55, y=69.94, z=346.24], EntityEnderman['Enderman'/370188, l='MpServer', x=121.07, y=22.00, z=186.30], EntityEnderman['Enderman'/370187, l='MpServer', x=127.12, y=22.00, z=182.62], EntityItem['item.item.egg'/373514, l='MpServer', x=166.62, y=66.00, z=67.79], EntityItem['item.item.egg'/368149, l='MpServer', x=201.62, y=68.00, z=58.46], EntitySkeleton['Skeleton'/360471, l='MpServer', x=180.48, y=59.00, z=144.27], EntityItem['item.item.egg'/371985, l='MpServer', x=237.21, y=72.00, z=73.89], EntityPig['Pig'/92439, l='MpServer', x=134.50, y=68.00, z=74.45], EntityPig['Pig'/92438, l='MpServer', x=133.45, y=70.00, z=73.45], EntityPig['Pig'/92440, l='MpServer', x=133.98, y=70.00, z=74.42], EntityPig['Pig'/354076, l='MpServer', x=224.74, y=69.00, z=193.46], EntitySpider['Spider'/367653, l='MpServer', x=252.50, y=15.00, z=81.50], EntityOtherPlayerMP['levineron'/5667, l='MpServer', x=171.73, y=69.00, z=121.51], EntitySkeleton['Skeleton'/370214, l='MpServer', x=126.50, y=30.00, z=178.50], EntityPig['Pig'/92709, l='MpServer', x=154.76, y=65.00, z=73.50], EntityPig['Pig'/92708, l='MpServer', x=157.33, y=67.00, z=55.48], EntityOtherPlayerMP['levineron'/5667, l='MpServer', x=48.04, y=70.33, z=342.35], EntityOtherPlayerMP['Mophise'/17385, l='MpServer', x=177.61, y=71.00, z=199.65], EntityBat['Bat'/375095, l='MpServer', x=251.44, y=22.32, z=144.27], Menelaos Pantagiota/loneshepherd_byzantine/7672453668505097430/-44/71/96, EntitySkeleton['Skeleton'/371763, l='MpServer', x=192.50, y=43.00, z=174.50], EntityOtherPlayerMP['levineron'/5667, l='MpServer', x=53.64, y=68.00, z=329.26], EntityZombie['Zombie'/371005, l='MpServer', x=245.20, y=45.00, z=51.50], EntitySkeleton['Skeleton'/374333, l='MpServer', x=239.50, y=44.00, z=156.96], EntitySkeleton['Skeleton'/374332, l='MpServer', x=239.50, y=44.00, z=156.30], EntityZombie['Zombie'/374335, l='MpServer', x=239.50, y=44.00, z=157.64], EntityZombie['Zombie'/374334, l='MpServer', x=238.50, y=44.00, z=156.50], EntityChicken['Chicken'/94012, l='MpServer', x=211.17, y=71.00, z=71.28], EntityChicken['Chicken'/94014, l='MpServer', x=200.86, y=69.00, z=58.37], EntityItem['item.item.egg'/374074, l='MpServer', x=181.17, y=70.00, z=90.10], EntityItem['item.tile.log.big_oak'/364100, l='MpServer', x=167.62, y=73.00, z=113.09], EntityPig['Pig'/94018, l='MpServer', x=200.31, y=71.00, z=72.58], EntityItem['item.tile.log.big_oak'/364097, l='MpServer', x=169.36, y=72.00, z=112.96], EntityItem['item.tile.log.big_oak'/355904, l='MpServer', x=228.49, y=72.00, z=77.22], EntityItem['item.tile.log.big_oak'/364099, l='MpServer', x=164.28, y=72.00, z=113.13], EntityOtherPlayerMP['levineron'/5667, l='MpServer', x=50.55, y=70.49, z=345.61], EntityPig['Pig'/347725, l='MpServer', x=227.44, y=71.00, z=56.26], EntityItem['item.tile.log.big_oak'/364117, l='MpServer', x=166.11, y=73.00, z=113.11], EntityChicken['Chicken'/347989, l='MpServer', x=236.65, y=72.00, z=73.20], EntityBat['Bat'/375893, l='MpServer', x=248.36, y=22.54, z=138.08], EntityItem['item.item.egg'/356692, l='MpServer', x=198.40, y=71.00, z=73.13], EntityPig['Pig'/347988, l='MpServer', x=235.53, y=66.00, z=129.71], EntityItem['item.tile.log.big_oak'/364119, l='MpServer', x=164.13, y=72.00, z=114.85], EntityWitch['Witch'/374871, l='MpServer', x=106.50, y=21.00, z=198.50], EntitySkeleton['Skeleton'/367953, l='MpServer', x=246.50, y=26.00, z=121.50], EntityItem['item.item.egg'/368209, l='MpServer', x=161.67, y=67.00, z=58.03], EntityPig['Pig'/347987, l='MpServer', x=226.50, y=68.00, z=131.75], EntityWitch['Witch'/374872, l='MpServer', x=109.50, y=21.00, z=200.50], EntityItem['item.item.egg'/360283, l='MpServer', x=171.09, y=72.00, z=73.35], EntityOtherPlayerMP['levineron'/5667, l='MpServer', x=49.70, y=69.50, z=349.22], EntityZombie['Zombie'/374874, l='MpServer', x=102.50, y=21.00, z=196.50], EntityMdBall['entity.EntityMdBall.name'/376163, l='MpServer', x=174.90, y=70.19, z=122.14], EntityCreeper['Creeper'/369516, l='MpServer', x=194.46, y=44.00, z=173.18], EntityItem['item.tile.sapling.big_oak'/364140, l='MpServer', x=166.91, y=73.00, z=113.51], EntityItem['item.item.minecraft:apple'/364143, l='MpServer', x=168.05, y=73.00, z=111.13], EntityItem['item.tile.sapling.big_oak'/364142, l='MpServer', x=171.92, y=70.00, z=111.08], EntityItem['item.tile.sapling.big_oak'/364145, l='MpServer', x=167.30, y=73.00, z=111.10], EntityPig['Pig'/93051, l='MpServer', x=106.21, y=78.00, z=44.48], EntityOtherPlayerMP['levineron'/5667, l='MpServer', x=214.46, y=72.33, z=85.32], EntityPig['Pig'/93052, l='MpServer', x=96.51, y=72.00, z=45.65], EntityChicken['Chicken'/93057, l='MpServer', x=106.37, y=77.00, z=44.99], EntityPig['Pig'/129, l='MpServer', x=200.09, y=73.00, z=95.65], EntityChicken['Chicken'/93056, l='MpServer', x=95.92, y=72.00, z=44.87], EntityItem['item.tile.sapling.big_oak'/370052, l='MpServer', x=179.53, y=69.00, z=121.85], EntitySpider['Spider'/373636, l='MpServer', x=124.50, y=25.00, z=194.50], EntityPig['Pig'/130, l='MpServer', x=124.34, y=70.00, z=139.51], EntityPig['Pig'/93827, l='MpServer', x=204.92, y=71.00, z=72.62], EntityPig['Pig'/93826, l='MpServer', x=194.51, y=70.00, z=53.69], EntityChicken['Chicken'/93829, l='MpServer', x=192.88, y=71.00, z=83.48], EntityPig['Pig'/93828, l='MpServer', x=184.43, y=69.00, z=57.05], EntityPig['Pig'/392, l='MpServer', x=219.47, y=72.00, z=104.34], EntityPig['Pig'/393, l='MpServer', x=229.52, y=70.00, z=106.30], EntitySkeleton['Skeleton'/371596, l='MpServer', x=250.50, y=21.00, z=138.50], EntityPig['Pig'/394, l='MpServer', x=213.33, y=72.00, z=86.45], EntityItem['item.tile.sapling.big_oak'/370056, l='MpServer', x=180.30, y=69.00, z=123.15], EntityBat['Bat'/368011, l='MpServer', x=150.03, y=25.55, z=183.28], EntityZombie['Zombie'/371861, l='MpServer', x=149.21, y=40.00, z=192.43], EntityWitch['Witch'/375441, l='MpServer', x=220.50, y=23.00, z=47.50], EntityCreeper['Creeper'/371859, l='MpServer', x=145.94, y=39.00, z=187.70], EntityPig['Pig'/150, l='MpServer', x=146.59, y=74.00, z=111.45], EntitySkeleton['Skeleton'/373139, l='MpServer', x=95.50, y=22.00, z=82.50], EntityCreeper['Creeper'/375443, l='MpServer', x=221.50, y=23.00, z=48.50], EntityCreeper['Creeper'/375442, l='MpServer', x=221.50, y=23.00, z=47.50], EntityItem['item.tile.sapling.big_oak'/355996, l='MpServer', x=225.99, y=77.00, z=79.25], EntityCreeper['Creeper'/375198, l='MpServer', x=237.50, y=14.00, z=108.50], EntityItem['item.tile.sapling.big_oak'/355993, l='MpServer', x=227.87, y=76.00, z=79.42], EntityOtherPlayerMP['Mophise'/17385, l='MpServer', x=73.09, y=70.00, z=190.42], EntityChicken['Chicken'/413, l='MpServer', x=196.78, y=71.00, z=82.11], EntityChicken['Chicken'/414, l='MpServer', x=199.45, y=72.00, z=92.80], EntityChicken['Chicken'/415, l='MpServer', x=180.53, y=70.00, z=90.88], EntityPig['Pig'/416, l='MpServer', x=201.47, y=71.00, z=82.70], EntityPig['Pig'/161, l='MpServer', x=103.24, y=69.00, z=116.62], EntityPig['Pig'/417, l='MpServer', x=225.23, y=72.00, z=94.32], EntityPig['Pig'/419, l='MpServer', x=151.78, y=72.00, z=145.50], EntityPig['Pig'/168, l='MpServer', x=117.50, y=69.00, z=125.30], EntityPig['Pig'/429, l='MpServer', x=188.50, y=70.00, z=87.72], EntityItem['item.tile.log.big_oak'/368552, l='MpServer', x=186.60, y=68.00, z=122.14], EntityChicken['Chicken'/430, l='MpServer', x=173.10, y=69.00, z=105.49], EntityCreeper['Creeper'/371370, l='MpServer', x=219.50, y=39.00, z=72.50], EntityOtherPlayerMP['levineron'/5667, l='MpServer', x=66.77, y=73.68, z=398.62], EntityBat['Bat'/374197, l='MpServer', x=234.67, y=45.15, z=99.64], EntityBat['Bat'/374199, l='MpServer', x=126.27, y=27.80, z=197.67], EntityBat['Bat'/374198, l='MpServer', x=249.19, y=43.02, z=99.51], EntityBat['Bat'/372662, l='MpServer', x=223.25, y=37.04, z=46.75], EntityBat['Bat'/374195, l='MpServer', x=226.40, y=44.08, z=100.89], EntityBat['Bat'/374194, l='MpServer', x=240.76, y=44.52, z=97.47], EntityPlayerSP['Darkveld'/634, l='MpServer', x=174.29, y=69.00, z=121.36], EntityOtherPlayerMP['levineron'/5667, l='MpServer', x=70.11, y=71.00, z=204.66], EntityBat['Bat'/364222, l='MpServer', x=192.94, y=32.00, z=126.25], EntityOtherPlayerMP['levineron'/5667, l='MpServer', x=171.73, y=69.00, z=121.51], EntityZombie['Zombie'/374712, l='MpServer', x=194.50, y=14.00, z=96.50], EntityItem['item.tile.sapling.big_oak'/368570, l='MpServer', x=183.51, y=70.00, z=116.89], EntityPig['Pig'/194, l='MpServer', x=106.37, y=69.00, z=97.74], EntityChicken['Chicken'/93379, l='MpServer', x=162.50, y=67.00, z=54.82], EntityPig['Pig'/92357, l='MpServer', x=125.51, y=72.00, z=63.78], EntityPig['Pig'/93381, l='MpServer', x=169.41, y=68.00, z=69.00], EntityChicken['Chicken'/93380, l='MpServer', x=162.52, y=67.00, z=58.56], EntitySkeleton['Skeleton'/374976, l='MpServer', x=224.51, y=21.00, z=56.29], EntityPig['Pig'/92359, l='MpServer', x=102.33, y=71.00, z=55.52], EntityChicken['Chicken'/93383, l='MpServer', x=167.13, y=66.00, z=68.03], EntityPig['Pig'/93382, l='MpServer', x=160.25, y=69.00, z=74.50], EntitySkeleton['Skeleton'/370380, l='MpServer', x=149.50, y=40.00, z=191.50], EntityPig['Pig'/92360, l='MpServer', x=95.32, y=73.00, z=53.50], EntityOtherPlayerMP['levineron'/5667, l='MpServer', x=49.59, y=68.00, z=342.66], EntityPig['Pig'/33482, l='MpServer', x=222.51, y=67.00, z=135.70], EntityPig['Pig'/33483, l='MpServer', x=222.94, y=67.00, z=139.96], EntityChicken['Chicken'/93386, l='MpServer', x=172.80, y=72.00, z=74.92], EntityOtherPlayerMP['levineron'/5667, l='MpServer', x=49.66, y=68.21, z=344.59], EntityBat['Bat'/371921, l='MpServer', x=125.50, y=25.18, z=194.57], EntitySkeleton['Skeleton'/373202, l='MpServer', x=220.50, y=19.00, z=60.50], EntityItem['item.tile.sapling.oak'/359135, l='MpServer', x=181.49, y=70.00, z=104.65], EntitySkeleton['Skeleton'/365022, l='MpServer', x=176.26, y=60.00, z=145.49], EntityOtherPlayerMP['levineron'/5667, l='MpServer', x=49.64, y=69.22, z=342.51], EntityZombie['Zombie'/374746, l='MpServer', x=253.50, y=13.00, z=126.50], EntityBat['Bat'/373477, l='MpServer', x=248.68, y=39.75, z=164.22], EntityItem['item.tile.sapling.big_oak'/365286, l='MpServer', x=190.88, y=71.00, z=110.86], EntityBat['Bat'/373478, l='MpServer', x=243.54, y=42.10, z=164.27], EntityZombie['Zombie'/373226, l='MpServer', x=253.50, y=13.00, z=110.50], EntityOtherPlayerMP['levineron'/5667, l='MpServer', x=51.30, y=68.00, z=339.31], EntityItem['item.tile.log.big_oak'/371953, l='MpServer', x=180.86, y=69.00, z=124.50], EntityPig['Pig'/93689, l='MpServer', x=181.80, y=70.00, z=64.21], EntityOtherPlayerMP['levineron'/5667, l='MpServer', x=48.31, y=72.14, z=354.41], EntityZombie['Zombie'/358136, l='MpServer', x=188.62, y=56.00, z=128.23]]
  Retry entities: 1 total; [Menelaos Pantagiota/loneshepherd_byzantine/7672453668505097430/-44/71/96]
  Server brand: fml,forge
  Server type: Non-integrated multiplayer server
```

**Comment by nirvanaxiao6** [comment]
Fixed: 1.1.0_beta2-0ae447
