### ISSUE TITLE
[Bug] 多人游戏服务器后台报错

### ISSUE THREAD

**Issue by sheng-ri** [LambdaInnovation/AcademyCraft#688]
/aim cat - /aim catlist 出现报错
[18:01:38] [Server thread/WARN] [net.minecraft.command.CommandHandler]: Couldn't process command: aim catlist
java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n
	at cn.academy.ability.Category.getDisplayName(Category.java:168) ~[Category.class:?]
	at cn.academy.command.CommandAIMBase.matchCommands(CommandAIMBase.java:183) ~[CommandAIMBase.class:?]
	at cn.academy.command.CommandAIMBase$CommandAIM.func_184881_a(CommandAIMBase.java:85) ~[CommandAIMBase$CommandAIM.class:?]
	at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:127) [bj.class:?]
	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:99) [bj.class:?]
	at catserver.server.command.CraftSimpleCommandMap.dispatch(CraftSimpleCommandMap.java:51) [CraftSimpleCommandMap.class:pro(free)-181231]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchVanillaCommand(CraftServer.java:713) [CraftServer.class:pro(free)-181231]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:708) [CraftServer.class:pro(free)-181231]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1591) [pa.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1436) [pa.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(CPacketChatMessage.java:38) [la.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(CPacketChatMessage.java:8) [la.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:15) [hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_192]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_192]
	at net.minecraft.util.Util.func_181617_a(Util.java:50) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:841) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:472) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:778) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:632) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_192]

使用穿透传送报错
[18:49:49] [Server thread/ERROR]: Error during network message.
java.lang.reflect.InvocationTargetException: null
        at sun.reflect.GeneratedMethodAccessor77.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_192]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_192]
        at cn.lambdalib2.s11n.network.NetworkMessage$2.invoke(NetworkMessage.java:230) ~[NetworkMessage$2.class:?]
        at cn.lambdalib2.s11n.network.NetworkMessage.invokeListener(NetworkMessage.java:157) ~[NetworkMessage.class:?]
        at cn.lambdalib2.s11n.network.NetworkMessage.processMessage(NetworkMessage.java:138) ~[NetworkMessage.class:?]
        at cn.lambdalib2.s11n.network.NetworkMessage.access$000(NetworkMessage.java:54) ~[NetworkMessage.class:?]
        at cn.lambdalib2.s11n.network.NetworkMessage$Handler.lambda$onMessage$0(NetworkMessage.java:381) ~[NetworkMessage$Handler.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_192]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_192]
        at net.minecraft.util.Util.func_181617_a(Util.java:50) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:841) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:472) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:778) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:632) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_192]
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.google.common.base.Throwables.propagate(Throwables.java:240) ~[guava-21.0.jar:?]
        at cn.academy.ability.context.ContextManager$ServerManager.hBeginLink(ContextManager.java:436) ~[ContextManager$ServerManager.class:?]
        ... 16 more
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.GeneratedConstructorAccessor194.newInstance(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_192]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_192]
        at cn.academy.ability.context.ContextManager$ServerManager.hBeginLink(ContextManager.java:412) ~[ContextManager$ServerManager.class:?]
        ... 16 more
Caused by: java.lang.NoSuchFieldError: mark
        at cn.academy.ability.vanilla.teleporter.skill.PenetrateTeleport$PTContext.<init>(PenetrateTeleport.java:58) ~[PenetrateTeleport$PTContext.class:?]
        at sun.reflect.GeneratedConstructorAccessor194.newInstance(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_192]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_192]
        at cn.academy.ability.context.ContextManager$ServerManager.hBeginLink(ContextManager.java:412) ~[ContextManager$ServerManager.class:?]
        ... 16 more

使用危险传送
[18:49:44] [Server thread/INFO]: [Server] 1
[18:49:49] [Server thread/ERROR]: Error during network message.
java.lang.reflect.InvocationTargetException: null
        at sun.reflect.GeneratedMethodAccessor77.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_192]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_192]
        at cn.lambdalib2.s11n.network.NetworkMessage$2.invoke(NetworkMessage.java:230) ~[NetworkMessage$2.class:?]
        at cn.lambdalib2.s11n.network.NetworkMessage.invokeListener(NetworkMessage.java:157) ~[NetworkMessage.class:?]
        at cn.lambdalib2.s11n.network.NetworkMessage.processMessage(NetworkMessage.java:138) ~[NetworkMessage.class:?]
        at cn.lambdalib2.s11n.network.NetworkMessage.access$000(NetworkMessage.java:54) ~[NetworkMessage.class:?]
        at cn.lambdalib2.s11n.network.NetworkMessage$Handler.lambda$onMessage$0(NetworkMessage.java:381) ~[NetworkMessage$Handler.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_192]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_192]
        at net.minecraft.util.Util.func_181617_a(Util.java:50) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:841) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:472) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:778) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:632) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_192]
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.google.common.base.Throwables.propagate(Throwables.java:240) ~[guava-21.0.jar:?]
        at cn.academy.ability.context.ContextManager$ServerManager.hBeginLink(ContextManager.java:436) ~[ContextManager$ServerManager.class:?]
        ... 16 more
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.GeneratedConstructorAccessor194.newInstance(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_192]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_192]
        at cn.academy.ability.context.ContextManager$ServerManager.hBeginLink(ContextManager.java:412) ~[ContextManager$ServerManager.class:?]
        ... 16 more
Caused by: java.lang.NoSuchFieldError: mark
        at cn.academy.ability.vanilla.teleporter.skill.PenetrateTeleport$PTContext.<init>(PenetrateTeleport.java:58) ~[PenetrateTeleport$PTContext.class:?]
        at sun.reflect.GeneratedConstructorAccessor194.newInstance(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_192]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_192]
        at cn.academy.ability.context.ContextManager$ServerManager.hBeginLink(ContextManager.java:412) ~[ContextManager$ServerManager.class:?]
        ... 16 more

使用转移传送（似乎拿不可以放置的物品的时候回出现）
[18:52:46] [Netty Server IO #0/INFO]: Ignored network message null, execute, reason: Can't find server context

更多信息
 - OS: Windows Server 2016
 - CatServer version pro(free)-181231 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT, Forge version 14.23.5.2796)
 - 1.1.0beta2

**Comment by WeAthFoLD** [comment]
@nirvanaxiao6 求帮忙分解一下issue
@sheng-ri 感谢反馈！不过下次多个bug麻烦开多个issue分别说明，这样我们容易处理。Thx =3=

**Comment by nirvanaxiao6** [comment]
@sheng-ri 请确认一下穿透传送和转移传送那段，究竟是哪一个技能导致了报错。
两段log完全一致（包括时间），故只可能为一个技能的锅
