### ISSUE TITLE
[Bug] 单人游戏基础能力学习机第一次获得能力后游戏崩溃

### ISSUE THREAD

**Issue by tt36999** [LambdaInnovation/AcademyCraft#706]
**Describe the bug**
使用能源桥链接IC线缆并用改良能量节点链接，在使用基础能力学习机输入learn，待进度条走完后游戏崩溃

**Desktop (please complete the following information):**
 - 系统：Win10
 - MC：Minecraft 1.7.10 Forge 1.7.10-Forge10.13.4.1614-1.7.10
 - Version AcademyCraft-1.0.7 with LambdaLib-1.2.3

部分崩溃日志
-- Head --
Stacktrace:
	at java.util.HashMap$HashIterator.nextNode(Unknown Source)
	at java.util.HashMap$ValueIterator.next(Unknown Source)
	at cn.lambdalib.util.datapart.EntityData.tick(EntityData.java:209)
	at cn.lambdalib.util.datapart.EntityData.access$000(EntityData.java:34)
	at cn.lambdalib.util.datapart.EntityData$EventListener.onLivingUpdate(EntityData.java:223)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_316_EventListener_onLivingUpdate_LivingUpdateEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:287)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1560)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:288)
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:295)

-- Player being ticked --
Details:
	Entity Type: null (net.minecraft.entity.player.EntityPlayerMP)
	Entity ID: 2707
	Entity Name: _Shigure
	Entity's Exact location: -331.24, 69.00, 200.96
	Entity's Block location: World: (-332,69,200), Chunk: (at 4,4,8 in -21,12; contains blocks -336,0,192 to -321,255,207), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
Stacktrace:
	at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:303)
	at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:137)
	at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:8)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@549abb13
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by WeAthFoLD** [comment]
由于beta版本较早，该bug可能已经被修复。可以在1.1.0版本尝试一下吗？如果没有后续反馈将在1.1.1关闭该bug。
