### ISSUE TITLE
[Bug] Random strange crash when changing dimensions

### ISSUE THREAD

**Issue by Darkveld** [LambdaInnovation/AcademyCraft#721]
Error log below is from changing dimensions while being a level 5 meltdowner, seems to be completely random, and the log indicates it was during standard world ticking which is odd in itself.

Time: 2019-01-23 15:07:54 MST
Description: Unexpected error

java.lang.NullPointerException
    at cn.lambdalib2.datapart.EntityData.getPart(EntityData.java:158)
    at cn.academy.ability.context.ClientRuntime.instance(ClientRuntime.java:53)
    at cn.academy.ability.context.ClientRuntime$Events.onClientTick(ClientRuntime.java:274)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_536_Events_onClientTick_ClientTickEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:344)
    at net.minecraft.client.Minecraft.runTick(Minecraft.java:1708)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1098)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Affected level --
  Level name: MpServer
  All players: 1 total; [EntityPlayerSP['Darkveld'/2206729, l='MpServer', x=7.50, y=42.00, z=7.50]]
  Chunk stats: MultiplayerChunkCache: 4, 4
  Level seed: 0
  Level generator: ID 00 - default, ver 1. Features enabled: false
  Level generator options: 
  Level spawn location: World: (96,64,208), Chunk: (at 0,4,0 in 6,13; contains blocks 96,0,208 to 111,255,223), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
  Level time: 31277067 game time, 34467578 day time
  Level dimension: 0
  Level storage version: 0x00000 - Unknown?
  Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
  Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
  Forced entities: 1 total; [EntityPlayerSP['Darkveld'/2206729, l='MpServer', x=7.50, y=42.00, z=7.50]]
  Retry entities: 0 total; []
  Server brand: fml,forge
  Server type: Non-integrated multiplayer server

**Comment by WeAthFoLD** [comment]
Not quite sure what happened here. I deployed a fix in LambdaLib2 that ensures data gets initialized, it shall fix the bug.
