### ISSUE TITLE
[Bug] 服务器进入玩家报错

### ISSUE THREAD

**Issue by sheng-ri** [LambdaInnovation/AcademyCraft#726]
[10:05:08] [Server thread/INFO]: 玩家 **** join the game.
[10:05:10] [Server thread/ERROR]: Error during network message.
java.lang.reflect.InvocationTargetException: null
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_192]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_192]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_192]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_192]
        at cn.lambdalib2.s11n.network.NetworkMessage$2.invoke(NetworkMessage.java:230) ~[NetworkMessage$2.class:?]
        at cn.lambdalib2.s11n.network.NetworkMessage.invokeListener(NetworkMessage.java:157) ~[NetworkMessage.class:?]
        at cn.lambdalib2.s11n.network.NetworkMessage.processMessage(NetworkMessage.java:138) ~[NetworkMessage.class:?]
        at cn.lambdalib2.s11n.network.NetworkMessage.access$000(NetworkMessage.java:54) ~[NetworkMessage.class:?]
        at cn.lambdalib2.s11n.network.NetworkMessage$Handler.lambda$onMessage$0(NetworkMessage.java:381) ~[NetworkMessage$Handler.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_192]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_192]
        at net.minecraft.util.Util.func_181617_a(Util.java:50) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:842) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:472) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:779) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:633) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_192]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
        at cn.academy.analyticUtil.AnalyticDataListener.serverIpCollector(AnalyticDataListener.java:87) ~[AnalyticDataListener.class:?]
        ... 17 more

更多信息
Windows Server 2016
CatServer version Personal-46e42f6 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT, Forge version 14.23.5.2796)
1.1.0beta2

**Comment by voidcl** [comment]
姑且询问一下，问题发生时您的服务器/客户端电脑的网络状况？

**Comment by sheng-ri** [comment]
网络状态较好，客户端可能有卡顿
