### ISSUE TITLE
getResourceStream Invalid resource academy

### ISSUE THREAD

**Issue by g-bo-wen** [LambdaInnovation/AcademyCraft#753]
WARNING: coremods are present:

  JechCore (JustEnoughCharacters-1.12.0-3.3.0.jar)

  CorePlugin (LambdaLib2-0.1.7.jar)

Contact their authors BEFORE contacting forge

// Don't do that.

Time: 3/3/19 7:37 PM

Description: Ticking player

java.lang.RuntimeException: Invalid resource academy:tutorials/zh_cn/solar_generator.md

	at cn.lambdalib2.util.ResourceUtils.getResourceStream(ResourceUtils.java:14)

	at cn.academy.tutorial.ACTutorial.getContent(ACTutorial.java:66)

	at cn.academy.tutorial.ACTutorial.getTitle(ACTutorial.java:85)

	at cn.academy.client.gui.NotifyUI.onAcquiredKnowledge(NotifyUI.java:159)

	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_216_NotifyUI_onAcquiredKnowledge_TutorialActivatedEvent.invoke(.dynamic)

	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)

	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)

	at cn.academy.tutorial.TutorialData.onTutorialActivate(TutorialData.java:133)

	at cn.academy.tutorial.TutorialData.lambda$null$0(TutorialData.java:73)

	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:408)

	at cn.academy.tutorial.TutorialData.lambda$new$1(TutorialData.java:67)

	at cn.lambdalib2.util.TickScheduler.runFrame(TickScheduler.java:142)

	at cn.lambdalib2.util.TickScheduler.runTick(TickScheduler.java:129)

	at cn.academy.tutorial.TutorialData.tick(TutorialData.java:98)

	at cn.lambdalib2.datapart.DataPart.callTick(DataPart.java:224)

	at cn.lambdalib2.datapart.EntityData.tick(EntityData.java:235)

	at cn.lambdalib2.datapart.EntityData.access$000(EntityData.java:32)

	at cn.lambdalib2.datapart.EntityData$EventListener.onLivingUpdate(EntityData.java:251)

	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_68_EventListener_onLivingUpdate_LivingUpdateEvent.invoke(.dynamic)

	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)

	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)

	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:575)

	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2095)

	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234)

	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382)

	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173)

	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209)

	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)

	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)

	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790)

	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)

	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)

	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)

	at java.lang.Thread.run(Thread.java:748)

Caused by: java.lang.RuntimeException: Can't find resource academy:tutorials/zh_cn/solar_generator.md

	at cn.lambdalib2.util.Debug.assertNotNull(Debug.java:64)

	at cn.lambdalib2.util.ResourceUtils.getResourceStream(ResourceUtils.java:12)

	... 33 more

WARNING: coremods are present:

  JechCore (JustEnoughCharacters-1.12.0-3.3.0.jar)

  CorePlugin (LambdaLib2-0.1.7.jar)

Contact their authors BEFORE contacting forge

// Don't do that.

Time: 3/3/19 7:47 PM

Description: Ticking player

java.lang.RuntimeException: Invalid resource academy:tutorials/zh_cn/imag_fusor.md

	at cn.lambdalib2.util.ResourceUtils.getResourceStream(ResourceUtils.java:14)

	at cn.academy.tutorial.ACTutorial.getContent(ACTutorial.java:66)

	at cn.academy.tutorial.ACTutorial.getTitle(ACTutorial.java:85)

	at cn.academy.client.gui.NotifyUI.onAcquiredKnowledge(NotifyUI.java:159)

	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_216_NotifyUI_onAcquiredKnowledge_TutorialActivatedEvent.invoke(.dynamic)

	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)

	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)

	at cn.academy.tutorial.TutorialData.onTutorialActivate(TutorialData.java:133)

	at cn.academy.tutorial.TutorialData.lambda$null$0(TutorialData.java:73)

	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:408)

	at cn.academy.tutorial.TutorialData.lambda$new$1(TutorialData.java:67)

	at cn.lambdalib2.util.TickScheduler.runFrame(TickScheduler.java:142)

	at cn.lambdalib2.util.TickScheduler.runTick(TickScheduler.java:129)

	at cn.academy.tutorial.TutorialData.tick(TutorialData.java:98)

	at cn.lambdalib2.datapart.DataPart.callTick(DataPart.java:224)

	at cn.lambdalib2.datapart.EntityData.tick(EntityData.java:235)

	at cn.lambdalib2.datapart.EntityData.access$000(EntityData.java:32)

	at cn.lambdalib2.datapart.EntityData$EventListener.onLivingUpdate(EntityData.java:251)

	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_68_EventListener_onLivingUpdate_LivingUpdateEvent.invoke(.dynamic)

	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)

	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)

	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:575)

	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2095)

	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234)

	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382)

	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173)

	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209)

	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)

	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)

	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790)

	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)

	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)

	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)

	at java.lang.Thread.run(Thread.java:748)

Caused by: java.lang.RuntimeException: Can't find resource academy:tutorials/zh_cn/imag_fusor.md

	at cn.lambdalib2.util.Debug.assertNotNull(Debug.java:64)

	at cn.lambdalib2.util.ResourceUtils.getResourceStream(ResourceUtils.java:12)

	... 33 more

**Comment by WeAthFoLD** [comment]
Duplicate with #749
