### ISSUE TITLE
[Bug] Fps Drop when casting Mark Teleport

### ISSUE THREAD

**Issue by CmdrJane** [LambdaInnovation/AcademyCraft#770]
In Multiplayer game when someone starting to cast mark teleport in your vision range it causes significant fps drop. Not sure but the same might appear for penetration teleport.

Console Message
`[23:20:41] [Client thread/ERROR] [lambdalib2]: Error during network message.
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.GeneratedMethodAccessor102.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_201]
	at cn.lambdalib2.s11n.network.NetworkMessage$2.invoke(NetworkMessage.java:230) ~[NetworkMessage$2.class:?]
	at cn.lambdalib2.s11n.network.NetworkMessage.invokeListener(NetworkMessage.java:157) [NetworkMessage.class:?]
	at cn.lambdalib2.s11n.network.NetworkMessage.processMessage(NetworkMessage.java:138) [NetworkMessage.class:?]
	at cn.lambdalib2.s11n.network.NetworkMessage.sendToSelf(NetworkMessage.java:91) [NetworkMessage.class:?]
	at cn.academy.ability.context.Context.onMessage(Context.java:192) [Context.class:?]
	at cn.lambdalib2.s11n.network.NetworkMessage.processMessage(NetworkMessage.java:132) [NetworkMessage.class:?]
	at cn.lambdalib2.s11n.network.NetworkMessage.sendToSelf(NetworkMessage.java:91) [NetworkMessage.class:?]
	at cn.academy.ability.context.ContextManager$ClientManager.__onClientTick(ContextManager.java:606) [ContextManager$ClientManager.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_686_ClientManager___onClientTick_ClientTickEvent.invoke(.dynamic) [?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:349) [FMLCommonHandler.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1911) [bib.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_201]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.IllegalStateException: Wrong context side!
	at cn.academy.ability.context.ContextManager.wrongSide(ContextManager.java:146) ~[ContextManager.class:?]
	at cn.academy.ability.context.ContextManager.terminate(ContextManager.java:75) ~[ContextManager.class:?]
	at cn.academy.ability.context.Context.terminate(Context.java:106) ~[Context.class:?]
	at cn.academy.ability.context.ClientContext.terminate(ClientContext.java:38) ~[ClientContext.class:?]
	at cn.academy.ability.vanilla.teleporter.skill.MTContextC.l_update(MarkTeleport.scala:154) ~[MTContextC.class:?]
	... 25 more`

------------------
System Information
------------------
      Time of this report: 3/20/2019, 01:13:45
             Machine name: DESKTOP-VKGTN4M
               Machine Id: {D6C5C92B-54FE-4B08-BB0A-8CECA0170E4E}
         Operating System: Windows 10 Pro 64-bit (10.0, Build 17763) (17763.rs5_release.180914-1434)
                 Language: Russian (Regional Setting: Russian)
      System Manufacturer: System manufacturer
             System Model: System Product Name
                     BIOS: BIOS Date: 11/14/12 10:20:05 Ver: 15.03 (type: BIOS)
                Processor: AMD FX(tm)-4100 Quad-Core Processor             (4 CPUs), ~4.0GHz
                   Memory: 8192MB RAM
      Available OS Memory: 8190MB RAM
                Page File: 4085MB used, 20488MB available
              Windows Dir: C:\Windows
          DirectX Version: DirectX 12
      DX Setup Parameters: Not found
         User DPI Setting: 96 DPI (100 percent)
       System DPI Setting: 96 DPI (100 percent)
          DWM DPI Scaling: Disabled
                 Miracast: Available, with HDCP
Microsoft Graphics Hybrid: Not Supported
           DxDiag Version: 10.00.17763.0001 64bit Unicode

------------
DxDiag Notes
------------
      Display Tab 1: No problems found.
        Sound Tab 1: No problems found.
        Sound Tab 2: No problems found.
        Sound Tab 3: No problems found.
          Input Tab: No problems found.

--------------------
DirectX Debug Levels
--------------------
Direct3D:    0/4 (retail)
DirectDraw:  0/4 (retail)
DirectInput: 0/5 (retail)
DirectMusic: 0/5 (retail)
DirectPlay:  0/9 (retail)
DirectSound: 0/5 (retail)
DirectShow:  0/6 (retail)

---------------
Display Devices
---------------
           Card name: NVIDIA GeForce GTX 750
        Manufacturer: NVIDIA
           Chip type: GeForce GTX 750
            DAC type: Integrated RAMDAC
         Device Type: Full Device (POST)
          Device Key: Enum\PCI\VEN_10DE&DEV_1407&SUBSYS_140710DE&REV_A1
       Device Status: 0180200A [DN_DRIVER_LOADED|DN_STARTED|DN_DISABLEABLE|DN_NT_ENUMERATOR|DN_NT_DRIVER]

**Comment by WeAthFoLD** [comment]
The console message shows a bug when triggering ability, but I'm not sure it's related to FPS drop. That bug shall still be fixed though. Did the error message flush the console or just pops up a few times?

**Comment by CmdrJane** [comment]
well, we test it several times and fps droping to 1 from 60 only when ability being charge. And yes its flushing console
