### ISSUE TITLE
[Bug] I can't use the mod

### ISSUE THREAD

**Issue by xXSolarGodXx** [LambdaInnovation/AcademyCraft#783]
When is create a new world and even when i try to get into a world it will load the world the the screen will go black then it crashes and the report is 

---- Minecraft Crash Report ----

WARNING: coremods are present:
  CorePlugin (LambdaLib2-0.1.8.jar)
Contact their authors BEFORE contacting forge

// I'm sorry, Dave.

Time: 4/7/19 5:44 PM
Description: Unexpected error

java.lang.RuntimeException: Error loading shader script at /assets/lambdalib2/shader/DebugDraw.glsl
	at cn.lambdalib2.render.ShaderScript.loadFromResource(ShaderScript.java:76)
	at cn.lambdalib2.util.DebugDraw.checkInit(DebugDraw.java:84)
	at cn.lambdalib2.util.DebugDraw.postRenderEntity(DebugDraw.java:73)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_77_DebugDraw_postRenderEntity_RenderAllEntityEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at cn.lambdalib2.render.mc.RenderEventDispatch.beginRenderEntities(RenderEventDispatch.java:87)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1413)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1062)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.RuntimeException: Error when compiling shader: ERROR: 0:2: '' :  version '330' is not supported
ERROR: 0:2: '' : syntax error: #version

	at cn.lambdalib2.render.ShaderScriptParser.linkShader(ShaderScript.java:279)
	at cn.lambdalib2.render.ShaderScriptParser.load(ShaderScript.java:189)
	at cn.lambdalib2.render.ShaderScript.load(ShaderScript.java:61)
	at cn.lambdalib2.render.ShaderScript.loadFromResource(ShaderScript.java:74)
	... 19 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at cn.lambdalib2.render.ShaderScript.loadFromResource(ShaderScript.java:76)
	at cn.lambdalib2.util.DebugDraw.checkInit(DebugDraw.java:84)
	at cn.lambdalib2.util.DebugDraw.postRenderEntity(DebugDraw.java:73)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_77_DebugDraw_postRenderEntity_RenderAllEntityEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at cn.lambdalib2.render.mc.RenderEventDispatch.beginRenderEntities(RenderEventDispatch.java:87)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1413)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['xXSolarGodXx'/867, l='MpServer', x=8.50, y=65.00, z=8.50]]
	Chunk stats: MultiplayerChunkCache: 0, 0
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 1 total; [EntityPlayerSP['xXSolarGodXx'/867, l='MpServer', x=8.50, y=65.00, z=8.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Mac OS X (x86_64) version 10.14.4
	Java Version: 1.8.0_191, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1058937008 bytes (1009 MB) / 1407188992 bytes (1342 MB) up to 5726797824 bytes (5461 MB)
	JVM Flags: 3 total; -Xmx6144m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2825 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID             | Version      | Source                        | Signature                                |
	|:------ |:-------------- |:------------ |:----------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft      | 1.12.2       | minecraft.jar                 | None                                     |
	| LCHIJA | mcp            | 9.42         | minecraft.jar                 | None                                     |
	| LCHIJA | FML            | 8.0.99.99    | forge-1.12.2-14.23.5.2825.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge          | 14.23.5.2825 | forge-1.12.2-14.23.5.2825.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | LambdaLib|Core | 0.1.8        | minecraft.jar                 | None                                     |
	| LCHIJA | lambdalib2     | 0.1.8        | LambdaLib2-0.1.8.jar          | None                                     |
	| LCHIJA | academy        | 1.1.1        | AcademyCraft-1.1.1.jar        | None                                     |

	Loaded coremods (and transformers): 
CorePlugin (LambdaLib2-0.1.8.jar)
  cn.lambdalib2.render.mc.PipelineTransformer
  cn.lambdalib2.registry.impl.RegistryTransformer
	GL info: ' Vendor: 'Intel Inc.' Version: '2.1 INTEL-12.8.38' Renderer: 'Intel HD Graphics 5000 OpenGL Engine'
	Launched Version: forge-14.23.5.2825
	LWJGL: 2.9.2
	OpenGL: Intel HD Graphics 5000 OpenGL Engine GL version 2.1 INTEL-12.8.38, Intel Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-4260U CPU @ 1.40GHz

**Comment by nirvanaxiao6** [comment]
It"s the problem of OpenGL version. In AcademyCraft 1.0.7, the version of OpenGL needs to be 3.3 or higher, but you just have OpenGL 2.1. Please update your OpenGL version through some ways that maybe you can google to get.

**Comment by handicraftsman** [comment]
My graphics card supports OpenGL 3.3 (but not higher), but i still get this error.

**Comment by nirvanaxiao6** [comment]
Your crash-report shows that you are using Intel HD Graphics 5000, not AMD Radeon HD 4350.
Maybe you should change it somehow.

**Comment by Ruchian** [comment]
Nirvana, the post you replied that to is not from the same user as the one who opened the issue.
XxSolarGodxX indeed has a HD Graphics 5000 chip, I cannot say from the error report what handycraftsman has.

XxSolarGodxX will likely not be able to use the mod because he/she has MacOS. Apple abandoned support for OpenGL a while ago. He maybe able to run the mod if he uses software that virtualizes the environment in which he's run the java applet, minecraft and the mod. (I mean something like a virtual machine or something else that the app is tunneled through basically) This way he can avoid Apples's hardcoded OpenGL blocking tricks.) handicraftsman I think is using a linux operating system, but I can't say this with certainty. If he/she is, he/she should be able to run minecraft and the mod without issues.
According to handycraftman's glxinfo output, at the very least he should be able to run anything that uses OpenGL Scripting Language version 3.0 codes, but I am not sure what his/her Java is allowing.
