### ISSUE TITLE
[Bug] Crashed when running on macOS

### ISSUE THREAD

**Issue by Diluka** [LambdaInnovation/AcademyCraft#796]
**Describe the bug**
Crashed when entering the world

**To Reproduce**
Just can't entering a world

**Expected behavior**
Not Crashed

**Screenshots**
Crashed

**Desktop (please complete the following information):**
 - OS: MacOS
 - MC Version and Forge version: 14.23.5.2836
 - Version: 1.1.1

**Additional context**
```log
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CorePlugin (LambdaLib2-0.1.8.jar)
Contact their authors BEFORE contacting forge

// Everything's going to plan. No, really, that was supposed to happen.

Time: 5/10/19 12:41 PM
Description: Unexpected error

java.lang.RuntimeException: Error loading shader script at /assets/lambdalib2/shader/DebugDraw.glsl
	at cn.lambdalib2.render.ShaderScript.loadFromResource(ShaderScript.java:76)
	at cn.lambdalib2.util.DebugDraw.checkInit(DebugDraw.java:84)
	at cn.lambdalib2.util.DebugDraw.postRenderEntity(DebugDraw.java:73)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_77_DebugDraw_postRenderEntity_RenderAllEntityEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at cn.lambdalib2.render.mc.RenderEventDispatch.beginRenderEntities(RenderEventDispatch.java:87)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1413)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1062)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.RuntimeException: Error when compiling shader: ERROR: 0:2: '' :  version '330' is not supported
ERROR: 0:2: '' : syntax error: #version

	at cn.lambdalib2.render.ShaderScriptParser.linkShader(ShaderScript.java:279)
	at cn.lambdalib2.render.ShaderScriptParser.load(ShaderScript.java:189)
	at cn.lambdalib2.render.ShaderScript.load(ShaderScript.java:61)
	at cn.lambdalib2.render.ShaderScript.loadFromResource(ShaderScript.java:74)
	... 19 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at cn.lambdalib2.render.ShaderScript.loadFromResource(ShaderScript.java:76)
	at cn.lambdalib2.util.DebugDraw.checkInit(DebugDraw.java:84)
	at cn.lambdalib2.util.DebugDraw.postRenderEntity(DebugDraw.java:73)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_77_DebugDraw_postRenderEntity_RenderAllEntityEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at cn.lambdalib2.render.mc.RenderEventDispatch.beginRenderEntities(RenderEventDispatch.java:87)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1413)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Diluka'/2026, l='MpServer', x=8.50, y=65.00, z=8.50]]
	Chunk stats: MultiplayerChunkCache: 0, 0
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 1 total; [EntityPlayerSP['Diluka'/2026, l='MpServer', x=8.50, y=65.00, z=8.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Mac OS X (x86_64) version 10.14.4
	Java Version: 1.8.0_171, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 589436768 bytes (562 MB) / 956301312 bytes (912 MB) up to 2147483648 bytes (2048 MB)
	LiteLoader Brand: 1.12.2-SNAPSHOT-r4CC2BB0-b4-4
	LiteLoader Mods: none
	LaunchWrapper: 26 active transformer(s)
          - Transformer: net.minecraftforge.fml.common.asm.transformers.PatchingTransformer
          - Transformer: org.spongepowered.asm.mixin.transformer.Proxy
          - Transformer: com.mumfrey.liteloader.transformers.event.EventProxyTransformer
          - Transformer: com.mumfrey.liteloader.launch.LiteLoaderTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.CrashReportTransformer
          - Transformer: org.spongepowered.asm.mixin.transformer.Proxy
          - Transformer: $wrapper.net.minecraftforge.fml.common.asm.transformers.SideTransformer
          - Transformer: $wrapper.net.minecraftforge.fml.common.asm.transformers.EventSubscriptionTransformer
          - Transformer: $wrapper.net.minecraftforge.fml.common.asm.transformers.EventSubscriberTransformer
          - Transformer: $wrapper.net.minecraftforge.fml.common.asm.transformers.SoundEngineFixTransformer
          - Transformer: $wrapper.cn.lambdalib2.render.mc.PipelineTransformer
          - Transformer: $wrapper.cn.lambdalib2.registry.impl.RegistryTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.DeobfuscationTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.AccessTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.ModAccessTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.ItemStackTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.ItemBlockTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.ItemBlockSpecialTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.PotionEffectTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.TerminalTransformer
          - Transformer: org.spongepowered.asm.mixin.transformer.Proxy
          - Transformer: com.mumfrey.liteloader.transformers.event.EventTransformer
          - Transformer: com.mumfrey.liteloader.common.transformers.LiteLoaderPacketTransformer
          - Transformer: com.mumfrey.liteloader.transformers.event.json.ModEventInjectionTransformer
          - Transformer: org.spongepowered.asm.mixin.transformer.Proxy
          - Transformer: net.minecraftforge.fml.common.asm.transformers.ModAPITransformer
	JVM Flags: 10 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx2048m
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2836 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID             | Version      | Source                        | Signature                                |
	|:------ |:-------------- |:------------ |:----------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft      | 1.12.2       | minecraft.jar                 | None                                     |
	| LCHIJA | mcp            | 9.42         | minecraft.jar                 | None                                     |
	| LCHIJA | FML            | 8.0.99.99    | forge-1.12.2-14.23.5.2836.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge          | 14.23.5.2836 | forge-1.12.2-14.23.5.2836.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | LambdaLib|Core | 0.1.8        | minecraft.jar                 | None                                     |
	| LCHIJA | lambdalib2     | 0.1.8        | LambdaLib2-0.1.8.jar          | None                                     |
	| LCHIJA | academy        | 1.1.1        | AcademyCraft-1.1.1.jar        | None                                     |

	Loaded coremods (and transformers): 
CorePlugin (LambdaLib2-0.1.8.jar)
  cn.lambdalib2.render.mc.PipelineTransformer
  cn.lambdalib2.registry.impl.RegistryTransformer
	GL info: ' Vendor: 'Intel Inc.' Version: '2.1 INTEL-12.8.38' Renderer: 'Intel(R) Iris(TM) Graphics 6100'
	Launched Version: HMCL 3.2.130
	LWJGL: 2.9.2
	OpenGL: Intel(R) Iris(TM) Graphics 6100 GL version 2.1 INTEL-12.8.38, Intel Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge,LiteLoader'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: 简体中文 (中国)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
```

**Comment by Ruchian** [comment]
https://www.imore.com/opengl-and-opencl-be-depreciated-ios-12-and-macos-mojave
OpenGL is no longer supported on Mac OS X (since version 10.14). To support Mac OS users, the developer may need to use the <developer.apple.com/metal>`metal api` or some other replacement.

**Comment by WeAthFoLD** [comment]
AcademyCraft does not and will not support MacOS.
