### ISSUE TITLE
[Bug] NPE preventing player to join server

### ISSUE THREAD

**Issue by LemADEC** [LambdaInnovation/AcademyCraft#804]
**Describe the bug**
Players are unable to join the server while an NPE is reported in lamdalib2:
```
[12:01:31] [Server thread/INFO] [minecraft/DedicatedServer]: LemADEC joined the game
[12:01:32] [Netty Epoll Server IO #6/ERROR] [FML]: FMLIndexedMessageCodec exception caught
io.netty.handler.codec.DecoderException: java.lang.RuntimeException: Error deserializing network message itn_query_init@null
>       at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98) ~[minecraft_server.1.12.2.jar:?]
...
>       at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.RuntimeException: Error deserializing network message itn_query_init@null
>       at cn.lambdalib2.s11n.network.NetworkMessage$Message.fromBytes(NetworkMessage.java:364) ~[NetworkMessage$Message.class:?]
>       at net.minecraftforge.fml.common.network.simpleimpl.SimpleIndexedCodec.decodeInto(SimpleIndexedCodec.java:36) ~[SimpleIndexedCodec.class:?]
>       at net.minecraftforge.fml.common.network.simpleimpl.SimpleIndexedCodec.decodeInto(SimpleIndexedCodec.java:26) ~[SimpleIndexedCodec.class:?]
>       at net.minecraftforge.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:111) ~[FMLIndexedMessageToMessageCodec.class:?]
>       at net.minecraftforge.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:41) ~[FMLIndexedMessageToMessageCodec.class:?]
>       at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81) ~[minecraft_server.1.12.2.jar:?]
>       at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[minecraft_server.1.12.2.jar:?]
>       ... 53 more
Caused by: java.lang.NullPointerException
>       at cn.lambdalib2.datapart.EntityData$2.read(EntityData.java:302) ~[EntityData$2.class:?]
>       at cn.lambdalib2.datapart.EntityData$2.read(EntityData.java:294) ~[EntityData$2.class:?]
>       at cn.lambdalib2.s11n.network.NetworkS11n.deserializeWithHint(NetworkS11n.java:603) ~[NetworkS11n.class:?]
>       at cn.lambdalib2.s11n.network.NetworkS11n.deserialize(NetworkS11n.java:584) ~[NetworkS11n.class:?]
>       at cn.lambdalib2.s11n.network.NetworkMessage$Message.fromBytes(NetworkMessage.java:352) ~[NetworkMessage$Message.class:?]
>       at net.minecraftforge.fml.common.network.simpleimpl.SimpleIndexedCodec.decodeInto(SimpleIndexedCodec.java:36) ~[SimpleIndexedCodec.class:?]
>       at net.minecraftforge.fml.common.network.simpleimpl.SimpleIndexedCodec.decodeInto(SimpleIndexedCodec.java:26) ~[SimpleIndexedCodec.class:?]
>       at net.minecraftforge.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:111) ~[FMLIndexedMessageToMessageCodec.class:?]
>       at net.minecraftforge.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:41) ~[FMLIndexedMessageToMessageCodec.class:?]
>       at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81) ~[minecraft_server.1.12.2.jar:?]
>       at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[minecraft_server.1.12.2.jar:?]
>       ... 53 more
...
[12:01:32] [Netty Epoll Server IO #6/ERROR] [FML]: Network Disconnect: A fatal error has occurred, this connection is terminated
[12:01:32] [Server thread/INFO] [minecraft/NetHandlerPlayServer]: LemADEC lost connection: A fatal error has occurred, this connection is terminated
```

**To Reproduce**
1. Start server on a fresh map
2. Connect,have some mobs spawning (I guess?)
3. Reconnect
=> console spamming and player gets kicked "

**Expected behavior**
Player being able to join

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: Linux
 - MC Version and Forge version: 1.12.2-2838-7.1.7-RC3830
 - Version: AcademyCraft-1.1.2

**Additional context**
Issue is intermittent.
Issue observed as part of a test modpack with ~120 mods.

**Comment by zeldacl** [comment]
Need lambdalib2 Version

**Comment by LemADEC** [comment]
lambdalib2@0.1.9

**Comment by zeldacl** [comment]
try fix in lambdalib2

**Comment by ColorfulGhost** [comment]
> lambdalib2@0.1.9

您好我看最新的AC MOD是把lambdalib2集成在了里面 ，curseforge上LambdaLib2 还是v0.1.8，想问下什么时候修复这个问题....我也遇见同样的情况
