### ISSUE TITLE
Game crashed on macOS

### ISSUE THREAD

**Issue by nozombieWK** [LambdaInnovation/AcademyCraft#811]
Here's what crash-report writes

> ---- Minecraft Crash Report ----

WARNING: coremods are present:
  ForgelinPlugin (Forgelin-1.8.3.jar)
  CorePlugin (AcademyCraft-1.1.2.jar)
Contact their authors BEFORE contacting forge

// Hey, that tickles! Hehehe!

Time: 7/23/19 7:35 AM
Description: Unexpected error

java.lang.RuntimeException: Error loading shader script at /assets/lambdalib2/shader/DebugDraw.glsl
	at cn.lambdalib2.render.ShaderScript.loadFromResource(ShaderScript.java:76)
	at cn.lambdalib2.util.DebugDraw.checkInit(DebugDraw.java:84)
	at cn.lambdalib2.util.DebugDraw.postRenderEntity(DebugDraw.java:73)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_405_DebugDraw_postRenderEntity_RenderAllEntityEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at cn.lambdalib2.render.mc.RenderEventDispatch.beginRenderEntities(RenderEventDispatch.java:87)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1927)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1613)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1384)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.RuntimeException: Error when compiling shader: ERROR: 0:2: '' :  version '330' is not supported
ERROR: 0:2: '' : syntax error: #version

	at cn.lambdalib2.render.ShaderScriptParser.linkShader(ShaderScript.java:279)
	at cn.lambdalib2.render.ShaderScriptParser.load(ShaderScript.java:189)
	at cn.lambdalib2.render.ShaderScript.load(ShaderScript.java:61)
	at cn.lambdalib2.render.ShaderScript.loadFromResource(ShaderScript.java:74)
	... 19 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at cn.lambdalib2.render.ShaderScript.loadFromResource(ShaderScript.java:76)
	at cn.lambdalib2.util.DebugDraw.checkInit(DebugDraw.java:84)
	at cn.lambdalib2.util.DebugDraw.postRenderEntity(DebugDraw.java:73)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_405_DebugDraw_postRenderEntity_RenderAllEntityEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at cn.lambdalib2.render.mc.RenderEventDispatch.beginRenderEntities(RenderEventDispatch.java:87)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1927)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1613)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['nozombie_WK'/17020, l='MpServer', x=8.50, y=65.00, z=8.50]]
	Chunk stats: MultiplayerChunkCache: 0, 0
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 1 total; [EntityPlayerSP['nozombie_WK'/17020, l='MpServer', x=8.50, y=65.00, z=8.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Mac OS X (x86_64) version 10.14.5
	Java Version: 1.8.0_201, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1439585112 bytes (1372 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 10 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx2048m
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 Optifine OptiFine_1.12.2_HD_U_E3 28 mods loaded, 28 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                      | Version           | Source                                        | Signature                                |
	|:------ |:----------------------- |:----------------- |:--------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft               | 1.12.2            | minecraft.jar                                 | None                                     |
	| LCHIJA | mcp                     | 9.42              | minecraft.jar                                 | None                                     |
	| LCHIJA | FML                     | 8.0.99.99         | forge-1.12.2-14.23.5.2838.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                   | 14.23.5.2838      | forge-1.12.2-14.23.5.2838.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | LambdaLib|Core          | 0.1.9             | minecraft.jar                                 | None                                     |
	| LCHIJA | lambdalib2              | 0.1.9             | AcademyCraft-1.1.2.jar                        | None                                     |
	| LCHIJA | academy                 | 1.1.2             | AcademyCraft-1.1.2.jar                        | None                                     |
	| LCHIJA | ic2                     | 2.8.109-ex112     | industrialcraft-2-2.8.109-ex112.jar           | de041f9f6187debbc77034a344134053277aa3b0 |
	| LCHIJA | advanced_solar_panels   | 4.3.0             | Advanced-Solar-Panels-4.3.0.jar               | None                                     |
	| LCHIJA | baubles                 | 1.5.2             | Baubles-1.12-1.5.2.jar                        | None                                     |
	| LCHIJA | forgelin                | 1.8.3             | Forgelin-1.8.3.jar                            | None                                     |
	| LCHIJA | betterrecords           | 1.12.2-1.6.1      | BetterRecords-1.12.2-1.6.1.jar                | None                                     |
	| LCHIJA | birdsfoods              | 3.1 - [1.12]      | birdsfoods-1.12-3.1.jar                       | None                                     |
	| LCHIJA | chopdownupdated         | 1.12.2-1.2.4      | chopdownupdated-1.12.2-1.2.4.jar              | None                                     |
	| LCHIJA | codechickenlib          | 3.2.2.353         | CodeChickenLib-1.12.2-3.2.2.353-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | forgemultipartcbe       | 2.6.1.81          | ForgeMultipart-1.12.2-2.6.1.81-universal.jar  | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | microblockcbe           | 2.6.1.81          | ForgeMultipart-1.12.2-2.6.1.81-universal.jar  | None                                     |
	| LCHIJA | minecraftmultipartcbe   | 2.6.1.81          | ForgeMultipart-1.12.2-2.6.1.81-universal.jar  | None                                     |
	| LCHIJA | ironchest               | 1.12.2-7.0.67.844 | ironchest-1.12.2-7.0.71.846.jar               | None                                     |
	| LCHIJA | mantle                  | 1.12-1.3.3.39     | Mantle-1.12-1.3.3.39.jar                      | None                                     |
	| LCHIJA | mrtjpcore               | 2.1.4.43          | MrTJPCore-1.12.2-2.1.4.43-universal.jar       | None                                     |
	| LCHIJA | projectred-core         | 4.9.4.120         | ProjectRed-1.12.2-4.9.4.120-Base.jar          | None                                     |
	| LCHIJA | projectred-illumination | 4.9.4.120         | ProjectRed-1.12.2-4.9.4.120-lighting.jar      | None                                     |
	| LCHIJA | projectred-exploration  | 4.9.4.120         | ProjectRed-1.12.2-4.9.4.120-world.jar         | None                                     |
	| LCHIJA | flammpfeil.slashblade   | mc1.12-r25        | SlashBlade-mc1.12-r25.jar                     | None                                     |
	| LCHIJA | tconstruct              | 1.12.2-2.12.0.123 | TConstruct-1.12.2-2.12.0.123.jar              | None                                     |
	| LCHIJA | thaumcraft              | 6.1.BETA26        | Thaumcraft-1.12.2-6.1.BETA26.jar              | None                                     |
	| LCHIJA | lastsmith               | V1.2.6.4-MC1.12.2 | TLS-V1.2.6.4-MC1.12.2.jar                     | None                                     |

	Loaded coremods (and transformers): 
ForgelinPlugin (Forgelin-1.8.3.jar)
  
CorePlugin (AcademyCraft-1.1.2.jar)
  cn.lambdalib2.render.mc.PipelineTransformer
  cn.lambdalib2.registry.impl.RegistryTransformer
	GL info: ' Vendor: 'Intel Inc.' Version: '2.1 INTEL-12.9.22' Renderer: 'Intel HD Graphics 5000 OpenGL Engine'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

	Launched Version: HMCL 3.2.130
	LWJGL: 2.9.2
	OpenGL: Intel HD Graphics 5000 OpenGL Engine GL version 2.1 INTEL-12.9.22, Intel Inc.
	GL Caps: VboRegions not supported, missing: OpenGL 1.3, ARB_copy_buffer
Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: ocd_1.11_1.12.zip
	Current Language: 简体中文 (中国)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-4250U CPU @ 1.30GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_E3
	OptiFine Build: 20181210-121000
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 2.1 INTEL-12.9.22
	OpenGlRenderer: Intel HD Graphics 5000 OpenGL Engine
	OpenGlVendor: Intel Inc.
	CpuCount: 4
Could you have a look at this error? Thanks

**Comment by nozombieWK** [comment]
I was trying to enter my server.
I can normally enter it using Windows10 1903 64Bit with jre8_221.

**Comment by 3TUSK** [comment]
Duplicate of #783 #796 #802 and LambdaInnovation/LambdaLib2#5.
There is a proposed workaround in LambdaInnovation/LambdaLib2#5 but I doubt if that is the proper fix.

**Comment by frostfire50** [comment]
Unfortunately Mac’s cant run this mod because Mac abandoned OpenGL which is used to manage graphics.
