### ISSUE TITLE
[Bug] Bug Title

### ISSUE THREAD

**Issue by 2113148985** [LambdaInnovation/AcademyCraft#814]
Fist，i am a Chinese，I have a problem。
I crashed while playing minecraft. It gives me a trouble. Here is the crash log:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  CorePlugin (AcademyCraft-1.1.2.jar)
  ForgePlugin (skin_common.jar)
Contact their authors BEFORE contacting forge

// Why did you do that?

Time: 8/8/19 12:21 PM
Description: Initializing game

java.lang.RuntimeException: Error when invoking registry callback private static void cn.academy.ACItems.registerItems(net.minecraftforge.event.RegistryEvent$Register)
	at cn.lambdalib2.registry.impl.RegistryManager$EventHandler.invokeCallback(RegistryManager.java:209)
	at cn.lambdalib2.registry.impl.RegistryManager$EventHandler.onRegisterItems(RegistryManager.java:197)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_24_EventHandler_onRegisterItems_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:143)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:739)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:603)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:270)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cn.lambdalib2.registry.impl.RegistryManager$EventHandler.invokeCallback(RegistryManager.java:207)
	... 17 more
Caused by: java.lang.NoSuchMethodError: cn.academy.item.ItemCoin.setTileEntityItemStackRenderer(Lnet/minecraft/client/renderer/tileentity/TileEntityItemStackRenderer;)V
	at cn.academy.item.ItemCoin.initClient(ItemCoin.java:56)
	at cn.academy.item.ItemCoin.afterRegistry(ItemCoin.java:49)
	at cn.academy.ACItems.registerItems(ACItems.java:120)
	... 22 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at cn.lambdalib2.registry.impl.RegistryManager$EventHandler.invokeCallback(RegistryManager.java:209)
	at cn.lambdalib2.registry.impl.RegistryManager$EventHandler.onRegisterItems(RegistryManager.java:197)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_24_EventHandler_onRegisterItems_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:143)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:739)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:603)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:270)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 7 (x86) version 6.1
	Java Version: 1.8.0_45, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 363341720 bytes (346 MB) / 519110656 bytes (495 MB) up to 1037959168 bytes (989 MB)
	JVM Flags: 2 total; -Xms512m -Xmx1024m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.1.2555 8 mods loaded, 8 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID             | Version      | Source                        | Signature                                |
	|:----- |:-------------- |:------------ |:----------------------------- |:---------------------------------------- |
	| UCH   | minecraft      | 1.12.2       | minecraft.jar                 | None                                     |
	| UCH   | mcp            | 9.42         | minecraft.jar                 | None                                     |
	| UCH   | FML            | 8.0.99.99    | forge-1.12.2-14.23.1.2555.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge          | 14.23.1.2555 | forge-1.12.2-14.23.1.2555.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | LambdaLib|Core | 0.1.9        | minecraft.jar                 | None                                     |
	| UCH   | lambdalib2     | 0.1.9        | AcademyCraft-1.1.2.jar        | None                                     |
	| UCH   | academy        | 1.1.2        | AcademyCraft-1.1.2.jar        | None                                     |
	| UCH   | myskin         | 14.7         | skin_common.jar               | None                                     |

	Loaded coremods (and transformers): 
CorePlugin (AcademyCraft-1.1.2.jar)
  cn.lambdalib2.render.mc.PipelineTransformer
  cn.lambdalib2.registry.impl.RegistryTransformer
ForgePlugin (skin_common.jar)
  myskin.forge.TransformerManager
	GL info: ' Vendor: 'Intel' Version: '2.1.0 - Build 8.15.10.2555' Renderer: 'Intel(R) G41 Express Chipset'
	Launched Version: 1.12.2-forge1.12.2-14.23.1.2555
	LWJGL: 2.9.4
	OpenGL: Intel(R) G41 Express Chipset GL version 2.1.0 - Build 8.15.10.2555, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because EXT_framebuffer_object is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: 简体中文 (中国)
	Profiler Position: N/A (disabled)
	CPU: 2x Intel(R) Celeron(R) CPU E3400 @ 2.60GHz

**Comment by 2113148985** [comment]
Did I send more?

**Comment by 2113148985** [comment]
希望有人能回答我。。。。

**Comment by Ruchian** [comment]
Update [Forge](https://files.minecraftforge.net/), then try again

**Comment by 2113148985** [comment]
thanks
