### ISSUE TITLE
[Bug] 这个MOD与LambdaLib冲突

### ISSUE THREAD

**Issue by RyuProject** [LambdaInnovation/AcademyCraft#815]
Time: 19-8-12 上午4:05
Description: Exception in server tick loop

Duplicate Mods:
	LambdaLib|Core : C:\Users\Administrator\Desktop\This is Minecraft Server\minecraft.jar
	lambdalib2 : C:\Users\Administrator\Desktop\This is Minecraft Server\.\mods\[Q]LambdaLib2-0.1.8.jar
	lambdalib2 : C:\Users\Administrator\Desktop\This is Minecraft Server\.\mods\【学园都市】AcademyCraft-1.1.2.jar

net.minecraftforge.fml.common.DuplicateModsFoundException
	at net.minecraftforge.fml.common.Loader.identifyDuplicates(Loader.java:464)
	at net.minecraftforge.fml.common.Loader.identifyMods(Loader.java:426)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:566)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Unknown Source)

**Comment by Ruchian** [comment]
A quote from the changelog of AcademyCraft update 1.1.2 [(found here)](https://www.curseforge.com/minecraft/mc-mods/academycraft/files/2724775):

> You don't need to install LambdaLib2 anymore in future verisons! (You have to remove previous LL2 installation!)

In other words:
LambdaLib2 is now integrated into AcademyCraft (the mod). There's a LambdaLib inside the mod jar. You no longer need to download LambdaLib seperately. Since you did download it seperately Forge detected two LambdaLibs in your installation. Obviously the one inside AcademyCraft 1.1.2 is newer. I suggest you remove LambdaLib from your mods directory, because its easier than editting LambdaLib out of the jar, which is also possible if you prefer that.

**Comment by RyuProject** [comment]
> 来自AcademyCraft更新1.1.2的更新日志的引用[（在此处找到）](https://www.curseforge.com/minecraft/mc-mods/academycraft/files/2724775)：
> 
> > 在将来的版本中，您不再需要安装LambdaLib2！（您必须删除以前的LL2安装！）
> 
> 换句话说：
> LambdaLib2现已集成到AcademyCraft（mod）中。mod jar里面有一个LambdaLib。您不再需要单独下载LambdaLib。由于您确实单独下载了Forge，因此在您的安装中检测到两个LambdaLib。显然，AcademyCraft 1.1.2中的一个更新。我建议你从你的mods目录中删除LambdaLib，因为它比从jar中编辑LambdaLib更容易，如果你愿意的话也可以。

Thank you
