### ISSUE TITLE
[Bug] 使用电击使磁场控制时闪退

### ISSUE THREAD

**Issue by abc1763613206** [LambdaInnovation/AcademyCraft#819]
我在提出 Issue 前搜寻到了类似的 #808      
但是显然它没有得到正确的处理。        

我将铁栅栏扔到了由[MmmMmmMmmMmm](https://www.curseforge.com/minecraft/mc-mods/mmmmmmmmmmmm) 提供的不掉血人偶上。   
通常情况下这个人偶被攻击后会显示此次攻击的伤害，而且前面的普通电击技能也能对该人偶正常释放。     

我在正常普通的Forge服务器(Minecraft 1.12.2, 详细信息见下)执行了如上操作，之后所有人掉线，显示"服务器已关闭"，后台日志显示服务器崩溃。   
并且再次启动服务器后，我复现了这一问题（x

以下是导出的全部`log`，包含了安装的模组等信息，可供参考。            

<https://paste.ubuntu.com/p/j5Cc8sYWwm/>    
```
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 2019-08-24 15:49:42 CST
Description: Ticking entity

java.lang.IllegalArgumentException: Cannot get property PropertyInteger{name=layers, clazz=class java.lang.Integer, values=[1, 2, 3, 4, 5, 6, 7, 8]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}
    at net.minecraft.block.state.BlockStateContainer$StateImplementation.getValue(BlockStateContainer.java:201)
    at net.minecraft.block.BlockSnow.isReplaceable(BlockSnow.java:159)
    at cn.academy.entity.EntityBlock$1.onEvent(EntityBlock.java:151)
    at cn.academy.entity.EntityBlock$1.onEvent(EntityBlock.java:135)
    at cn.lambdalib2.util.entityx.EntityX.postEvent(EntityX.java:121)
    at cn.lambdalib2.util.entityx.handlers.Rigidbody.onUpdate(Rigidbody.java:72)
    at cn.lambdalib2.util.entityx.EntityX.update(EntityX.java:53)
    at cn.lambdalib2.util.entityx.EntityAdvanced.onUpdate(EntityAdvanced.java:31)
    at cn.academy.entity.EntityBlock.onUpdate(EntityBlock.java:113)
    at cn.academy.entity.MagManipEntityBlock.onUpdate(MagManipEntityBlock.java:121)
    at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1993)
    at net.minecraft.world.WorldServer.updateEntityWithOptionalForce(WorldServer.java:832)
    at net.minecraft.world.World.updateEntity(World.java:1955)
    at net.minecraft.world.World.redirect$updateEntity$zbd000(World.java:5118)
    at net.minecraft.world.World.updateEntities(World.java:1759)
    at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767)
    at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:748)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Entity being ticked --
  Entity Type: academy:magmanipentityblock (cn.academy.entity.MagManipEntityBlock)
  Entity ID: 293140
  Entity Name: entity.MagManipEntityBlock.name
  Entity's Exact location: 3102.54, 100.14, -3043.20
  Entity's Block location: World: (3102,100,-3044), Chunk: (at 14,6,12 in 193,-191; contains blocks 3088,0,-3056 to 3103,255,-3041), Region: (6,-6; contains chunks 192,-192 to 223,-161, blocks 3072,0,-3072 to 3583,255,-2561)
  Entity's Momentum: -0.12, -0.47, -0.69
  Entity's Passengers: []
  Entity's Vehicle: ~~ERROR~~ NullPointerException: null
  Entity NBT: {Motion:[-0.1155692827700141d,-0.4677353757073133d,-0.6899585743744822d],ForgeData:{"roughmobs:featuresApplied":1b},UUIDLeast:-5694742612245718582L,Invulnerable:0b,Air:300s,OnGround:0b,Dimension:0,PortalCooldown:0,Rotation:[0.0f,0.0f],UpdateBlocked:0b,FallDistance:0.0f,UUIDMost:-1203300019595230942L,Pos:[3102.5445481770457d,100.13661977997327d,-3043.204129694735d],Fire:-1s,SurgeAABB:[3102.160117459816d,100.60435515568058d,-3043.0141711203605d,3103.160117459816d,101.60435515568058d,-3042.0141711203605d]}

-- Affected level --
  Level name: world
  All players: 4 total; [EntityPlayerMP['Ishiki233'/252658, l='world', x=-478.49, y=66.00, z=-78.10], EntityPlayerMP['abc1763613206'/253568, l='world', x=3104.55, y=104.00, z=-3030.39], EntityPlayerMP['NeptunePoi'/280411, l='world', x=-177.05, y=86.77, z=278.50], EntityPlayerMP['KilaBash'/281200, l='world', x=3105.26, y=103.00, z=-3028.24]]
  Chunk stats: ServerChunkCache: 1157 Drop: 0
  Level seed: 2535336618765797287
  Level generator: ID 00 - default, ver 1. Features enabled: true
  Level generator options: 
  Level spawn location: World: (-133,75,314), Chunk: (at 11,4,10 in -9,19; contains blocks -144,0,304 to -129,255,319), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
  Level time: 42199564 game time, 126001 day time
  Level dimension: 0
  Level storage version: 0x04ABD - Anvil
  Level weather: Rain time: 50363 (now: false), thunder time: 125602 (now: false)
  Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Linux (amd64) version 4.12.10-1.el7.elrepo.x86_64
  Java Version: 1.8.0_202, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 1830510320 bytes (1745 MB) / 8589934592 bytes (8192 MB) up to 17179869184 bytes (16384 MB)
  JVM Flags: 3 total; -Xms8G -XX:+UseG1GC -Xmx16G
  IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 95
  FML: MCP 9.42 Powered by Forge 14.23.5.2838 146 mods loaded, 146 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State  | ID                        | Version                 | Source                                               | Signature                                |
       |:------ |:------------------------- |:----------------------- |:---------------------------------------------------- |:---------------------------------------- |
       | LCHIJA | minecraft                 | 1.12.2                  | minecraft.jar                                        | None                                     |
       | LCHIJA | mcp                       | 9.42                    | minecraft.jar                                        | None                                     |
       | LCHIJA | FML                       | 8.0.99.99               | forge-1.12.2-14.23.5.2838-universal.jar              | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | forge                     | 14.23.5.2838            | forge-1.12.2-14.23.5.2838-universal.jar              | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | LambdaLib|Core            | 0.1.9                   | minecraft.jar                                        | None                                     |
       | LCHIJA | creativecoredummy         | 1.0.0                   | minecraft.jar                                        | None                                     |
       | LCHIJA | dcs_asm                   | 2.0.1                   | minecraft.jar                                        | 4cd12b92959105443b7b694fffe0cea9ed004886 |
       | LCHIJA | jecharacters              | 1.12.0-3.4.3            | JustEnoughCharacters-1.12.0-3.4.3.jar                | None                                     |
       | LCHIJA | littletilescore           | 1.0.0                   | minecraft.jar                                        | None                                     |
       | LCHIJA | foamfixcore               | 7.7.4                   | minecraft.jar                                        | None                                     |
       | LCHIJA | obfuscate                 | 0.2.6                   | minecraft.jar                                        | None                                     |
       | LCHIJA | dsurroundcore             | 3.5.4.3                 | minecraft.jar                                        | None                                     |
       | LCHIJA | mapgadgets                | @VERSION@               | 's+Gadgets-1.2_for_1.12.x.jar                        | None                                     |
       | LCHIJA | aiimprovements            | 0.0.1.3                 | (优化)AIImprovements-1.12-0.0.1b3.jar                  | None                                     |
       | LCHIJA | foamfix                   | 0.10.5-1.12.2           | (优化)foamfix-0.10.5-1.12.2.jar                        | None                                     |
       | LCHIJA | lambdalib2                | 0.1.9                   | AcademyCraft-1.1.2.jar                               | None                                     |
       | LCHIJA | academy                   | 1.1.2                   | AcademyCraft-1.1.2.jar                               | None                                     |
       | LCHIJA | biomesoplenty             | 7.0.1.2439              | BiomesOPlenty-1.12.2-7.0.1.2439-universal.jar        | None                                     |
       | LCHIJA | craftstudioapi            | 1.0.0                   | CraftStudioAPI-universal-1.0.1.95-mc1.12-alpha.jar   | None                                     |
       | LCHIJA | harvestcraft              | 1.12.2zb                | Pam's+HarvestCraft+1.12.2zd+Surprise+for+Yogcast.jar | None                                     |
       | LCHIJA | animania                  | 1.6.2                   | animania-1.12.2-1.6.2.jar                            | None                                     |
       | LCHIJA | antiqueatlas              | 4.5.1                   | antiqueatlas-1.12.2-4.5.1.jar                        | e631d7254e451d0360d0148cb21407d5511d45e9 |
       | LCHIJA | applecore                 | 3.2.0                   | AppleCore-mc1.12.2-3.2.0.jar                         | None                                     |
       | LCHIJA | jei                       | 4.15.0.281              | jei_1.12.2-4.15.0.281.jar                            | None                                     |
       | LCHIJA | appleskin                 | 1.0.9                   | AppleSkin-mc1.12-1.0.9.jar                           | None                                     |
       | LCHIJA | armourers_workshop        | 1.12.2-0.49.1           | Armourers-Workshop-1.12.2-0.49.1.jar                 | None                                     |
       | LCHIJA | attributefix              | 1.0.4                   | AttributeFix-1.12.2-1.0.4.jar                        | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | cd4017be_lib              | 6.4.8                   | CD4017BE_lib-1.12.2-6.4.8.jar                        | None                                     |
       | LCHIJA | circuits                  | 6.1.6                   | AutomatedRedstone-1.12.2-6.1.6.jar                   | None                                     |
       | LCHIJA | badwithernocookiereloaded | 1.12.2-3.3.16           | badwithernocookiereloaded-1.12.2-3.3.16.jar          | None                                     |
       | LCHIJA | baubles                   | 1.5.2                   | Baubles-1.12-1.5.2.jar                               | None                                     |
       | LCHIJA | bibliocraft               | 2.4.5                   | BiblioCraft[v2.4.5][MC1.12.2].jar                    | None                                     |
       | LCHIJA | buildcraftlib             | 7.99.24.1               | buildcraft-all-7.99.24.1.jar                         | None                                     |
       | LCHIJA | buildcraftcore            | 7.99.24.1               | buildcraft-all-7.99.24.1.jar                         | None                                     |
       | LCHIJA | buildcraftbuilders        | 7.99.24.1               | buildcraft-all-7.99.24.1.jar                         | None                                     |
       | LCHIJA | buildcrafttransport       | 7.99.24.1               | buildcraft-all-7.99.24.1.jar                         | None                                     |
       | LCHIJA | buildcraftsilicon         | 7.99.24.1               | buildcraft-all-7.99.24.1.jar                         | None                                     |
       | LCHIJA | crafttweaker              | 4.1.19                  | CraftTweaker2-1.12-4.1.19.jar                        | None                                     |
       | LCHIJA | buildcraftenergy          | 7.99.24.1               | buildcraft-all-7.99.24.1.jar                         | None                                     |
       | LCHIJA | forestry                  | 5.8.2.387               | forestry_1.12.2-5.8.2.387.jar                        | None                                     |
       | LCHIJA | theoneprobe               | 1.4.28                  | theoneprobe-1.12-1.4.28.jar                          | None                                     |
       | LCHIJA | buildcraftcompat          | 7.99.24.1               | buildcraft-all-7.99.24.1.jar                         | None                                     |
       | LCHIJA | buildcraftfactory         | 7.99.24.1               | buildcraft-all-7.99.24.1.jar                         | None                                     |
       | LCHIJA | buildcraftrobotics        | 7.99.24.1               | buildcraft-all-7.99.24.1.jar                         | None                                     |
       | LCHIJA | buildinggadgets           | 2.6.8                   | BuildingGadgets-2.6.8.jar                            | None                                     |
       | LCHIJA | chesttransporter          | 2.8.8                   | ChestTransporter-1.12.2-2.8.8.jar                    | None                                     |
       | LCHIJA | chineseworkshop           | 1.2.6                   | ChineseWorkshop-1.12.2_1.2.6.jar                     | None                                     |
       | LCHIJA | chisel                    | MC1.12.2-0.2.1.35       | Chisel-MC1.12.2-0.2.1.35.jar                         | None                                     |
       | LCHIJA | chiselsandbits            | 14.33                   | chiselsandbits-14.33.jar                             | None                                     |
       | LCHIJA | codechickenlib            | 3.2.2.353               | CodeChickenLib-1.12.2-3.2.2.353-universal.jar        | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCHIJA | cookingforblockheads      | 6.4.71                  | CookingForBlockheads_1.12.2-6.4.71.jar               | None                                     |
       | LCHIJA | corpse                    | 1.12.2-1.0.2            | corpse-1.12.2-1.0.2.jar                              | None                                     |
       | LCHIJA | crafttweakerjei           | 2.0.3                   | CraftTweaker2-1.12-4.1.19.jar                        | None                                     |
       | LCHIJA | creativecore              | 1.9.9                   | CreativeCore_v1.9.59_mc1.12.2.jar                    | None                                     |
       | LCHIJA | modcurrency               | 1.12-1.3.11             | Currency-1.12.0-1.3.11.jar                           | None                                     |
       | LCHIJA | customstartinggear        | 1.2.0                   | CustomStartingGear-1.12-1.2.0.9-universal.jar        | None                                     |
       | LCHIJA | diethopper                | 1.1                     | diethopper-1.1.jar                                   | None                                     |
       | LCHIJA | dynamictrees              | 1.12.2-0.9.5            | DynamicTrees-1.12.2-0.9.5.jar                        | None                                     |
       | LCHIJA | traverse                  | 1.6.0                   | Traverse-1.12.2-1.6.0-69.jar                         | None                                     |
       | LCHIJA | dttraverse                | 1.5                     | dttraverse-1.5.jar                                   | None                                     |
       | LCHIJA | dynamictreesbop           | 1.12.2-1.4.1e           | DynamicTreesBOP-1.12.2-1.4.1e.jar                    | None                                     |
       | LCHIJA | dynamictreesphc           | 1.12.2-1.4.2            | DynamicTreesPHC-1.12.2-1.4.2.jar                     | None                                     |
       | LCHIJA | elevatorid                | 1.3.10                  | ElevatorMod-1.12.2-1.3.10.jar                        | None                                     |
       | LCHIJA | exhaustedstamina          | 1.2                     | exhaustedstamina-1.2.jar                             | None                                     |
       | LCHIJA | silentlib                 | 3.0.13                  | SilentLib-1.12.2-3.0.13+167.jar                      | None                                     |
       | LCHIJA | extendeddays              | 0.2.9                   | ExtendedDays-1.12.2-0.2.9-28.jar                     | None                                     |
       | LCHIJA | extrabitmanipulation      | 1.12.2-3.4.1            | ExtraBitManipulation-1.12.2-3.4.1.jar                | None                                     |
       | LCHIJA | factorytech               | 1.5                     | FactoryTech-1.6.8.jar                                | None                                     |
       | LCHIJA | familiarfauna             | 1.0.11                  | FamiliarFauna-1.12.2-1.0.11.jar                      | None                                     |
       | LCHIJA | fasterladderclimbing      | 0.1-146                 | FasterLadderClimbing-1.12-0.1-146.jar                | None                                     |
       | LCHIJA | fastfood                  | 0.2.121859723           | FastFood-0.2.121859723.jar                           | None                                     |
       | LCHIJA | fastleafdecay             | v14                     | FastLeafDecay-v14.jar                                | None                                     |
       | LCHIJA | fastbench                 | 1.7.2                   | FastWorkbench-1.12.2-1.7.2.jar                       | None                                     |
       | LCHIJA | fishingmadebetter         | 1.1.3                   | FishingMadeBetter-1.12.2-1.1.3.jar                   | None                                     |
       | LCHIJA | forgelin                  | 1.8.3                   | Forgelin-1.8.3.jar                                   | None                                     |
       | LCHIJA | forgemultipartcbe         | 2.6.1.81                | ForgeMultipart-1.12.2-2.6.1.81-universal.jar         | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCHIJA | microblockcbe             | 2.6.1.81                | ForgeMultipart-1.12.2-2.6.1.81-universal.jar         | None                                     |
       | LCHIJA | minecraftmultipartcbe     | 2.6.1.81                | ForgeMultipart-1.12.2-2.6.1.81-universal.jar         | None                                     |
       | LCHIJA | ftblib                    | 5.4.3.103               | FTBLib-5.4.3.103.jar                                 | None                                     |
       | LCHIJA | ftbutilities              | 5.4.0.97                | FTBUtilities-5.4.0.97.jar                            | None                                     |
       | LCHIJA | trashcansreborn           | 1.1.0                   | GarbageBins-1.1.1.jar                                | None                                     |
       | LCHIJA | guideapi                  | 1.12-2.1.8-63           | Guide-API-1.12-2.1.8-63.jar                          | None                                     |
       | LCHIJA | hardcoredarkness          | 2.0                     | HardcoreDarkness-MC1.12.2-2.0.jar                    | d72e0dd57935b3e9476212aea0c0df352dd76291 |
       | LCHIJA | dcs_lib                   | 3.0.4                   | HeatAndClimateLib_1.12.2-3.0.4.jar                   | None                                     |
       | LCHIJA | dcs_climate               | 3.0.10                  | HeatAndClimateMod_1.12.2-3.0.10.jar                  | None                                     |
       | LCHIJA | indlog                    | 1.3.3                   | InductiveLogistics-1.12.2-1.3.3.jar                  | None                                     |
       | LCHIJA | inventorytweaks           | 1.64+dev.146.2180b27    | InventoryTweaks-1.64+dev.146.jar                     | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
       | LCHIJA | ironchest                 | 1.12.2-7.0.67.844       | ironchest-1.12.2-7.0.72.847.jar                      | None                                     |
       | LCHIJA | jecalculation             | 1.12.2-3.1.4            | JustEnoughCalculation-1.12.2-3.1.4.jar               | None                                     |
       | LCHIJA | littletiles               | 1.5.0                   | LittleTiles_v1.5.0-pre155_mc1.12.2.jar               | None                                     |
       | LCHIJA | logisticalautomation      | 0.1.0                   | logisticalautomation-0.1.0.jar                       | None                                     |
       | LCHIJA | logisticspipes            | 0.10.2.203              | logisticspipes-0.10.2.203.jar                        | e0c86912b2f7cc0cc646ad57799574aea43dbd45 |
       | LCHIJA | malisiscore               | 1.12.2-6.5.1-SNAPSHOT   | malisiscore-1.12.2-6.5.1.jar                         | None                                     |
       | LCHIJA | mantle                    | 1.12-1.3.3.55           | Mantle-1.12-1.3.3.55.jar                             | None                                     |
       | LCHIJA | testdummy                 | 1.12                    | MmmMmmMmmMmm-1.12-1.14.jar                           | None                                     |
       | LCHIJA | mrtjpcore                 | 2.1.4.43                | MrTJPCore-1.12.2-2.1.4.43-universal.jar              | None                                     |
       | LCHIJA | netherportalfix           | 5.3.17                  | NetherPortalFix_1.12.1-5.3.17.jar                    | None                                     |
       | LCHIJA | opframe                   | 1.4.0                   | OnlinePicFrame_v1.4.26_mc1.12.2.jar                  | None                                     |
       | LCHIJA | openfm                    | 0.1.0.19                | OpenFM-1.12.2-0.1.0.19.jar                           | None                                     |
       | LCHIJA | pamscookables             | 1.1                     | pamscookables-1.1.jar                                | None                                     |
       | LCHIJA | ping                      | 1.4.5                   | Ping-1.12.2-1.4.5.jar                                | None                                     |
       | LCHIJA | playerrevive              | 1.0                     | PlayerRevive_v1.2.26_mc1.12.2.jar                    | None                                     |
       | LCHIJA | projectred-core           | 4.9.4.120               | ProjectRed-1.12.2-4.9.4.120-Base.jar                 | None                                     |
       | LCHIJA | tconstruct                | 1.12.2-2.12.0.135       | TConstruct-1.12.2-2.12.0.135.jar                     | None                                     |
       | LCHIJA | plustic                   | 7.1.0.0                 | plustic-7.1.0.0.jar                                  | None                                     |
       | LCHIJA | progressivebosses         | 1.5.0                   | ProgressiveBosses-1.5.0-mc1.12.x.jar                 | None                                     |
       | LCHIJA | projectred-compat         | 1.0                     | ProjectRed-1.12.2-4.9.4.120-compat.jar               | None                                     |
       | LCHIJA | projectred-integration    | 4.9.4.120               | ProjectRed-1.12.2-4.9.4.120-integration.jar          | None                                     |
       | LCHIJA | projectred-transmission   | 4.9.4.120               | ProjectRed-1.12.2-4.9.4.120-integration.jar          | None                                     |
       | LCHIJA | projectred-fabrication    | 4.9.4.120               | ProjectRed-1.12.2-4.9.4.120-fabrication.jar          | None                                     |
       | LCHIJA | projectred-illumination   | 4.9.4.120               | ProjectRed-1.12.2-4.9.4.120-lighting.jar             | None                                     |
       | LCHIJA | projectred-expansion      | 4.9.4.120               | ProjectRed-1.12.2-4.9.4.120-mechanical.jar           | None                                     |
       | LCHIJA | projectred-relocation     | 4.9.4.120               | ProjectRed-1.12.2-4.9.4.120-mechanical.jar           | None                                     |
       | LCHIJA | projectred-transportation | 4.9.4.120               | ProjectRed-1.12.2-4.9.4.120-mechanical.jar           | None                                     |
       | LCHIJA | projectred-exploration    | 4.9.4.120               | ProjectRed-1.12.2-4.9.4.120-world.jar                | None                                     |
       | LCHIJA | pvj                       | 1.6.3                   | ProjectVibrantJourneys-1.12.2-1.6.3.jar              | None                                     |
       | LCHIJA | railcraft                 | 12.0.0                  | railcraft-12.0.0.jar                                 | a0c255ac501b2749537d5824bb0f0588bf0320fa |
       | LCHIJA | realdrops                 | 1.2.14                  | RealisticItemDrops-1.2.14.jar                        | None                                     |
       | LCHIJA | rs_ctr                    | 0.1.2                   | RedstoneControl-1.12.2-0.1.2.jar                     | None                                     |
       | LCHIJA | ropebridge                | 2.0.5                   | ropebridge-1.12-2.0.7.jar                            | None                                     |
       | LCHIJA | roughmobs                 | 2.0.0                   | roughmobs2-1.12.2_2.0.15.jar                         | None                                     |
       | LCHIJA | rsgauges                  | 1.1.6                   | rsgauges-1.12.2-1.1.6.jar                            | ed58ed655893ced6280650866985abcae2bf7559 |
       | LCHIJA | spiceoflife               | 1.3.12                  | SpiceOfLife-mc1.12-1.3.12.jar                        | None                                     |
       | LCHIJA | stg                       | 1.12.2-1.2.3            | stg-1.12.2-1.2.3.jar                                 | None                                     |
       | LCHIJA | supersoundmuffler         | 1.0.2.10                | supersoundmuffler-1.12.2-1.0.2.10.jar                | None                                     |
       | LCHIJA | surge                     | 2.0.77                  | Surge-1.12.2-2.0.77.jar                              | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | survivalistlighting       | 1.0                     | survivalistlighting-1.12.2-6.jar                     | None                                     |
       | LCHIJA | taiga                     | 1.12.2-1.3.3            | taiga-1.12.2-1.3.4.jar                               | None                                     |
       | LCHIJA | tinkersaddons             | 1.0.7                   | Tinkers'+Addons-1.12.1-1.0.7.jar                     | None                                     |
       | LCHIJA | tinkerscompendium         | 1.4.2.28                | tinkersdefense-1.4.2.28.jar                          | None                                     |
       | LCHIJA | tinkersjei                | 1.2                     | tinkersjei-1.2.jar                                   | None                                     |
       | LCHIJA | trashslot                 | 8.4.10                  | TrashSlot_1.12.2-8.4.10.jar                          | None                                     |
       | LCHIJA | travellersbackpack        | 1.0.19.19               | TravellersBackpack-1.12.2-1.0.19.19.jar              | None                                     |
       | LCHIJA | vanillafix                | 1.0.10-SNAPSHOT         | VanillaFix-1.0.10-99.jar                             | None                                     |
       | LCHIJA | vanillafoodpantry         | 4.3.1                   | vanillafoodpantry-mc1.12.2-4.3.1.jar                 | None                                     |
       | LCHIJA | vehicle                   | 0.41.0                  | vehicle-mod-0.41.0-1.12.2.jar                        | None                                     |
       | LCHIJA | winterwonderland          | 1.0                     | WinterWonderLand-1.0.0.jar                           | None                                     |
       | LCHIJA | worldedit                 | 6.1.10-SNAPSHOT         | worldedit-forge-mc1.12.2-6.1.10-SNAPSHOT-dist.jar    | None                                     |
       | LCHIJA | worleycaves               | 1.4.1                   | worleycaves-1.4.1.jar                                | None                                     |
       | LCHIJA | xlfoodmod                 | 1.12.2-1.9.1            | XL-Food-Mod-1.12.2-1.9.1.jar                         | None                                     |
       | LCHIJA | yabba                     | 1.1.2.52                | YABBA-1.1.2.52.jar                                   | None                                     |
       | LCHIJA | recipehandler             | 0.13                    | （解决合成冲突T）NoMoreRecipeConflict-0.13(1.12.2).jar       | None                                     |
       | LCHIJA | orelib                    | 3.5.2.2                 | OreLib-1.12.2-3.5.2.2.jar                            | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
       | LCHIJA | dsurround                 | 3.5.4.3                 | DynamicSurroundings-1.12.2-3.5.4.3.jar               | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
       | LCHIJA | phosphor-lighting         | 1.12.2-0.2.4            | (优化)phosphor-1.12.2-0.2.4+build46-universal.jar      | f0387d288626cc2d937daa504e74af570c52a2f1 |
       | LCHIJA | hungeroverhaul            | 1.12.2-1.3.3.jenkins148 | HungerOverhaul-1.12.2-1.3.3.jenkins148.jar           | None                                     |
  Loaded coremods (and transformers): PhosphorFMLLoadingPlugin ((优化)phosphor-1.12.2-0.2.4+build46-universal.jar)
                                        
                                      OFMDepLoader (OpenFM-1.12.2-0.1.0.19.jar)
                                        
                                      CorePlugin (AcademyCraft-1.1.2.jar)
                                        cn.lambdalib2.render.mc.PipelineTransformer
                                        cn.lambdalib2.registry.impl.RegistryTransformer
                                      AppleCore (AppleCore-mc1.12.2-3.2.0.jar)
                                        squeek.applecore.asm.TransformerModuleHandler
                                      CreativePatchingLoader (CreativeCore_v1.9.59_mc1.12.2.jar)
                                        
                                      Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.146.jar)
                                        invtweaks.forge.asm.ContainerTransformer
                                      ObfuscatePlugin (obfuscate-0.2.6-1.12.2.jar)
                                        com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
                                      LittlePatchingLoader (LittleTiles_v1.5.0-pre155_mc1.12.2.jar)
                                        com.creativemd.littletiles.LittleTilesTransformer
                                      CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
                                      ForgelinPlugin (Forgelin-1.8.3.jar)
                                        
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) ((优化)foamfix-0.10.5-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      DCASMPlugin (HeatAndClimateLib_1.12.2-3.0.4.jar)
                                        defeatedcrow.hac.asm.DCMethodTransformer
                                      JechCore (JustEnoughCharacters-1.12.0-3.4.3.jar)
                                        me.towdium.jecharacters.core.JechClassTransformer
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-99.jar)
                                        
                                      MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
                                        
                                      SurgeLoadingPlugin (Surge-1.12.2-2.0.77.jar)
                                        
                                      LoadingPlugin (HardcoreDarkness-MC1.12.2-2.0.jar)
                                        lumien.hardcoredarkness.asm.ClassTransformer
                                      CustomSkinLoader (CustomSkinLoader_Forge-14.11-SNAPSHOT-89.jar)
                                        customskinloader.forge.loader.LaunchWrapper
                                      LogisticsPipesCoreLoader (logisticspipes-0.10.2.203.jar)
                                        logisticspipes.asm.LogisticsClassTransformer
                                      DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.5.4.3.jar)
                                        org.orecruncher.dsurround.asm.Transformer
  Pulsar/tconstruct loaded Pulses: - TinkerCommons (Enabled/Forced)
                                   - TinkerWorld (Enabled/Not Forced)
                                   - TinkerTools (Enabled/Not Forced)
                                   - TinkerHarvestTools (Enabled/Forced)
                                   - TinkerMeleeWeapons (Enabled/Forced)
                                   - TinkerRangedWeapons (Enabled/Forced)
                                   - TinkerModifiers (Enabled/Forced)
                                   - TinkerSmeltery (Enabled/Not Forced)
                                   - TinkerGadgets (Enabled/Not Forced)
                                   - TinkerOredict (Enabled/Forced)
                                   - TinkerIntegration (Enabled/Forced)
                                   - TinkerFluids (Enabled/Forced)
                                   - TinkerMaterials (Enabled/Forced)
                                   - TinkerModelRegister (Enabled/Forced)
                                   - chiselIntegration (Enabled/Not Forced)
                                   - chiselsandbitsIntegration (Enabled/Not Forced)
                                   - theoneprobeIntegration (Enabled/Not Forced)
  Suspected Mods: Academy Craft (academy)
  Profiler Position: N/A (disabled)
  Player Count: 4 / 20; [EntityPlayerMP['Ishiki233'/252658, l='world', x=-478.49, y=66.00, z=-78.10], EntityPlayerMP['abc1763613206'/253568, l='world', x=3104.55, y=104.00, z=-3030.39], EntityPlayerMP['NeptunePoi'/280411, l='world', x=-177.05, y=86.77, z=278.50], EntityPlayerMP['KilaBash'/281200, l='world', x=3105.26, y=103.00, z=-3028.24]]
  Is Modded: Definitely; Server brand changed to 'fml,forge'
  Type: Dedicated Server (map_server.txt)
```

**Comment by abc1763613206** [comment]
这玩意儿还没法往雪上扔


**惨痛的教训**
