### ISSUE TITLE
[Bug] Bug Title

### ISSUE THREAD

**Issue by haozhi233** [LambdaInnovation/AcademyCraft#820]
模组冲突。
1.7.10 模组版本1.0.7
Type: Minecraft Crash
Minecraft已崩溃
---- Minecraft崩溃报告 ----
// Hey, that tickles! Hehehe!

Time: 19-8-28 ����10:07
崩溃类型： Rendering screen

java.lang.NullPointerException: Rendering screen
	at cpw.mods.fml.common.versioning.VersionRange.getLowerBoundString(VersionRange.java:573)
	at cpw.mods.fml.client.GuiModsMissing.func_73863_a(GuiModsMissing.java:54)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at cpw.mods.fml.common.versioning.VersionRange.getLowerBoundString(VersionRange.java:573)
	at cpw.mods.fml.client.GuiModsMissing.func_73863_a(GuiModsMissing.java:54)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061)

-- Screen render details --
Details:
	Screen name: cpw.mods.fml.client.GuiModsMissing
	Mouse location: Scaled: (323, 78). Absolute: (646, 323)
	Screen size: Scaled: (427, 240). Absolute: (854, 480). Scale factor of 2
Stacktrace:
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_211, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 139724912 bytes (133 MB) / 298360832 bytes (284 MB) up to 4207738880 bytes (4012 MB)
	JVM Flags: 2 total; -Xincgc -Xmx4096M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 29 mods loaded, 29 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	U	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	U	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	U	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	U	CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar) 
	U	InputFix{1.7.10-v5} [InputFix] (minecraft.jar) 
	U	NotEnoughItems{1.0.3.74} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.3.74-universal.jar) 
	U	FastCraft{1.25} [FastCraft] (fastcraft-1.25.jar) 
	U	academy-craft{1.0.7} [Academy Craft] (AcademyCraft-1.0.7.jar) 
	U	AdvancedSolarPanel{1.7.10-3.5.1} [Advanced Solar Panels] (AdvancedSolarPanel-1.7.10-3.5.1[TFCN].jar) 
	U	hud{1.3.5} [Better HUD] (Better+HUD+by+NukeDuck+[1.7.10][1.3.5].jar) 
	U	craftguide{1.7.1.0} [CraftGuide] (CraftGuide-1.7.1.0-forge.jar) 
	U	DamageIndicatorsMod{3.2.3} [Damage Indicators] (Damage-Indicators-Mod-1.7.10.jar) 
	U	jinryuudragonblockc{1.4.61} [Dragon Block C] (DragonBlockC-v1.4.61.jar) 
	U	DummyCore{1.13} [DummyCore] (DummyCore1.13.jar) 
	U	GraviSuite{1.7.10-2.0.3} [Graviation Suite] (GraviSuite-1.7.10-2.0.3[TFCN].jar) 
	U	IC2{2.2.828-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.828-experimental.jar) 
	U	jinryuubetterrenderaddon{1.6.36} [JinRyuu's Better Render Addon] (JBRA-Client-v1.6.36.jar) 
	U	journeymap{5.1.4p2} [JourneyMap] (journeymap-1.7.10-5.1.4p2-unlimited.jar) 
	U	jinryuujrmcore{1.3.21a} [JinRyuu's JRMCore] (JRMCore-v1.3.21a.jar) 
	U	KeepingInventory{2.1} [Keeping Inventory] (KeepingInventory-1.7.10-2.1.jar) 
	U	Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (Mantle-1.7.10-0.3.2b.jar) 
	U	MyHome{2.0.0} [MyHome] (myHome-2.0.0.jar) 
	U	flammpfeil.slashblade{mc1.7.10-r87} [SlashBlade] (SlashBlade-mc1.7.10-r87.jar) 
	U	TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct] (TConstruct-1.7.10-1.8.8.jar) 
	U	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) 
	U	thaumicbases{1.3.1710.2} [Thaumic Bases] (ThaumicBases-1.3.1710.4.jar) 
	U	TwilightForest{2.3.7} [The Twilight Forest] (twilightforest-1.7.10-2.3.7.jar) 
	U	UnicodeFontFixer{1.1.12-mc1.7.10} [UnicodeFontFixer] (UnicodeFontFixer-1.1.12-mc1.7.10.jar) 
	U	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 417.98' Renderer: 'GeForce GTX 1660 Ti/PCIe/SSE2'
	Launched Version: 1.7.10-Forge10.13.4.1614-1.7.10
	LWJGL: 2.9.1
	OpenGL: GeForce GTX 1660 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 417.98, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: �������� (�й�)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by Ruchian** [comment]
You're at the very least missing [LambdaLib](https://www.curseforge.com/minecraft/mc-mods/lambdalib/files/2321336)

**Comment by zeldacl** [comment]
Yes, missing LambdaLib 1.2.3
