### ISSUE TITLE
[Bug] 玩家上线时或是传送完成时 经常会出现fatal error后掉线

### ISSUE THREAD

**Issue by ShigureYuki** [LambdaInnovation/AcademyCraft#823]
如题 玩家上线后或者当玩家使用/tp等指令传送完成时 经常会出现fatal error然后掉线
掉线后再次登录依然有可能出现此问题 但是重复多次登录却仍能正常登录游戏并游玩一段时间直至下一次fatal error并掉线
从debug.log以及客户端crash-report.txt的文本可以发现有academycraft
这是服务器端debug.log的部分文本
[11:36:45] [Server thread/INFO] []: [BanItem] 检查了玩家 Yuki 的 2 个背包
[11:36:45] [Server thread/INFO] []: [BanItem] 未发现任何禁用物品
[11:36:47] [Server thread/ERROR] [FML]: FMLIndexedMessageCodec exception caught
java.lang.NullPointerException: null
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770) ~[guava-21.0.jar:?]
	at com.google.common.collect.SingletonImmutableList.<init>(SingletonImmutableList.java:38) ~[guava-21.0.jar:?]
	at com.google.common.collect.ImmutableList.of(ImmutableList.java:93) ~[guava-21.0.jar:?]
	at net.minecraftforge.fml.common.network.FMLOutboundHandler$OutboundTarget$3.selectNetworks(FMLOutboundHandler.java:120) ~[FMLOutboundHandler$OutboundTarget$3.class:git-CatServer-1.12.2-3c5e7d0]
	at net.minecraftforge.fml.common.network.FMLOutboundHandler.write(FMLOutboundHandler.java:378) ~[FMLOutboundHandler.class:git-CatServer-1.12.2-3c5e7d0]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:111) ~[MessageToMessageEncoder.class:4.1.9.Final]
	at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[MessageToMessageCodec.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032) ~[DefaultChannelPipeline.class:4.1.9.Final]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296) ~[AbstractChannel.class:4.1.9.Final]
	at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendToAllAround(SimpleNetworkWrapper.java:264) [SimpleNetworkWrapper.class:git-CatServer-1.12.2-3c5e7d0]
	at cn.lambdalib2.s11n.network.NetworkMessage.sendToAllAround(NetworkMessage.java:114) [NetworkMessage.class:?]
	at cn.academy.block.tileentity.TileReceiverBase.func_73660_a(TileReceiverBase.java:38) [TileReceiverBase.class:?]
	at cn.academy.block.tileentity.TileImagFusor.func_73660_a(TileImagFusor.java:109) [TileImagFusor.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:2107) [amu.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:857) [oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:908) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:472) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:778) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:632) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
[11:36:47] [Server thread/ERROR] [FML]: SimpleChannelHandlerWrapper exception
java.lang.NullPointerException: null
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770) ~[guava-21.0.jar:?]
	at com.google.common.collect.SingletonImmutableList.<init>(SingletonImmutableList.java:38) ~[guava-21.0.jar:?]
	at com.google.common.collect.ImmutableList.of(ImmutableList.java:93) ~[guava-21.0.jar:?]
	at net.minecraftforge.fml.common.network.FMLOutboundHandler$OutboundTarget$3.selectNetworks(FMLOutboundHandler.java:120) ~[FMLOutboundHandler$OutboundTarget$3.class:git-CatServer-1.12.2-3c5e7d0]
	at net.minecraftforge.fml.common.network.FMLOutboundHandler.write(FMLOutboundHandler.java:378) ~[FMLOutboundHandler.class:git-CatServer-1.12.2-3c5e7d0]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:111) ~[MessageToMessageEncoder.class:4.1.9.Final]
	at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[MessageToMessageCodec.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032) ~[DefaultChannelPipeline.class:4.1.9.Final]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296) ~[AbstractChannel.class:4.1.9.Final]
	at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendToAllAround(SimpleNetworkWrapper.java:264) [SimpleNetworkWrapper.class:git-CatServer-1.12.2-3c5e7d0]
	at cn.lambdalib2.s11n.network.NetworkMessage.sendToAllAround(NetworkMessage.java:114) [NetworkMessage.class:?]
	at cn.academy.block.tileentity.TileReceiverBase.func_73660_a(TileReceiverBase.java:38) [TileReceiverBase.class:?]
	at cn.academy.block.tileentity.TileImagFusor.func_73660_a(TileImagFusor.java:109) [TileImagFusor.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:2107) [amu.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:857) [oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:908) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:472) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:778) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:632) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
[11:36:47] [Server thread/ERROR] [FML]: SimpleChannelHandlerWrapper exception
java.lang.NullPointerException: null
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770) ~[guava-21.0.jar:?]
	at com.google.common.collect.SingletonImmutableList.<init>(SingletonImmutableList.java:38) ~[guava-21.0.jar:?]
	at com.google.common.collect.ImmutableList.of(ImmutableList.java:93) ~[guava-21.0.jar:?]
	at net.minecraftforge.fml.common.network.FMLOutboundHandler$OutboundTarget$3.selectNetworks(FMLOutboundHandler.java:120) ~[FMLOutboundHandler$OutboundTarget$3.class:git-CatServer-1.12.2-3c5e7d0]
	at net.minecraftforge.fml.common.network.FMLOutboundHandler.write(FMLOutboundHandler.java:378) ~[FMLOutboundHandler.class:git-CatServer-1.12.2-3c5e7d0]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:111) ~[MessageToMessageEncoder.class:4.1.9.Final]
	at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[MessageToMessageCodec.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032) ~[DefaultChannelPipeline.class:4.1.9.Final]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296) ~[AbstractChannel.class:4.1.9.Final]
	at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendToAllAround(SimpleNetworkWrapper.java:264) [SimpleNetworkWrapper.class:git-CatServer-1.12.2-3c5e7d0]
	at cn.lambdalib2.s11n.network.NetworkMessage.sendToAllAround(NetworkMessage.java:114) [NetworkMessage.class:?]
	at cn.academy.block.tileentity.TileReceiverBase.func_73660_a(TileReceiverBase.java:38) [TileReceiverBase.class:?]
	at cn.academy.block.tileentity.TileImagFusor.func_73660_a(TileImagFusor.java:109) [TileImagFusor.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:2107) [amu.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:857) [oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:908) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:472) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:778) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:632) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
[11:36:47] [Server thread/ERROR] [FML]: SimpleChannelHandlerWrapper exception
java.lang.NullPointerException: null
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770) ~[guava-21.0.jar:?]
	at com.google.common.collect.SingletonImmutableList.<init>(SingletonImmutableList.java:38) ~[guava-21.0.jar:?]
	at com.google.common.collect.ImmutableList.of(ImmutableList.java:93) ~[guava-21.0.jar:?]
	at net.minecraftforge.fml.common.network.FMLOutboundHandler$OutboundTarget$3.selectNetworks(FMLOutboundHandler.java:120) ~[FMLOutboundHandler$OutboundTarget$3.class:git-CatServer-1.12.2-3c5e7d0]
	at net.minecraftforge.fml.common.network.FMLOutboundHandler.write(FMLOutboundHandler.java:378) ~[FMLOutboundHandler.class:git-CatServer-1.12.2-3c5e7d0]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:111) ~[MessageToMessageEncoder.class:4.1.9.Final]
	at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[MessageToMessageCodec.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032) ~[DefaultChannelPipeline.class:4.1.9.Final]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296) ~[AbstractChannel.class:4.1.9.Final]
	at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendToAllAround(SimpleNetworkWrapper.java:264) [SimpleNetworkWrapper.class:git-CatServer-1.12.2-3c5e7d0]
	at cn.lambdalib2.s11n.network.NetworkMessage.sendToAllAround(NetworkMessage.java:114) [NetworkMessage.class:?]
	at cn.academy.block.tileentity.TileReceiverBase.func_73660_a(TileReceiverBase.java:38) [TileReceiverBase.class:?]
	at cn.academy.block.tileentity.TileImagFusor.func_73660_a(TileImagFusor.java:109) [TileImagFusor.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:2107) [amu.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:857) [oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:908) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:472) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:778) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:632) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
[11:36:47] [Netty Server IO #1/ERROR] [FML]: There was a critical exception handling a packet on channel lambdalib2
java.lang.NullPointerException: null
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770) ~[guava-21.0.jar:?]
	at com.google.common.collect.SingletonImmutableList.<init>(SingletonImmutableList.java:38) ~[guava-21.0.jar:?]
	at com.google.common.collect.ImmutableList.of(ImmutableList.java:93) ~[guava-21.0.jar:?]
	at net.minecraftforge.fml.common.network.FMLOutboundHandler$OutboundTarget$3.selectNetworks(FMLOutboundHandler.java:120) ~[FMLOutboundHandler$OutboundTarget$3.class:git-CatServer-1.12.2-3c5e7d0]
	at net.minecraftforge.fml.common.network.FMLOutboundHandler.write(FMLOutboundHandler.java:378) ~[FMLOutboundHandler.class:git-CatServer-1.12.2-3c5e7d0]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:111) ~[MessageToMessageEncoder.class:4.1.9.Final]
	at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[MessageToMessageCodec.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032) ~[DefaultChannelPipeline.class:4.1.9.Final]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296) ~[AbstractChannel.class:4.1.9.Final]
	at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendToAllAround(SimpleNetworkWrapper.java:264) ~[SimpleNetworkWrapper.class:git-CatServer-1.12.2-3c5e7d0]
	at cn.lambdalib2.s11n.network.NetworkMessage.sendToAllAround(NetworkMessage.java:114) ~[NetworkMessage.class:?]
	at cn.academy.block.tileentity.TileReceiverBase.func_73660_a(TileReceiverBase.java:38) ~[TileReceiverBase.class:?]
	at cn.academy.block.tileentity.TileImagFusor.func_73660_a(TileImagFusor.java:109) ~[TileImagFusor.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:2107) ~[amu.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:857) ~[oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:908) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:472) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:778) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:632) ~[MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
[11:36:47] [Netty Server IO #1/ERROR] [FML]: Network Disconnect: A fatal error has occurred, this connection is terminated
[11:36:52] [Server thread/INFO] [net.minecraft.network.NetHandlerPlayServer]: Yuki lost connection: A fatal error has occurred, this connection is terminated
[11:36:52] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Yuki left the game
其中可以发现有
cn.lambdalib2.s11n.network.NetworkMessage.sendToAllAround(NetworkMessage.java:114) [NetworkMessage.class:?]
	at cn.academy.block.tileentity.TileReceiverBase.func_73660_a(TileReceiverBase.java:38) [TileReceiverBase.class:?]
	at cn.academy.block.tileentity.TileImagFusor.func_73660_a(TileImagFusor.java:109) [TileImagFusor.class:?]
cn.lambdalib2.s11n.network.NetworkMessage.sendToAllAround(NetworkMessage.java:114) [NetworkMessage.class:?]
	at cn.academy.block.tileentity.TileReceiverBase.func_73660_a(TileReceiverBase.java:38) [TileReceiverBase.class:?]
	at cn.academy.block.tileentity.TileImagFusor.func_73660_a(TileImagFusor.java:109) [TileImagFusor.class:?]

 - 服务器OS: Windows Server 2016:amd64:10.0
 - MC Version and Forge version: 14.23.5.2848 for Minecraft 1.12.2
 - Version 1.1.2

**Comment by Ruchian** [comment]
It doesn't seem to be caused by AcademyCraft nor LambdaLib, though LambdaLib did error as well due to this.

This likely only happens on your CatServer setup. (not in single player)
I think it maybe a bad plugin. What plugins do you use?

Also. https://github.com/CatServer/CatServer

**Comment by ShigureYuki** [comment]
> (Sorry, I am not chinese. I am just looking at it and replying because almost no one looks at this github's issues board anymore.)
> 
> From what I can tell here is that it doesn't look like the issue you're experiencing is caused by AcademyCraft.
> LambdaLib an error in response to what caused your issue, but it didn't start it.
> 
> The issue you're experiencing is likely caused by something uniquely found on your CatServer setup, and I cannot say why.
> Could you post the full "debug.log" on https://gist.github.com/ or something similar and post the link to it here?
> 
> You may also want to inform https://github.com/CatServer/CatServer



> (Sorry, I am not chinese. I am just looking at it and replying because almost no one looks at this github's issues board anymore.)
> 
> From what I can tell here is that it doesn't look like the issue you're experiencing is caused by AcademyCraft.
> LambdaLib an error in response to what caused your issue, but it didn't start it.
> 
> The issue you're experiencing is likely caused by something uniquely found on your CatServer setup, and I cannot say why.
> Could you post the full "debug.log" on https://gist.github.com/ or something similar and post the link to it here?
> 
> You may also want to inform https://github.com/CatServer/CatServer

Thanks for your reply. I'm afraid that I could not post the full debug.log because it has been a long time since I last found it. Fortunately I have latest.log at that time and I can post it here
[2019-09-21-2.log](https://github.com/LambdaInnovation/AcademyCraft/files/3702256/2019-09-21-2.log)
Let me discribe this issue again. When players log in the game or complete executing teleport command like /tp or /spawn, they would often get disconnected and the game client would display "A fatal error has occurred, this connection is terminated". They can continue to try to log in the game, then meet the same issue and disconnect again. However, by attempting loging in the game over and over again, they can still get logged in and play normally just like this issue has never happened before until next disconnection.
I'm sure only AcademyCraft need LambdaLib in my mod list.
To my surprise, I tried to remove AcademyCraft related blocks like Imagfusor(machine) in the chunks which I always played in and the frequency of disconnection actually dropped.

**Comment by zeldacl** [comment]
More info [https://www.minecraftforge.net/forum/topic/72198-1122-packethandler-is-annoying-like-a-fly/](https://www.minecraftforge.net/forum/topic/72198-1122-packethandler-is-annoying-like-a-fly/)
