### ISSUE TITLE
[Bug] 游戏启动时崩溃 Game crashed

### ISSUE THREAD

**Issue by Jinzero0** [LambdaInnovation/AcademyCraft#824]
Minecraft 1.12.2
Forge 14.23.5.2847

---- Minecraft Crash Report ----

WARNING: coremods are present:
  CorePlugin (AcademyCraft-1.1.2.jar)
Contact their authors BEFORE contacting forge

// On the bright side, I bought you a teddy bear!

Time: 10/1/19 7:56 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Minecraft Forge (forge)
Caused by: java.lang.IndexOutOfBoundsException: 0
	at scala.collection.mutable.ResizableArray$class.apply(ResizableArray.scala:43)
	at scala.collection.mutable.ArrayBuffer.apply(ArrayBuffer.scala:48)
	at cn.academy.item.MediaItem.getMedia(MediaItem.java:95)
	at cn.academy.item.MediaItem.func_77653_i(MediaItem.java:71)
	at net.minecraft.item.ItemStack.func_82833_r(ItemStack.java:617)
	at net.minecraft.item.ItemStack.func_151000_E(ItemStack.java:1048)
	at net.minecraft.stats.StatList.func_75925_c(StatList.java:201)
	at net.minecraft.stats.StatList.reinit(StatList.java:346)
	at net.minecraftforge.common.ForgeModContainer.mappingChanged(ForgeModContainer.java:586)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at net.minecraftforge.fml.common.Loader.fireRemapEvent(Loader.java:916)
	at net.minecraftforge.registries.GameData.freezeData(GameData.java:259)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:758)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_221, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 124480800 bytes (118 MB) / 320593920 bytes (305 MB) up to 4260102144 bytes (4062 MB)
	JVM Flags: 2 total; -Xincgc -Xmx4096M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State   | ID             | Version      | Source                        | Signature |
	|:------- |:-------------- |:------------ |:----------------------------- |:--------- |
	| LCHIJA  | minecraft      | 1.12.2       | minecraft.jar                 | None      |
	| LCHIJA  | mcp            | 9.42         | minecraft.jar                 | None      |
	| LCHIJA  | FML            | 8.0.99.99    | forge-1.12.2-14.23.5.2847.jar | None      |
	| LCHIJAE | forge          | 14.23.5.2847 | forge-1.12.2-14.23.5.2847.jar | None      |
	| LCHIJA  | LambdaLib|Core | 0.1.9        | minecraft.jar                 | None      |
	| LCHIJA  | lambdalib2     | 0.1.9        | AcademyCraft-1.1.2.jar        | None      |
	| LCHIJA  | academy        | 1.1.2        | AcademyCraft-1.1.2.jar        | None      |

	Loaded coremods (and transformers): 
CorePlugin (AcademyCraft-1.1.2.jar)
  cn.lambdalib2.render.mc.PipelineTransformer
  cn.lambdalib2.registry.impl.RegistryTransformer
	GL info: ' Vendor: 'Intel' Version: '4.5.0 - Build 23.20.16.4974' Renderer: 'Intel(R) HD Graphics 615'

**Comment by Ruchian** [comment]
cannot reproduce

![afbeelding](https://user-images.githubusercontent.com/24900404/66125718-09236a00-e5e8-11e9-9550-6cb1a30af228.png)

I completely copied your modpack setup and it runs fine over here.
You may need to reinstall things to fix this. (start from a clean folder)
