### ISSUE TITLE
[Bug]Game breakdown

### ISSUE THREAD

**Issue by shuxinkong** [LambdaInnovation/AcademyCraft#827]
[17:55:11] [main/INFO] [STDERR]: [mod.lucky.structure.SchematicStructure:readFromFile:78]: 	at net.minecraft.client.main.Main.main(SourceFile:123)

[17:55:11] [main/INFO] [STDERR]: [mod.lucky.structure.SchematicStructure:readFromFile:78]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

[17:55:11] [main/INFO] [STDERR]: [mod.lucky.structure.SchematicStructure:readFromFile:78]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)

[17:55:11] [main/INFO] [STDERR]: [mod.lucky.structure.SchematicStructure:readFromFile:78]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

[17:55:11] [main/INFO] [STDERR]: [mod.lucky.structure.SchematicStructure:readFromFile:78]: 	at java.lang.reflect.Method.invoke(Unknown Source)

[17:55:11] [main/INFO] [STDERR]: [mod.lucky.structure.SchematicStructure:readFromFile:78]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)

[17:55:11] [main/INFO] [STDERR]: [mod.lucky.structure.SchematicStructure:readFromFile:78]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

[17:55:11] [main/INFO] [STDERR]: [mod.lucky.resources.ResourceStructures:process:29]: Lucky Block: Error reading 'structures.txt'

[17:55:11] [main/INFO] [STDERR]: [mod.lucky.resources.ResourceStructures:process:30]: java.lang.NullPointerException

[17:55:11] [main/INFO] [STDERR]: [mod.lucky.resources.ResourceStructures:process:30]: 	at mod.lucky.structure.SchematicStructure.readFromFile(SchematicStructure.java:82)

[17:55:11] [main/INFO] [STDERR]: [mod.lucky.resources.ResourceStructures:process:30]: 	at mod.lucky.resources.ResourceStructures.process(ResourceStructures.java:22)

[17:55:11] [main/INFO] [STDERR]: [mod.lucky.resources.ResourceStructures:process:30]: 	at mod.lucky.resources.loader.BaseLoader.loadResource(BaseLoader.java:29)

[17:55:11] [main/INFO] [STDERR]: [mod.lucky.resources.ResourceStructures:process:30]: 	at mod.lucky.resources.loader.PluginLoader.loadResource(PluginLoader.java:124)

[17:55:11] [main/INFO] [STDERR]: [mod.lucky.resources.ResourceStructures:process:30]: 	at mod.lucky.resources.loader.ResourceLoader.loadAllResources(ResourceLoader.java:80)

[17:55:11] [main/INFO] [STDERR]: [mod.lucky.resources.ResourceStructures:process:30]: 	at mod.lucky.Lucky.<init>(Lucky.java:88)

[17:55:11] [main/INFO] [STDERR]: [mod.lucky.resources.ResourceStructures:process:30]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

[17:55:11] [main/INFO] [STDERR]: [mod.lucky.resources.ResourceStructures:process:30]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)

[17:55:11] [main/INFO] [STDERR]: [mod.lucky.resources.ResourceStructures:process:30]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)

[17:55:11] [main/INFO] [STDERR]: [mod.lucky.resources.ResourceStructures:process:30]: 	at java.lang.reflect.Constructor.newInstance(Unknown Source)

[17:55:11] [main/INFO] [STDERR]: [mod.lucky.resources.ResourceStructures:process:30]: 	at java.lang.Class.newInstance(Unknown Source)

[17:55:11] [main/INFO] [STDERR]: [mod.lucky.resources.ResourceStructures:process:30]: 	at net.minecraftforge.fml.common.ILanguageAdapter$JavaAdapter.getNewInstance(ILanguageAdapter.java:193)

[17:55:11] [main/INFO] [STDERR]: [mod.lucky.resources.ResourceStructures:process:30]: 	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:577)

[17:55:11] [main/INFO] [STDERR]: [mod.lucky.resources.ResourceStructures:process:30]: 	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)

[17:55:11] [main/INFO] [STDERR]: [mod.lucky.resources.ResourceStructures:process:30]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

[17:55:11] [main/INFO] [STDERR]: [mod.lucky.resources.ResourceStructures:process:30]: 	at java.lang.reflect.Method.invoke(Unknown Source)

[17:55:11] [main/INFO] [STDERR]: [mod.lucky.resources.ResourceStructures:process:30]: 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)

[17:55:11] [main/INFO] [STDERR]: [mod.lucky.resources.ResourceStructures:process:30]: 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)

[17:55:11] [main/INFO] [STDERR]: [mod.lucky.resources.ResourceStructures:process:30]: 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)

[17:55:11] [main/INFO] [STDERR]: [mod.lucky.resources.ResourceStructures:process:30]: 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)

[17:55:11] [main/INFO] [STDERR]: [mod.lucky.resources.ResourceStructures:process:30]: 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)

[17:55:11] [main/INFO] [STDERR]: [mod.lucky.resources.ResourceStructures:process:30]: 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)

[17:55:11] [main/INFO] [STDERR]: [mod.lucky.resources.ResourceStructures:process:30]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)

[17:55:11] [main/INFO] [STDERR]: [mod.lucky.resources.ResourceStructures:process:30]: 	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:278)

[17:55:11] [main/INFO] [STDERR]: [mod.lucky.resources.ResourceStructures:process:30]: 	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:256)

[17:55:11] [main/INFO] [STDERR]: [mod.lucky.resources.ResourceStructures:process:30]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

[17:55:11] [main/INFO] [STDERR]: [mod.lucky.resources.ResourceStructures:process:30]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)

[17:55:11] [main/INFO] [STDERR]: [mod.lucky.resources.ResourceStructures:process:30]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

[17:55:11] [main/INFO] [STDERR]: [mod.lucky.resources.ResourceStructures:process:30]: 	at java.lang.reflect.Method.invoke(Unknown Source)

[17:55:11] [main/INFO] [STDERR]: [mod.lucky.resources.ResourceStructures:process:30]: 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)

[17:55:11] [main/INFO] [STDERR]: [mod.lucky.resources.ResourceStructures:process:30]: 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)

[17:55:11] [main/INFO] [STDERR]: [mod.lucky.resources.ResourceStructures:process:30]: 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)

[17:55:11] [main/INFO] [STDERR]: [mod.lucky.resources.ResourceStructures:process:30]: 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)

[17:55:11] [main/INFO] [STDERR]: [mod.lucky.resources.ResourceStructures:process:30]: 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)

[17:55:11] [main/INFO] [STDERR]: [mod.lucky.resources.ResourceStructures:process:30]: 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)

[17:55:11] [main/INFO] [STDERR]: [mod.lucky.resources.ResourceStructures:process:30]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)

[17:55:11] [main/INFO] [STDERR]: [mod.lucky.resources.ResourceStructures:process:30]: 	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)

[17:55:11] [main/INFO] [STDERR]: [mod.lucky.resources.ResourceStructures:process:30]: 	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:568)

[17:55:11] [main/INFO] [STDERR]: [mod.lucky.resources.ResourceStructures:process:30]: 	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:231)

[17:55:11] [main/INFO] [STDERR]: [mod.lucky.resources.ResourceStructures:process:30]: 	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)

[17:55:11] [main/INFO] [STDERR]: [mod.lucky.resources.ResourceStructures:process:30]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)

[17:55:11] [main/INFO] [STDERR]: [mod.lucky.resources.ResourceStructures:process:30]: 	at net.minecraft.client.main.Main.main(SourceFile:123)

[17:55:11] [main/INFO] [STDERR]: [mod.lucky.resources.ResourceStructures:process:30]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

[17:55:11] [main/INFO] [STDERR]: [mod.lucky.resources.ResourceStructures:process:30]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)

[17:55:11] [main/INFO] [STDERR]: [mod.lucky.resources.ResourceStructures:process:30]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

[17:55:11] [main/INFO] [STDERR]: [mod.lucky.resources.ResourceStructures:process:30]: 	at java.lang.reflect.Method.invoke(Unknown Source)

[17:55:11] [main/INFO] [STDERR]: [mod.lucky.resources.ResourceStructures:process:30]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)

[17:55:11] [main/INFO] [STDERR]: [mod.lucky.resources.ResourceStructures:process:30]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

[17:55:39] [main/INFO] [STDERR]: [com.lycanitesmobs.LycanitesMobs:printWarning:293]: [LycanitesMobs] [WARNING] [] Unable to find the creature type: serpix when load creature: serpix

[17:55:39] [main/INFO] [STDERR]: [com.lycanitesmobs.LycanitesMobs:printWarning:293]: [LycanitesMobs] [WARNING] [] Unable to find the creature type: gorger when load creature: gorger

[17:55:41] [main/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.RegistryEvent$Register@52ef98d8:

[17:55:41] [main/ERROR] [FML]: Index: 19 Listeners:

[17:55:41] [main/ERROR] [FML]: 0: NORMAL

[17:55:41] [main/ERROR] [FML]: 1: net.minecraftforge.fml.common.eventhandler.EventBus$1@5535b0c0

[17:55:41] [main/ERROR] [FML]: 2: net.minecraftforge.fml.common.eventhandler.EventBus$1@7b32dbe6

[17:55:41] [main/ERROR] [FML]: 3: net.minecraftforge.fml.common.eventhandler.EventBus$1@1be10a5

[17:55:41] [main/ERROR] [FML]: 4: net.minecraftforge.fml.common.eventhandler.EventBus$1@47b4c2

[17:55:41] [main/ERROR] [FML]: 5: net.minecraftforge.fml.common.eventhandler.EventBus$1@788ca7ba

[17:55:41] [main/ERROR] [FML]: 6: net.minecraftforge.fml.common.eventhandler.EventBus$1@150cbea6

[17:55:41] [main/ERROR] [FML]: 7: net.minecraftforge.fml.common.eventhandler.EventBus$1@64c6af9a

[17:55:41] [main/ERROR] [FML]: 8: net.minecraftforge.fml.common.eventhandler.EventBus$1@599ae664

[17:55:41] [main/ERROR] [FML]: 9: net.minecraftforge.fml.common.eventhandler.EventBus$1@44b63b9a

[17:55:41] [main/ERROR] [FML]: 10: net.minecraftforge.fml.common.eventhandler.EventBus$1@34bf4424

[17:55:41] [main/ERROR] [FML]: 11: net.minecraftforge.fml.common.eventhandler.EventBus$1@65549756

[17:55:41] [main/ERROR] [FML]: 12: net.minecraftforge.fml.common.eventhandler.EventBus$1@6bf3e45e

[17:55:41] [main/ERROR] [FML]: 13: net.minecraftforge.fml.common.eventhandler.EventBus$1@1e6c7851

[17:55:41] [main/ERROR] [FML]: 14: net.minecraftforge.fml.common.eventhandler.EventBus$1@50bc81dc

[17:55:41] [main/ERROR] [FML]: 15: net.minecraftforge.fml.common.eventhandler.EventBus$1@111342ba

[17:55:41] [main/ERROR] [FML]: 16: net.minecraftforge.fml.common.eventhandler.EventBus$1@65b685d2

[17:55:41] [main/ERROR] [FML]: 17: net.minecraftforge.fml.common.eventhandler.EventBus$1@1865d7c5

[17:55:41] [main/ERROR] [FML]: 18: net.minecraftforge.fml.common.eventhandler.EventBus$1@2c630774

[17:55:41] [main/ERROR] [FML]: 19: net.minecraftforge.fml.common.eventhandler.EventBus$1@27ee86d0

[17:55:41] [main/ERROR] [FML]: 20: net.minecraftforge.fml.common.eventhandler.EventBus$1@76a70fea

[17:55:41] [main/ERROR] [FML]: 21: net.minecraftforge.fml.common.eventhandler.EventBus$1@404a3504

[17:55:41] [main/ERROR] [FML]: 22: net.minecraftforge.fml.common.eventhandler.EventBus$1@74a6d2de

[17:55:41] [main/ERROR] [FML]: 23: net.minecraftforge.fml.common.eventhandler.EventBus$1@272d029c

[17:55:41] [main/ERROR] [FML]: 24: net.minecraftforge.fml.common.eventhandler.EventBus$1@693b81cc

[17:55:41] [main/ERROR] [FML]: 25: net.minecraftforge.fml.common.eventhandler.EventBus$1@78486bfa

[17:55:41] [main/ERROR] [FML]: 26: net.minecraftforge.fml.common.eventhandler.EventBus$1@3a3a760f

[17:55:41] [main/ERROR] [FML]: 27: LOWEST

[17:55:41] [main/ERROR] [FML]: 28: net.minecraftforge.fml.common.eventhandler.EventBus$1@754caa36

[17:55:41] [main/ERROR] [FML]: 29: net.minecraftforge.fml.common.eventhandler.EventBus$1@404c70b2

**Comment by zeldacl** [comment]
The error is "Lucky Block: Error reading 'structures.txt'", please check the Lucky Block mod
