### ISSUE TITLE
[Bug] 玩家点击UI客户端崩溃，空指针异常

### ISSUE THREAD

**Issue by ColorfulGhost** [LambdaInnovation/AcademyCraft#837]
```
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 2020-01-13 14:15:32 CST
Description: Updating screen events

java.lang.NullPointerException
    at cn.academy.core.client.ui.WirelessPage$$anonfun$apply$5.apply$mcV$sp(TechUI.scala:705)
    at cn.academy.core.client.ui.WirelessPage$$anonfun$apply$5.apply(TechUI.scala:705)
    at cn.academy.core.client.ui.WirelessPage$$anonfun$apply$5.apply(TechUI.scala:705)
    at cn.lambdalib2.cgui.RichWidget$$anonfun$listens$extension2$1.apply(ScalaCGUI.scala:31)
    at cn.lambdalib2.cgui.RichWidget$$anonfun$listens$extension2$1.apply(ScalaCGUI.scala:31)
    at cn.lambdalib2.cgui.RichWidget$$anon$1.handleEvent(ScalaCGUI.scala:19)
    at cn.lambdalib2.cgui.event.GuiEventBus.postEvent(GuiEventBus.java:74)
    at cn.lambdalib2.cgui.CGui.postMouseEv(CGui.java:173)
    at cn.lambdalib2.cgui.CGui.mouseClicked(CGui.java:194)
    at cn.lambdalib2.cgui.CGuiScreenContainer.mouseClicked(CGuiScreenContainer.java:67)
    at net.minecraft.client.gui.GuiScreen.handleMouseInput(GuiScreen.java:533)
    at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:501)
    at net.minecraft.client.Minecraft.runTick(Minecraft.java:1759)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1098)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Affected screen --
  Screen name: cn.academy.core.client.ui.TechUI.ContainerUI

```

**Comment by Ruchian** [comment]
duplicate of #831 
Which is interesting.
