### ISSUE TITLE
[Bug]CatServer端技能超电磁炮无法使用

### ISSUE THREAD

**Issue by starxjys** [LambdaInnovation/AcademyCraft#839]
如题，报错：
`[19:12:02] [Server thread/ERROR]: Error during network message.
java.lang.reflect.InvocationTargetException: null
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_241]
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241]
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_241]
at cn.lambdalib2.s11n.network.NetworkMessage$2.invoke(NetworkMessage.java:230) ~[NetworkMessage$2.class:?]
at cn.lambdalib2.s11n.network.NetworkMessage.invokeListener(NetworkMessage.java:157) ~[NetworkMessage.class:?]
at cn.lambdalib2.s11n.network.NetworkMessage.processMessage(NetworkMessage.java:138) ~[NetworkMessage.class:?]
at cn.lambdalib2.s11n.network.NetworkMessage.access$000(NetworkMessage.java:54) ~[NetworkMessage.class:?]
at cn.lambdalib2.s11n.network.NetworkMessage$Handler.lambda$onMessage$0(NetworkMessage.java:381) ~[NetworkMessage$Handler.class:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_241]
at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_241]
at net.minecraft.util.Util.runTask(Util.java:529) [h.class:?]
at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:843) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:473) [nz.class:?]
at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:780) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:634) [MinecraftServer.class:?]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
Caused by: java.lang.NoSuchMethodError: net.minecraft.entity.EntityLivingBase.func_189653_aC()Lnet/minecraft/util/math/Vec2f;
at cn.paindar.academymonster.playerskill.electromaster.Railgun.selectTargets(Railgun.java:147) ~[Railgun.class:?]
at cn.paindar.academymonster.playerskill.electromaster.Railgun.performServer(Railgun.java:205) ~[Railgun.class:?]
at cn.paindar.academymonster.playerskill.electromaster.Railgun.consumeItemAtServer(Railgun.java:336) ~[Railgun.class:?]
... 17 more`
版本：AcademyCraft-1.1.2.jar

**Comment by starxjys** [comment]
在使用此技能时服务器后台刷报错，游戏中没有正常出现技能效果
Cat作者：不要在服务端调用客户端的方法ヽ(´ー`)ﾉ

**Comment by CarierxGroup** [comment]
我并没有问题，再下使用CatServer和Mohist这俩服务端都可以正常使用。
建议更新到最新版本看看。
