### ISSUE TITLE
[Invalid Resource] Crash on Tutorial

### ISSUE THREAD

**Issue by chocolat-cpu** [LambdaInnovation/AcademyCraft#861]
When I right click the Misaka item, my game crashes and says "Shutting down internal server..."

1. Installed LambdaLib2 1.12.2 and AcademyCraft 1.12.2
2. Loaded with forge
3. In a new world, right clicked terminal
4. Crashes

I assume the tutorial screen and GUI is supposed to open here but it just crashes

![image](https://user-images.githubusercontent.com/65203585/81627904-3382a480-93cd-11ea-85c8-fd4b520129fa.png)

 - Windows 10
 - 1.12.2-forge1.12.2-14.23.5.2857
 - AcademyCraft-Mod-1.12.2
 - LambdaLib2-0.1.7

---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  CorePlugin (LambdaLib2-0.1.7.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.10-1.12.2.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
Contact their authors BEFORE contacting forge

// I let you down. Sorry :(

Time: 5/11/20 9:14 PM
Description: Unexpected error

java.lang.RuntimeException: Invalid resource academy:tutorials/en_us/welcome.md
	at cn.lambdalib2.util.ResourceUtils.getResourceStream(ResourceUtils.java:14)
	at cn.academy.tutorial.ACTutorial.getContent(ACTutorial.java:66)
	at cn.academy.client.gui.GuiTutorial.renderInfo(GuiTutorial.java:136)
	at cn.academy.client.gui.GuiTutorial._build(GuiTutorial.java:407)
	at cn.academy.client.gui.GuiTutorial.rebuildList(GuiTutorial.java:437)
	at cn.academy.client.gui.GuiTutorial.initUI(GuiTutorial.java:337)
	at cn.academy.client.gui.GuiTutorial.<init>(GuiTutorial.java:171)
	at cn.academy.item.ItemTutorial.func_77659_a(ItemTutorial.java:31)
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:217)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187101_a(PlayerControllerMP.java:511)
	at net.optifine.override.PlayerControllerOF.func_187101_a(PlayerControllerOF.java:80)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1597)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2254)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2020)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1808)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.RuntimeException: Can't find resource academy:tutorials/en_us/welcome.md
	at cn.lambdalib2.util.Debug.assertNotNull(Debug.java:64)
	at cn.lambdalib2.util.ResourceUtils.getResourceStream(ResourceUtils.java:12)
	... 23 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at cn.lambdalib2.util.ResourceUtils.getResourceStream(ResourceUtils.java:14)
	at cn.academy.tutorial.ACTutorial.getContent(ACTutorial.java:66)
	at cn.academy.client.gui.GuiTutorial.renderInfo(GuiTutorial.java:136)
	at cn.academy.client.gui.GuiTutorial._build(GuiTutorial.java:407)
	at cn.academy.client.gui.GuiTutorial.rebuildList(GuiTutorial.java:437)
	at cn.academy.client.gui.GuiTutorial.initUI(GuiTutorial.java:337)
	at cn.academy.client.gui.GuiTutorial.<init>(GuiTutorial.java:171)
	at cn.academy.item.ItemTutorial.func_77659_a(ItemTutorial.java:31)
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:217)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187101_a(PlayerControllerMP.java:511)
	at net.optifine.override.PlayerControllerOF.func_187101_a(PlayerControllerOF.java:80)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1597)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2254)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2020)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['chocolat_'/223, l='MpServer', x=-147.98, y=76.00, z=63.41]]
	Chunk stats: MultiplayerChunkCache: 506, 506
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-176,64,76), Chunk: (at 0,4,12 in -11,4; contains blocks -176,0,64 to -161,255,79), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 2243 game time, 2243 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 93 total; [EntityCreeper['Creeper'/135, l='MpServer', x=-121.57, y=50.00, z=-0.52], EntityCreeper['Creeper'/136, l='MpServer', x=-121.50, y=50.00, z=-1.50], EntityZombie['Zombie'/137, l='MpServer', x=-117.50, y=50.00, z=8.50], EntityHenRhodeIslandRed['Rhode Island Red Hen'/138, l='MpServer', x=-113.31, y=63.00, z=4.61], EntitySpider['Spider'/139, l='MpServer', x=-121.04, y=49.00, z=9.04], EntitySkeleton['Skeleton'/140, l='MpServer', x=-120.62, y=49.00, z=7.97], EntityItem['item.item.minecraft:apple'/141, l='MpServer', x=-120.61, y=65.00, z=11.71], EntityCreeper['Creeper'/142, l='MpServer', x=-122.50, y=51.00, z=22.50], EntityCreeper['Creeper'/143, l='MpServer', x=-122.76, y=50.00, z=17.31], EntitySkeleton['Skeleton'/144, l='MpServer', x=-112.50, y=60.00, z=59.50], EntityCreeper['Creeper'/145, l='MpServer', x=-125.50, y=23.00, z=68.50], EntitySkeleton['Skeleton'/146, l='MpServer', x=-125.50, y=30.00, z=91.26], EntityHenRhodeIslandRed['Rhode Island Red Hen'/151, l='MpServer', x=-111.55, y=63.00, z=6.75], EntityWolf['Wolf'/152, l='MpServer', x=-113.41, y=64.00, z=8.65], EntityWolf['Wolf'/153, l='MpServer', x=-107.50, y=63.00, z=3.50], EntityHenRhodeIslandRed['Rhode Island Red Hen'/154, l='MpServer', x=-110.14, y=63.00, z=12.33], EntitySquid['Squid'/155, l='MpServer', x=-110.45, y=51.60, z=99.30], EntitySquid['Squid'/156, l='MpServer', x=-109.56, y=52.69, z=103.56], EntitySquid['Squid'/157, l='MpServer', x=-101.97, y=59.22, z=130.06], EntitySquid['Squid'/158, l='MpServer', x=-106.80, y=62.35, z=127.35], EntitySquid['Squid'/159, l='MpServer', x=-105.00, y=61.56, z=114.92], EntitySpider['Spider'/37, l='MpServer', x=-226.50, y=50.00, z=63.50], EntityZombie['Zombie'/168, l='MpServer', x=-81.50, y=29.00, z=64.11], EntityCreeper['Creeper'/169, l='MpServer', x=-91.51, y=26.69, z=71.50], EntityCreeper['Creeper'/170, l='MpServer', x=-84.50, y=29.00, z=64.50], EntityZombie['Zombie'/43, l='MpServer', x=-214.50, y=54.00, z=24.50], EntityCreeper['Creeper'/171, l='MpServer', x=-83.50, y=29.00, z=66.50], EntityCreeper['Creeper'/172, l='MpServer', x=-81.56, y=30.00, z=67.34], EntityCreeper['Creeper'/173, l='MpServer', x=-81.50, y=30.00, z=70.50], EntityBat['Bat'/174, l='MpServer', x=-83.50, y=45.00, z=98.75], EntityBat['Bat'/175, l='MpServer', x=-82.25, y=46.10, z=97.75], EntityZombie['Zombie'/48, l='MpServer', x=-210.50, y=55.00, z=68.50], EntityCreeper['Creeper'/176, l='MpServer', x=-81.50, y=33.00, z=99.50], EntitySkeleton['Skeleton'/49, l='MpServer', x=-204.50, y=20.00, z=27.50], EntityCreeper['Creeper'/177, l='MpServer', x=-86.50, y=33.00, z=99.50], EntityChickWyandotte['Wyandotte Chick'/50, l='MpServer', x=-203.41, y=63.00, z=17.56], EntityCreeper['Creeper'/178, l='MpServer', x=-86.37, y=33.00, z=97.80], EntitySkeleton['Skeleton'/51, l='MpServer', x=-202.50, y=23.00, z=47.50], EntityCreeper['Creeper'/52, l='MpServer', x=-194.58, y=30.00, z=42.81], EntitySquid['Squid'/180, l='MpServer', x=-87.79, y=61.96, z=104.57], EntityBat['Bat'/53, l='MpServer', x=-194.35, y=31.84, z=44.15], EntitySquid['Squid'/181, l='MpServer', x=-86.81, y=62.42, z=101.60], EntityBat['Bat'/54, l='MpServer', x=-194.94, y=30.85, z=43.66], EntitySquid['Squid'/182, l='MpServer', x=-88.62, y=59.14, z=127.72], EntityEnderman['Enderman'/55, l='MpServer', x=-201.32, y=23.00, z=49.71], EntityBat['Bat'/56, l='MpServer', x=-199.23, y=54.10, z=60.02], EntityZombie['Zombie'/57, l='MpServer', x=-200.50, y=57.00, z=58.50], EntitySkeleton['Skeleton'/185, l='MpServer', x=-76.50, y=32.00, z=21.50], EntitySpider['Spider'/58, l='MpServer', x=-206.50, y=59.00, z=54.50], EntitySkeleton['Skeleton'/186, l='MpServer', x=-77.50, y=32.00, z=23.50], EntityBat['Bat'/59, l='MpServer', x=-192.71, y=55.13, z=53.07], EntityBat['Bat'/60, l='MpServer', x=-190.71, y=53.28, z=55.76], EntityBat['Bat'/61, l='MpServer', x=-192.13, y=54.67, z=51.45], EntityZombie['Zombie'/189, l='MpServer', x=-71.50, y=31.00, z=61.50], EntityEweJacob['Jacob Ewe'/62, l='MpServer', x=-206.00, y=67.00, z=62.50], EntityCreeper['Creeper'/190, l='MpServer', x=-74.21, y=27.00, z=70.56], EntityEweJacob['Jacob Ewe'/63, l='MpServer', x=-202.27, y=68.00, z=51.93], EntityBat['Bat'/191, l='MpServer', x=-76.25, y=29.10, z=65.74], EntityEweJacob['Jacob Ewe'/64, l='MpServer', x=-202.06, y=73.00, z=61.73], EntityCreeper['Creeper'/192, l='MpServer', x=-79.50, y=30.00, z=69.50], EntitySkeleton['Skeleton'/65, l='MpServer', x=-203.50, y=18.00, z=71.50], EntityBat['Bat'/193, l='MpServer', x=-72.69, y=27.32, z=73.28], EntityItem['item.item.seeds'/66, l='MpServer', x=-201.88, y=60.00, z=77.13], EntitySkeleton['Skeleton'/194, l='MpServer', x=-70.50, y=14.00, z=81.50], EntityCreeper['Creeper'/67, l='MpServer', x=-206.50, y=56.00, z=76.50], EntityBat['Bat'/195, l='MpServer', x=-72.81, y=39.03, z=106.22], EntityCreeper['Creeper'/68, l='MpServer', x=-207.50, y=55.00, z=71.50], EntityBat['Bat'/196, l='MpServer', x=-71.65, y=39.93, z=104.30], EntityEweJacob['Jacob Ewe'/69, l='MpServer', x=-203.74, y=66.00, z=73.03], EntityCreeper['Creeper'/70, l='MpServer', x=-201.50, y=13.00, z=120.50], EntitySkeleton['Skeleton'/71, l='MpServer', x=-193.50, y=14.00, z=128.50], EntityHenWyandotte['Wyandotte Hen'/78, l='MpServer', x=-190.50, y=63.00, z=-0.35], EntityHenWyandotte['Wyandotte Hen'/79, l='MpServer', x=-189.31, y=63.00, z=4.36], EntitySquid['Squid'/80, l='MpServer', x=-186.40, y=57.38, z=105.25], EntitySkeleton['Skeleton'/81, l='MpServer', x=-184.50, y=15.00, z=127.50], EntitySquid['Squid'/82, l='MpServer', x=-187.89, y=57.39, z=125.05], EntitySquid['Squid'/83, l='MpServer', x=-185.25, y=53.73, z=128.17], EntityBat['Bat'/104, l='MpServer', x=-166.96, y=22.10, z=107.55], EntityZombie['Zombie'/105, l='MpServer', x=-171.50, y=20.00, z=115.50], EntityZombie['Zombie'/106, l='MpServer', x=-167.50, y=20.00, z=116.50], EntityCreeper['Creeper'/107, l='MpServer', x=-172.50, y=20.00, z=112.50], EntityCreeper['Creeper'/113, l='MpServer', x=-157.50, y=58.00, z=19.50], EntityItem['item.tile.sapling.birch'/114, l='MpServer', x=-148.64, y=79.00, z=71.71], EntityZombie['Zombie'/115, l='MpServer', x=-145.50, y=20.00, z=140.50], EntityCreeper['Creeper'/116, l='MpServer', x=-144.70, y=20.00, z=137.50], EntityCreeper['Creeper'/117, l='MpServer', x=-144.10, y=20.00, z=137.49], EntityPlayerSP['chocolat_'/223, l='MpServer', x=-147.98, y=76.00, z=63.41], EntitySkeleton['Skeleton'/122, l='MpServer', x=-129.50, y=50.00, z=3.50], EntitySkeleton['Skeleton'/123, l='MpServer', x=-129.50, y=50.00, z=5.50], EntityItem['item.tile.flower1.dandelion'/124, l='MpServer', x=-129.28, y=63.00, z=25.45], EntityItem['item.tile.flower1.dandelion'/125, l='MpServer', x=-130.40, y=63.00, z=25.13], EntityZombie['Zombie'/126, l='MpServer', x=-134.16, y=33.00, z=96.56], EntityZombie['Zombie'/127, l='MpServer', x=-132.78, y=33.00, z=97.56]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 692889448 bytes (660 MB) / 1207959552 bytes (1152 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 Optifine OptiFine_1.12.2_HD_U_F5 25 mods loaded, 25 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID             | Version           | Source                                             | Signature                                |
	|:------ |:-------------- |:----------------- |:-------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft      | 1.12.2            | minecraft.jar                                      | None                                     |
	| LCHIJA | mcp            | 9.42              | minecraft.jar                                      | None                                     |
	| LCHIJA | FML            | 8.0.99.99         | forge-1.12.2-14.23.5.2847.jar                      | None                                     |
	| LCHIJA | forge          | 14.23.5.2847      | forge-1.12.2-14.23.5.2847.jar                      | None                                     |
	| LCHIJA | LambdaLib|Core | 0.1.7             | minecraft.jar                                      | None                                     |
	| LCHIJA | openmodscore   | 0.12.2            | minecraft.jar                                      | None                                     |
	| LCHIJA | foamfixcore    | 7.7.4             | minecraft.jar                                      | None                                     |
	| LCHIJA | lambdalib2     | 0.1.7             | LambdaLib2-0.1.7.jar                               | None                                     |
	| LCHIJA | academy        | 1.1.0             | AcademyCraft-Mod-1.12.2.jar                        | None                                     |
	| LCHIJA | biomesoplenty  | 7.0.1.2444        | BiomesOPlenty-1.12.2-7.0.1.2444-universal.jar      | None                                     |
	| LCHIJA | craftstudioapi | 1.0.0             | CraftStudioAPI-universal-1.0.1.95-mc1.12-alpha.jar | None                                     |
	| LCHIJA | harvestcraft   | 1.12.2zb          | Pam's+HarvestCraft+1.12.2zg.jar                    | None                                     |
	| LCHIJA | animania       | 1.7.3             | animania-1.12.2-1.7.3.jar                          | None                                     |
	| LCHIJA | fcl            | 1.XII.53          | Fexcraft Common Library-1.XII.53.jar               | None                                     |
	| LCHIJA | tmt            | 1.8               | Fexcraft Common Library-1.XII.53.jar               | None                                     |
	| LCHIJA | foamfix        | 0.10.10-1.12.2    | foamfix-0.10.10-1.12.2.jar                         | None                                     |
	| LCHIJA | frsm           | 4.3.0             | FRSM-4.3.0.jar                                     | None                                     |
	| LCHIJA | inventorypets  | 2.0.5             | inventorypets-1.12-2.0.5.jar                       | None                                     |
	| LCHIJA | jei            | 4.15.0.293        | jei_1.12.2-4.15.0.293.jar                          | None                                     |
	| LCHIJA | mantle         | 1.12-1.3.3.55     | Mantle-1.12-1.3.3.55.jar                           | None                                     |
	| LCHIJA | llibrary       | 1.7.19            | llibrary-1.7.19-1.12.2.jar                         | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHIJA | mowziesmobs    | 1.5.4             | mowziesmobs-1.5.4.jar                              | None                                     |
	| LCHIJA | openmods       | 0.12.2            | OpenModsLib-1.12.2-0.12.2.jar                      | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| LCHIJA | openblocks     | 1.8.1             | OpenBlocks-1.12.2-1.8.1.jar                        | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| LCHIJA | tconstruct     | 1.12.2-2.13.0.183 | TConstruct-1.12.2-2.13.0.183.jar                   | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
CorePlugin (LambdaLib2-0.1.7.jar)
  cn.lambdalib2.render.mc.PipelineTransformer
  cn.lambdalib2.registry.impl.RegistryTransformer
Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.10-1.12.2.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
  openmods.core.OpenModsClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 445.87' Renderer: 'GeForce GTX 970/PCIe/SSE2'
	OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:FINISHED],[player_render_hook:FINISHED],[horse_null_fix:FINISHED]
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

	Launched Version: 1.12.2-forge1.12.2-14.23.5.2847
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 970/PCIe/SSE2 GL version 4.6.0 NVIDIA 445.87, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_F5
	OptiFine Build: 20191204-141934
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 445.87
	OpenGlRenderer: GeForce GTX 970/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8
I have the game in English (United States) in both client and in-game.

**Comment by chocolat-cpu** [comment]
*Downloaded this from 9minecraft.net as well the as the dependency.
If you are playing on 1.12.2 and download these two off of curseforge it should work fine.
![image](https://user-images.githubusercontent.com/65203585/81628920-fd92ef80-93cf-11ea-8d5d-37a877517d5e.png)
![image](https://user-images.githubusercontent.com/65203585/81628943-08e61b00-93d0-11ea-9cf6-c6072cf51fde.png)
