### ISSUE TITLE
Game crash when using Vector Manip(Deviation and Reflextion)

### ISSUE THREAD

**Issue by YouBugTv** [LambdaInnovation/AcademyCraft#862]
**If you use on of the 2 skils the game crashed**

1. Do /aim cat vecmanip
2. Do /aim learn_all
3. Use ether Vector Deviation or Reflextion

java.lang.IllegalStateException: Function is not supported
	at org.lwjgl.BufferChecks.checkFunctionAddress(BufferChecks.java:58)
	at org.lwjgl.opengl.GL33.glVertexAttribDivisor(GL33.java:377)
	at cn.lambdalib2.render.RenderPass.emitDrawCall(RenderPass.java:177)
	at cn.lambdalib2.render.RenderPass.dispatch(RenderPass.java:79)
	at cn.academy.ability.vanilla.vecmanip.client.effect.WaveEffectUI.render(WaveEffectUI.scala:120)
	at cn.academy.ability.vanilla.vecmanip.client.effect.WaveEffectUI.onFrame(WaveEffectUI.scala:75)
	at cn.academy.ability.vanilla.vecmanip.skill.VecDeviationContextC.onRenderOverlay(VecDeviation.scala:194)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_101_VecDeviationContextC_onRenderOverlay_RenderGameOverlayEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.client.GuiIngameForge.pre(GuiIngameForge.java:907)
	at net.minecraftforge.client.GuiIngameForge.renderCrosshairs(GuiIngameForge.java:217)
	at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:148)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1098)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at org.lwjgl.BufferChecks.checkFunctionAddress(BufferChecks.java:58)
	at org.lwjgl.opengl.GL33.glVertexAttribDivisor(GL33.java:377)
	at cn.lambdalib2.render.RenderPass.emitDrawCall(RenderPass.java:177)
	at cn.lambdalib2.render.RenderPass.dispatch(RenderPass.java:79)
	at cn.academy.ability.vanilla.vecmanip.client.effect.WaveEffectUI.render(WaveEffectUI.scala:120)
	at cn.academy.ability.vanilla.vecmanip.client.effect.WaveEffectUI.onFrame(WaveEffectUI.scala:75)
	at cn.academy.ability.vanilla.vecmanip.skill.VecDeviationContextC.onRenderOverlay(VecDeviation.scala:194)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_101_VecDeviationContextC_onRenderOverlay_RenderGameOverlayEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.client.GuiIngameForge.pre(GuiIngameForge.java:907)
	at net.minecraftforge.client.GuiIngameForge.renderCrosshairs(GuiIngameForge.java:217)
	at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:148)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['YouBugTv'/154, l='MpServer', x=202.62, y=64.00, z=121.68]]
	Chunk stats: MultiplayerChunkCache: 121, 121
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (211,64,119), Chunk: (at 3,4,7 in 13,7; contains blocks 208,0,112 to 223,255,127), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 3528 game time, 3528 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 149 total; [EntityCreeper['Creeper'/768, l='MpServer', x=238.50, y=24.00, z=151.50], EntityZombie['Zombie'/770, l='MpServer', x=217.50, y=13.00, z=119.50], EntityCreeper['Creeper'/1028, l='MpServer', x=214.00, y=23.00, z=125.50], EntityWitch['Witch'/774, l='MpServer', x=151.50, y=14.00, z=130.50], EntityItem['item.tile.doublePlant.syringa'/266, l='MpServer', x=144.90, y=64.00, z=69.13], EntityBat['Bat'/525, l='MpServer', x=149.47, y=26.10, z=73.75], EntitySquid['Squid'/1039, l='MpServer', x=257.55, y=61.11, z=160.53], EntitySquid['Squid'/1040, l='MpServer', x=261.99, y=62.20, z=155.59], EntitySquid['Squid'/1041, l='MpServer', x=262.34, y=61.52, z=151.35], EntitySquid['Squid'/1042, l='MpServer', x=264.42, y=62.38, z=151.37], EntitySquid['Squid'/23, l='MpServer', x=144.67, y=44.52, z=169.52], EntitySquid['Squid'/1058, l='MpServer', x=249.39, y=48.28, z=143.17], EntitySquid['Squid'/1059, l='MpServer', x=246.52, y=50.67, z=149.56], EntitySquid['Squid'/1060, l='MpServer', x=255.54, y=51.29, z=150.12], EntitySquid['Squid'/1061, l='MpServer', x=257.34, y=48.77, z=147.51], EntitySquid['Squid'/1066, l='MpServer', x=202.91, y=57.70, z=181.78], EntitySquid['Squid'/1067, l='MpServer', x=201.95, y=56.98, z=181.06], EntityItem['item.tile.doublePlant.syringa'/43, l='MpServer', x=146.51, y=64.00, z=69.13], EntityZombie['Zombie'/1323, l='MpServer', x=170.50, y=26.00, z=61.50], EntityCreeper['Creeper'/44, l='MpServer', x=158.41, y=14.00, z=131.17], EntityEnderman['Enderman'/556, l='MpServer', x=189.50, y=20.00, z=149.50], EntitySquid['Squid'/1068, l='MpServer', x=196.63, y=56.84, z=182.77], EntitySquid['Squid'/1070, l='MpServer', x=161.18, y=47.29, z=158.85], EntitySquid['Squid'/1071, l='MpServer', x=158.38, y=48.43, z=159.76], EntityCreeper['Creeper'/816, l='MpServer', x=165.50, y=25.00, z=161.50], EntitySquid['Squid'/1072, l='MpServer', x=164.60, y=45.43, z=156.97], EntitySkeleton['Skeleton'/1328, l='MpServer', x=213.30, y=23.00, z=125.50], EntitySquid['Squid'/1073, l='MpServer', x=164.44, y=47.71, z=149.94], EntityCreeper['Creeper'/819, l='MpServer', x=234.50, y=24.00, z=155.50], EntitySquid['Squid'/1077, l='MpServer', x=265.66, y=51.00, z=123.33], EntitySquid['Squid'/1078, l='MpServer', x=231.66, y=60.73, z=175.40], EntitySquid['Squid'/1080, l='MpServer', x=233.15, y=55.63, z=173.72], EntitySquid['Squid'/1081, l='MpServer', x=234.64, y=59.30, z=171.57], EntitySkeleton['Skeleton'/320, l='MpServer', x=208.50, y=24.00, z=129.50], EntitySquid['Squid'/1090, l='MpServer', x=194.45, y=48.96, z=90.06], EntitySquid['Squid'/1091, l='MpServer', x=191.09, y=47.47, z=90.69], EntitySquid['Squid'/1092, l='MpServer', x=191.43, y=46.20, z=87.00], EntityZombie['Zombie'/69, l='MpServer', x=162.76, y=17.00, z=80.48], EntitySquid['Squid'/1093, l='MpServer', x=192.89, y=47.13, z=92.81], EntityZombie['Zombie'/1349, l='MpServer', x=178.50, y=23.00, z=142.50], EntityCreeper['Creeper'/70, l='MpServer', x=166.50, y=17.00, z=79.50], EntitySquid['Squid'/1094, l='MpServer', x=255.26, y=48.48, z=116.90], EntitySkeleton['Skeleton'/583, l='MpServer', x=157.50, y=33.00, z=77.50], EntitySquid['Squid'/1095, l='MpServer', x=247.70, y=48.53, z=117.17], EntitySquid['Squid'/1096, l='MpServer', x=252.26, y=49.92, z=116.74], EntitySquid['Squid'/1097, l='MpServer', x=254.30, y=51.61, z=124.77], EntityWitch['Witch'/850, l='MpServer', x=201.50, y=14.00, z=83.50], EntitySkeleton['Skeleton'/1363, l='MpServer', x=207.50, y=21.00, z=129.50], EntitySquid['Squid'/90, l='MpServer', x=166.13, y=62.48, z=130.52], EntitySquid['Squid'/1114, l='MpServer', x=246.19, y=53.66, z=102.67], EntitySquid['Squid'/1115, l='MpServer', x=247.19, y=52.88, z=105.61], EntitySquid['Squid'/1116, l='MpServer', x=248.63, y=51.67, z=106.46], EntitySquid['Squid'/1117, l='MpServer', x=246.97, y=52.36, z=111.38], EntitySquid['Squid'/1118, l='MpServer', x=264.31, y=47.16, z=76.61], EntitySquid['Squid'/1119, l='MpServer', x=264.36, y=46.98, z=83.97], EntitySpider['Spider'/607, l='MpServer', x=165.50, y=25.00, z=67.50], EntitySpider['Spider'/609, l='MpServer', x=172.95, y=25.00, z=64.70], EntitySquid['Squid'/1124, l='MpServer', x=149.66, y=53.83, z=161.53], EntityZombie['Zombie'/1380, l='MpServer', x=184.50, y=27.00, z=104.50], EntitySquid['Squid'/1125, l='MpServer', x=175.05, y=47.78, z=79.63], EntitySquid['Squid'/1126, l='MpServer', x=164.67, y=47.82, z=83.10], EntitySquid['Squid'/1127, l='MpServer', x=172.18, y=49.28, z=77.62], EntitySquid['Squid'/1128, l='MpServer', x=171.79, y=47.62, z=75.21], EntitySkeleton['Skeleton'/1387, l='MpServer', x=176.50, y=12.00, z=86.50], EntityCreeper['Creeper'/879, l='MpServer', x=167.50, y=25.00, z=144.50], EntityZombie['Zombie'/623, l='MpServer', x=163.50, y=25.00, z=67.50], EntitySpider['Spider'/1391, l='MpServer', x=156.50, y=22.00, z=61.50], EntityZombie['Zombie'/626, l='MpServer', x=165.50, y=25.00, z=69.50], EntitySpider['Spider'/1394, l='MpServer', x=154.50, y=22.00, z=63.50], EntityCreeper['Creeper'/887, l='MpServer', x=227.50, y=24.00, z=164.50], EntityZombie['Zombie'/377, l='MpServer', x=187.50, y=22.00, z=134.50], EntityZombie['Zombie'/378, l='MpServer', x=186.50, y=22.00, z=134.50], EntityZombie['Zombie'/891, l='MpServer', x=158.62, y=14.00, z=131.96], EntityCow['Cow'/383, l='MpServer', x=243.50, y=64.00, z=71.50], EntityCreeper['Creeper'/895, l='MpServer', x=171.50, y=17.00, z=59.50], EntitySkeleton['Skeleton'/1407, l='MpServer', x=161.50, y=21.00, z=60.50], EntityCreeper['Creeper'/896, l='MpServer', x=174.50, y=17.00, z=60.50], EntitySkeleton['Skeleton'/897, l='MpServer', x=167.50, y=14.00, z=87.50], EntityZombie['Zombie'/1409, l='MpServer', x=203.50, y=20.00, z=131.50], EntitySpider['Spider'/1410, l='MpServer', x=201.50, y=20.00, z=132.50], EntityChicken['Chicken'/132, l='MpServer', x=238.50, y=65.00, z=61.50], EntityChicken['Chicken'/133, l='MpServer', x=238.50, y=65.00, z=62.50], EntityZombie['Zombie'/906, l='MpServer', x=153.18, y=16.00, z=79.68], EntitySquid['Squid'/1162, l='MpServer', x=221.34, y=56.07, z=147.34], EntityZombie['Zombie'/907, l='MpServer', x=162.49, y=14.00, z=80.29], EntitySquid['Squid'/1163, l='MpServer', x=179.86, y=60.23, z=173.13], EntityZombie['Zombie'/908, l='MpServer', x=159.50, y=17.00, z=76.50], EntitySquid['Squid'/1164, l='MpServer', x=183.89, y=57.63, z=180.57], EntitySkeleton['Skeleton'/909, l='MpServer', x=153.50, y=17.00, z=74.50], EntitySquid['Squid'/1166, l='MpServer', x=176.34, y=57.16, z=175.11], EntityBat['Bat'/654, l='MpServer', x=154.25, y=25.01, z=59.25], EntitySquid['Squid'/1167, l='MpServer', x=176.92, y=57.44, z=174.28], EntityChicken['Chicken'/144, l='MpServer', x=240.50, y=65.00, z=59.50], EntityItem['item.tile.gravel'/148, l='MpServer', x=240.88, y=17.00, z=154.97], EntityBat['Bat'/916, l='MpServer', x=173.35, y=22.08, z=132.67], EntityItem['item.tile.gravel'/149, l='MpServer', x=240.33, y=17.00, z=155.88], EntityZombie['Zombie'/665, l='MpServer', x=154.50, y=12.00, z=137.50], EntityPlayerSP['YouBugTv'/154, l='MpServer', x=202.62, y=64.00, z=121.68], EntitySkeleton['Skeleton'/923, l='MpServer', x=169.50, y=32.00, z=76.50], EntitySkeleton['Skeleton'/926, l='MpServer', x=157.50, y=20.00, z=65.50], EntityCreeper['Creeper'/672, l='MpServer', x=174.50, y=26.00, z=147.50], EntitySkeleton['Skeleton'/673, l='MpServer', x=175.50, y=26.00, z=146.50], EntitySkeleton['Skeleton'/674, l='MpServer', x=177.50, y=26.00, z=146.50], EntitySkeleton['Skeleton'/676, l='MpServer', x=173.50, y=26.00, z=147.50], EntitySquid['Squid'/1190, l='MpServer', x=238.20, y=59.03, z=108.68], EntitySkeleton['Skeleton'/935, l='MpServer', x=223.50, y=24.00, z=168.50], EntitySquid['Squid'/1191, l='MpServer', x=237.60, y=58.99, z=107.88], EntitySkeleton['Skeleton'/936, l='MpServer', x=220.50, y=24.00, z=164.50], EntitySquid['Squid'/1192, l='MpServer', x=230.07, y=57.56, z=103.54], EntitySquid['Squid'/1193, l='MpServer', x=231.33, y=56.77, z=106.12], EntitySkeleton['Skeleton'/683, l='MpServer', x=163.29, y=21.00, z=80.52], EntitySkeleton['Skeleton'/948, l='MpServer', x=159.50, y=32.00, z=79.50], EntityZombie['Zombie'/437, l='MpServer', x=212.50, y=24.00, z=126.50], EntityCreeper['Creeper'/693, l='MpServer', x=162.50, y=14.00, z=69.50], EntitySkeleton['Skeleton'/694, l='MpServer', x=162.50, y=14.00, z=66.50], EntitySquid['Squid'/1211, l='MpServer', x=231.69, y=48.26, z=110.22], EntitySquid['Squid'/1212, l='MpServer', x=237.88, y=48.35, z=116.20], EntitySquid['Squid'/1213, l='MpServer', x=241.90, y=49.00, z=117.18], EntitySquid['Squid'/1214, l='MpServer', x=230.59, y=47.92, z=124.86], EntityCreeper['Creeper'/962, l='MpServer', x=149.48, y=24.00, z=74.20], EntitySquid['Squid'/1221, l='MpServer', x=242.36, y=49.26, z=131.33], EntityCreeper['Creeper'/710, l='MpServer', x=152.50, y=15.00, z=80.50], EntitySquid['Squid'/1223, l='MpServer', x=246.23, y=49.70, z=133.98], EntitySquid['Squid'/1224, l='MpServer', x=235.99, y=48.70, z=139.60], EntityZombie['Zombie'/969, l='MpServer', x=148.81, y=22.00, z=148.51], EntitySquid['Squid'/1225, l='MpServer', x=239.70, y=49.10, z=141.06], EntitySquid['Squid'/1226, l='MpServer', x=169.80, y=55.27, z=174.16], EntitySquid['Squid'/1227, l='MpServer', x=168.62, y=55.64, z=171.41], EntitySquid['Squid'/1228, l='MpServer', x=165.63, y=56.54, z=181.56], EntitySquid['Squid'/1229, l='MpServer', x=175.16, y=55.09, z=178.03], EntitySquid['Squid'/1236, l='MpServer', x=182.81, y=53.63, z=158.16], EntitySquid['Squid'/1237, l='MpServer', x=183.15, y=53.28, z=159.74], EntitySquid['Squid'/1238, l='MpServer', x=181.92, y=53.33, z=162.32], EntitySquid['Squid'/1239, l='MpServer', x=178.04, y=53.15, z=167.29], EntitySkeleton['Skeleton'/988, l='MpServer', x=167.50, y=24.00, z=142.50], EntitySquid['Squid'/1244, l='MpServer', x=216.64, y=56.54, z=173.18], EntitySquid['Squid'/1246, l='MpServer', x=222.07, y=56.04, z=176.17], EntitySkeleton['Skeleton'/991, l='MpServer', x=143.50, y=44.00, z=90.50], EntitySquid['Squid'/1247, l='MpServer', x=213.36, y=58.14, z=172.03], EntitySquid['Squid'/1248, l='MpServer', x=219.69, y=59.55, z=176.10], EntityBat['Bat'/994, l='MpServer', x=236.96, y=12.17, z=153.48], EntityBat['Bat'/483, l='MpServer', x=152.31, y=24.10, z=68.36], EntityBat['Bat'/996, l='MpServer', x=241.54, y=18.94, z=151.48], EntityBat['Bat'/997, l='MpServer', x=238.51, y=12.42, z=153.77], EntityBat['Bat'/998, l='MpServer', x=242.75, y=15.02, z=153.52], EntityZombie['Zombie'/492, l='MpServer', x=169.50, y=24.00, z=145.50], EntityBat['Bat'/748, l='MpServer', x=210.59, y=25.10, z=129.66], EntityBat['Bat'/749, l='MpServer', x=183.45, y=24.62, z=134.67], EntitySkeleton['Skeleton'/1016, l='MpServer', x=152.50, y=13.00, z=131.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 615286816 bytes (586 MB) / 939524096 bytes (896 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID             | Version      | Source                        | Signature |
	|:------ |:-------------- |:------------ |:----------------------------- |:--------- |
	| LCHIJA | minecraft      | 1.12.2       | minecraft.jar                 | None      |
	| LCHIJA | mcp            | 9.42         | minecraft.jar                 | None      |
	| LCHIJA | FML            | 8.0.99.99    | forge-1.12.2-14.23.5.2847.jar | None      |
	| LCHIJA | forge          | 14.23.5.2847 | forge-1.12.2-14.23.5.2847.jar | None      |
	| LCHIJA | LambdaLib|Core | 0.1.9        | minecraft.jar                 | None      |
	| LCHIJA | lambdalib2     | 0.1.9        | AcademyCraft-1.1.2.jar        | None      |
	| LCHIJA | academy        | 1.1.2        | AcademyCraft-1.1.2.jar        | None      |

	Loaded coremods (and transformers): 
CorePlugin (AcademyCraft-1.1.2.jar)
  cn.lambdalib2.render.mc.PipelineTransformer
  cn.lambdalib2.registry.impl.RegistryTransformer
	GL info: ' Vendor: 'Intel' Version: '3.1.0 - Build 9.17.10.4459' Renderer: 'Intel(R) HD Graphics 2000'
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2847
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 2000 GL version 3.1.0 - Build 9.17.10.4459, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (United Kingdom)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz

**Desktop is Windows
 - MC Version and Forge version: [e.g. 14.23.5.2847-1.12.2]
 - Version [e.g. 1.1.0beta1]

Pls someone help me i realy like this mod and wanted to do a rp wit hmy friends so

**Comment by YouBugTv** [comment]
Windows 10 i forgot

**Comment by zeldacl** [comment]
AC need GL 3.3.0
