### ISSUE TITLE
AMServer crash

### ISSUE THREAD

**Issue by WeAthFoLD** [LambdaInnovation/AcademyCraft#89]
At the instant when player leaves the server, the following crash occured.

```
io.netty.handler.timeout.ReadTimeoutException
[15:23:11] [Server thread/INFO]: WeAthFolD lost connection: TranslatableComponent{key='disconnect.timeout', args=[], siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null}}
[15:23:11] [Server thread/INFO]: WeAthFolD left the game
[15:23:11] [Server thread/ERROR] [FML]: Exception caught during firing event cpw.mods.fml.common.gameevent.PlayerEvent$PlayerLoggedOutEvent@7dc5eb19:
java.lang.NullPointerException
	at cn.academy.ability.api.ctrl.AMServer.abortPlayer(AMServer.java:112) ~[AMServer.class:?]
	at cn.academy.ability.api.ctrl.AMServer.onPlayerLoggedOut(AMServer.java:174) ~[AMServer.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_7_AMServer_onPlayerLoggedOut_PlayerLoggedOutEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) [EventBus.class:?]
	at cpw.mods.fml.common.FMLCommonHandler.firePlayerLoggedOut(FMLCommonHandler.java:555) [FMLCommonHandler.class:?]
	at net.minecraft.server.management.ServerConfigurationManager.playerLoggedOut(ServerConfigurationManager.java:332) [ServerConfigurationManager.class:?]
	at net.minecraft.network.NetHandlerPlayServer.onDisconnect(NetHandlerPlayServer.java:673) [NetHandlerPlayServer.class:?]
	at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:171) [NetworkSystem.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:726) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:349) [DedicatedServer.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:614) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:485) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:752) [MinecraftServer$2.class:?]
```

**Comment by EAirPeter** [comment]
Actually, it's related to FML's bug.
